import type { TtsRequest } from "../../../schemas/providers/voice.ai/index.ts";
import type { Auth } from "../../auth.ts";
import type { Fetch } from "../../runtime/fetch.ts";
export type { TtsRequest } from "../../../schemas/providers/voice.ai/index.ts";
export interface SynthesizeOptions { readonly auth?: Auth; readonly fetch?: Fetch; readonly baseUrl?: string; readonly signal?: AbortSignal }
function environment(): Record<string, string | undefined> { return typeof process === "undefined" ? {} : process.env; }
function apiKey(options: SynthesizeOptions): string { const value = options.auth?.["voice.ai"]?.apiKey ?? environment().SPEECHSWITCH_VOICE_AI_API_KEY ?? environment().VOICE_AI_API_KEY; if (!value) throw new TypeError("Missing auth['voice.ai'].apiKey configuration"); return value; }
const model = { "voiceai-tts-v1": "voiceai-tts-v1-latest", "voiceai-tts-v1-2026-02-10": "voiceai-tts-v1-2026-02-10", "voiceai-tts-multilingual-v1": "voiceai-tts-multilingual-v1-latest", "voiceai-tts-multilingual-v1-2026-02-10": "voiceai-tts-multilingual-v1-2026-02-10" } as const;
function format(output: TtsRequest["output"]): string { if (output.format === "mp3" && output.sampleRateHz === 32000) return "mp3"; if (output.format === "wav" && output.sampleRateHz === 32000) return "wav"; if (output.format === "pcm" && output.sampleRateHz === 32000) return "pcm"; if (output.format === "alaw") return "alaw_8000"; if (output.format === "mulaw") return "ulaw_8000"; const name = output.format === "opus" ? "opus" : output.format; const rate = output.sampleRateHz; const bitrate = "bitRateBps" in output && output.bitRateBps !== undefined ? `_${output.bitRateBps / 1000}` : ""; return `${name}_${rate}${bitrate}`; }
async function failure(response: Response): Promise<TypeError> { const detail = (await response.text()).trim(); return new TypeError(`Voice.ai returned HTTP ${response.status}${detail ? `: ${detail}` : ""}`); }
export async function* synthesize(request: TtsRequest, options: SynthesizeOptions = {}): AsyncIterableIterator<Uint8Array> { const dictionary = request.dictionarySelection; const response = await (options.fetch ?? globalThis.fetch)(`${options.baseUrl ?? "https://dev.voice.ai"}/api/v1/tts/speech`, { method: "POST", headers: { authorization: `Bearer ${apiKey(options)}`, "content-type": "application/json" }, body: JSON.stringify({ text: request.text, voice_id: request.voice, audio_format: format(request.output), temperature: request.temperature, top_p: request.topProbabilityMass, model: model[request.model], language: request.language, dictionary_id: dictionary?.dictionaryIds[0], dictionary_version: dictionary?.version }), signal: options.signal }); if (!response.ok) throw await failure(response); if (!response.body) throw new TypeError("Voice.ai returned no audio stream"); yield* response.body; }
