import type { TtsRequest } from "../../../schemas/providers/vocu/index.ts";
import { createJob, defaultBaseUrl, getJob, synthesizeDirect, type Job, type Language, type SpeechInput } from "../../generated/clients/vocu.ts";
import type { Auth } from "../../auth.ts";
import type { Fetch } from "../../runtime/fetch.ts";
export type { TtsRequest } from "../../../schemas/providers/vocu/index.ts";
export interface SynthesizeOptions { readonly auth?: Auth; readonly fetch?: Fetch; readonly baseUrl?: string; readonly signal?: AbortSignal; readonly pollIntervalMs?: number }
function environment(): Record<string, string | undefined> { return typeof process === "undefined" ? {} : process.env; }
function key(options: SynthesizeOptions): string | undefined { return options.auth?.vocu?.apiKey ?? environment().SPEECHSWITCH_VOCU_API_KEY ?? environment().VOCU_API_KEY; }
function client(options: SynthesizeOptions, authenticated = false) { const apiKey = key(options); if (authenticated && !apiKey) throw new TypeError("Missing auth.vocu.apiKey configuration"); return { apiKey, fetch: options.fetch ?? globalThis.fetch, baseUrl: options.baseUrl ?? defaultBaseUrl, signal: options.signal }; }
interface Controls { readonly voice: string; readonly text: string; readonly language?: string; readonly voiceVariant?: string; readonly deliveryVariation?: string; readonly textEmotionBias?: boolean; readonly expressivenessEnhancement?: boolean; readonly emotionBlend?: { readonly anger?: number; readonly happiness?: number; readonly neutral?: number; readonly sadness?: number; readonly contextual?: number }; readonly speed?: number; readonly randomSeed?: number }
function input(request: Controls): SpeechInput { const emotion = request.emotionBlend; return { voiceId: request.voice, text: request.text, promptId: request.voiceVariant, preset: request.deliveryVariation === "balanced" ? "balance" : request.deliveryVariation as "stable" | "creative" | undefined, break_clone: request.textEmotionBias, language: request.language as Language | undefined, vivid: request.expressivenessEnhancement, emo_switch: emotion ? [emotion.anger ?? 0, emotion.happiness ?? 0, emotion.neutral ?? 0, emotion.sadness ?? 0, emotion.contextual ?? 0] : undefined, speechRate: request.speed === undefined ? undefined : 1 / request.speed, flash: true, seed: request.randomSeed }; }
async function checked(response: Response): Promise<Response> { if (response.ok) return response; const detail = (await response.text()).trim(); throw new TypeError(`Vocu returned HTTP ${response.status}${detail ? `: ${detail}` : ""}`); }
async function responseData<T>(response: Response): Promise<T> { const value = await (await checked(response)).json() as { readonly status?: number; readonly message?: string; readonly data?: T }; if (value.status !== 200 || value.data === undefined) throw new TypeError(`Vocu returned an invalid response${value.message ? `: ${value.message}` : ""}`); return value.data; }
async function wait(milliseconds: number, signal?: AbortSignal): Promise<void> { await new Promise<void>((resolve, reject) => { const timeout = setTimeout(resolve, milliseconds); signal?.addEventListener("abort", () => { clearTimeout(timeout); reject(signal.reason); }, { once: true }); }); }
async function completedJob(contents: readonly SpeechInput[], options: SynthesizeOptions): Promise<Job> { const config = client(options); let job = await responseData<Job>(await createJob(contents, config)); while (job.status === "pending" || job.status === "processing") { await wait(options.pollIntervalMs ?? 1000, options.signal); job = await responseData<Job>(await getJob(job.id, config)); } if (job.status === "failed" || !job.metadata.audio) throw new TypeError(`Vocu generation ${job.id} failed`); return job; }
export async function* synthesize(request: TtsRequest, options: SynthesizeOptions = {}): AsyncIterableIterator<Uint8Array> {
  let response: Response;
  if ("segments" in request && request.segments) { const job = await completedJob(request.segments.map((segment) => input(segment)), options); response = await (options.fetch ?? globalThis.fetch)(job.metadata.audio!, { signal: options.signal }); }
  else response = await synthesizeDirect(input(request as Extract<TtsRequest, { readonly text: string }>), client(options, true));
  await checked(response); if (!response.body) throw new TypeError("Vocu returned no audio stream"); yield* response.body;
}
