use super::*;

#[test]
fn explicit_adjustments_replacements_and_mp3_controls_survive() {
    let mut r = request();
    r.speed = Some(1.5);
    r.volume_scale = Some(2.0);
    r.pitch_bias = Some(0.0);
    r.replacements = Some(vec![TtsRequestText77d171beReplacementsItem {
        pattern: "Acme".into(),
        replacement: "ækmi".into(),
    }]);
    r.language = Some(TtsRequestTexte253c939Language::Fa(Default::default()));
    r.text_normalization = Some(TtsRequestText77d171beOutputMp3ConstantBitRate::True(
        Default::default(),
    ));
    r.output = Some(TtsRequestTextf2dcc77eOutput::Mp3(
        TtsRequestText77d171beOutputMp3 {
            format: Default::default(),
            sample_rate_hz: Some(TtsRequestText77d171beOutputFlacSampleRateHz::Number44100(
                Default::default(),
            )),
            bit_rate_bps: Some(TtsRequestText77d171beOutputMp3BitRateBps::Number256000(
                Default::default(),
            )),
            channel_count: Some(TtsRequestText77d171beOutputFlacChannelCount::Number2(
                Default::default(),
            )),
            constant_bit_rate: Some(TtsRequestText77d171beOutputMp3ConstantBitRate::False(
                Default::default(),
            )),
        },
    ));
    let r = TtsRequest::TextVoice9b47fc40(r);
    let _validate = validate_request(&r).unwrap();
    let c = settings::settings(r);
    assert_eq!(
        value(&encoded(&JsonValue::Object(c.wire))),
        value(
            r#"{"model":"speech-2.8-hd","language_boost":"Persian","voice_setting":{"voice_id":"existing-voice","speed":1.5,"vol":2,"pitch":0,"latex_read":false,"text_normalization":true},"audio_setting":{"format":"mp3","sample_rate":44100,"channel":2,"bitrate":256000,"force_cbr":false},"pronunciation_dict":{"tone":["Acme/ækmi"]}}"#
        )
    );
}

#[test]
fn formula_and_effects_choose_nonstreaming_flac() {
    let r = TtsRequest::TextVoice6862a939(TtsRequestTextVoice6862a939 {
        model: None,
        text: "$$1+1$$".into(),
        voice: "existing".into(),
        formula_reading: Default::default(),
        language: None,
        emotion: None,
        pitch_bias: None,
        replacements: None,
        speed: None,
        text_normalization: None,
        timestamp_delivery: None,
        timestamp_granularity: None,
        volume_scale: None,
        output: Some(TtsRequestText77d171beOutput::Flac(
            TtsRequestText77d171beOutputFlac {
                format: Default::default(),
                sample_rate_hz: None,
                channel_count: None,
            },
        )),
        voice_transform: TtsRequestText77d171beVoiceTransform {
            brightness: Some(0.0),
            softness: Some(-100.0),
            crispness: Some(100.0),
            effect: Some(TtsRequestText77d171beVoiceTransformEffect::Telephone(
                Default::default(),
            )),
        },
    });
    let _validate = validate_request(&r).unwrap();
    let c = settings::settings(r);
    assert!(!c.streaming);
    assert_eq!(
        c.wire["language_boost"],
        JsonValue::String("Chinese".into())
    );
    assert_eq!(
        value(&encoded(&c.wire["voice_modify"])),
        value(r#"{"pitch":0,"intensity":-100,"timbre":100,"sound_effects":"lofi_telephone"}"#)
    );
}

#[test]
fn all_eight_native_model_names_are_preserved() {
    let requests = vec![
        (
            TtsRequest::TextVoiceab653629(TtsRequestTextVoiceab653629 {
                emotion: None,
                language: None,
                model: TtsRequestText77d171beModel::Speech01Hd(Default::default()),
                output: None,
                pitch_bias: None,
                replacements: None,
                speed: None,
                text: "Hi".into(),
                text_normalization: None,
                timestamp_delivery: None,
                timestamp_granularity: None,
                voice: "existing".into(),
                volume_scale: None,
            }),
            "speech-01-hd",
        ),
        (
            TtsRequest::TextVoiceab653629(TtsRequestTextVoiceab653629 {
                emotion: None,
                language: None,
                model: TtsRequestText77d171beModel::Speech01Turbo(Default::default()),
                output: None,
                pitch_bias: None,
                replacements: None,
                speed: None,
                text: "Hi".into(),
                text_normalization: None,
                timestamp_delivery: None,
                timestamp_granularity: None,
                voice: "existing".into(),
                volume_scale: None,
            }),
            "speech-01-turbo",
        ),
        (
            TtsRequest::TextVoiceab653629(TtsRequestTextVoiceab653629 {
                emotion: None,
                language: None,
                model: TtsRequestText77d171beModel::Speech02Hd(Default::default()),
                output: None,
                pitch_bias: None,
                replacements: None,
                speed: None,
                text: "Hi".into(),
                text_normalization: None,
                timestamp_delivery: None,
                timestamp_granularity: None,
                voice: "existing".into(),
                volume_scale: None,
            }),
            "speech-02-hd",
        ),
        (
            TtsRequest::TextVoiceab653629(TtsRequestTextVoiceab653629 {
                emotion: None,
                language: None,
                model: TtsRequestText77d171beModel::Speech02Turbo(Default::default()),
                output: None,
                pitch_bias: None,
                replacements: None,
                speed: None,
                text: "Hi".into(),
                text_normalization: None,
                timestamp_delivery: None,
                timestamp_granularity: None,
                voice: "existing".into(),
                volume_scale: None,
            }),
            "speech-02-turbo",
        ),
        (
            TtsRequest::TextVoicecbe3fac7(TtsRequestTextVoicecbe3fac7 {
                emotion: None,
                language: None,
                model: TtsRequestTexte253c939Model::Speech26Hd(Default::default()),
                output: None,
                pitch_bias: None,
                replacements: None,
                speed: None,
                text: "Hi".into(),
                text_normalization: None,
                timestamp_delivery: None,
                timestamp_granularity: None,
                voice: "existing".into(),
                volume_scale: None,
            }),
            "speech-2.6-hd",
        ),
        (
            TtsRequest::TextVoicecbe3fac7(TtsRequestTextVoicecbe3fac7 {
                emotion: None,
                language: None,
                model: TtsRequestTexte253c939Model::Speech26Turbo(Default::default()),
                output: None,
                pitch_bias: None,
                replacements: None,
                speed: None,
                text: "Hi".into(),
                text_normalization: None,
                timestamp_delivery: None,
                timestamp_granularity: None,
                voice: "existing".into(),
                volume_scale: None,
            }),
            "speech-2.6-turbo",
        ),
        (
            TtsRequest::TextVoice9b47fc40(TtsRequestTextVoice9b47fc40 {
                emotion: None,
                language: None,
                model: Some(TtsRequestText21d6f721Model::Speech28Hd(Default::default())),
                output: None,
                pitch_bias: None,
                replacements: None,
                speed: None,
                text: "Hi".into(),
                text_normalization: None,
                timestamp_delivery: None,
                timestamp_granularity: None,
                voice: "existing".into(),
                volume_scale: None,
            }),
            "speech-2.8-hd",
        ),
        (
            TtsRequest::TextVoice9b47fc40(TtsRequestTextVoice9b47fc40 {
                emotion: None,
                language: None,
                model: Some(TtsRequestText21d6f721Model::Speech28Turbo(
                    Default::default(),
                )),
                output: None,
                pitch_bias: None,
                replacements: None,
                speed: None,
                text: "Hi".into(),
                text_normalization: None,
                timestamp_delivery: None,
                timestamp_granularity: None,
                voice: "existing".into(),
                volume_scale: None,
            }),
            "speech-2.8-turbo",
        ),
    ];
    for (r, expected) in requests {
        let _validate = validate_request(&r).unwrap();
        let c = settings::settings(r);
        assert_eq!(c.wire["model"], JsonValue::String(expected.into()));
    }
}

#[test]
fn all_generated_variants_have_explicit_wire_conversions() {
    struct Expected {
        live: bool,
        formula: bool,
        blend: bool,
        effects: bool,
        split: bool,
    }
    let requests = vec![
        (
            TtsRequest::Text77d171be(TtsRequestText77d171be {
                emotion: None,
                language: None,
                model: TtsRequestText77d171beModel::Speech01Hd(Default::default()),
                output: None,
                pitch_bias: None,
                replacements: None,
                speed: None,
                text: "Hello".into(),
                text_normalization: None,
                timestamp_delivery: None,
                timestamp_granularity: None,
                voice_blend: vec![TtsRequestText77d171beVoiceBlendItem {
                    voice: "blend".into(),
                    weight: 100.0,
                }],
                voice_transform: TtsRequestText77d171beVoiceTransform {
                    brightness: None,
                    crispness: None,
                    effect: None,
                    softness: None,
                },
                volume_scale: None,
            }),
            Expected {
                live: false,
                formula: false,
                blend: true,
                effects: true,
                split: false,
            },
        ),
        (
            TtsRequest::Text8a99d813(TtsRequestText8a99d813 {
                emotion: None,
                formula_reading: Default::default(),
                language: None,
                model: TtsRequestText77d171beModel::Speech01Hd(Default::default()),
                output: None,
                pitch_bias: None,
                replacements: None,
                speed: None,
                text: "Hello".into(),
                text_normalization: None,
                timestamp_delivery: None,
                timestamp_granularity: None,
                voice_blend: vec![TtsRequestText77d171beVoiceBlendItem {
                    voice: "blend".into(),
                    weight: 100.0,
                }],
                voice_transform: TtsRequestText77d171beVoiceTransform {
                    brightness: None,
                    crispness: None,
                    effect: None,
                    softness: None,
                },
                volume_scale: None,
            }),
            Expected {
                live: false,
                formula: true,
                blend: true,
                effects: true,
                split: false,
            },
        ),
        (
            TtsRequest::Textf2dcc77e(TtsRequestTextf2dcc77e {
                emotion: None,
                formula_reading: Default::default(),
                language: None,
                model: TtsRequestText77d171beModel::Speech01Hd(Default::default()),
                output: None,
                pitch_bias: None,
                replacements: None,
                speed: None,
                text: "Hello".into(),
                text_normalization: None,
                timestamp_delivery: None,
                timestamp_granularity: None,
                voice_blend: vec![TtsRequestText77d171beVoiceBlendItem {
                    voice: "blend".into(),
                    weight: 100.0,
                }],
                volume_scale: None,
            }),
            Expected {
                live: false,
                formula: true,
                blend: true,
                effects: false,
                split: false,
            },
        ),
        (
            TtsRequest::Textbc3e8901(TtsRequestTextbc3e8901 {
                emotion: None,
                language: None,
                model: TtsRequestText77d171beModel::Speech01Hd(Default::default()),
                output: None,
                pitch_bias: None,
                replacements: None,
                speed: None,
                text: "Hello".into(),
                text_normalization: None,
                timestamp_delivery: None,
                timestamp_granularity: None,
                voice_blend: vec![TtsRequestText77d171beVoiceBlendItem {
                    voice: "blend".into(),
                    weight: 100.0,
                }],
                volume_scale: None,
            }),
            Expected {
                live: false,
                formula: false,
                blend: true,
                effects: false,
                split: false,
            },
        ),
        (
            TtsRequest::TextVoice9d11e112(TtsRequestTextVoice9d11e112 {
                emotion: None,
                language: None,
                model: TtsRequestText77d171beModel::Speech01Hd(Default::default()),
                output: None,
                pitch_bias: None,
                replacements: None,
                speed: None,
                text: "Hello".into(),
                text_normalization: None,
                timestamp_delivery: None,
                timestamp_granularity: None,
                voice: "existing-voice".into(),
                voice_transform: TtsRequestText77d171beVoiceTransform {
                    brightness: None,
                    crispness: None,
                    effect: None,
                    softness: None,
                },
                volume_scale: None,
            }),
            Expected {
                live: false,
                formula: false,
                blend: false,
                effects: true,
                split: false,
            },
        ),
        (
            TtsRequest::TextVoicec9541dfe(TtsRequestTextVoicec9541dfe {
                emotion: None,
                formula_reading: Default::default(),
                language: None,
                model: TtsRequestText77d171beModel::Speech01Hd(Default::default()),
                output: None,
                pitch_bias: None,
                replacements: None,
                speed: None,
                text: "Hello".into(),
                text_normalization: None,
                timestamp_delivery: None,
                timestamp_granularity: None,
                voice: "existing-voice".into(),
                voice_transform: TtsRequestText77d171beVoiceTransform {
                    brightness: None,
                    crispness: None,
                    effect: None,
                    softness: None,
                },
                volume_scale: None,
            }),
            Expected {
                live: false,
                formula: true,
                blend: false,
                effects: true,
                split: false,
            },
        ),
        (
            TtsRequest::TextVoice579df7d3(TtsRequestTextVoice579df7d3 {
                emotion: None,
                formula_reading: Default::default(),
                language: None,
                model: TtsRequestText77d171beModel::Speech01Hd(Default::default()),
                output: None,
                pitch_bias: None,
                replacements: None,
                speed: None,
                text: "Hello".into(),
                text_normalization: None,
                timestamp_delivery: None,
                timestamp_granularity: None,
                voice: "existing-voice".into(),
                volume_scale: None,
            }),
            Expected {
                live: false,
                formula: true,
                blend: false,
                effects: false,
                split: false,
            },
        ),
        (
            TtsRequest::TextVoiceab653629(TtsRequestTextVoiceab653629 {
                emotion: None,
                language: None,
                model: TtsRequestText77d171beModel::Speech01Hd(Default::default()),
                output: None,
                pitch_bias: None,
                replacements: None,
                speed: None,
                text: "Hello".into(),
                text_normalization: None,
                timestamp_delivery: None,
                timestamp_granularity: None,
                voice: "existing-voice".into(),
                volume_scale: None,
            }),
            Expected {
                live: false,
                formula: false,
                blend: false,
                effects: false,
                split: false,
            },
        ),
        (
            TtsRequest::StreamingText12421ea0(TtsRequestStreamingText12421ea0 {
                emotion: None,
                language: None,
                language_text_normalization: None,
                model: TtsRequestText77d171beModel::Speech01Hd(Default::default()),
                output: None,
                pitch_bias: None,
                replacements: None,
                speed: None,
                text: source(vec![Input::String("Hello".into())]),
                voice_blend: vec![TtsRequestText77d171beVoiceBlendItem {
                    voice: "blend".into(),
                    weight: 100.0,
                }],
                voice_transform: TtsRequestText77d171beVoiceTransform {
                    brightness: None,
                    crispness: None,
                    effect: None,
                    softness: None,
                },
                volume_scale: None,
            }),
            Expected {
                live: true,
                formula: false,
                blend: true,
                effects: true,
                split: false,
            },
        ),
        (
            TtsRequest::StreamingText3a58293c(TtsRequestStreamingText3a58293c {
                emotion: None,
                formula_reading: Default::default(),
                language: None,
                language_text_normalization: None,
                model: TtsRequestText77d171beModel::Speech01Hd(Default::default()),
                output: None,
                pitch_bias: None,
                replacements: None,
                speed: None,
                text: source(vec![Input::String("Hello".into())]),
                voice_blend: vec![TtsRequestText77d171beVoiceBlendItem {
                    voice: "blend".into(),
                    weight: 100.0,
                }],
                voice_transform: TtsRequestText77d171beVoiceTransform {
                    brightness: None,
                    crispness: None,
                    effect: None,
                    softness: None,
                },
                volume_scale: None,
            }),
            Expected {
                live: true,
                formula: true,
                blend: true,
                effects: true,
                split: false,
            },
        ),
        (
            TtsRequest::StreamingTextaa771f19(TtsRequestStreamingTextaa771f19 {
                emotion: None,
                formula_reading: Default::default(),
                language: None,
                language_text_normalization: None,
                model: TtsRequestText77d171beModel::Speech01Hd(Default::default()),
                output: None,
                pitch_bias: None,
                replacements: None,
                speed: None,
                text: source(vec![Input::String("Hello".into())]),
                voice_blend: vec![TtsRequestText77d171beVoiceBlendItem {
                    voice: "blend".into(),
                    weight: 100.0,
                }],
                volume_scale: None,
            }),
            Expected {
                live: true,
                formula: true,
                blend: true,
                effects: false,
                split: false,
            },
        ),
        (
            TtsRequest::StreamingText62be105a(TtsRequestStreamingText62be105a {
                emotion: None,
                language: None,
                language_text_normalization: None,
                model: TtsRequestText77d171beModel::Speech01Hd(Default::default()),
                output: None,
                pitch_bias: None,
                replacements: None,
                speed: None,
                text: source(vec![Input::String("Hello".into())]),
                voice_blend: vec![TtsRequestText77d171beVoiceBlendItem {
                    voice: "blend".into(),
                    weight: 100.0,
                }],
                volume_scale: None,
            }),
            Expected {
                live: true,
                formula: false,
                blend: true,
                effects: false,
                split: false,
            },
        ),
        (
            TtsRequest::StreamingTextVoice6d21fc54(TtsRequestStreamingTextVoice6d21fc54 {
                emotion: None,
                language: None,
                language_text_normalization: None,
                model: TtsRequestText77d171beModel::Speech01Hd(Default::default()),
                output: None,
                pitch_bias: None,
                replacements: None,
                speed: None,
                text: source(vec![Input::String("Hello".into())]),
                voice: "existing-voice".into(),
                voice_transform: TtsRequestText77d171beVoiceTransform {
                    brightness: None,
                    crispness: None,
                    effect: None,
                    softness: None,
                },
                volume_scale: None,
            }),
            Expected {
                live: true,
                formula: false,
                blend: false,
                effects: true,
                split: false,
            },
        ),
        (
            TtsRequest::StreamingTextVoice80c0de17(TtsRequestStreamingTextVoice80c0de17 {
                emotion: None,
                formula_reading: Default::default(),
                language: None,
                language_text_normalization: None,
                model: TtsRequestText77d171beModel::Speech01Hd(Default::default()),
                output: None,
                pitch_bias: None,
                replacements: None,
                speed: None,
                text: source(vec![Input::String("Hello".into())]),
                voice: "existing-voice".into(),
                voice_transform: TtsRequestText77d171beVoiceTransform {
                    brightness: None,
                    crispness: None,
                    effect: None,
                    softness: None,
                },
                volume_scale: None,
            }),
            Expected {
                live: true,
                formula: true,
                blend: false,
                effects: true,
                split: false,
            },
        ),
        (
            TtsRequest::StreamingTextVoiceb9340145(TtsRequestStreamingTextVoiceb9340145 {
                emotion: None,
                formula_reading: Default::default(),
                language: None,
                language_text_normalization: None,
                model: TtsRequestText77d171beModel::Speech01Hd(Default::default()),
                output: None,
                pitch_bias: None,
                replacements: None,
                speed: None,
                text: source(vec![Input::String("Hello".into())]),
                voice: "existing-voice".into(),
                volume_scale: None,
            }),
            Expected {
                live: true,
                formula: true,
                blend: false,
                effects: false,
                split: false,
            },
        ),
        (
            TtsRequest::StreamingTextVoice40504229(TtsRequestStreamingTextVoice40504229 {
                emotion: None,
                language: None,
                language_text_normalization: None,
                model: TtsRequestText77d171beModel::Speech01Hd(Default::default()),
                output: None,
                pitch_bias: None,
                replacements: None,
                speed: None,
                text: source(vec![Input::String("Hello".into())]),
                voice: "existing-voice".into(),
                volume_scale: None,
            }),
            Expected {
                live: true,
                formula: false,
                blend: false,
                effects: false,
                split: false,
            },
        ),
        (
            TtsRequest::Texte253c939(TtsRequestTexte253c939 {
                emotion: None,
                language: None,
                model: TtsRequestTexte253c939Model::Speech26Hd(Default::default()),
                output: None,
                pitch_bias: None,
                replacements: None,
                speed: None,
                text: "Hello".into(),
                text_normalization: None,
                timestamp_delivery: None,
                timestamp_granularity: None,
                voice_blend: vec![TtsRequestText77d171beVoiceBlendItem {
                    voice: "blend".into(),
                    weight: 100.0,
                }],
                voice_transform: TtsRequestText77d171beVoiceTransform {
                    brightness: None,
                    crispness: None,
                    effect: None,
                    softness: None,
                },
                volume_scale: None,
            }),
            Expected {
                live: false,
                formula: false,
                blend: true,
                effects: true,
                split: false,
            },
        ),
        (
            TtsRequest::Text75fe6b00(TtsRequestText75fe6b00 {
                emotion: None,
                formula_reading: Default::default(),
                language: None,
                model: TtsRequestTexte253c939Model::Speech26Hd(Default::default()),
                output: None,
                pitch_bias: None,
                replacements: None,
                speed: None,
                text: "Hello".into(),
                text_normalization: None,
                timestamp_delivery: None,
                timestamp_granularity: None,
                voice_blend: vec![TtsRequestText77d171beVoiceBlendItem {
                    voice: "blend".into(),
                    weight: 100.0,
                }],
                voice_transform: TtsRequestText77d171beVoiceTransform {
                    brightness: None,
                    crispness: None,
                    effect: None,
                    softness: None,
                },
                volume_scale: None,
            }),
            Expected {
                live: false,
                formula: true,
                blend: true,
                effects: true,
                split: false,
            },
        ),
        (
            TtsRequest::Text1ddad1c5(TtsRequestText1ddad1c5 {
                emotion: None,
                formula_reading: Default::default(),
                language: None,
                model: TtsRequestTexte253c939Model::Speech26Hd(Default::default()),
                output: None,
                pitch_bias: None,
                replacements: None,
                speed: None,
                text: "Hello".into(),
                text_normalization: None,
                timestamp_delivery: None,
                timestamp_granularity: None,
                voice_blend: vec![TtsRequestText77d171beVoiceBlendItem {
                    voice: "blend".into(),
                    weight: 100.0,
                }],
                volume_scale: None,
            }),
            Expected {
                live: false,
                formula: true,
                blend: true,
                effects: false,
                split: false,
            },
        ),
        (
            TtsRequest::Text7c0eb1eb(TtsRequestText7c0eb1eb {
                emotion: None,
                language: None,
                model: TtsRequestTexte253c939Model::Speech26Hd(Default::default()),
                output: None,
                pitch_bias: None,
                replacements: None,
                speed: None,
                text: "Hello".into(),
                text_normalization: None,
                timestamp_delivery: None,
                timestamp_granularity: None,
                voice_blend: vec![TtsRequestText77d171beVoiceBlendItem {
                    voice: "blend".into(),
                    weight: 100.0,
                }],
                volume_scale: None,
            }),
            Expected {
                live: false,
                formula: false,
                blend: true,
                effects: false,
                split: false,
            },
        ),
        (
            TtsRequest::TextVoicedd885701(TtsRequestTextVoicedd885701 {
                emotion: None,
                language: None,
                model: TtsRequestTexte253c939Model::Speech26Hd(Default::default()),
                output: None,
                pitch_bias: None,
                replacements: None,
                speed: None,
                text: "Hello".into(),
                text_normalization: None,
                timestamp_delivery: None,
                timestamp_granularity: None,
                voice: "existing-voice".into(),
                voice_transform: TtsRequestText77d171beVoiceTransform {
                    brightness: None,
                    crispness: None,
                    effect: None,
                    softness: None,
                },
                volume_scale: None,
            }),
            Expected {
                live: false,
                formula: false,
                blend: false,
                effects: true,
                split: false,
            },
        ),
        (
            TtsRequest::TextVoice36766bcb(TtsRequestTextVoice36766bcb {
                emotion: None,
                formula_reading: Default::default(),
                language: None,
                model: TtsRequestTexte253c939Model::Speech26Hd(Default::default()),
                output: None,
                pitch_bias: None,
                replacements: None,
                speed: None,
                text: "Hello".into(),
                text_normalization: None,
                timestamp_delivery: None,
                timestamp_granularity: None,
                voice: "existing-voice".into(),
                voice_transform: TtsRequestText77d171beVoiceTransform {
                    brightness: None,
                    crispness: None,
                    effect: None,
                    softness: None,
                },
                volume_scale: None,
            }),
            Expected {
                live: false,
                formula: true,
                blend: false,
                effects: true,
                split: false,
            },
        ),
        (
            TtsRequest::TextVoicea492ec5e(TtsRequestTextVoicea492ec5e {
                emotion: None,
                formula_reading: Default::default(),
                language: None,
                model: TtsRequestTexte253c939Model::Speech26Hd(Default::default()),
                output: None,
                pitch_bias: None,
                replacements: None,
                speed: None,
                text: "Hello".into(),
                text_normalization: None,
                timestamp_delivery: None,
                timestamp_granularity: None,
                voice: "existing-voice".into(),
                volume_scale: None,
            }),
            Expected {
                live: false,
                formula: true,
                blend: false,
                effects: false,
                split: false,
            },
        ),
        (
            TtsRequest::TextVoicecbe3fac7(TtsRequestTextVoicecbe3fac7 {
                emotion: None,
                language: None,
                model: TtsRequestTexte253c939Model::Speech26Hd(Default::default()),
                output: None,
                pitch_bias: None,
                replacements: None,
                speed: None,
                text: "Hello".into(),
                text_normalization: None,
                timestamp_delivery: None,
                timestamp_granularity: None,
                voice: "existing-voice".into(),
                volume_scale: None,
            }),
            Expected {
                live: false,
                formula: false,
                blend: false,
                effects: false,
                split: false,
            },
        ),
        (
            TtsRequest::StreamingText81902e1a(TtsRequestStreamingText81902e1a {
                emotion: None,
                language: None,
                language_text_normalization: None,
                model: TtsRequestTexte253c939Model::Speech26Hd(Default::default()),
                output: None,
                pitch_bias: None,
                replacements: None,
                speed: None,
                text: source(vec![Input::String("Hello".into())]),
                voice_blend: vec![TtsRequestText77d171beVoiceBlendItem {
                    voice: "blend".into(),
                    weight: 100.0,
                }],
                voice_transform: TtsRequestText77d171beVoiceTransform {
                    brightness: None,
                    crispness: None,
                    effect: None,
                    softness: None,
                },
                volume_scale: None,
            }),
            Expected {
                live: true,
                formula: false,
                blend: true,
                effects: true,
                split: false,
            },
        ),
        (
            TtsRequest::StreamingText909fab39(TtsRequestStreamingText909fab39 {
                emotion: None,
                formula_reading: Default::default(),
                language: None,
                language_text_normalization: None,
                model: TtsRequestTexte253c939Model::Speech26Hd(Default::default()),
                output: None,
                pitch_bias: None,
                replacements: None,
                speed: None,
                text: source(vec![Input::String("Hello".into())]),
                voice_blend: vec![TtsRequestText77d171beVoiceBlendItem {
                    voice: "blend".into(),
                    weight: 100.0,
                }],
                voice_transform: TtsRequestText77d171beVoiceTransform {
                    brightness: None,
                    crispness: None,
                    effect: None,
                    softness: None,
                },
                volume_scale: None,
            }),
            Expected {
                live: true,
                formula: true,
                blend: true,
                effects: true,
                split: false,
            },
        ),
        (
            TtsRequest::StreamingText67fca2f3(TtsRequestStreamingText67fca2f3 {
                emotion: None,
                formula_reading: Default::default(),
                language: None,
                language_text_normalization: None,
                model: TtsRequestTexte253c939Model::Speech26Hd(Default::default()),
                output: None,
                pitch_bias: None,
                replacements: None,
                speed: None,
                text: source(vec![Input::String("Hello".into())]),
                voice_blend: vec![TtsRequestText77d171beVoiceBlendItem {
                    voice: "blend".into(),
                    weight: 100.0,
                }],
                volume_scale: None,
            }),
            Expected {
                live: true,
                formula: true,
                blend: true,
                effects: false,
                split: false,
            },
        ),
        (
            TtsRequest::StreamingText5ae80cbf(TtsRequestStreamingText5ae80cbf {
                emotion: None,
                language: None,
                language_text_normalization: None,
                model: TtsRequestTexte253c939Model::Speech26Hd(Default::default()),
                output: None,
                pitch_bias: None,
                replacements: None,
                speed: None,
                text: source(vec![Input::String("Hello".into())]),
                voice_blend: vec![TtsRequestText77d171beVoiceBlendItem {
                    voice: "blend".into(),
                    weight: 100.0,
                }],
                volume_scale: None,
            }),
            Expected {
                live: true,
                formula: false,
                blend: true,
                effects: false,
                split: false,
            },
        ),
        (
            TtsRequest::StreamingTextVoicee206c70a(TtsRequestStreamingTextVoicee206c70a {
                emotion: None,
                language: None,
                language_text_normalization: None,
                model: TtsRequestTexte253c939Model::Speech26Hd(Default::default()),
                output: None,
                pitch_bias: None,
                replacements: None,
                speed: None,
                text: source(vec![Input::String("Hello".into())]),
                voice: "existing-voice".into(),
                voice_transform: TtsRequestText77d171beVoiceTransform {
                    brightness: None,
                    crispness: None,
                    effect: None,
                    softness: None,
                },
                volume_scale: None,
            }),
            Expected {
                live: true,
                formula: false,
                blend: false,
                effects: true,
                split: false,
            },
        ),
        (
            TtsRequest::StreamingTextVoiceeb83b1ec(TtsRequestStreamingTextVoiceeb83b1ec {
                emotion: None,
                formula_reading: Default::default(),
                language: None,
                language_text_normalization: None,
                model: TtsRequestTexte253c939Model::Speech26Hd(Default::default()),
                output: None,
                pitch_bias: None,
                replacements: None,
                speed: None,
                text: source(vec![Input::String("Hello".into())]),
                voice: "existing-voice".into(),
                voice_transform: TtsRequestText77d171beVoiceTransform {
                    brightness: None,
                    crispness: None,
                    effect: None,
                    softness: None,
                },
                volume_scale: None,
            }),
            Expected {
                live: true,
                formula: true,
                blend: false,
                effects: true,
                split: false,
            },
        ),
        (
            TtsRequest::StreamingTextVoice96bca430(TtsRequestStreamingTextVoice96bca430 {
                emotion: None,
                formula_reading: Default::default(),
                language: None,
                language_text_normalization: None,
                model: TtsRequestTexte253c939Model::Speech26Hd(Default::default()),
                output: None,
                pitch_bias: None,
                replacements: None,
                speed: None,
                text: source(vec![Input::String("Hello".into())]),
                voice: "existing-voice".into(),
                volume_scale: None,
            }),
            Expected {
                live: true,
                formula: true,
                blend: false,
                effects: false,
                split: false,
            },
        ),
        (
            TtsRequest::StreamingTextVoice21264c0c(TtsRequestStreamingTextVoice21264c0c {
                emotion: None,
                language: None,
                language_text_normalization: None,
                model: TtsRequestTexte253c939Model::Speech26Hd(Default::default()),
                output: None,
                pitch_bias: None,
                replacements: None,
                speed: None,
                text: source(vec![Input::String("Hello".into())]),
                voice: "existing-voice".into(),
                volume_scale: None,
            }),
            Expected {
                live: true,
                formula: false,
                blend: false,
                effects: false,
                split: false,
            },
        ),
        (
            TtsRequest::Text21d6f721(TtsRequestText21d6f721 {
                emotion: None,
                language: None,
                model: None,
                output: None,
                pitch_bias: None,
                replacements: None,
                speed: None,
                text: "Hello".into(),
                text_normalization: None,
                timestamp_delivery: None,
                timestamp_granularity: None,
                voice_blend: vec![TtsRequestText77d171beVoiceBlendItem {
                    voice: "blend".into(),
                    weight: 100.0,
                }],
                voice_transform: TtsRequestText77d171beVoiceTransform {
                    brightness: None,
                    crispness: None,
                    effect: None,
                    softness: None,
                },
                volume_scale: None,
            }),
            Expected {
                live: false,
                formula: false,
                blend: true,
                effects: true,
                split: false,
            },
        ),
        (
            TtsRequest::Text5b5ff955(TtsRequestText5b5ff955 {
                emotion: None,
                formula_reading: Default::default(),
                language: None,
                model: None,
                output: None,
                pitch_bias: None,
                replacements: None,
                speed: None,
                text: "Hello".into(),
                text_normalization: None,
                timestamp_delivery: None,
                timestamp_granularity: None,
                voice_blend: vec![TtsRequestText77d171beVoiceBlendItem {
                    voice: "blend".into(),
                    weight: 100.0,
                }],
                voice_transform: TtsRequestText77d171beVoiceTransform {
                    brightness: None,
                    crispness: None,
                    effect: None,
                    softness: None,
                },
                volume_scale: None,
            }),
            Expected {
                live: false,
                formula: true,
                blend: true,
                effects: true,
                split: false,
            },
        ),
        (
            TtsRequest::Text6f172e70(TtsRequestText6f172e70 {
                emotion: None,
                formula_reading: Default::default(),
                language: None,
                model: None,
                output: None,
                pitch_bias: None,
                replacements: None,
                speed: None,
                text: "Hello".into(),
                text_normalization: None,
                timestamp_delivery: None,
                timestamp_granularity: None,
                voice_blend: vec![TtsRequestText77d171beVoiceBlendItem {
                    voice: "blend".into(),
                    weight: 100.0,
                }],
                volume_scale: None,
            }),
            Expected {
                live: false,
                formula: true,
                blend: true,
                effects: false,
                split: false,
            },
        ),
        (
            TtsRequest::Texta20d3295(TtsRequestTexta20d3295 {
                emotion: None,
                language: None,
                model: None,
                output: None,
                pitch_bias: None,
                replacements: None,
                speed: None,
                text: "Hello".into(),
                text_normalization: None,
                timestamp_delivery: None,
                timestamp_granularity: None,
                voice_blend: vec![TtsRequestText77d171beVoiceBlendItem {
                    voice: "blend".into(),
                    weight: 100.0,
                }],
                volume_scale: None,
            }),
            Expected {
                live: false,
                formula: false,
                blend: true,
                effects: false,
                split: false,
            },
        ),
        (
            TtsRequest::TextVoice472a8ec3(TtsRequestTextVoice472a8ec3 {
                emotion: None,
                language: None,
                model: None,
                output: None,
                pitch_bias: None,
                replacements: None,
                speed: None,
                text: "Hello".into(),
                text_normalization: None,
                timestamp_delivery: None,
                timestamp_granularity: None,
                voice: "existing-voice".into(),
                voice_transform: TtsRequestText77d171beVoiceTransform {
                    brightness: None,
                    crispness: None,
                    effect: None,
                    softness: None,
                },
                volume_scale: None,
            }),
            Expected {
                live: false,
                formula: false,
                blend: false,
                effects: true,
                split: false,
            },
        ),
        (
            TtsRequest::TextVoice6862a939(TtsRequestTextVoice6862a939 {
                emotion: None,
                formula_reading: Default::default(),
                language: None,
                model: None,
                output: None,
                pitch_bias: None,
                replacements: None,
                speed: None,
                text: "Hello".into(),
                text_normalization: None,
                timestamp_delivery: None,
                timestamp_granularity: None,
                voice: "existing-voice".into(),
                voice_transform: TtsRequestText77d171beVoiceTransform {
                    brightness: None,
                    crispness: None,
                    effect: None,
                    softness: None,
                },
                volume_scale: None,
            }),
            Expected {
                live: false,
                formula: true,
                blend: false,
                effects: true,
                split: false,
            },
        ),
        (
            TtsRequest::TextVoice7c08f303(TtsRequestTextVoice7c08f303 {
                emotion: None,
                formula_reading: Default::default(),
                language: None,
                model: None,
                output: None,
                pitch_bias: None,
                replacements: None,
                speed: None,
                text: "Hello".into(),
                text_normalization: None,
                timestamp_delivery: None,
                timestamp_granularity: None,
                voice: "existing-voice".into(),
                volume_scale: None,
            }),
            Expected {
                live: false,
                formula: true,
                blend: false,
                effects: false,
                split: false,
            },
        ),
        (
            TtsRequest::TextVoice9b47fc40(TtsRequestTextVoice9b47fc40 {
                emotion: None,
                language: None,
                model: None,
                output: None,
                pitch_bias: None,
                replacements: None,
                speed: None,
                text: "Hello".into(),
                text_normalization: None,
                timestamp_delivery: None,
                timestamp_granularity: None,
                voice: "existing-voice".into(),
                volume_scale: None,
            }),
            Expected {
                live: false,
                formula: false,
                blend: false,
                effects: false,
                split: false,
            },
        ),
        (
            TtsRequest::StreamingText1aae4cf9(TtsRequestStreamingText1aae4cf9 {
                emotion: None,
                language: None,
                language_text_normalization: None,
                model: None,
                output: None,
                pitch_bias: None,
                replacements: None,
                speed: None,
                split_turns: None,
                text: source(vec![Input::String("Hello".into())]),
                voice_blend: vec![TtsRequestText77d171beVoiceBlendItem {
                    voice: "blend".into(),
                    weight: 100.0,
                }],
                voice_transform: TtsRequestText77d171beVoiceTransform {
                    brightness: None,
                    crispness: None,
                    effect: None,
                    softness: None,
                },
                volume_scale: None,
            }),
            Expected {
                live: true,
                formula: false,
                blend: true,
                effects: true,
                split: true,
            },
        ),
        (
            TtsRequest::StreamingText09035640(TtsRequestStreamingText09035640 {
                emotion: None,
                formula_reading: Default::default(),
                language: None,
                language_text_normalization: None,
                model: None,
                output: None,
                pitch_bias: None,
                replacements: None,
                speed: None,
                split_turns: None,
                text: source(vec![Input::String("Hello".into())]),
                voice_blend: vec![TtsRequestText77d171beVoiceBlendItem {
                    voice: "blend".into(),
                    weight: 100.0,
                }],
                voice_transform: TtsRequestText77d171beVoiceTransform {
                    brightness: None,
                    crispness: None,
                    effect: None,
                    softness: None,
                },
                volume_scale: None,
            }),
            Expected {
                live: true,
                formula: true,
                blend: true,
                effects: true,
                split: true,
            },
        ),
        (
            TtsRequest::StreamingTexte79a87b2(TtsRequestStreamingTexte79a87b2 {
                emotion: None,
                formula_reading: Default::default(),
                language: None,
                language_text_normalization: None,
                model: None,
                output: None,
                pitch_bias: None,
                replacements: None,
                speed: None,
                split_turns: None,
                text: source(vec![Input::String("Hello".into())]),
                voice_blend: vec![TtsRequestText77d171beVoiceBlendItem {
                    voice: "blend".into(),
                    weight: 100.0,
                }],
                volume_scale: None,
            }),
            Expected {
                live: true,
                formula: true,
                blend: true,
                effects: false,
                split: true,
            },
        ),
        (
            TtsRequest::StreamingTextb71a212f(TtsRequestStreamingTextb71a212f {
                emotion: None,
                language: None,
                language_text_normalization: None,
                model: None,
                output: None,
                pitch_bias: None,
                replacements: None,
                speed: None,
                split_turns: None,
                text: source(vec![Input::String("Hello".into())]),
                voice_blend: vec![TtsRequestText77d171beVoiceBlendItem {
                    voice: "blend".into(),
                    weight: 100.0,
                }],
                volume_scale: None,
            }),
            Expected {
                live: true,
                formula: false,
                blend: true,
                effects: false,
                split: true,
            },
        ),
        (
            TtsRequest::StreamingTextVoice84ca6717(TtsRequestStreamingTextVoice84ca6717 {
                emotion: None,
                language: None,
                language_text_normalization: None,
                model: None,
                output: None,
                pitch_bias: None,
                replacements: None,
                speed: None,
                split_turns: None,
                text: source(vec![Input::String("Hello".into())]),
                voice: "existing-voice".into(),
                voice_transform: TtsRequestText77d171beVoiceTransform {
                    brightness: None,
                    crispness: None,
                    effect: None,
                    softness: None,
                },
                volume_scale: None,
            }),
            Expected {
                live: true,
                formula: false,
                blend: false,
                effects: true,
                split: true,
            },
        ),
        (
            TtsRequest::StreamingTextVoicee1061835(TtsRequestStreamingTextVoicee1061835 {
                emotion: None,
                formula_reading: Default::default(),
                language: None,
                language_text_normalization: None,
                model: None,
                output: None,
                pitch_bias: None,
                replacements: None,
                speed: None,
                split_turns: None,
                text: source(vec![Input::String("Hello".into())]),
                voice: "existing-voice".into(),
                voice_transform: TtsRequestText77d171beVoiceTransform {
                    brightness: None,
                    crispness: None,
                    effect: None,
                    softness: None,
                },
                volume_scale: None,
            }),
            Expected {
                live: true,
                formula: true,
                blend: false,
                effects: true,
                split: true,
            },
        ),
        (
            TtsRequest::StreamingTextVoice94f805c2(TtsRequestStreamingTextVoice94f805c2 {
                emotion: None,
                formula_reading: Default::default(),
                language: None,
                language_text_normalization: None,
                model: None,
                output: None,
                pitch_bias: None,
                replacements: None,
                speed: None,
                split_turns: None,
                text: source(vec![Input::String("Hello".into())]),
                voice: "existing-voice".into(),
                volume_scale: None,
            }),
            Expected {
                live: true,
                formula: true,
                blend: false,
                effects: false,
                split: true,
            },
        ),
        (
            TtsRequest::StreamingTextVoice9e2e17ce(TtsRequestStreamingTextVoice9e2e17ce {
                emotion: None,
                language: None,
                language_text_normalization: None,
                model: None,
                output: None,
                pitch_bias: None,
                replacements: None,
                speed: None,
                split_turns: None,
                text: source(vec![Input::String("Hello".into())]),
                voice: "existing-voice".into(),
                volume_scale: None,
            }),
            Expected {
                live: true,
                formula: false,
                blend: false,
                effects: false,
                split: true,
            },
        ),
    ];
    assert_eq!(requests.len(), 48);
    for (r, expected) in requests {
        let _validate = validate_request(&r).unwrap();
        let c = settings::settings(r);
        let Expected {
            live,
            formula,
            blend,
            effects,
            split,
        } = expected;
        assert_eq!(c.input.is_some(), live);
        assert_eq!(c.text.is_none(), live);
        assert_eq!(c.timing, None);
        assert_eq!(
            c.wire["language_boost"],
            JsonValue::String(if formula { "Chinese" } else { "auto" }.into())
        );
        let JsonValue::Object(voice) = &c.wire["voice_setting"] else {
            panic!("voice")
        };
        assert_eq!(
            voice["voice_id"],
            JsonValue::String(if blend { "" } else { "existing-voice" }.into())
        );
        assert_eq!(voice["latex_read"], JsonValue::Bool(formula));
        assert_eq!(c.wire.get("timbre_weights").is_some(), blend);
        assert_eq!(c.wire.get("voice_modify").is_some(), effects);
        assert_eq!(
            c.wire.get("continuous_sound"),
            if split {
                Some(&JsonValue::Bool(false))
            } else {
                None
            }
        );
    }
}
#[test]
fn codecs_resolve_native_formats_without_guessing_pcm_encoding() {
    use super::super::format::IntoAudio;
    let formats = vec![
        TtsRequestText77d171beOutputMp3 {
            bit_rate_bps: None,
            channel_count: None,
            constant_bit_rate: None,
            format: Default::default(),
            sample_rate_hz: None,
        }
        .into_audio(),
        TtsRequestText77d171beOutputFlac {
            channel_count: None,
            format: Default::default(),
            sample_rate_hz: None,
        }
        .into_audio(),
        TtsRequestText77d171beOutputWav {
            channel_count: None,
            format: Default::default(),
            sample_rate_hz: None,
        }
        .into_audio(),
        TtsRequestTextf2dcc77eOutputMulaw {
            channel_count: None,
            format: Default::default(),
            sample_rate_hz: None,
        }
        .into_audio(),
        TtsRequestTextf2dcc77eOutputWav6dd8e06a {
            channel_count: None,
            format: Default::default(),
            sample_encoding: Default::default(),
            sample_rate_hz: None,
        }
        .into_audio(),
        TtsRequestTextf2dcc77eOutputOggOpus {
            channel_count: None,
            format: Default::default(),
            sample_rate_hz: None,
        }
        .into_audio(),
    ];
    for (audio, (format, rate)) in formats.into_iter().zip([
        ("mp3", 32000.0),
        ("flac", 32000.0),
        ("wav", 32000.0),
        ("pcmu_raw", 8000.0),
        ("pcmu_wav", 8000.0),
        ("opus", 24000.0),
    ]) {
        let (wire, native) = audio.wire(false);
        assert_eq!(native, format);
        assert_eq!(wire["sample_rate"], JsonValue::Number(rate));
        assert_eq!(wire["channel"], JsonValue::Number(1.0));
        if format == "mp3" {
            assert_eq!(wire["force_cbr"], JsonValue::Bool(false));
            assert_eq!(wire["bitrate"], JsonValue::Number(128000.0));
        }
    }
}
