import { describe, expect, test } from "bun:test";
import type { Fetch } from "../../runtime/fetch.ts";
import { createVoice, listVoices, synthesize, synthesizeWithTimestamps } from "./index.ts";
const auth = { typecast: { apiKey: "key" } } as const;
describe("Typecast", () => {
  test("streams speech with model-specific delivery controls", async () => { let url = ""; let body: any; const fetch: Fetch = async (input, init) => { url = String(input); body = JSON.parse(String(init?.body)); return new Response(Uint8Array.of(1)); }; expect(await Array.fromAsync(synthesize({ text: "hello", voice: "tc_voice", voiceSource: "catalog", model: "ssfm-v30", language: "eng", output: { format: "wav", sampleRateHz: 32000 }, emotion: "happy", emotionIntensity: 1.5, volumeScale: 1.2 }, { auth, fetch }))).toEqual([Uint8Array.of(1)]); expect(url).toEndWith("/v1/text-to-speech/stream"); expect(body).toMatchObject({ model: "ssfm-v30", prompt: { emotion_type: "preset", emotion_preset: "happy", emotion_intensity: 1.5 }, output: { volume: 120 } }); });
  test("composes speech and pauses", async () => { let body: any; const fetch: Fetch = async (_input, init) => { body = JSON.parse(String(init?.body)); return new Response(Uint8Array.of(2)); }; await Array.fromAsync(synthesize({ segments: [{ text: "hi", voice: "uc_voice", model: "ssfm-v21", language: "eng", output: { format: "wav", sampleRateHz: 44100 } }, { pauseSeconds: 1 }] }, { auth, fetch })); expect(body.segments).toEqual([{ type: "tts", voice_id: "uc_voice", text: "hi", model: "ssfm-v21", language: "eng", output: { audio_format: "wav" } }, { type: "pause", duration_seconds: 1 }]); });
  test("returns native chunk-correlated timestamps", async () => { const fetch: Fetch = async () => Response.json({ audio: "AQI=", audio_format: "wav", audio_duration: 0.5, words: [{ text: "hi", start: 0, end: 0.5 }], characters: null }); expect(await Array.fromAsync(synthesizeWithTimestamps({ text: "hi", voice: "tc_voice", model: "ssfm-v21", language: "eng", output: { format: "wav", sampleRateHz: 44100 }, timestampGranularity: "word" }, { auth, fetch }))).toEqual([{ correlation: "chunk", audio: Uint8Array.of(1, 2), timestamps: [{ kind: "word", value: "hi", startTimeMs: 0, endTimeMs: 500 }] }]); });
  test("lists and creates existing custom voices", async () => { const requests: { url: string; init?: RequestInit }[] = []; const fetch: Fetch = async (input, init) => { requests.push({ url: String(input), init }); return Response.json(input.toString().includes("instant-clone") ? { voice_id: "uc_new", name: "Mine", model: "ssfm-v30", source: "instant", status: "completed", created_at: "now" } : []); }; expect(await listVoices({ model: "ssfm-v30", source: "custom" }, { auth, fetch })).toEqual([]); expect((await createVoice({ name: "Mine", model: "ssfm-v30", audio: Uint8Array.of(1), mediaType: "audio/wav" }, { auth, fetch })).voice_id).toBe("uc_new"); expect(requests[0]!.url).toContain("voice_type=custom"); expect(requests[1]!.init?.body).toBeInstanceOf(FormData); });
});
