package typecast

import (
	schema "github.com/speechswitch/client/sdks/go/generated/typecast"
	"github.com/speechswitch/client/sdks/go/runtime"
)

func fixtureRequests() []schema.TtsRequest {
	return []schema.TtsRequest{
		schema.TtsRequestAsSsfmV21TextVoicef82be0f4{Value: schema.TtsRequestSsfmV21TextVoicef82be0f4{Text: " Hello <|0.3s|> ", Voice: "tc_voice"}},
		schema.TtsRequestAsSsfmV21TextVoicec8409957{Value: schema.TtsRequestSsfmV21TextVoicec8409957{Text: "안녕!", Voice: "uc_voice", Language: runtime.Some(schema.TtsRequestObjectSegmentsItemSsfmV21TextVoiceb3babbe2Language(schema.TtsRequestObjectSegmentsItemSsfmV21TextVoiceb3babbe2LanguageAsKo{})), TimestampGranularity: schema.TtsRequestSsfmV21TextVoicec8409957TimestampGranularityAsWord{}}},
		schema.TtsRequestAsSsfmV21TextVoiceb54b9734{Value: schema.TtsRequestSsfmV21TextVoiceb54b9734{Text: "Hi", Voice: "tc_voice", VolumeScale: 0, RandomSeed: runtime.Some(0.0), Emotion: runtime.Some(schema.TtsRequestObjectSegmentsItemSsfmV21TextVoiceb3babbe2Emotion(schema.TtsRequestObjectSegmentsItemSsfmV21TextVoiceb3babbe2EmotionAsAngry{})), EmotionIntensity: runtime.Some(0.0)}},
		schema.TtsRequestAsSsfmV30TextVoicec9d5257e{Value: schema.TtsRequestSsfmV30TextVoicec9d5257e{Text: "Hi", Voice: "uc_voice", Emotion: runtime.Some(schema.TtsRequestObjectSegmentsItemSsfmV30TextVoiceaa70b792Emotion(schema.TtsRequestObjectSegmentsItemSsfmV30TextVoiceaa70b792EmotionAsWhisper{})), Language: runtime.Some(schema.TtsRequestObjectSegmentsItemSsfmV30TextVoiceaa70b792Language(schema.TtsRequestObjectSegmentsItemSsfmV30TextVoiceaa70b792LanguageAsHi{})), PitchSemitones: runtime.Some(-12.0), Speed: runtime.Some(.5), Output: runtime.Some(schema.TtsRequestSsfmV21TextVoicef82be0f4Output(schema.TtsRequestSsfmV21TextVoicef82be0f4OutputAsMp3{Value: schema.TtsRequestObjectOutputMp3{BitRateBps: runtime.Some(schema.TtsRequestObjectOutputMp3BitRateBps{}), SampleRateHz: runtime.Some(schema.TtsRequestObjectOutputWavSampleRateHz{})}}))}},
		schema.TtsRequestAsSsfmV30TextVoiceda7d6fa9{Value: schema.TtsRequestSsfmV30TextVoiceda7d6fa9{Text: "안녕!", Voice: "tc_voice", Emotion: runtime.Some(schema.TtsRequestObjectSegmentsItemSsfmV30TextVoiceaa70b792Emotion(schema.TtsRequestObjectSegmentsItemSsfmV30TextVoiceaa70b792EmotionAsToneup{})), EmotionIntensity: runtime.Some(2.0), TimestampGranularity: schema.TtsRequestSsfmV21TextVoicec8409957TimestampGranularityAsArray{Value: []schema.TtsRequestSsfmV21TextVoicec8409957TimestampGranularityArrayItem{schema.TtsRequestSsfmV21TextVoicec8409957TimestampGranularityArrayItemAsCharacter{}, schema.TtsRequestSsfmV21TextVoicec8409957TimestampGranularityArrayItemAsWord{}, schema.TtsRequestSsfmV21TextVoicec8409957TimestampGranularityArrayItemAsWord{}}}}},
		schema.TtsRequestAsSsfmV30TextVoice2e7e5231{Value: schema.TtsRequestSsfmV30TextVoice2e7e5231{Text: "Hi", Voice: "tc_voice", VolumeScale: .005, Speed: runtime.Some(2.0), RandomSeed: runtime.Some(4294967295.0)}},
		schema.TtsRequestAsSsfmV30TextVoicebb79df90{Value: schema.TtsRequestSsfmV30TextVoicebb79df90{Text: "Hi", Voice: "uc_voice", Language: runtime.Some(schema.TtsRequestObjectSegmentsItemSsfmV30TextVoiceaa70b792Language(schema.TtsRequestObjectSegmentsItemSsfmV30TextVoiceaa70b792LanguageAsAuto{})), ContextBefore: runtime.Some(schema.TtsRequestObjectSegmentsItemSsfmV30TextVoice0e2e956cContextAfter{Text: "Before"}), ContextAfter: runtime.Some(schema.TtsRequestObjectSegmentsItemSsfmV30TextVoice0e2e956cContextAfter{Text: "After"}), TargetLoudnessLufs: runtime.Some(0.0)}},
		schema.TtsRequestAsSsfmV30TextVoice862867af{Value: schema.TtsRequestSsfmV30TextVoice862867af{Text: "안녕!", Voice: "tc_voice", TimestampGranularity: schema.TtsRequestSsfmV21TextVoicec8409957TimestampGranularityAsCharacter{}}},
		schema.TtsRequestAsSsfmV30TextVoicec3047c31{Value: schema.TtsRequestSsfmV30TextVoicec3047c31{Text: "Hi", Voice: "uc_voice", VolumeScale: 2, ContextBefore: runtime.Some(schema.TtsRequestObjectSegmentsItemSsfmV30TextVoice0e2e956cContextAfter{Text: ""})}},
		schema.TtsRequestAsSsfmV30TextVoiceda7d6fa9{Value: schema.TtsRequestSsfmV30TextVoiceda7d6fa9{Text: "Hi", Voice: "tc_voice", TimestampGranularity: schema.TtsRequestSsfmV21TextVoicec8409957TimestampGranularityAsArray{Value: []schema.TtsRequestSsfmV21TextVoicec8409957TimestampGranularityArrayItem{}}}},
		schema.TtsRequestAsSsfmV21TextVoicef82be0f4{Value: schema.TtsRequestSsfmV21TextVoicef82be0f4{Text: "Hi", Voice: "tc_voice", Output: runtime.Some(schema.TtsRequestSsfmV21TextVoicef82be0f4Output(schema.TtsRequestSsfmV21TextVoicef82be0f4OutputAsWav{Value: schema.TtsRequestSsfmV21TextVoicef82be0f4OutputWav{SampleRateHz: runtime.Some(schema.TtsRequestSsfmV21TextVoicef82be0f4OutputWavSampleRateHz(schema.TtsRequestSsfmV21TextVoicef82be0f4OutputWavSampleRateHzAsNumber44100{}))}}))}},
		schema.TtsRequestAsObject{Value: schema.TtsRequestObject{Output: runtime.Some(schema.TtsRequestObjectOutput(schema.TtsRequestObjectOutputAsMp3{})), Segments: []schema.TtsRequestObjectSegmentsItem{
			schema.TtsRequestObjectSegmentsItemAsSsfmV21TextVoice4e8a729e{Value: schema.TtsRequestObjectSegmentsItemSsfmV21TextVoice4e8a729e{Text: "A", Voice: "tc_one", VolumeScale: runtime.Some(0.0)}},
			schema.TtsRequestObjectSegmentsItemAsSsfmV21TextVoiceb3babbe2{Value: schema.TtsRequestObjectSegmentsItemSsfmV21TextVoiceb3babbe2{Text: "B", Voice: "uc_two", TargetLoudnessLufs: -70}},
			schema.TtsRequestObjectSegmentsItemAsSsfmV30TextVoice0a18e1a3{Value: schema.TtsRequestObjectSegmentsItemSsfmV30TextVoice0a18e1a3{Text: "C", Voice: "tc_three", Emotion: runtime.Some(schema.TtsRequestObjectSegmentsItemSsfmV30TextVoiceaa70b792Emotion(schema.TtsRequestObjectSegmentsItemSsfmV30TextVoiceaa70b792EmotionAsWhisper{}))}},
			schema.TtsRequestObjectSegmentsItemAsSsfmV30TextVoiceaa70b792{Value: schema.TtsRequestObjectSegmentsItemSsfmV30TextVoiceaa70b792{Text: "D", Voice: "tc_four", TargetLoudnessLufs: 0}},
			schema.TtsRequestObjectSegmentsItemAsObject{Value: schema.TtsRequestObjectSegmentsItemObject{PauseMs: 500}},
			schema.TtsRequestObjectSegmentsItemAsSsfmV30TextVoice9cf1a777{Value: schema.TtsRequestObjectSegmentsItemSsfmV30TextVoice9cf1a777{Text: "E", Voice: "uc_five", VolumeScale: runtime.Some(1.0)}},
			schema.TtsRequestObjectSegmentsItemAsSsfmV30TextVoice0e2e956c{Value: schema.TtsRequestObjectSegmentsItemSsfmV30TextVoice0e2e956c{Text: "F", Voice: "uc_six", TargetLoudnessLufs: -20, ContextAfter: runtime.Some(schema.TtsRequestObjectSegmentsItemSsfmV30TextVoice0e2e956cContextAfter{Text: "Next"})}},
		}}},
	}
}
