use super::*;
pub(super) fn timed_tts(
    input: StreamingInput<settings::Input>,
) -> TtsRequestStreamingTextVoice04078405 {
    TtsRequestStreamingTextVoice04078405 {
        input_type: None,
        language: None,
        model: TtsRequestTextVoice4a0120aeModel::FlashV2(Default::default()),
        output: TtsRequestStreamingTextVoice194990a6Output::Mp31de777c9(
            TtsRequestTextVoice4a0120aeOutputMp31de777c9 {
                bit_rate_bps: Default::default(),
                format: Default::default(),
                sample_rate_hz: Default::default(),
            },
        ),
        pronunciation_dictionaries: None,
        random_seed: None,
        speed: None,
        stability: None,
        style_exaggeration: None,
        text: input,
        text_buffering: None,
        text_buffer_thresholds: None,
        text_normalization: None,
        timestamp_granularity: Default::default(),
        timestamp_text: None,
        voice: "custom/id".into(),
        voice_boost: None,
        voice_similarity: None,
    }
}
pub(super) fn timed_dialogue(
    input: StreamingInput<settings::DialogueInput>,
) -> TtsRequestElevenV3StreamingTextVoicec9aef256 {
    TtsRequestElevenV3StreamingTextVoicec9aef256 {
        language: None,
        model: Default::default(),
        output: TtsRequestStreamingTextVoice194990a6Output::Mp31de777c9(
            TtsRequestTextVoice4a0120aeOutputMp31de777c9 {
                bit_rate_bps: Default::default(),
                format: Default::default(),
                sample_rate_hz: Default::default(),
            },
        ),
        pronunciation_dictionaries: None,
        random_seed: None,
        stability: None,
        text: input,
        text_normalization: None,
        timestamp_granularity: Default::default(),
        timestamp_text: None,
        voice: "custom/id".into(),
    }
}

pub(super) fn requests() -> Vec<TtsRequest> {
    vec![
        TtsRequest::TextVoice4a0120ae(TtsRequestTextVoice4a0120ae {
            context_after: None,
            context_before: None,
            language: None,
            language_text_normalization: None,
            latency_optimization: None,
            model: TtsRequestTextVoice4a0120aeModel::FlashV25(Default::default()),
            output: TtsRequestTextVoice4a0120aeOutput::Mp356cad1fb(
                TtsRequestTextVoice4a0120aeOutputMp356cad1fb {
                    bit_rate_bps: None,
                    format: Default::default(),
                    sample_rate_hz: None,
                },
            ),
            pronunciation_dictionaries: None,
            random_seed: None,
            speed: None,
            stability: None,
            style_exaggeration: None,
            text: "Hello".into(),
            text_normalization: None,
            voice: "custom/id".into(),
            voice_boost: None,
            voice_similarity: None,
        }),
        TtsRequest::TextVoice4a0120ae(TtsRequestTextVoice4a0120ae {
            context_after: Some(TtsRequestTextVoice4a0120aeContextAfter::Object(
                TtsRequestTextVoice4a0120aeContextAfterObject {
                    request_ids: vec!["next".into()],
                },
            )),
            context_before: Some(TtsRequestTextVoice4a0120aeContextAfter::Text(
                TtsRequestTextVoice4a0120aeContextAfterText { text: "".into() },
            )),
            language: Some("ja".into()),
            language_text_normalization: Some(
                TtsRequestTextVoice4a0120aeLanguageTextNormalization::True(Default::default()),
            ),
            latency_optimization: None,
            model: TtsRequestTextVoice4a0120aeModel::FlashV2(Default::default()),
            output: TtsRequestTextVoice4a0120aeOutput::Pcm(TtsRequestTextVoice4a0120aeOutputPcm {
                byte_order: Some(Default::default()),
                format: Default::default(),
                sample_encoding: Some(Default::default()),
                sample_rate_hz: TtsRequestTextVoice4a0120aeOutputPcmSampleRateHz::Number24000(
                    Default::default(),
                ),
            }),
            pronunciation_dictionaries: Some(vec![
                TtsRequestTextVoice4a0120aePronunciationDictionariesItem {
                    id: "lex".into(),
                    version_id: None,
                },
                TtsRequestTextVoice4a0120aePronunciationDictionariesItem {
                    id: "lex2".into(),
                    version_id: Some("v2".into()),
                },
            ]),
            random_seed: Some(4294967295.0),
            speed: Some(0.7),
            stability: Some(0.0),
            style_exaggeration: Some(0.3),
            text: "雪\n\"hi\"".into(),
            text_normalization: Some(TtsRequestTextVoice4a0120aeTextNormalization::False(
                Default::default(),
            )),
            voice: "custom/id".into(),
            voice_boost: Some(TtsRequestTextVoice4a0120aeLanguageTextNormalization::False(
                Default::default(),
            )),
            voice_similarity: Some(0.2),
        }),
        TtsRequest::MultilingualV2TextVoice6b4236de(TtsRequestMultilingualV2TextVoice6b4236de {
            context_after: Some(TtsRequestTextVoice4a0120aeContextAfter::Text(
                TtsRequestTextVoice4a0120aeContextAfterText {
                    text: "after".into(),
                },
            )),
            context_before: Some(TtsRequestTextVoice4a0120aeContextAfter::Object(
                TtsRequestTextVoice4a0120aeContextAfterObject {
                    request_ids: vec!["1".into(), "2".into(), "3".into()],
                },
            )),
            language_text_normalization: None,
            latency_optimization: Default::default(),
            model: Default::default(),
            output: TtsRequestTextVoice4a0120aeOutput::Wav(TtsRequestTextVoice4a0120aeOutputWav {
                byte_order: None,
                format: Default::default(),
                sample_encoding: None,
                sample_rate_hz: TtsRequestTextVoice4a0120aeOutputPcmSampleRateHz::Number48000(
                    Default::default(),
                ),
            }),
            pronunciation_dictionaries: Some(vec![]),
            random_seed: None,
            speed: None,
            stability: None,
            style_exaggeration: None,
            text: "Hello".into(),
            text_normalization: Some(Default::default()),
            voice: "v".into(),
            voice_boost: None,
            voice_similarity: None,
        }),
        TtsRequest::ElevenV3TextVoiceedc22df3(TtsRequestElevenV3TextVoiceedc22df3 {
            context_after: None,
            context_before: None,
            language: Some("en".into()),
            language_text_normalization: None,
            latency_optimization: None,
            model: Default::default(),
            output: TtsRequestTextVoice4a0120aeOutput::Mp31de777c9(
                TtsRequestTextVoice4a0120aeOutputMp31de777c9 {
                    bit_rate_bps: Default::default(),
                    format: Default::default(),
                    sample_rate_hz: Default::default(),
                },
            ),
            pronunciation_dictionaries: None,
            random_seed: Some(0.0),
            stability: Some(0.5),
            text: "Hello".into(),
            text_normalization: Some(TtsRequestTextVoice4a0120aeTextNormalization::True(
                Default::default(),
            )),
            voice: "v".into(),
        }),
        TtsRequest::TextVoice4a0120ae(TtsRequestTextVoice4a0120ae {
            context_after: None,
            context_before: None,
            language: None,
            language_text_normalization: None,
            latency_optimization: Some(TtsRequestTextVoice4a0120aeLatencyOptimization::Moderate(
                Default::default(),
            )),
            model: TtsRequestTextVoice4a0120aeModel::FlashV25(Default::default()),
            output: TtsRequestTextVoice4a0120aeOutput::Mp34def27fa(
                TtsRequestTextVoice4a0120aeOutputMp34def27fa {
                    bit_rate_bps: Default::default(),
                    format: Default::default(),
                    sample_rate_hz: Default::default(),
                },
            ),
            pronunciation_dictionaries: None,
            random_seed: None,
            speed: None,
            stability: None,
            style_exaggeration: None,
            text: "Hello".into(),
            text_normalization: None,
            voice: "v".into(),
            voice_boost: None,
            voice_similarity: None,
        }),
        TtsRequest::TextVoice4a0120ae(TtsRequestTextVoice4a0120ae {
            context_after: None,
            context_before: None,
            language: None,
            language_text_normalization: None,
            latency_optimization: Some(TtsRequestTextVoice4a0120aeLatencyOptimization::Strong(
                Default::default(),
            )),
            model: TtsRequestTextVoice4a0120aeModel::FlashV25(Default::default()),
            output: TtsRequestTextVoice4a0120aeOutput::OggOpus(
                TtsRequestTextVoice4a0120aeOutputOggOpus {
                    bit_rate_bps: None,
                    format: Default::default(),
                    sample_rate_hz: None,
                },
            ),
            pronunciation_dictionaries: None,
            random_seed: None,
            speed: None,
            stability: None,
            style_exaggeration: None,
            text: "Hello".into(),
            text_normalization: None,
            voice: "v".into(),
            voice_boost: None,
            voice_similarity: None,
        }),
        TtsRequest::TextVoice4a0120ae(TtsRequestTextVoice4a0120ae {
            context_after: None,
            context_before: None,
            language: None,
            language_text_normalization: None,
            latency_optimization: Some(TtsRequestTextVoice4a0120aeLatencyOptimization::Aggressive(
                Default::default(),
            )),
            model: TtsRequestTextVoice4a0120aeModel::FlashV25(Default::default()),
            output: TtsRequestTextVoice4a0120aeOutput::Object(
                TtsRequestTextVoice4a0120aeOutputObject {
                    format: TtsRequestTextVoice4a0120aeOutputObjectFormat::Mulaw(Default::default()),
                    sample_rate_hz: None,
                },
            ),
            pronunciation_dictionaries: None,
            random_seed: None,
            speed: None,
            stability: None,
            style_exaggeration: None,
            text: "Hello".into(),
            text_normalization: None,
            voice: "v".into(),
            voice_boost: None,
            voice_similarity: None,
        }),
        TtsRequest::TextVoice4a0120ae(TtsRequestTextVoice4a0120ae {
            context_after: None,
            context_before: None,
            language: None,
            language_text_normalization: None,
            latency_optimization: Some(TtsRequestTextVoice4a0120aeLatencyOptimization::None(
                Default::default(),
            )),
            model: TtsRequestTextVoice4a0120aeModel::FlashV25(Default::default()),
            output: TtsRequestTextVoice4a0120aeOutput::Object(
                TtsRequestTextVoice4a0120aeOutputObject {
                    format: TtsRequestTextVoice4a0120aeOutputObjectFormat::Alaw(Default::default()),
                    sample_rate_hz: Some(Default::default()),
                },
            ),
            pronunciation_dictionaries: None,
            random_seed: None,
            speed: None,
            stability: None,
            style_exaggeration: None,
            text: "Hello".into(),
            text_normalization: None,
            voice: "v".into(),
            voice_boost: None,
            voice_similarity: None,
        }),
        TtsRequest::TextVoiceac5e804b(TtsRequestTextVoiceac5e804b {
            context_after: None,
            context_before: None,
            language: None,
            language_text_normalization: None,
            latency_optimization: None,
            model: TtsRequestTextVoice4a0120aeModel::FlashV25(Default::default()),
            output: TtsRequestTextVoice4a0120aeOutput::Mp356cad1fb(
                TtsRequestTextVoice4a0120aeOutputMp356cad1fb {
                    bit_rate_bps: None,
                    format: Default::default(),
                    sample_rate_hz: None,
                },
            ),
            pronunciation_dictionaries: None,
            random_seed: None,
            speed: None,
            stability: None,
            style_exaggeration: None,
            text: "Hello".into(),
            text_normalization: None,
            timestamp_granularity: Default::default(),
            timestamp_text: Some(TtsRequestTextVoice9cb211adTimestampText::Normalized(
                Default::default(),
            )),
            voice: "v".into(),
            voice_boost: None,
            voice_similarity: None,
        }),
        TtsRequest::ElevenV3TextVoicef41607cd(TtsRequestElevenV3TextVoicef41607cd {
            context_after: None,
            context_before: None,
            language: None,
            language_text_normalization: None,
            latency_optimization: None,
            model: Default::default(),
            output: TtsRequestTextVoice4a0120aeOutput::Wav(TtsRequestTextVoice4a0120aeOutputWav {
                byte_order: None,
                format: Default::default(),
                sample_encoding: None,
                sample_rate_hz: TtsRequestTextVoice4a0120aeOutputPcmSampleRateHz::Number16000(
                    Default::default(),
                ),
            }),
            pronunciation_dictionaries: None,
            random_seed: None,
            stability: None,
            text: "Hello".into(),
            text_normalization: None,
            timestamp_granularity: Default::default(),
            timestamp_text: Some(TtsRequestTextVoice9cb211adTimestampText::Original(
                Default::default(),
            )),
            voice: "v".into(),
        }),
    ]
}
pub(super) fn flash() -> TtsRequestTextVoice4a0120ae {
    TtsRequestTextVoice4a0120ae {
        context_after: None,
        context_before: None,
        language: None,
        language_text_normalization: None,
        latency_optimization: None,
        model: TtsRequestTextVoice4a0120aeModel::FlashV2(Default::default()),
        output: TtsRequestTextVoice4a0120aeOutput::Mp31de777c9(
            TtsRequestTextVoice4a0120aeOutputMp31de777c9 {
                bit_rate_bps: Default::default(),
                format: Default::default(),
                sample_rate_hz: Default::default(),
            },
        ),
        pronunciation_dictionaries: None,
        random_seed: None,
        speed: None,
        stability: None,
        style_exaggeration: None,
        text: "Hello".into(),
        text_normalization: None,
        voice: "custom/id".into(),
        voice_boost: None,
        voice_similarity: None,
    }
}
pub(super) fn tts(input: StreamingInput<settings::Input>) -> TtsRequestStreamingTextVoice194990a6 {
    TtsRequestStreamingTextVoice194990a6 {
        input_type: None,
        language: None,
        model: TtsRequestTextVoice4a0120aeModel::FlashV2(Default::default()),
        output: TtsRequestStreamingTextVoice194990a6Output::Mp31de777c9(
            TtsRequestTextVoice4a0120aeOutputMp31de777c9 {
                bit_rate_bps: Default::default(),
                format: Default::default(),
                sample_rate_hz: Default::default(),
            },
        ),
        pronunciation_dictionaries: None,
        random_seed: None,
        speed: None,
        stability: None,
        style_exaggeration: None,
        text: input,
        text_buffering: None,
        text_buffer_thresholds: None,
        text_normalization: None,
        voice: "custom/id".into(),
        voice_boost: None,
        voice_similarity: None,
    }
}
pub(super) fn dialogue(
    input: StreamingInput<settings::DialogueInput>,
) -> TtsRequestElevenV3StreamingTextVoicef18e078f {
    TtsRequestElevenV3StreamingTextVoicef18e078f {
        language: None,
        model: Default::default(),
        output: TtsRequestStreamingTextVoice194990a6Output::Mp31de777c9(
            TtsRequestTextVoice4a0120aeOutputMp31de777c9 {
                bit_rate_bps: Default::default(),
                format: Default::default(),
                sample_rate_hz: Default::default(),
            },
        ),
        pronunciation_dictionaries: None,
        random_seed: None,
        stability: None,
        text: input,
        text_normalization: None,
        voice: "custom/id".into(),
    }
}

#[test]
fn all_generated_request_variants_convert_without_consuming_input() {
    let counts = Arc::new(Counts::default());
    let requests = vec![
        TtsRequest::TextVoice4a0120ae(TtsRequestTextVoice4a0120ae {
            context_after: None,
            context_before: None,
            language: None,
            language_text_normalization: None,
            latency_optimization: None,
            model: TtsRequestTextVoice4a0120aeModel::FlashV2(Default::default()),
            output: TtsRequestTextVoice4a0120aeOutput::Mp31de777c9(
                TtsRequestTextVoice4a0120aeOutputMp31de777c9 {
                    bit_rate_bps: Default::default(),
                    format: Default::default(),
                    sample_rate_hz: Default::default(),
                },
            ),
            pronunciation_dictionaries: None,
            random_seed: None,
            speed: None,
            stability: None,
            style_exaggeration: None,
            text: "hi".into(),
            text_normalization: None,
            voice: "hi".into(),
            voice_boost: None,
            voice_similarity: None,
        }),
        TtsRequest::TextVoice68b36b42(TtsRequestTextVoice68b36b42 {
            context_after: None,
            context_before: None,
            language: None,
            language_text_normalization: None,
            latency_optimization: Default::default(),
            model: TtsRequestTextVoice4a0120aeModel::FlashV2(Default::default()),
            output: TtsRequestTextVoice4a0120aeOutput::Mp31de777c9(
                TtsRequestTextVoice4a0120aeOutputMp31de777c9 {
                    bit_rate_bps: Default::default(),
                    format: Default::default(),
                    sample_rate_hz: Default::default(),
                },
            ),
            pronunciation_dictionaries: None,
            random_seed: None,
            speed: None,
            stability: None,
            style_exaggeration: None,
            text: "hi".into(),
            text_normalization: None,
            voice: "hi".into(),
            voice_boost: None,
            voice_similarity: None,
        }),
        TtsRequest::TextVoice9cb211ad(TtsRequestTextVoice9cb211ad {
            context_after: None,
            context_before: None,
            language: None,
            language_text_normalization: None,
            latency_optimization: Default::default(),
            model: TtsRequestTextVoice4a0120aeModel::FlashV2(Default::default()),
            output: TtsRequestTextVoice4a0120aeOutput::Mp31de777c9(
                TtsRequestTextVoice4a0120aeOutputMp31de777c9 {
                    bit_rate_bps: Default::default(),
                    format: Default::default(),
                    sample_rate_hz: Default::default(),
                },
            ),
            pronunciation_dictionaries: None,
            random_seed: None,
            speed: None,
            stability: None,
            style_exaggeration: None,
            text: "hi".into(),
            text_normalization: None,
            timestamp_granularity: Default::default(),
            timestamp_text: None,
            voice: "hi".into(),
            voice_boost: None,
            voice_similarity: None,
        }),
        TtsRequest::StreamingTextVoice194990a6(TtsRequestStreamingTextVoice194990a6 {
            input_type: None,
            language: None,
            model: TtsRequestTextVoice4a0120aeModel::FlashV2(Default::default()),
            output: TtsRequestStreamingTextVoice194990a6Output::Mp31de777c9(
                TtsRequestTextVoice4a0120aeOutputMp31de777c9 {
                    bit_rate_bps: Default::default(),
                    format: Default::default(),
                    sample_rate_hz: Default::default(),
                },
            ),
            pronunciation_dictionaries: None,
            random_seed: None,
            speed: None,
            stability: None,
            style_exaggeration: None,
            text: source(vec![], &counts, false),
            text_buffering: None,
            text_buffer_thresholds: None,
            text_normalization: None,
            voice: "hi".into(),
            voice_boost: None,
            voice_similarity: None,
        }),
        TtsRequest::TextVoiceac5e804b(TtsRequestTextVoiceac5e804b {
            context_after: None,
            context_before: None,
            language: None,
            language_text_normalization: None,
            latency_optimization: None,
            model: TtsRequestTextVoice4a0120aeModel::FlashV2(Default::default()),
            output: TtsRequestTextVoice4a0120aeOutput::Mp31de777c9(
                TtsRequestTextVoice4a0120aeOutputMp31de777c9 {
                    bit_rate_bps: Default::default(),
                    format: Default::default(),
                    sample_rate_hz: Default::default(),
                },
            ),
            pronunciation_dictionaries: None,
            random_seed: None,
            speed: None,
            stability: None,
            style_exaggeration: None,
            text: "hi".into(),
            text_normalization: None,
            timestamp_granularity: Default::default(),
            timestamp_text: None,
            voice: "hi".into(),
            voice_boost: None,
            voice_similarity: None,
        }),
        TtsRequest::StreamingTextVoice04078405(TtsRequestStreamingTextVoice04078405 {
            input_type: None,
            language: None,
            model: TtsRequestTextVoice4a0120aeModel::FlashV2(Default::default()),
            output: TtsRequestStreamingTextVoice194990a6Output::Mp31de777c9(
                TtsRequestTextVoice4a0120aeOutputMp31de777c9 {
                    bit_rate_bps: Default::default(),
                    format: Default::default(),
                    sample_rate_hz: Default::default(),
                },
            ),
            pronunciation_dictionaries: None,
            random_seed: None,
            speed: None,
            stability: None,
            style_exaggeration: None,
            text: source(vec![], &counts, false),
            text_buffering: None,
            text_buffer_thresholds: None,
            text_normalization: None,
            timestamp_granularity: Default::default(),
            timestamp_text: None,
            voice: "hi".into(),
            voice_boost: None,
            voice_similarity: None,
        }),
        TtsRequest::StreamingTextVoicef49cfea8(TtsRequestStreamingTextVoicef49cfea8 {
            input_type: None,
            language: None,
            model: TtsRequestTextVoice4a0120aeModel::FlashV2(Default::default()),
            output: TtsRequestStreamingTextVoice194990a6Output::Mp31de777c9(
                TtsRequestTextVoice4a0120aeOutputMp31de777c9 {
                    bit_rate_bps: Default::default(),
                    format: Default::default(),
                    sample_rate_hz: Default::default(),
                },
            ),
            pronunciation_dictionaries: None,
            random_seed: None,
            speed: None,
            stability: None,
            style_exaggeration: None,
            text: source(vec![], &counts, false),
            text_buffering: Default::default(),
            text_normalization: None,
            voice: "hi".into(),
            voice_boost: None,
            voice_similarity: None,
        }),
        TtsRequest::StreamingTextVoice282de2db(TtsRequestStreamingTextVoice282de2db {
            input_type: None,
            language: None,
            model: TtsRequestTextVoice4a0120aeModel::FlashV2(Default::default()),
            output: TtsRequestStreamingTextVoice194990a6Output::Mp31de777c9(
                TtsRequestTextVoice4a0120aeOutputMp31de777c9 {
                    bit_rate_bps: Default::default(),
                    format: Default::default(),
                    sample_rate_hz: Default::default(),
                },
            ),
            pronunciation_dictionaries: None,
            random_seed: None,
            speed: None,
            stability: None,
            style_exaggeration: None,
            text: source(vec![], &counts, false),
            text_buffering: Default::default(),
            text_normalization: None,
            timestamp_granularity: Default::default(),
            timestamp_text: None,
            voice: "hi".into(),
            voice_boost: None,
            voice_similarity: None,
        }),
        TtsRequest::MultilingualV2TextVoiceb7dcb211(TtsRequestMultilingualV2TextVoiceb7dcb211 {
            context_after: None,
            context_before: None,
            language_text_normalization: None,
            latency_optimization: None,
            model: Default::default(),
            output: TtsRequestTextVoice4a0120aeOutput::Mp31de777c9(
                TtsRequestTextVoice4a0120aeOutputMp31de777c9 {
                    bit_rate_bps: Default::default(),
                    format: Default::default(),
                    sample_rate_hz: Default::default(),
                },
            ),
            pronunciation_dictionaries: None,
            random_seed: None,
            speed: None,
            stability: None,
            style_exaggeration: None,
            text: "hi".into(),
            text_normalization: None,
            voice: "hi".into(),
            voice_boost: None,
            voice_similarity: None,
        }),
        TtsRequest::MultilingualV2TextVoice6b4236de(TtsRequestMultilingualV2TextVoice6b4236de {
            context_after: None,
            context_before: None,
            language_text_normalization: None,
            latency_optimization: Default::default(),
            model: Default::default(),
            output: TtsRequestTextVoice4a0120aeOutput::Mp31de777c9(
                TtsRequestTextVoice4a0120aeOutputMp31de777c9 {
                    bit_rate_bps: Default::default(),
                    format: Default::default(),
                    sample_rate_hz: Default::default(),
                },
            ),
            pronunciation_dictionaries: None,
            random_seed: None,
            speed: None,
            stability: None,
            style_exaggeration: None,
            text: "hi".into(),
            text_normalization: None,
            voice: "hi".into(),
            voice_boost: None,
            voice_similarity: None,
        }),
        TtsRequest::MultilingualV2TextVoiceca4ba9c1(TtsRequestMultilingualV2TextVoiceca4ba9c1 {
            context_after: None,
            context_before: None,
            language_text_normalization: None,
            latency_optimization: Default::default(),
            model: Default::default(),
            output: TtsRequestTextVoice4a0120aeOutput::Mp31de777c9(
                TtsRequestTextVoice4a0120aeOutputMp31de777c9 {
                    bit_rate_bps: Default::default(),
                    format: Default::default(),
                    sample_rate_hz: Default::default(),
                },
            ),
            pronunciation_dictionaries: None,
            random_seed: None,
            speed: None,
            stability: None,
            style_exaggeration: None,
            text: "hi".into(),
            text_normalization: None,
            timestamp_granularity: Default::default(),
            timestamp_text: None,
            voice: "hi".into(),
            voice_boost: None,
            voice_similarity: None,
        }),
        TtsRequest::MultilingualV2StreamingTextVoice90f3837b(
            TtsRequestMultilingualV2StreamingTextVoice90f3837b {
                input_type: None,
                model: Default::default(),
                output: TtsRequestStreamingTextVoice194990a6Output::Mp31de777c9(
                    TtsRequestTextVoice4a0120aeOutputMp31de777c9 {
                        bit_rate_bps: Default::default(),
                        format: Default::default(),
                        sample_rate_hz: Default::default(),
                    },
                ),
                pronunciation_dictionaries: None,
                random_seed: None,
                speed: None,
                stability: None,
                style_exaggeration: None,
                text: source(vec![], &counts, false),
                text_buffering: None,
                text_buffer_thresholds: None,
                text_normalization: None,
                voice: "hi".into(),
                voice_boost: None,
                voice_similarity: None,
            },
        ),
        TtsRequest::MultilingualV2TextVoice51150c25(TtsRequestMultilingualV2TextVoice51150c25 {
            context_after: None,
            context_before: None,
            language_text_normalization: None,
            latency_optimization: None,
            model: Default::default(),
            output: TtsRequestTextVoice4a0120aeOutput::Mp31de777c9(
                TtsRequestTextVoice4a0120aeOutputMp31de777c9 {
                    bit_rate_bps: Default::default(),
                    format: Default::default(),
                    sample_rate_hz: Default::default(),
                },
            ),
            pronunciation_dictionaries: None,
            random_seed: None,
            speed: None,
            stability: None,
            style_exaggeration: None,
            text: "hi".into(),
            text_normalization: None,
            timestamp_granularity: Default::default(),
            timestamp_text: None,
            voice: "hi".into(),
            voice_boost: None,
            voice_similarity: None,
        }),
        TtsRequest::MultilingualV2StreamingTextVoice7bc2227c(
            TtsRequestMultilingualV2StreamingTextVoice7bc2227c {
                input_type: None,
                model: Default::default(),
                output: TtsRequestStreamingTextVoice194990a6Output::Mp31de777c9(
                    TtsRequestTextVoice4a0120aeOutputMp31de777c9 {
                        bit_rate_bps: Default::default(),
                        format: Default::default(),
                        sample_rate_hz: Default::default(),
                    },
                ),
                pronunciation_dictionaries: None,
                random_seed: None,
                speed: None,
                stability: None,
                style_exaggeration: None,
                text: source(vec![], &counts, false),
                text_buffering: None,
                text_buffer_thresholds: None,
                text_normalization: None,
                timestamp_granularity: Default::default(),
                timestamp_text: None,
                voice: "hi".into(),
                voice_boost: None,
                voice_similarity: None,
            },
        ),
        TtsRequest::MultilingualV2StreamingTextVoice388d65c0(
            TtsRequestMultilingualV2StreamingTextVoice388d65c0 {
                input_type: None,
                model: Default::default(),
                output: TtsRequestStreamingTextVoice194990a6Output::Mp31de777c9(
                    TtsRequestTextVoice4a0120aeOutputMp31de777c9 {
                        bit_rate_bps: Default::default(),
                        format: Default::default(),
                        sample_rate_hz: Default::default(),
                    },
                ),
                pronunciation_dictionaries: None,
                random_seed: None,
                speed: None,
                stability: None,
                style_exaggeration: None,
                text: source(vec![], &counts, false),
                text_buffering: Default::default(),
                text_normalization: None,
                voice: "hi".into(),
                voice_boost: None,
                voice_similarity: None,
            },
        ),
        TtsRequest::MultilingualV2StreamingTextVoice1e73ed4e(
            TtsRequestMultilingualV2StreamingTextVoice1e73ed4e {
                input_type: None,
                model: Default::default(),
                output: TtsRequestStreamingTextVoice194990a6Output::Mp31de777c9(
                    TtsRequestTextVoice4a0120aeOutputMp31de777c9 {
                        bit_rate_bps: Default::default(),
                        format: Default::default(),
                        sample_rate_hz: Default::default(),
                    },
                ),
                pronunciation_dictionaries: None,
                random_seed: None,
                speed: None,
                stability: None,
                style_exaggeration: None,
                text: source(vec![], &counts, false),
                text_buffering: Default::default(),
                text_normalization: None,
                timestamp_granularity: Default::default(),
                timestamp_text: None,
                voice: "hi".into(),
                voice_boost: None,
                voice_similarity: None,
            },
        ),
        TtsRequest::ElevenV3TextVoiceedc22df3(TtsRequestElevenV3TextVoiceedc22df3 {
            context_after: None,
            context_before: None,
            language: None,
            language_text_normalization: None,
            latency_optimization: None,
            model: Default::default(),
            output: TtsRequestTextVoice4a0120aeOutput::Mp31de777c9(
                TtsRequestTextVoice4a0120aeOutputMp31de777c9 {
                    bit_rate_bps: Default::default(),
                    format: Default::default(),
                    sample_rate_hz: Default::default(),
                },
            ),
            pronunciation_dictionaries: None,
            random_seed: None,
            stability: None,
            text: "hi".into(),
            text_normalization: None,
            voice: "hi".into(),
        }),
        TtsRequest::ElevenV3TextVoicea067d696(TtsRequestElevenV3TextVoicea067d696 {
            context_after: None,
            context_before: None,
            language: None,
            language_text_normalization: None,
            latency_optimization: Default::default(),
            model: Default::default(),
            output: TtsRequestTextVoice4a0120aeOutput::Mp31de777c9(
                TtsRequestTextVoice4a0120aeOutputMp31de777c9 {
                    bit_rate_bps: Default::default(),
                    format: Default::default(),
                    sample_rate_hz: Default::default(),
                },
            ),
            pronunciation_dictionaries: None,
            random_seed: None,
            stability: None,
            text: "hi".into(),
            text_normalization: None,
            voice: "hi".into(),
        }),
        TtsRequest::ElevenV3TextVoiceb4b74c48(TtsRequestElevenV3TextVoiceb4b74c48 {
            context_after: None,
            context_before: None,
            language: None,
            language_text_normalization: None,
            latency_optimization: Default::default(),
            model: Default::default(),
            output: TtsRequestTextVoice4a0120aeOutput::Mp31de777c9(
                TtsRequestTextVoice4a0120aeOutputMp31de777c9 {
                    bit_rate_bps: Default::default(),
                    format: Default::default(),
                    sample_rate_hz: Default::default(),
                },
            ),
            pronunciation_dictionaries: None,
            random_seed: None,
            stability: None,
            text: "hi".into(),
            text_normalization: None,
            timestamp_granularity: Default::default(),
            timestamp_text: None,
            voice: "hi".into(),
        }),
        TtsRequest::ElevenV3StreamingTextVoicef18e078f(
            TtsRequestElevenV3StreamingTextVoicef18e078f {
                language: None,
                model: Default::default(),
                output: TtsRequestStreamingTextVoice194990a6Output::Mp31de777c9(
                    TtsRequestTextVoice4a0120aeOutputMp31de777c9 {
                        bit_rate_bps: Default::default(),
                        format: Default::default(),
                        sample_rate_hz: Default::default(),
                    },
                ),
                pronunciation_dictionaries: None,
                random_seed: None,
                stability: None,
                text: source(vec![], &counts, false),
                text_normalization: None,
                voice: "hi".into(),
            },
        ),
        TtsRequest::ElevenV3TextVoicef41607cd(TtsRequestElevenV3TextVoicef41607cd {
            context_after: None,
            context_before: None,
            language: None,
            language_text_normalization: None,
            latency_optimization: None,
            model: Default::default(),
            output: TtsRequestTextVoice4a0120aeOutput::Mp31de777c9(
                TtsRequestTextVoice4a0120aeOutputMp31de777c9 {
                    bit_rate_bps: Default::default(),
                    format: Default::default(),
                    sample_rate_hz: Default::default(),
                },
            ),
            pronunciation_dictionaries: None,
            random_seed: None,
            stability: None,
            text: "hi".into(),
            text_normalization: None,
            timestamp_granularity: Default::default(),
            timestamp_text: None,
            voice: "hi".into(),
        }),
        TtsRequest::ElevenV3StreamingTextVoicec9aef256(
            TtsRequestElevenV3StreamingTextVoicec9aef256 {
                language: None,
                model: Default::default(),
                output: TtsRequestStreamingTextVoice194990a6Output::Mp31de777c9(
                    TtsRequestTextVoice4a0120aeOutputMp31de777c9 {
                        bit_rate_bps: Default::default(),
                        format: Default::default(),
                        sample_rate_hz: Default::default(),
                    },
                ),
                pronunciation_dictionaries: None,
                random_seed: None,
                stability: None,
                text: source(vec![], &counts, false),
                text_normalization: None,
                timestamp_granularity: Default::default(),
                timestamp_text: None,
                voice: "hi".into(),
            },
        ),
    ];
    assert_eq!(requests.len(), 22);
    for request in requests {
        let _validate = validate_request(&request).unwrap();
        let c = settings::prepare(request);
        assert_eq!(settings::output_format(&c.output), "mp3_22050_32");
        assert_eq!(c.voice, "hi");
    }
    assert_eq!(counts.reads.load(Ordering::SeqCst), 0);
}
