use super::*;
pub(super) fn timed_tts(
    input: StreamingInput<settings::Input>,
) -> TtsRequestStreamingTextVoiceb9af60c3 {
    TtsRequestStreamingTextVoiceb9af60c3 {
        input_type: None,
        language: None,
        model: TtsRequestTextVoice814840b5Model::FlashV2(Default::default()),
        output: TtsRequestStreamingTextVoice5024de38Output::Mp31de777c9(
            TtsRequestTextVoice814840b5OutputMp31de777c9 {
                bit_rate_bps: Default::default(),
                format: Default::default(),
                sample_rate_hz: Default::default(),
            },
        ),
        pronunciation_dictionaries: None,
        random_seed: None,
        speed: None,
        stability: None,
        style_exaggeration: None,
        text: input,
        text_buffering: None,
        text_buffer_thresholds: None,
        text_normalization: None,
        timestamp_granularity: Default::default(),
        timestamp_text: None,
        voice: "custom/id".into(),
        voice_boost: None,
        voice_similarity: None,
    }
}
pub(super) fn timed_dialogue(
    input: StreamingInput<settings::DialogueInput>,
) -> TtsRequestElevenV3StreamingTextVoicec1dc022a {
    TtsRequestElevenV3StreamingTextVoicec1dc022a {
        language: None,
        model: Default::default(),
        output: TtsRequestStreamingTextVoice5024de38Output::Mp31de777c9(
            TtsRequestTextVoice814840b5OutputMp31de777c9 {
                bit_rate_bps: Default::default(),
                format: Default::default(),
                sample_rate_hz: Default::default(),
            },
        ),
        pronunciation_dictionaries: None,
        random_seed: None,
        stability: None,
        text: input,
        text_normalization: None,
        timestamp_granularity: Default::default(),
        timestamp_text: None,
        voice: "custom/id".into(),
    }
}

pub(super) fn requests() -> Vec<TtsRequest> {
    vec![
        TtsRequest::TextVoice814840b5(TtsRequestTextVoice814840b5 {
            context_after: None,
            context_before: None,
            language: None,
            language_text_normalization: None,
            latency_optimization: None,
            model: TtsRequestTextVoice814840b5Model::FlashV25(Default::default()),
            output: TtsRequestTextVoice814840b5Output::Mp356cad1fb(
                TtsRequestTextVoice814840b5OutputMp356cad1fb {
                    bit_rate_bps: None,
                    format: Default::default(),
                    sample_rate_hz: None,
                },
            ),
            pronunciation_dictionaries: None,
            random_seed: None,
            speed: None,
            stability: None,
            style_exaggeration: None,
            text: "Hello".into(),
            text_normalization: None,
            voice: "custom/id".into(),
            voice_boost: None,
            voice_similarity: None,
        }),
        TtsRequest::TextVoice814840b5(TtsRequestTextVoice814840b5 {
            context_after: Some(TtsRequestTextVoice814840b5ContextAfter::Object(
                TtsRequestTextVoice814840b5ContextAfterObject {
                    request_ids: vec!["next".into()],
                },
            )),
            context_before: Some(TtsRequestTextVoice814840b5ContextAfter::Text(
                TtsRequestTextVoice814840b5ContextAfterText { text: "".into() },
            )),
            language: Some("ja".into()),
            language_text_normalization: Some(
                TtsRequestTextVoice814840b5LanguageTextNormalization::True(Default::default()),
            ),
            latency_optimization: None,
            model: TtsRequestTextVoice814840b5Model::FlashV2(Default::default()),
            output: TtsRequestTextVoice814840b5Output::Pcm(TtsRequestTextVoice814840b5OutputPcm {
                byte_order: Some(Default::default()),
                format: Default::default(),
                sample_encoding: Some(Default::default()),
                sample_rate_hz: TtsRequestTextVoice814840b5OutputPcmSampleRateHz::Number24000(
                    Default::default(),
                ),
            }),
            pronunciation_dictionaries: Some(vec![
                TtsRequestTextVoice814840b5PronunciationDictionariesItem {
                    id: "lex".into(),
                    version_id: None,
                },
                TtsRequestTextVoice814840b5PronunciationDictionariesItem {
                    id: "lex2".into(),
                    version_id: Some("v2".into()),
                },
            ]),
            random_seed: Some(4294967295.0),
            speed: Some(0.7),
            stability: Some(0.0),
            style_exaggeration: Some(0.3),
            text: "雪\n\"hi\"".into(),
            text_normalization: Some(TtsRequestTextVoice814840b5TextNormalization::False(
                Default::default(),
            )),
            voice: "custom/id".into(),
            voice_boost: Some(TtsRequestTextVoice814840b5LanguageTextNormalization::False(
                Default::default(),
            )),
            voice_similarity: Some(0.2),
        }),
        TtsRequest::MultilingualV2TextVoice2ee6cad1(TtsRequestMultilingualV2TextVoice2ee6cad1 {
            context_after: Some(TtsRequestTextVoice814840b5ContextAfter::Text(
                TtsRequestTextVoice814840b5ContextAfterText {
                    text: "after".into(),
                },
            )),
            context_before: Some(TtsRequestTextVoice814840b5ContextAfter::Object(
                TtsRequestTextVoice814840b5ContextAfterObject {
                    request_ids: vec!["1".into(), "2".into(), "3".into()],
                },
            )),
            language_text_normalization: None,
            latency_optimization: Default::default(),
            model: Default::default(),
            output: TtsRequestTextVoice814840b5Output::Wav(TtsRequestTextVoice814840b5OutputWav {
                byte_order: None,
                format: Default::default(),
                sample_encoding: None,
                sample_rate_hz: TtsRequestTextVoice814840b5OutputPcmSampleRateHz::Number48000(
                    Default::default(),
                ),
            }),
            pronunciation_dictionaries: Some(vec![]),
            random_seed: None,
            speed: None,
            stability: None,
            style_exaggeration: None,
            text: "Hello".into(),
            text_normalization: Some(Default::default()),
            voice: "v".into(),
            voice_boost: None,
            voice_similarity: None,
        }),
        TtsRequest::ElevenV3TextVoicec3eabebc(TtsRequestElevenV3TextVoicec3eabebc {
            context_after: None,
            context_before: None,
            language: Some("en".into()),
            language_text_normalization: None,
            latency_optimization: None,
            model: Default::default(),
            output: TtsRequestTextVoice814840b5Output::Mp31de777c9(
                TtsRequestTextVoice814840b5OutputMp31de777c9 {
                    bit_rate_bps: Default::default(),
                    format: Default::default(),
                    sample_rate_hz: Default::default(),
                },
            ),
            pronunciation_dictionaries: None,
            random_seed: Some(0.0),
            stability: Some(0.5),
            text: "Hello".into(),
            text_normalization: Some(TtsRequestTextVoice814840b5TextNormalization::True(
                Default::default(),
            )),
            voice: "v".into(),
        }),
        TtsRequest::TextVoice814840b5(TtsRequestTextVoice814840b5 {
            context_after: None,
            context_before: None,
            language: None,
            language_text_normalization: None,
            latency_optimization: Some(TtsRequestTextVoice814840b5LatencyOptimization::Moderate(
                Default::default(),
            )),
            model: TtsRequestTextVoice814840b5Model::FlashV25(Default::default()),
            output: TtsRequestTextVoice814840b5Output::Mp34def27fa(
                TtsRequestTextVoice814840b5OutputMp34def27fa {
                    bit_rate_bps: Default::default(),
                    format: Default::default(),
                    sample_rate_hz: Default::default(),
                },
            ),
            pronunciation_dictionaries: None,
            random_seed: None,
            speed: None,
            stability: None,
            style_exaggeration: None,
            text: "Hello".into(),
            text_normalization: None,
            voice: "v".into(),
            voice_boost: None,
            voice_similarity: None,
        }),
        TtsRequest::TextVoice814840b5(TtsRequestTextVoice814840b5 {
            context_after: None,
            context_before: None,
            language: None,
            language_text_normalization: None,
            latency_optimization: Some(TtsRequestTextVoice814840b5LatencyOptimization::Strong(
                Default::default(),
            )),
            model: TtsRequestTextVoice814840b5Model::FlashV25(Default::default()),
            output: TtsRequestTextVoice814840b5Output::OggOpus(
                TtsRequestTextVoice814840b5OutputOggOpus {
                    bit_rate_bps: None,
                    format: Default::default(),
                    sample_rate_hz: None,
                },
            ),
            pronunciation_dictionaries: None,
            random_seed: None,
            speed: None,
            stability: None,
            style_exaggeration: None,
            text: "Hello".into(),
            text_normalization: None,
            voice: "v".into(),
            voice_boost: None,
            voice_similarity: None,
        }),
        TtsRequest::TextVoice814840b5(TtsRequestTextVoice814840b5 {
            context_after: None,
            context_before: None,
            language: None,
            language_text_normalization: None,
            latency_optimization: Some(TtsRequestTextVoice814840b5LatencyOptimization::Aggressive(
                Default::default(),
            )),
            model: TtsRequestTextVoice814840b5Model::FlashV25(Default::default()),
            output: TtsRequestTextVoice814840b5Output::Object(
                TtsRequestTextVoice814840b5OutputObject {
                    format: TtsRequestTextVoice814840b5OutputObjectFormat::Mulaw(Default::default()),
                    sample_rate_hz: None,
                },
            ),
            pronunciation_dictionaries: None,
            random_seed: None,
            speed: None,
            stability: None,
            style_exaggeration: None,
            text: "Hello".into(),
            text_normalization: None,
            voice: "v".into(),
            voice_boost: None,
            voice_similarity: None,
        }),
        TtsRequest::TextVoice814840b5(TtsRequestTextVoice814840b5 {
            context_after: None,
            context_before: None,
            language: None,
            language_text_normalization: None,
            latency_optimization: Some(TtsRequestTextVoice814840b5LatencyOptimization::None(
                Default::default(),
            )),
            model: TtsRequestTextVoice814840b5Model::FlashV25(Default::default()),
            output: TtsRequestTextVoice814840b5Output::Object(
                TtsRequestTextVoice814840b5OutputObject {
                    format: TtsRequestTextVoice814840b5OutputObjectFormat::Alaw(Default::default()),
                    sample_rate_hz: Some(Default::default()),
                },
            ),
            pronunciation_dictionaries: None,
            random_seed: None,
            speed: None,
            stability: None,
            style_exaggeration: None,
            text: "Hello".into(),
            text_normalization: None,
            voice: "v".into(),
            voice_boost: None,
            voice_similarity: None,
        }),
        TtsRequest::TextVoice6596490e(TtsRequestTextVoice6596490e {
            context_after: None,
            context_before: None,
            language: None,
            language_text_normalization: None,
            latency_optimization: None,
            model: TtsRequestTextVoice814840b5Model::FlashV25(Default::default()),
            output: TtsRequestTextVoice814840b5Output::Mp356cad1fb(
                TtsRequestTextVoice814840b5OutputMp356cad1fb {
                    bit_rate_bps: None,
                    format: Default::default(),
                    sample_rate_hz: None,
                },
            ),
            pronunciation_dictionaries: None,
            random_seed: None,
            speed: None,
            stability: None,
            style_exaggeration: None,
            text: "Hello".into(),
            text_normalization: None,
            timestamp_granularity: Default::default(),
            timestamp_text: Some(TtsRequestTextVoice1aa1b026TimestampText::Normalized(
                Default::default(),
            )),
            voice: "v".into(),
            voice_boost: None,
            voice_similarity: None,
        }),
        TtsRequest::ElevenV3TextVoicede803f4c(TtsRequestElevenV3TextVoicede803f4c {
            context_after: None,
            context_before: None,
            language: None,
            language_text_normalization: None,
            latency_optimization: None,
            model: Default::default(),
            output: TtsRequestTextVoice814840b5Output::Wav(TtsRequestTextVoice814840b5OutputWav {
                byte_order: None,
                format: Default::default(),
                sample_encoding: None,
                sample_rate_hz: TtsRequestTextVoice814840b5OutputPcmSampleRateHz::Number16000(
                    Default::default(),
                ),
            }),
            pronunciation_dictionaries: None,
            random_seed: None,
            stability: None,
            text: "Hello".into(),
            text_normalization: None,
            timestamp_granularity: Default::default(),
            timestamp_text: Some(TtsRequestTextVoice1aa1b026TimestampText::Original(
                Default::default(),
            )),
            voice: "v".into(),
        }),
    ]
}
pub(super) fn flash() -> TtsRequestTextVoice814840b5 {
    TtsRequestTextVoice814840b5 {
        context_after: None,
        context_before: None,
        language: None,
        language_text_normalization: None,
        latency_optimization: None,
        model: TtsRequestTextVoice814840b5Model::FlashV2(Default::default()),
        output: TtsRequestTextVoice814840b5Output::Mp31de777c9(
            TtsRequestTextVoice814840b5OutputMp31de777c9 {
                bit_rate_bps: Default::default(),
                format: Default::default(),
                sample_rate_hz: Default::default(),
            },
        ),
        pronunciation_dictionaries: None,
        random_seed: None,
        speed: None,
        stability: None,
        style_exaggeration: None,
        text: "Hello".into(),
        text_normalization: None,
        voice: "custom/id".into(),
        voice_boost: None,
        voice_similarity: None,
    }
}
pub(super) fn tts(input: StreamingInput<settings::Input>) -> TtsRequestStreamingTextVoice5024de38 {
    TtsRequestStreamingTextVoice5024de38 {
        input_type: None,
        language: None,
        model: TtsRequestTextVoice814840b5Model::FlashV2(Default::default()),
        output: TtsRequestStreamingTextVoice5024de38Output::Mp31de777c9(
            TtsRequestTextVoice814840b5OutputMp31de777c9 {
                bit_rate_bps: Default::default(),
                format: Default::default(),
                sample_rate_hz: Default::default(),
            },
        ),
        pronunciation_dictionaries: None,
        random_seed: None,
        speed: None,
        stability: None,
        style_exaggeration: None,
        text: input,
        text_buffering: None,
        text_buffer_thresholds: None,
        text_normalization: None,
        voice: "custom/id".into(),
        voice_boost: None,
        voice_similarity: None,
    }
}
pub(super) fn dialogue(
    input: StreamingInput<settings::DialogueInput>,
) -> TtsRequestElevenV3StreamingTextVoice145c0c5a {
    TtsRequestElevenV3StreamingTextVoice145c0c5a {
        language: None,
        model: Default::default(),
        output: TtsRequestStreamingTextVoice5024de38Output::Mp31de777c9(
            TtsRequestTextVoice814840b5OutputMp31de777c9 {
                bit_rate_bps: Default::default(),
                format: Default::default(),
                sample_rate_hz: Default::default(),
            },
        ),
        pronunciation_dictionaries: None,
        random_seed: None,
        stability: None,
        text: input,
        text_normalization: None,
        voice: "custom/id".into(),
    }
}

#[test]
fn all_generated_request_variants_convert_without_consuming_input() {
    let counts = Arc::new(Counts::default());
    let requests = vec![
        TtsRequest::TextVoice814840b5(TtsRequestTextVoice814840b5 {
            context_after: None,
            context_before: None,
            language: None,
            language_text_normalization: None,
            latency_optimization: None,
            model: TtsRequestTextVoice814840b5Model::FlashV2(Default::default()),
            output: TtsRequestTextVoice814840b5Output::Mp31de777c9(
                TtsRequestTextVoice814840b5OutputMp31de777c9 {
                    bit_rate_bps: Default::default(),
                    format: Default::default(),
                    sample_rate_hz: Default::default(),
                },
            ),
            pronunciation_dictionaries: None,
            random_seed: None,
            speed: None,
            stability: None,
            style_exaggeration: None,
            text: "hi".into(),
            text_normalization: None,
            voice: "hi".into(),
            voice_boost: None,
            voice_similarity: None,
        }),
        TtsRequest::TextVoiceeabc9ca0(TtsRequestTextVoiceeabc9ca0 {
            context_after: None,
            context_before: None,
            language: None,
            language_text_normalization: None,
            latency_optimization: Default::default(),
            model: TtsRequestTextVoice814840b5Model::FlashV2(Default::default()),
            output: TtsRequestTextVoice814840b5Output::Mp31de777c9(
                TtsRequestTextVoice814840b5OutputMp31de777c9 {
                    bit_rate_bps: Default::default(),
                    format: Default::default(),
                    sample_rate_hz: Default::default(),
                },
            ),
            pronunciation_dictionaries: None,
            random_seed: None,
            speed: None,
            stability: None,
            style_exaggeration: None,
            text: "hi".into(),
            text_normalization: None,
            voice: "hi".into(),
            voice_boost: None,
            voice_similarity: None,
        }),
        TtsRequest::TextVoice1aa1b026(TtsRequestTextVoice1aa1b026 {
            context_after: None,
            context_before: None,
            language: None,
            language_text_normalization: None,
            latency_optimization: Default::default(),
            model: TtsRequestTextVoice814840b5Model::FlashV2(Default::default()),
            output: TtsRequestTextVoice814840b5Output::Mp31de777c9(
                TtsRequestTextVoice814840b5OutputMp31de777c9 {
                    bit_rate_bps: Default::default(),
                    format: Default::default(),
                    sample_rate_hz: Default::default(),
                },
            ),
            pronunciation_dictionaries: None,
            random_seed: None,
            speed: None,
            stability: None,
            style_exaggeration: None,
            text: "hi".into(),
            text_normalization: None,
            timestamp_granularity: Default::default(),
            timestamp_text: None,
            voice: "hi".into(),
            voice_boost: None,
            voice_similarity: None,
        }),
        TtsRequest::StreamingTextVoice5024de38(TtsRequestStreamingTextVoice5024de38 {
            input_type: None,
            language: None,
            model: TtsRequestTextVoice814840b5Model::FlashV2(Default::default()),
            output: TtsRequestStreamingTextVoice5024de38Output::Mp31de777c9(
                TtsRequestTextVoice814840b5OutputMp31de777c9 {
                    bit_rate_bps: Default::default(),
                    format: Default::default(),
                    sample_rate_hz: Default::default(),
                },
            ),
            pronunciation_dictionaries: None,
            random_seed: None,
            speed: None,
            stability: None,
            style_exaggeration: None,
            text: source(vec![], &counts, false),
            text_buffering: None,
            text_buffer_thresholds: None,
            text_normalization: None,
            voice: "hi".into(),
            voice_boost: None,
            voice_similarity: None,
        }),
        TtsRequest::TextVoice6596490e(TtsRequestTextVoice6596490e {
            context_after: None,
            context_before: None,
            language: None,
            language_text_normalization: None,
            latency_optimization: None,
            model: TtsRequestTextVoice814840b5Model::FlashV2(Default::default()),
            output: TtsRequestTextVoice814840b5Output::Mp31de777c9(
                TtsRequestTextVoice814840b5OutputMp31de777c9 {
                    bit_rate_bps: Default::default(),
                    format: Default::default(),
                    sample_rate_hz: Default::default(),
                },
            ),
            pronunciation_dictionaries: None,
            random_seed: None,
            speed: None,
            stability: None,
            style_exaggeration: None,
            text: "hi".into(),
            text_normalization: None,
            timestamp_granularity: Default::default(),
            timestamp_text: None,
            voice: "hi".into(),
            voice_boost: None,
            voice_similarity: None,
        }),
        TtsRequest::StreamingTextVoiceb9af60c3(TtsRequestStreamingTextVoiceb9af60c3 {
            input_type: None,
            language: None,
            model: TtsRequestTextVoice814840b5Model::FlashV2(Default::default()),
            output: TtsRequestStreamingTextVoice5024de38Output::Mp31de777c9(
                TtsRequestTextVoice814840b5OutputMp31de777c9 {
                    bit_rate_bps: Default::default(),
                    format: Default::default(),
                    sample_rate_hz: Default::default(),
                },
            ),
            pronunciation_dictionaries: None,
            random_seed: None,
            speed: None,
            stability: None,
            style_exaggeration: None,
            text: source(vec![], &counts, false),
            text_buffering: None,
            text_buffer_thresholds: None,
            text_normalization: None,
            timestamp_granularity: Default::default(),
            timestamp_text: None,
            voice: "hi".into(),
            voice_boost: None,
            voice_similarity: None,
        }),
        TtsRequest::StreamingTextVoice732994d4(TtsRequestStreamingTextVoice732994d4 {
            input_type: None,
            language: None,
            model: TtsRequestTextVoice814840b5Model::FlashV2(Default::default()),
            output: TtsRequestStreamingTextVoice5024de38Output::Mp31de777c9(
                TtsRequestTextVoice814840b5OutputMp31de777c9 {
                    bit_rate_bps: Default::default(),
                    format: Default::default(),
                    sample_rate_hz: Default::default(),
                },
            ),
            pronunciation_dictionaries: None,
            random_seed: None,
            speed: None,
            stability: None,
            style_exaggeration: None,
            text: source(vec![], &counts, false),
            text_buffering: Default::default(),
            text_normalization: None,
            voice: "hi".into(),
            voice_boost: None,
            voice_similarity: None,
        }),
        TtsRequest::StreamingTextVoicebc33fdb4(TtsRequestStreamingTextVoicebc33fdb4 {
            input_type: None,
            language: None,
            model: TtsRequestTextVoice814840b5Model::FlashV2(Default::default()),
            output: TtsRequestStreamingTextVoice5024de38Output::Mp31de777c9(
                TtsRequestTextVoice814840b5OutputMp31de777c9 {
                    bit_rate_bps: Default::default(),
                    format: Default::default(),
                    sample_rate_hz: Default::default(),
                },
            ),
            pronunciation_dictionaries: None,
            random_seed: None,
            speed: None,
            stability: None,
            style_exaggeration: None,
            text: source(vec![], &counts, false),
            text_buffering: Default::default(),
            text_normalization: None,
            timestamp_granularity: Default::default(),
            timestamp_text: None,
            voice: "hi".into(),
            voice_boost: None,
            voice_similarity: None,
        }),
        TtsRequest::MultilingualV2TextVoiceae5db0bf(TtsRequestMultilingualV2TextVoiceae5db0bf {
            context_after: None,
            context_before: None,
            language_text_normalization: None,
            latency_optimization: None,
            model: Default::default(),
            output: TtsRequestTextVoice814840b5Output::Mp31de777c9(
                TtsRequestTextVoice814840b5OutputMp31de777c9 {
                    bit_rate_bps: Default::default(),
                    format: Default::default(),
                    sample_rate_hz: Default::default(),
                },
            ),
            pronunciation_dictionaries: None,
            random_seed: None,
            speed: None,
            stability: None,
            style_exaggeration: None,
            text: "hi".into(),
            text_normalization: None,
            voice: "hi".into(),
            voice_boost: None,
            voice_similarity: None,
        }),
        TtsRequest::MultilingualV2TextVoice2ee6cad1(TtsRequestMultilingualV2TextVoice2ee6cad1 {
            context_after: None,
            context_before: None,
            language_text_normalization: None,
            latency_optimization: Default::default(),
            model: Default::default(),
            output: TtsRequestTextVoice814840b5Output::Mp31de777c9(
                TtsRequestTextVoice814840b5OutputMp31de777c9 {
                    bit_rate_bps: Default::default(),
                    format: Default::default(),
                    sample_rate_hz: Default::default(),
                },
            ),
            pronunciation_dictionaries: None,
            random_seed: None,
            speed: None,
            stability: None,
            style_exaggeration: None,
            text: "hi".into(),
            text_normalization: None,
            voice: "hi".into(),
            voice_boost: None,
            voice_similarity: None,
        }),
        TtsRequest::MultilingualV2TextVoice4ed687d7(TtsRequestMultilingualV2TextVoice4ed687d7 {
            context_after: None,
            context_before: None,
            language_text_normalization: None,
            latency_optimization: Default::default(),
            model: Default::default(),
            output: TtsRequestTextVoice814840b5Output::Mp31de777c9(
                TtsRequestTextVoice814840b5OutputMp31de777c9 {
                    bit_rate_bps: Default::default(),
                    format: Default::default(),
                    sample_rate_hz: Default::default(),
                },
            ),
            pronunciation_dictionaries: None,
            random_seed: None,
            speed: None,
            stability: None,
            style_exaggeration: None,
            text: "hi".into(),
            text_normalization: None,
            timestamp_granularity: Default::default(),
            timestamp_text: None,
            voice: "hi".into(),
            voice_boost: None,
            voice_similarity: None,
        }),
        TtsRequest::MultilingualV2StreamingTextVoice729ee226(
            TtsRequestMultilingualV2StreamingTextVoice729ee226 {
                input_type: None,
                model: Default::default(),
                output: TtsRequestStreamingTextVoice5024de38Output::Mp31de777c9(
                    TtsRequestTextVoice814840b5OutputMp31de777c9 {
                        bit_rate_bps: Default::default(),
                        format: Default::default(),
                        sample_rate_hz: Default::default(),
                    },
                ),
                pronunciation_dictionaries: None,
                random_seed: None,
                speed: None,
                stability: None,
                style_exaggeration: None,
                text: source(vec![], &counts, false),
                text_buffering: None,
                text_buffer_thresholds: None,
                text_normalization: None,
                voice: "hi".into(),
                voice_boost: None,
                voice_similarity: None,
            },
        ),
        TtsRequest::MultilingualV2TextVoice11f62a92(TtsRequestMultilingualV2TextVoice11f62a92 {
            context_after: None,
            context_before: None,
            language_text_normalization: None,
            latency_optimization: None,
            model: Default::default(),
            output: TtsRequestTextVoice814840b5Output::Mp31de777c9(
                TtsRequestTextVoice814840b5OutputMp31de777c9 {
                    bit_rate_bps: Default::default(),
                    format: Default::default(),
                    sample_rate_hz: Default::default(),
                },
            ),
            pronunciation_dictionaries: None,
            random_seed: None,
            speed: None,
            stability: None,
            style_exaggeration: None,
            text: "hi".into(),
            text_normalization: None,
            timestamp_granularity: Default::default(),
            timestamp_text: None,
            voice: "hi".into(),
            voice_boost: None,
            voice_similarity: None,
        }),
        TtsRequest::MultilingualV2StreamingTextVoice3f7db298(
            TtsRequestMultilingualV2StreamingTextVoice3f7db298 {
                input_type: None,
                model: Default::default(),
                output: TtsRequestStreamingTextVoice5024de38Output::Mp31de777c9(
                    TtsRequestTextVoice814840b5OutputMp31de777c9 {
                        bit_rate_bps: Default::default(),
                        format: Default::default(),
                        sample_rate_hz: Default::default(),
                    },
                ),
                pronunciation_dictionaries: None,
                random_seed: None,
                speed: None,
                stability: None,
                style_exaggeration: None,
                text: source(vec![], &counts, false),
                text_buffering: None,
                text_buffer_thresholds: None,
                text_normalization: None,
                timestamp_granularity: Default::default(),
                timestamp_text: None,
                voice: "hi".into(),
                voice_boost: None,
                voice_similarity: None,
            },
        ),
        TtsRequest::MultilingualV2StreamingTextVoiceac3750e0(
            TtsRequestMultilingualV2StreamingTextVoiceac3750e0 {
                input_type: None,
                model: Default::default(),
                output: TtsRequestStreamingTextVoice5024de38Output::Mp31de777c9(
                    TtsRequestTextVoice814840b5OutputMp31de777c9 {
                        bit_rate_bps: Default::default(),
                        format: Default::default(),
                        sample_rate_hz: Default::default(),
                    },
                ),
                pronunciation_dictionaries: None,
                random_seed: None,
                speed: None,
                stability: None,
                style_exaggeration: None,
                text: source(vec![], &counts, false),
                text_buffering: Default::default(),
                text_normalization: None,
                voice: "hi".into(),
                voice_boost: None,
                voice_similarity: None,
            },
        ),
        TtsRequest::MultilingualV2StreamingTextVoiceb51c2303(
            TtsRequestMultilingualV2StreamingTextVoiceb51c2303 {
                input_type: None,
                model: Default::default(),
                output: TtsRequestStreamingTextVoice5024de38Output::Mp31de777c9(
                    TtsRequestTextVoice814840b5OutputMp31de777c9 {
                        bit_rate_bps: Default::default(),
                        format: Default::default(),
                        sample_rate_hz: Default::default(),
                    },
                ),
                pronunciation_dictionaries: None,
                random_seed: None,
                speed: None,
                stability: None,
                style_exaggeration: None,
                text: source(vec![], &counts, false),
                text_buffering: Default::default(),
                text_normalization: None,
                timestamp_granularity: Default::default(),
                timestamp_text: None,
                voice: "hi".into(),
                voice_boost: None,
                voice_similarity: None,
            },
        ),
        TtsRequest::ElevenV3TextVoicec3eabebc(TtsRequestElevenV3TextVoicec3eabebc {
            context_after: None,
            context_before: None,
            language: None,
            language_text_normalization: None,
            latency_optimization: None,
            model: Default::default(),
            output: TtsRequestTextVoice814840b5Output::Mp31de777c9(
                TtsRequestTextVoice814840b5OutputMp31de777c9 {
                    bit_rate_bps: Default::default(),
                    format: Default::default(),
                    sample_rate_hz: Default::default(),
                },
            ),
            pronunciation_dictionaries: None,
            random_seed: None,
            stability: None,
            text: "hi".into(),
            text_normalization: None,
            voice: "hi".into(),
        }),
        TtsRequest::ElevenV3TextVoicefade944d(TtsRequestElevenV3TextVoicefade944d {
            context_after: None,
            context_before: None,
            language: None,
            language_text_normalization: None,
            latency_optimization: Default::default(),
            model: Default::default(),
            output: TtsRequestTextVoice814840b5Output::Mp31de777c9(
                TtsRequestTextVoice814840b5OutputMp31de777c9 {
                    bit_rate_bps: Default::default(),
                    format: Default::default(),
                    sample_rate_hz: Default::default(),
                },
            ),
            pronunciation_dictionaries: None,
            random_seed: None,
            stability: None,
            text: "hi".into(),
            text_normalization: None,
            voice: "hi".into(),
        }),
        TtsRequest::ElevenV3TextVoicebb26fac2(TtsRequestElevenV3TextVoicebb26fac2 {
            context_after: None,
            context_before: None,
            language: None,
            language_text_normalization: None,
            latency_optimization: Default::default(),
            model: Default::default(),
            output: TtsRequestTextVoice814840b5Output::Mp31de777c9(
                TtsRequestTextVoice814840b5OutputMp31de777c9 {
                    bit_rate_bps: Default::default(),
                    format: Default::default(),
                    sample_rate_hz: Default::default(),
                },
            ),
            pronunciation_dictionaries: None,
            random_seed: None,
            stability: None,
            text: "hi".into(),
            text_normalization: None,
            timestamp_granularity: Default::default(),
            timestamp_text: None,
            voice: "hi".into(),
        }),
        TtsRequest::ElevenV3StreamingTextVoice145c0c5a(
            TtsRequestElevenV3StreamingTextVoice145c0c5a {
                language: None,
                model: Default::default(),
                output: TtsRequestStreamingTextVoice5024de38Output::Mp31de777c9(
                    TtsRequestTextVoice814840b5OutputMp31de777c9 {
                        bit_rate_bps: Default::default(),
                        format: Default::default(),
                        sample_rate_hz: Default::default(),
                    },
                ),
                pronunciation_dictionaries: None,
                random_seed: None,
                stability: None,
                text: source(vec![], &counts, false),
                text_normalization: None,
                voice: "hi".into(),
            },
        ),
        TtsRequest::ElevenV3TextVoicede803f4c(TtsRequestElevenV3TextVoicede803f4c {
            context_after: None,
            context_before: None,
            language: None,
            language_text_normalization: None,
            latency_optimization: None,
            model: Default::default(),
            output: TtsRequestTextVoice814840b5Output::Mp31de777c9(
                TtsRequestTextVoice814840b5OutputMp31de777c9 {
                    bit_rate_bps: Default::default(),
                    format: Default::default(),
                    sample_rate_hz: Default::default(),
                },
            ),
            pronunciation_dictionaries: None,
            random_seed: None,
            stability: None,
            text: "hi".into(),
            text_normalization: None,
            timestamp_granularity: Default::default(),
            timestamp_text: None,
            voice: "hi".into(),
        }),
        TtsRequest::ElevenV3StreamingTextVoicec1dc022a(
            TtsRequestElevenV3StreamingTextVoicec1dc022a {
                language: None,
                model: Default::default(),
                output: TtsRequestStreamingTextVoice5024de38Output::Mp31de777c9(
                    TtsRequestTextVoice814840b5OutputMp31de777c9 {
                        bit_rate_bps: Default::default(),
                        format: Default::default(),
                        sample_rate_hz: Default::default(),
                    },
                ),
                pronunciation_dictionaries: None,
                random_seed: None,
                stability: None,
                text: source(vec![], &counts, false),
                text_normalization: None,
                timestamp_granularity: Default::default(),
                timestamp_text: None,
                voice: "hi".into(),
            },
        ),
    ];
    assert_eq!(requests.len(), 22);
    for request in requests {
        let _validate = validate_request(&request).unwrap();
        let c = settings::prepare(request);
        assert_eq!(settings::output_format(&c.output), "mp3_22050_32");
        assert_eq!(c.voice, "hi");
    }
    assert_eq!(counts.reads.load(Ordering::SeqCst), 0);
}
