interface Schema {
  readonly type?: string;
  readonly required?: readonly string[];
  readonly properties?: Readonly<Record<string, Schema>>;
  readonly description?: string;
  readonly minimum?: number;
  readonly maximum?: number;
  readonly $ref?: string;
}
interface Operation {
  readonly operationId?: string;
  readonly description?: string;
  readonly parameters?: readonly { readonly name?: string; readonly in?: string; readonly required?: boolean }[];
  readonly requestBody?: { readonly required?: boolean; readonly content?: { readonly "application/json"?: { readonly schema?: Schema } } };
  readonly responses?: Readonly<Record<string, { readonly description?: string; readonly content?: { readonly "application/json"?: { readonly schema?: Schema } } }>>;
}
interface OpenApi {
  readonly openapi?: string;
  readonly servers?: readonly { readonly url?: string }[];
  readonly paths?: Readonly<Record<string, { readonly post?: Operation }>>;
  readonly components?: { readonly schemas?: Readonly<Record<string, Schema>>; readonly securitySchemes?: Readonly<Record<string, { readonly type?: string; readonly in?: string; readonly name?: string }>> };
}

export interface DeepdubContract { readonly baseUrl: "https://restapi.deepdub.ai/api/v1" }

export function deepdubContract(value: unknown, documentation: string): DeepdubContract {
  const api = value as OpenApi;
  if (api.openapi !== "3.0.0" || api.servers?.[0]?.url !== "https://restapi.deepdub.ai/api/v1") throw new TypeError("Deepdub OpenAPI metadata changed");
  const operation = api.paths?.["/tts"]?.post;
  if (operation?.operationId !== "generateTTS" || operation.requestBody?.required !== true) throw new TypeError("Deepdub lost POST /tts");
  const header = operation.parameters?.find((parameter) => parameter.name === "x-api-key" && parameter.in === "header");
  const security = api.components?.securitySchemes?.ApiKeyAuth;
  if (!header?.required || security?.type !== "apiKey" || security.in !== "header" || security.name !== "x-api-key") throw new TypeError("Deepdub authentication changed");
  const reference = operation.requestBody.content?.["application/json"]?.schema?.$ref;
  const schema = api.components?.schemas?.["model.GenerationRequest"];
  if (reference !== "#/components/schemas/model.GenerationRequest" || JSON.stringify(schema?.required) !== JSON.stringify(["locale", "model", "targetText", "voicePromptId"])) throw new TypeError("Deepdub TTS request changed");
  const fields = schema?.properties;
  if (!fields || JSON.stringify(Object.keys(fields)) !== JSON.stringify(["model", "targetText", "locale", "voicePromptId"])) throw new TypeError("Deepdub required TTS fields changed");
  const description = schema.description ?? "";
  for (const option of ["targetDuration", "tempo", "variance", "seed", "temperature", "sampleRate", "format", "promptBoost", "superStretch", "realtime", "cleanAudio", "autoGain", "publish", "accentControl", "performanceReferencePromptId", "voiceReference", "targetGender"] as const) {
    if (!description.includes(`\`${option}\``)) throw new TypeError(`Deepdub TTS description lost ${option}`);
  }
  const error = api.components?.schemas?.["model.APIError"];
  if (JSON.stringify(error?.required) !== JSON.stringify(["success", "message"]) || !operation.responses?.["200"]?.description?.includes("raw audio bytes")) throw new TypeError("Deepdub TTS responses changed");
  if (!documentation.includes("Generate and stream TTS audio") || !documentation.includes("WebSocket Streaming API")) throw new TypeError("Deepdub documentation index changed");
  return { baseUrl: "https://restapi.deepdub.ai/api/v1" };
}

export function renderDeepdubClient(contract: DeepdubContract, urls: readonly string[]): string {
  return `// Generated by codegen/generate-clients.ts from ${urls.join(", ")}. Do not edit.
import type { Fetch } from "../../runtime/fetch.ts";
export type Model = "dd-etts-2.5" | "dd-etts-1.1" | "dd-etts-3.2";
export interface AccentControl { readonly accentBaseLocale: string; readonly accentLocale: string; readonly accentRatio: number }
export interface GenerationRequest { readonly model: Model; readonly targetText: string; readonly locale: string; readonly voicePromptId: string; readonly targetDuration?: number; readonly tempo?: number; readonly variance?: number; readonly seed?: number; readonly temperature?: number; readonly sampleRate?: number; readonly format?: "mp3" | "opus" | "mulaw"; readonly promptBoost?: boolean; readonly superStretch?: boolean; readonly realtime?: boolean; readonly cleanAudio?: boolean; readonly autoGain?: boolean; readonly publish?: boolean; readonly accentControl?: AccentControl; readonly performanceReferencePromptId?: string; readonly voiceReference?: string; readonly targetGender?: "male" | "female" }
export interface ApiError { readonly success: false; readonly message: string }
export interface ClientOptions { readonly apiKey: string; readonly fetch: Fetch; readonly baseUrl: string; readonly signal?: AbortSignal }
export const defaultBaseUrl = ${JSON.stringify(contract.baseUrl)};
export function synthesize(input: GenerationRequest, options: ClientOptions): Promise<Response> { const baseUrl = options.baseUrl.endsWith("/") ? options.baseUrl.slice(0, -1) : options.baseUrl; return options.fetch(\`\${baseUrl}/tts\`, { method: "POST", headers: { "content-type": "application/json", "x-api-key": options.apiKey }, body: JSON.stringify(input), signal: options.signal }); }
`;
}
