interface DeepgramContracts {
  readonly models: readonly string[];
  readonly streamingEncodings: readonly string[];
}

function record(value: unknown, name: string): Record<string, any> {
  if (!value || typeof value !== "object" || Array.isArray(value)) {
    throw new TypeError(`Deepgram ${name} must be an object`);
  }
  return value as Record<string, any>;
}

export function deepgramContracts(openapi: unknown, asyncapi: unknown): DeepgramContracts {
  const open = record(openapi, "OpenAPI document");
  const operation = record(record(record(open.paths, "paths")["/v1/speak"], "/v1/speak").post, "POST /v1/speak");
  if (operation.operationId !== "generate") throw new TypeError("Deepgram POST /v1/speak operation changed");
  const schemas = record(record(open.components, "components").schemas, "OpenAPI schemas");
  const models = record(schemas.V1SpeakPostParametersModel, "model schema").enum;
  if (!Array.isArray(models) || !models.every((value) => typeof value === "string")) {
    throw new TypeError("Deepgram model enum changed");
  }

  const asynchronous = record(asyncapi, "AsyncAPI document");
  const channel = record(record(asynchronous.channels, "channels")["/v1/speak"], "streaming /v1/speak");
  const subscriptions = record(record(channel.subscribe, "subscribe").message, "subscribe message").oneOf;
  const publications = record(record(channel.publish, "publish").message, "publish message").oneOf;
  if (!Array.isArray(subscriptions) || subscriptions.length !== 4 || !Array.isArray(publications) || publications.length !== 5) {
    throw new TypeError("Deepgram streaming message union changed");
  }
  const streamingSchemas = record(record(asynchronous.components, "components").schemas, "AsyncAPI schemas");
  const streamingEncodings = record(streamingSchemas.SpeakV1Encoding, "streaming encoding schema").enum;
  if (!Array.isArray(streamingEncodings) || !streamingEncodings.every((value) => typeof value === "string")) {
    throw new TypeError("Deepgram streaming encoding enum changed");
  }
  return { models, streamingEncodings };
}

export function renderDeepgramClient(contracts: DeepgramContracts, sources: readonly string[]): string {
  const models = JSON.stringify(contracts.models);
  const encodings = JSON.stringify(contracts.streamingEncodings);
  return `// Generated by codegen/generate-clients.ts from ${sources.join(" and ")}. Do not edit.
import type { Fetch } from "../../runtime/fetch.ts";

export const models = ${models} as const;
export type Model = (typeof models)[number];
export const streamingEncodings = ${encodings} as const;
export type StreamingEncoding = (typeof streamingEncodings)[number];

export function isModel(value: string): value is Model {
  return (models as readonly string[]).includes(value);
}

export interface GenerateSpeechInput {
  readonly text: string;
  readonly model: Model;
  readonly encoding: "linear16" | "flac" | "mulaw" | "alaw" | "mp3" | "opus" | "aac";
  readonly container?: "none" | "wav" | "ogg";
  readonly sampleRate?: number;
  readonly bitRate?: number;
  readonly speed?: number;
}

export interface ClientOptions {
  readonly apiKey: string;
  readonly baseUrl: string;
  readonly fetch: Fetch;
  readonly signal?: AbortSignal | null;
}

export function generateSpeech(input: GenerateSpeechInput, options: ClientOptions): Promise<Response> {
  const url = new URL("/v1/speak", options.baseUrl);
  url.searchParams.set("model", input.model);
  url.searchParams.set("encoding", input.encoding);
  if (input.container) url.searchParams.set("container", input.container);
  if (input.sampleRate !== undefined) url.searchParams.set("sample_rate", String(input.sampleRate));
  if (input.bitRate !== undefined) url.searchParams.set("bit_rate", String(input.bitRate));
  if (input.speed !== undefined) url.searchParams.set("speed", String(input.speed));
  return options.fetch(url, {
    method: "POST",
    headers: { authorization: \`Token \${options.apiKey}\`, "content-type": "application/json" },
    body: JSON.stringify({ text: input.text }),
    signal: options.signal,
  });
}

export type ClientMessage =
  | { readonly type: "Speak"; readonly text: string }
  | { readonly type: "Clear" }
  | { readonly type: "Close" };

export type ServerMessage =
  | Uint8Array
  | { readonly type: "Metadata"; readonly request_id: string; readonly model_name: string; readonly model_version: string; readonly model_uuid: string }
  | { readonly type: "Flushed" | "Cleared"; readonly sequence_id: number }
  | { readonly type: "Warning"; readonly description: string; readonly code: string };

export function encodeMessage(message: ClientMessage): string {
  return JSON.stringify(message);
}

export function decodeMessage(data: unknown): ServerMessage {
  if (data instanceof ArrayBuffer) return new Uint8Array(data);
  if (ArrayBuffer.isView(data)) return new Uint8Array(data.buffer, data.byteOffset, data.byteLength);
  if (typeof data !== "string") throw new TypeError("Deepgram returned an unsupported WebSocket frame");
  const value: unknown = JSON.parse(data);
  if (!value || typeof value !== "object" || typeof (value as { type?: unknown }).type !== "string") {
    throw new TypeError("Deepgram returned an invalid WebSocket event");
  }
  return value as Exclude<ServerMessage, Uint8Array>;
}
`;
}
