interface FishContracts {
  readonly models: readonly string[];
  readonly formats: readonly string[];
  readonly mp3Bitrates: readonly number[];
  readonly opusBitrates: readonly number[];
  readonly latency: readonly string[];
}

function record(value: unknown, name: string): Record<string, any> {
  if (!value || typeof value !== "object" || Array.isArray(value)) throw new TypeError(`Fish ${name} must be an object`);
  return value as Record<string, any>;
}

function values(schema: Record<string, any>, field: string, kind: "string" | "number"): readonly any[] {
  const enumeration = record(record(schema.properties, "TTS properties")[field], field).enum;
  if (!Array.isArray(enumeration) || !enumeration.every((value) => typeof value === kind)) {
    throw new TypeError(`Fish ${field} enum changed`);
  }
  return enumeration;
}

export function fishContracts(value: unknown): FishContracts {
  const openapi = record(value, "OpenAPI document");
  const paths = record(openapi.paths, "paths");
  const speech = record(record(paths["/v1/tts"], "/v1/tts").post, "POST /v1/tts");
  const timestamps = record(record(paths["/v1/tts/stream/with-timestamp"], "timestamp path").post, "timestamp operation");
  if (speech.summary !== "Text to Speech" || timestamps.summary !== "Text to Speech Stream with Timestamps") {
    throw new TypeError("Fish TTS operations changed");
  }
  const model = speech.parameters?.find((parameter: any) => parameter.name === "model")?.schema?.enum;
  if (!Array.isArray(model) || !model.every((item) => typeof item === "string")) {
    throw new TypeError("Fish model enum changed");
  }
  const schemas = record(record(openapi.components, "components").schemas, "schemas");
  const request = record(schemas.TTSRequest, "TTSRequest");
  const timestampRequest = record(schemas.TTSStreamWithTimestampRequest, "TTSStreamWithTimestampRequest");
  if (JSON.stringify(Object.keys(request.properties)) !== JSON.stringify(Object.keys(timestampRequest.properties))) {
    throw new TypeError("Fish timestamp request diverged from TTSRequest");
  }
  return {
    models: model,
    formats: values(request, "format", "string"),
    mp3Bitrates: values(request, "mp3_bitrate", "number"),
    opusBitrates: values(request, "opus_bitrate", "number"),
    latency: values(request, "latency", "string"),
  };
}

export function renderFishClient(contract: FishContracts, source: string): string {
  return `// Generated by codegen/generate-clients.ts from ${source}. Do not edit.
import type { Fetch } from "../../runtime/fetch.ts";

export const models = ${JSON.stringify(contract.models)} as const;
export type Model = (typeof models)[number];
export const formats = ${JSON.stringify(contract.formats)} as const;
export type Format = (typeof formats)[number];
export type Mp3BitRateKbps = ${contract.mp3Bitrates.join(" | ")};
export type OpusBitRateBps = ${contract.opusBitrates.join(" | ")};
export type Latency = ${contract.latency.map((value) => JSON.stringify(value)).join(" | ")};

export interface TtsInput {
  readonly text: string;
  readonly reference_id: string;
  readonly prosody?: {
    readonly speed?: number;
    readonly volume?: number;
    readonly normalize_loudness?: boolean;
  };
  readonly normalize?: boolean;
  readonly format: Format;
  readonly sample_rate: number;
  readonly mp3_bitrate?: Mp3BitRateKbps;
  readonly opus_bitrate?: OpusBitRateBps;
  readonly latency?: Latency;
}

export interface ClientOptions {
  readonly apiKey: string;
  readonly baseUrl: string;
  readonly fetch: Fetch;
  readonly signal?: AbortSignal | null;
}

function request(path: string, input: TtsInput, model: Model, options: ClientOptions): Promise<Response> {
  return options.fetch(new URL(path, options.baseUrl), {
    method: "POST",
    headers: {
      authorization: \`Bearer \${options.apiKey}\`,
      "content-type": "application/json",
      model,
    },
    body: JSON.stringify(input),
    signal: options.signal,
  });
}

export function createSpeech(input: TtsInput, model: Model, options: ClientOptions): Promise<Response> {
  return request("/v1/tts", input, model, options);
}

export function streamSpeechWithTimestamps(input: TtsInput, model: Model, options: ClientOptions): Promise<Response> {
  return request("/v1/tts/stream/with-timestamp", input, model, options);
}
`;
}
