import { mkdir, readFile, readdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { extractRepositorySpeechSpec } from "./repository-spec.ts";
import { languageTypeFiles } from "./language-types.ts";
import { extractSchemaTypes } from "./specgen.ts";
import { renderPythonValidator } from "./python-validator.ts";
import { renderGoValidator } from "./go-validator.ts";
import { renderRustValidator } from "./rust-validator.ts";
import { snake } from "./language-types.ts";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const spec = extractRepositorySpeechSpec(root);
const files = languageTypeFiles(spec, extractSchemaTypes({
  root, tsconfig: "schemas/tsconfig.json", file: "schemas/stream.ts",
  names: ["Timestamp", "SynthesisEnvelope", "ClearEvent", "FlushEvent", "UpdatedEvent", "DoneEvent", "BatchEvent", "AudioStreamItem", "TimestampStreamItem", "AudioStream", "TimestampStream"],
}), extractSchemaTypes({
  root, tsconfig: "schemas/tsconfig.json", file: "schemas/transport.ts", names: ["SseMessage"],
}), new Map([
  ["auth", extractSchemaTypes({ root, tsconfig: "schemas/tsconfig.json", file: "schemas/auth.ts", names: ["Auth", "AwsAuth"] })],
  ["async_output", extractSchemaTypes({ root, tsconfig: "schemas/tsconfig.json", file: "schemas/providers/async/index.ts", names: ["WordTimestamp", "TimestampedAudio", "SynthesisItem"] })],
  ["camb_output", extractSchemaTypes({ root, tsconfig: "schemas/tsconfig.json", file: "schemas/providers/camb/index.ts", names: ["WordTimestamp", "SegmentOutput", "SynthesisItem"] })],
  ["cartesia_output", extractSchemaTypes({ root, tsconfig: "schemas/tsconfig.json", file: "schemas/providers/cartesia/index.ts", names: ["Timestamp", "TimelineOutput", "SynthesisItem"] })],
  ["deepgram_output", extractSchemaTypes({ root, tsconfig: "schemas/tsconfig.json", file: "schemas/providers/deepgram/index.ts", names: ["ClearEvent", "DoneEvent", "StreamEvent", "SynthesisItem"] })],
  ["elevenlabs_output", extractSchemaTypes({ root, tsconfig: "schemas/tsconfig.json", file: "schemas/providers/elevenlabs/index.ts", names: ["CharacterTimestamp", "TimestampedAudio", "ClearEvent", "SynthesisItem"] })],
  ["fish_output", extractSchemaTypes({ root, tsconfig: "schemas/tsconfig.json", file: "schemas/providers/fish/index.ts", names: ["SegmentTimestamp", "TimelineOutput", "SynthesisItem"] })],
  ["gradium_output", extractSchemaTypes({ root, tsconfig: "schemas/tsconfig.json", file: "schemas/providers/gradium/index.ts", names: ["SegmentTimestamp", "TimelineOutput", "SynthesisItem"] })],
  ["hume_output", extractSchemaTypes({ root, tsconfig: "schemas/tsconfig.json", file: "schemas/providers/hume/index.ts", names: ["Timestamp", "HumeEnvelope", "SynthesisItem"] })],
  ["inworld_output", extractSchemaTypes({ root, tsconfig: "schemas/tsconfig.json", file: "schemas/providers/inworld/index.ts", names: ["InworldTimestamp", "InworldChunkEnvelope", "InworldTimelineEnvelope", "FlushEvent", "SynthesisItem"] })],
  ["kugelaudio_output", extractSchemaTypes({ root, tsconfig: "schemas/tsconfig.json", file: "schemas/providers/kugelaudio/index.ts", names: ["KugelAudioTimestamp", "KugelAudioEnvelope", "KugelAudioUsage", "KugelAudioTurnEvent", "KugelAudioDoneEvent", "SynthesisItem"] })],
  ["lovo_output", extractSchemaTypes({ root, tsconfig: "schemas/tsconfig.json", file: "schemas/providers/lovo/index.ts", names: ["LovoAudioEnvelope", "SynthesisItem"] })],
  ["mistral_output", extractSchemaTypes({ root, tsconfig: "schemas/tsconfig.json", file: "schemas/providers/mistral/index.ts", names: ["PromptTokensDetails", "Usage", "DoneEvent", "SynthesisItem"] })],
]));
if (files.has("sdks/rust/src/generated/validators.rs")) throw new TypeError("Generated validator module collision: validators");
for (const provider of spec.tts.providers) {
  const file = `sdks/python/speechswitch/generated/validators/${snake(provider.id)}.py`;
  if (files.has(file)) throw new TypeError(`Generated validator module collision: ${file}`);
  files.set(file, renderPythonValidator(provider));
  files.set(`sdks/go/generated/${snake(provider.id)}/validation.go`, renderGoValidator(provider));
  files.set(`sdks/rust/src/generated/validators/${snake(provider.id)}.rs`, renderRustValidator(provider));
}
files.set("sdks/rust/src/generated/validators/mod.rs", "// Generated by codegen/generate-language-types.ts from schemas/. Do not edit.\n" + spec.tts.providers.map(provider => `pub mod ${snake(provider.id)};`).join("\n") + "\n");
files.set("sdks/rust/src/generated/mod.rs", files.get("sdks/rust/src/generated/mod.rs")! + "pub mod validators;\n");
files.set("sdks/python/speechswitch/generated/validators/__init__.py", "# Generated by codegen/generate-language-types.ts from schemas/. Do not edit.\n");
const stale: string[] = [];
for (const [file, expected] of files) {
  if (process.argv.includes("--check")) {
    if (await readFile(path.join(root, file), "utf8").catch(() => "") !== expected) stale.push(file);
  } else {
    await mkdir(path.dirname(path.join(root, file)), { recursive: true });
    await writeFile(path.join(root, file), expected);
  }
}
// Detect removed providers too; never silently retain stale generated APIs or
// delete files that might contain user changes.
for (const directory of ["sdks/rust/src/generated", "sdks/python/speechswitch/generated", "sdks/go/generated"]) {
  const entries = await readdir(path.join(root, directory), { recursive: true, withFileTypes: true }).catch(() => []);
  for (const entry of entries) {
    if (!entry.isFile() || !/\.(rs|py|go)$/.test(entry.name)) continue;
    const file = path.relative(root, path.join(entry.parentPath, entry.name));
    if (!files.has(file)) stale.push(file);
  }
}
if (stale.length) {
  console.error(`Generated language types are stale: ${stale.join(", ")}. Run bun run generate:languages; review obsolete files explicitly.`);
  process.exitCode = 1;
} else console.log(`${process.argv.includes("--check") ? "Verified" : "Generated"} ${files.size} Rust/Python/Go files`);
