interface GoogleContracts {
  readonly encodings: readonly string[];
}

function record(value: unknown, name: string): Record<string, any> {
  if (!value || typeof value !== "object" || Array.isArray(value)) throw new TypeError(`Google ${name} must be an object`);
  return value as Record<string, any>;
}

export function googleContracts(v1: unknown, beta: unknown): GoogleContracts {
  const stable = record(v1, "v1 Discovery document");
  const preview = record(beta, "v1beta1 Discovery document");
  for (const [version, document] of [["v1", stable], ["v1beta1", preview]] as const) {
    const text = record(record(record(document.resources, `${version} resources`).text, "text resource").methods, "text methods");
    if (record(text.synthesize, "synthesize").id !== "texttospeech.text.synthesize") {
      throw new TypeError(`Google ${version} synthesize operation changed`);
    }
    if (!record(record(document.schemas, `${version} schemas`).SynthesizeSpeechResponse, "response").properties.audioContent) {
      throw new TypeError(`Google ${version} audio response changed`);
    }
  }
  const audio = record(record(stable.schemas, "v1 schemas").AudioConfig, "AudioConfig");
  const encodings = record(audio.properties, "AudioConfig properties").audioEncoding.enum;
  if (!Array.isArray(encodings) || !encodings.every((value) => typeof value === "string")) {
    throw new TypeError("Google audio encoding enum changed");
  }
  return { encodings };
}

export function renderGoogleClient(contract: GoogleContracts, sources: readonly string[]): string {
  return `// Generated by codegen/generate-clients.ts from ${sources.join(" and ")}. Do not edit.
import type { Fetch } from "../../runtime/fetch.ts";

export const audioEncodings = ${JSON.stringify(contract.encodings)} as const;
export type AudioEncoding = (typeof audioEncodings)[number];

export interface SynthesizeSpeechInput {
  readonly input: { readonly text: string } | { readonly ssml: string };
  readonly voice: {
    readonly languageCode: string;
    readonly name?: string;
    readonly modelName: string;
  };
  readonly audioConfig: {
    readonly audioEncoding: Exclude<AudioEncoding, "AUDIO_ENCODING_UNSPECIFIED">;
    readonly sampleRateHertz?: number;
    readonly speakingRate?: number;
    readonly pitch?: number;
    readonly volumeGainDb?: number;
  };
}

export interface Voice {
  readonly name?: string;
  readonly languageCodes?: readonly string[];
  readonly ssmlGender?: "SSML_VOICE_GENDER_UNSPECIFIED" | "MALE" | "FEMALE" | "NEUTRAL";
  readonly naturalSampleRateHertz?: number;
}

export type Credential =
  | { readonly kind: "apiKey"; readonly value: string }
  | { readonly kind: "accessToken"; readonly value: string };

export interface ClientOptions {
  readonly credential: Credential;
  readonly baseUrl: string;
  readonly fetch: Fetch;
  readonly signal?: AbortSignal | null;
}

function request(path: string, options: ClientOptions, init: RequestInit = {}): Promise<Response> {
  const url = new URL(path, options.baseUrl);
  if (options.credential.kind === "apiKey") url.searchParams.set("key", options.credential.value);
  return options.fetch(url, {
    ...init,
    headers: {
      ...(options.credential.kind === "accessToken" ? { authorization: \`Bearer \${options.credential.value}\` } : {}),
      ...init.headers,
    },
    signal: options.signal,
  });
}

export function synthesizeSpeech(input: SynthesizeSpeechInput, options: ClientOptions): Promise<Response> {
  return request("/v1/text:synthesize", options, {
    method: "POST",
    headers: { "content-type": "application/json" },
    body: JSON.stringify(input),
  });
}

export async function listVoices(languageCode: string | undefined, options: ClientOptions): Promise<readonly Voice[]> {
  const path = languageCode ? \`/v1/voices?languageCode=\${encodeURIComponent(languageCode)}\` : "/v1/voices";
  const response = await request(path, options);
  if (!response.ok) throw new TypeError(\`Google Cloud TTS returned HTTP \${response.status}: \${await response.text()}\`);
  return ((await response.json()) as { readonly voices?: readonly Voice[] }).voices ?? [];
}
`;
}
