interface GradiumContracts { readonly outputFormats: readonly string[] }

function record(value: unknown, name: string): Record<string, any> {
  if (!value || typeof value !== "object" || Array.isArray(value)) throw new TypeError(`Gradium ${name} must be an object`);
  return value as Record<string, any>;
}

export function gradiumContracts(value: unknown): GradiumContracts {
  const openapi = record(value, "OpenAPI document");
  const paths = record(openapi.paths, "paths");
  const speech = record(record(paths["/post/speech/tts"], "HTTP TTS path").post, "HTTP TTS operation");
  if (speech.operationId !== "post_text_to_speech"
    || !speech.description.includes("`model_name`")
    || !speech.description.includes("`only_audio`")) {
    throw new TypeError("Gradium HTTP TTS operation changed");
  }
  const schema = record(speech.requestBody?.content?.["application/json"]?.schema, "HTTP TTS request");
  const outputFormats = record(schema.properties, "HTTP TTS properties").output_format.enum;
  if (!Array.isArray(outputFormats) || !outputFormats.every((item) => typeof item === "string")) {
    throw new TypeError("Gradium output format enum changed");
  }
  const websocket = record(record(paths["/speech/tts"], "WebSocket TTS path").get, "WebSocket TTS operation");
  if (websocket.operationId !== "stream_text_to_speech"
    || !websocket.description.includes('"type": "setup"')
    || !websocket.description.includes('"type": "end_of_stream"')) {
    throw new TypeError("Gradium WebSocket protocol description changed");
  }
  if (record(record(paths["/voices/"], "voices path").get, "voices operation").operationId !== "get_voices_voices__get"
    || record(record(paths["/voices/{voice_uid}"], "voice path").get, "voice operation").operationId !== "get_voice_voices__voice_uid__get") {
    throw new TypeError("Gradium voice operations changed");
  }
  return { outputFormats };
}

export function renderGradiumClient(contract: GradiumContracts, source: string): string {
  return `// Generated by codegen/generate-clients.ts from ${source}. Do not edit.
import type { Fetch } from "../../runtime/fetch.ts";

export const outputFormats = ${JSON.stringify(contract.outputFormats)} as const;
export type OutputFormat = (typeof outputFormats)[number];

export interface ClientOptions {
  readonly apiKey: string;
  readonly baseUrl: string;
  readonly fetch: Fetch;
  readonly signal?: AbortSignal | null;
}

export interface Voice {
  readonly uid: string;
  readonly name: string;
  readonly description?: string | null;
  readonly filename?: string | null;
  readonly start_s?: number | null;
  readonly language?: string | null;
  readonly is_catalog: boolean;
  readonly is_pro_clone: boolean;
  readonly tags?: readonly { readonly category?: string | null; readonly value: string }[];
}

export interface VoiceListInput {
  readonly skip?: number;
  readonly limit?: number;
  readonly includeCatalog?: boolean;
}

function request(path: string, options: ClientOptions, init: RequestInit = {}): Promise<Response> {
  return options.fetch(new URL(path, options.baseUrl), {
    ...init,
    headers: { "x-api-key": options.apiKey, ...init.headers },
    signal: options.signal,
  });
}

export function createSpeech(input: {
  readonly text: string;
  readonly voice_id: string;
  readonly output_format: OutputFormat;
  readonly model_name: string;
  readonly only_audio: true;
}, options: ClientOptions): Promise<Response> {
  return request("/api/post/speech/tts", options, {
    method: "POST",
    headers: { "content-type": "application/json" },
    body: JSON.stringify(input),
  });
}

async function json<ResponseBody>(path: string, options: ClientOptions): Promise<ResponseBody> {
  const response = await request(path, options);
  if (!response.ok) throw new TypeError(\`Gradium returned HTTP \${response.status}: \${await response.text()}\`);
  return response.json() as Promise<ResponseBody>;
}

export function listVoices(input: VoiceListInput, options: ClientOptions): Promise<readonly Voice[]> {
  const query = new URLSearchParams();
  if (input.skip !== undefined) query.set("skip", String(input.skip));
  if (input.limit !== undefined) query.set("limit", String(input.limit));
  if (input.includeCatalog !== undefined) query.set("include_catalog", String(input.includeCatalog));
  const suffix = query.size ? \`?\${query}\` : "";
  return json<readonly Voice[]>(\`/api/voices/\${suffix}\`, options);
}

export function getVoice(voiceId: string, options: ClientOptions): Promise<Voice> {
  return json<Voice>(\`/api/voices/\${encodeURIComponent(voiceId)}\`, options);
}
`;
}
