import { createHash } from "node:crypto";
import type { SchemaField, SchemaLiteral, SchemaType, SpeechSpec } from "./spec-model.ts";

export type Language = "rust" | "python" | "go";
const banner = "Generated by codegen/generate-language-types.ts from schemas/. Do not edit.";
const keywords = new Set("abstract as async await become box break case chan class const continue crate def default defer del do dyn elif else enum except extern fallthrough false final finally fn for from func global go goto if impl import in interface is lambda let loop macro match mod move mut nonlocal not or override package pass priv pub raise range ref return select self static struct super switch trait true try type typeof union unsafe unsized use var virtual where while with yield".split(" "));
function snake(value: string): string {
  const result = value.replace(/([a-z0-9])([A-Z])/g, "$1_$2").replace(/[^a-zA-Z0-9]+/g, "_").toLowerCase().replace(/^_+|_+$/g, "");
  return !result || /^\d/.test(result) ? `value_${result}` : keywords.has(result) ? `${result}_` : result;
}
function pascal(value: string): string {
  const result = value.replace(/([a-z0-9])([A-Z])/g, "$1_$2").split(/[^a-zA-Z0-9]+/).filter(Boolean).map(word => word[0]!.toUpperCase() + word.slice(1)).join("");
  return !result || /^\d/.test(result) ? `Value${result}` : result === "Self" ? "Self_" : result;
}
function identity(type: SchemaType): string {
  // Rendered TypeScript is diagnostic text, never a source of type semantics.
  return JSON.stringify(type, (key, value) => ["typeScriptType", "documentation", "deprecated", "examples"].includes(key) ? undefined : value);
}
function label(type: SchemaType): string {
  if (type.kind === "literal") return pascal(type.value === null ? "Null" : typeof type.value === "number" ? `Number_${String(type.value).replace(/-/g, "Minus_").replace(/\./g, "Point_")}` : String(type.value));
  if (type.kind === "object") {
    const input = type.fields.find(field => !field.optional && ["text", "turns"].includes(field.name));
    if (input && ["string", "array", "async-iterable"].includes(input.type.kind)) {
      const model = type.fields.find(field => field.name === "model" && !field.optional && field.type.kind === "literal");
      const voice = type.fields.find(field => !field.optional && ["voice", "voiceName"].includes(field.name));
      return (model?.type.kind === "literal" ? pascal(String(model.type.value)) : "")
        + (input.type.kind === "async-iterable" ? "Streaming" : "") + pascal(input.name) + (voice ? pascal(voice.name) : "");
    }
    for (const key of ["model", "command", "format", "event"]) {
      const field = type.fields.find(field => field.name === key && !field.optional && field.type.kind === "literal");
      if (field?.type.kind === "literal") return pascal(String(field.type.value));
    }
  }
  return pascal(type.kind);
}
function comments(field: SchemaField): string[] {
  return [`TypeScript field: ${field.name}.`, ...field.documentation.split(/\r?\n/).filter(Boolean),
    ...(field.default === undefined ? [] : [`Default when omitted: ${JSON.stringify(field.default)}. Omission is preserved by this type.`]),
    ...(field.constraints?.minimum === undefined ? [] : [`Minimum: ${field.constraints.minimum}.`]),
    ...(field.constraints?.maximum === undefined ? [] : [`Maximum: ${field.constraints.maximum}.`]),
    ...(field.constraints?.pattern === undefined ? [] : [`Pattern (ECMAScript): ${field.constraints.pattern}.`]),
    ...(field.deprecated ? [`Deprecated: ${field.deprecated}.`] : []),
    ...(field.examples?.map(example => `Example: ${example}`) ?? []),
  ].flatMap(line => line.split(/\r?\n/));
}
function literal(value: SchemaLiteral, language: Language): string {
  if (value === null) return language === "python" ? "None" : language === "rust" ? "()" : "struct{}{}";
  if (typeof value === "boolean" && language === "python") return value ? "True" : "False";
  if (typeof value === "number") {
    if (!Number.isFinite(value)) throw new TypeError("Cannot generate a non-finite schema literal");
    return language === "rust" ? `${value}.0`.replace(/(\.[\d]+|e[+-]?\d+)\.0$/, "$1") : String(value);
  }
  if (typeof value === "string" && !value.isWellFormed()) throw new TypeError("Cannot generate an unpaired Unicode surrogate literal");
  // Consume whole escapes so a literal backslash followed by uXXXX stays text.
  // Rust uses \u{...}, not JSON \uXXXX; Go/Python accept JSON string escapes.
  return language === "rust" ? JSON.stringify(value).replace(/\\(?:u([0-9a-f]{4})|[\s\S])/gi, (escape, hex: string | undefined) => hex ? `\\u{${hex}}` : escape) : JSON.stringify(value);
}

export function renderLanguageTypes(type: SchemaType, language: Language, moduleName: string, namingIdentity: (type: SchemaType) => string = identity): string {
  const declarations: string[] = [];
  const names = new Map<string, string>();
  const owners = new Map<string, string>();
  let streaming = false; let bigint = false; let json = false; let record = false;
  function reserve(key: string, hint: string, namingKey = key): string {
    const previous = names.get(key); if (previous) return previous;
    let name = pascal(hint);
    if (owners.has(name) && owners.get(name) !== key) name += createHash("sha256").update(namingKey).digest("hex").slice(0, 8);
    if (owners.has(name) && owners.get(name) !== key) throw new TypeError(`Generated type name collision: ${name}`);
    names.set(key, name); owners.set(name, key); return name;
  }
  function compile(type: SchemaType, hint: string, root = false): string {
    if (type.kind === "json-value" && !root) {
      json = true;
      return language === "rust" ? "crate::runtime::JsonValue" : language === "go" ? "runtime.JsonValue" : "JsonValue";
    }
    if (type.kind === "record" && !root) {
      record = true;
      const value = compile(type.values, `${hint}Value`);
      return language === "rust" ? `std::collections::BTreeMap<String, ${value}>` : language === "go" ? `map[string]${value}` : `Mapping[str, ${value}]`;
    }
    const primitives = language === "rust" ? { string: "String", number: "f64", boolean: "bool", bytes: "Vec<u8>", bigint: "crate::runtime::BigInt" }
      : language === "go" ? { string: "string", number: "float64", boolean: "bool", bytes: "[]byte", bigint: "*big.Int" }
      : { string: "str", number: "float", boolean: "bool", bytes: "bytes", bigint: "int" };
    if (type.kind in primitives && !root) {
      if (type.kind === "bigint") bigint = true;
      return primitives[type.kind as keyof typeof primitives];
    }
    if (type.kind === "array" && !root) {
      const item = compile(type.items, `${hint}Item`);
      return language === "rust" ? `Vec<${item}>` : language === "go" ? `[]${item}` : `Sequence[${item}]`;
    }
    if (type.kind === "async-iterable" && !root) {
      streaming = true; const item = compile(type.items, `${hint}Item`);
      return language === "rust" ? `crate::runtime::StreamingInput<${item}>` : language === "go" ? `runtime.Input[${item}]` : `AsyncIterable[${item}]`;
    }
    const key = identity(type); const previous = names.get(key); if (previous) return previous;
    const name = reserve(key, hint, namingIdentity(type));
    if (type.kind === "object") {
      const fieldNames = new Set<string>();
      const fields = type.fields.map(field => {
        const fieldName = language === "go" ? pascal(field.name) : snake(field.name);
        if (fieldNames.has(fieldName)) throw new TypeError(`Generated field name collision in ${name}: ${fieldName}`);
        fieldNames.add(fieldName);
        let fieldType = compile(field.type, `${name}${pascal(field.name)}`);
        if (field.optional) fieldType = language === "rust" ? `Option<${fieldType}>` : language === "go" ? `runtime.Optional[${fieldType}]` : `NotRequired[${fieldType}]`;
        const docs = comments(field).map(line => `    ${language === "rust" ? "///" : language === "go" ? "//" : "#"} ${line}`).join("\n");
        return `${docs}\n    ${language === "rust" ? `pub ${fieldName}: ${fieldType},` : language === "go" ? `${fieldName} ${fieldType}` : `${fieldName}: ReadOnly[${fieldType}]`}`;
      });
      if (language === "python") for (const forbidden of type.forbidden ?? []) {
        const fieldName = snake(forbidden);
        if (fieldNames.has(fieldName)) throw new TypeError(`Generated forbidden field collision in ${name}: ${fieldName}`);
        fieldNames.add(fieldName); fields.push(`    ${fieldName}: ReadOnly[NotRequired[Never]]`);
      }
      declarations.push(language === "rust" ? `pub struct ${name} {\n${fields.join("\n")}\n}`
        : language === "go" ? `type ${name} struct {\n${fields.join("\n")}\n}`
        : `class ${name}(TypedDict):\n${fields.join("\n") || "    pass"}`);
    } else if (type.kind === "literal") {
      if (language === "python") {
        if (typeof type.value === "number" && !Number.isInteger(type.value)) {
          declarations.push(`class ${name}(float, Enum):\n    VALUE = ${literal(type.value, language)}`);
        } else declarations.push(`type ${name} = Literal[${literal(type.value, language)}]`);
      } else if (language === "rust") {
        const valueType = type.value === null ? "()" : typeof type.value === "string" ? "&'static str" : typeof type.value === "boolean" ? "bool" : "f64";
        declarations.push(`#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]\npub struct ${name};\nimpl ${name} {\n    pub const fn value(&self) -> ${valueType} { ${literal(type.value, language)} }\n}`);
      } else {
        const valueType = type.value === null ? "struct{}" : typeof type.value === "string" ? "string" : typeof type.value === "boolean" ? "bool" : "float64";
        declarations.push(`type ${name} struct{}\nfunc (${name}) Value() ${valueType} { return ${literal(type.value, language)} }`);
      }
    } else if (type.kind === "union") {
      if (!type.anyOf.length) throw new TypeError("Cannot generate an empty union");
      const counts = new Map<string, number>();
      for (const part of type.anyOf) counts.set(label(part), (counts.get(label(part)) ?? 0) + 1);
      const variants = type.anyOf.map(part => {
        const variant = label(part) + (counts.get(label(part))! > 1 ? createHash("sha256").update(namingIdentity(part)).digest("hex").slice(0, 8) : "");
        return { variant, type: compile(part, `${name}${variant}`) };
      });
      if (language === "python") declarations.push(`type ${name} = Union[${variants.map(part => part.type).join(", ")}]`);
      else if (language === "rust") declarations.push(`pub enum ${name} {\n${variants.map(part => `    ${part.variant}(${part.type}),`).join("\n")}\n}`);
      else {
        declarations.push(`type ${name} interface { is${name}() }`);
        for (const part of variants) {
          const wrapper = reserve(`wrapper:${key}:${part.variant}`, `${name}As${part.variant}`);
          declarations.push(`type ${wrapper} struct { Value ${part.type} }\nfunc (${wrapper}) is${name}() {}`);
        }
      }
    } else {
      // Root aliases are uncommon (requests are objects/unions), but the emitter
      // also supports isolated scalar/collection fixtures without widening them.
      names.delete(key);
      const target = compile(type, `${name}Value`);
      names.set(key, name);
      declarations.push(language === "rust" ? `pub type ${name} = ${target};` : language === "go" ? `type ${name} = ${target}` : `type ${name} = ${target}`);
    }
    return name;
  }
  compile(type, "TtsRequest", true);
  const header = language === "rust" ? `// ${banner}\n#![allow(non_camel_case_types)]`
    : language === "python" ? `# ${banner}\nfrom collections.abc import AsyncIterable, ${record ? "Mapping, " : ""}Sequence\nfrom enum import Enum\nfrom typing import Literal, Never, NotRequired, ReadOnly, TypedDict, Union${json ? '\nfrom speechswitch.json import JsonValue' : ''}`
    : `// ${banner}\npackage ${snake(moduleName)}\n${streaming || json || declarations.some(line => line.includes("runtime.Optional[")) || bigint ? `\nimport (\n${streaming || json || declarations.some(line => line.includes("runtime.Optional[")) ? '    "github.com/speechswitch/client/sdks/go/runtime"\n' : ""}${bigint ? '    "math/big"\n' : ""})` : ""}`;
  return `${header}\n\n${declarations.join("\n\n")}\n`;
}

export function languageTypeFiles(spec: SpeechSpec): Map<string, string> {
  const modules = [{ id: "base", request: { kind: "object" as const, fields: spec.tts.request.fields } }, ...spec.tts.providers];
  const ids = new Set<string>(); const files = new Map<string, string>();
  for (const module of modules) {
    const id = snake(module.id);
    if (ids.has(id)) throw new TypeError(`Generated provider name collision: ${id}`); ids.add(id);
    for (const language of ["rust", "python", "go"] as const) {
      const file = language === "rust" ? `sdks/rust/src/generated/${id}.rs` : language === "python" ? `sdks/python/speechswitch/generated/${id}.py` : `sdks/go/generated/${id}/types.go`;
      const origins = new Map<SchemaType, string>();
      const request = language === "python" ? pythonSubset(module.request, modules[0]!.request, origins) : module.request;
      files.set(file, renderLanguageTypes(request, language, id, type => origins.get(type) ?? identity(type)));
    }
  }
  files.set("sdks/rust/src/generated/mod.rs", `// ${banner}\n${modules.map(module => `pub mod ${snake(module.id)};`).join("\n")}\n`);
  files.set("sdks/python/speechswitch/generated/__init__.py", `# ${banner}\n`);
  return files;
}

function pythonSubset(type: SchemaType, base: SchemaType, origins: Map<SchemaType, string>): SchemaType {
  // An open TypedDict's missing key means "unknown extra key", not "absent".
  // Spell unsupported base fields as NotRequired[Never], including nested
  // shapes, so provider requests remain assignable to the readonly base API.
  // Keep naming tied to the authored provider graph, not extra Never fields
  // introduced merely to express Python's provider-to-base assignability.
  let result: SchemaType = type;
  if (type.kind === "union") result = { ...type, anyOf: type.anyOf.map(part => pythonSubset(part, base, origins)) };
  const bases = base.kind === "union" ? base.anyOf : [base];
  const combine = (types: SchemaType[]): SchemaType => types.length === 1 ? types[0]! : { kind: "union", anyOf: types };
  if (type.kind === "record") {
    const values = bases.flatMap(part => part.kind === "record" ? [part.values] : []);
    if (values.length) result = { ...type, values: pythonSubset(type.values, combine(values), origins) };
  }
  if (type.kind === "array" || type.kind === "async-iterable") {
    const items = bases.flatMap(part => part.kind === type.kind && (part.kind === "array" || part.kind === "async-iterable") ? [part.items] : []);
    if (items.length) result = { ...type, items: pythonSubset(type.items, combine(items), origins) };
  }
  if (type.kind === "object") {
    const fields = bases.flatMap(part => part.kind === "object" ? part.fields : []);
    result = { ...type, forbidden: [...new Set([...(type.forbidden ?? []), ...fields.map(field => field.name).filter(name => !type.fields.some(field => field.name === name))])].sort(),
      fields: type.fields.map(field => {
        const matches = fields.filter(baseField => baseField.name === field.name).map(baseField => baseField.type);
        return matches.length ? { ...field, type: pythonSubset(field.type, combine(matches), origins) } : field;
      }),
    };
  }
  origins.set(result, identity(type)); return result;
}
