import { expect, test } from "bun:test";
import { languageTypeFiles, renderLanguageTypes } from "./language-types.ts";
import type { SchemaField, SchemaType, SpeechSpec } from "./spec-model.ts";

test("literal emission is concrete in each target, not an open scalar or descriptor", () => {
  const type = { kind: "literal", value: "clear" } as const;
  expect(renderLanguageTypes(type, "rust", "fixture")).toBe(`// Generated by codegen/generate-language-types.ts from schemas/. Do not edit.
#![allow(non_camel_case_types)]

#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct TtsRequest;
impl TtsRequest {
    pub const fn value(&self) -> &'static str { "clear" }
}
`);
  expect(renderLanguageTypes(type, "go", "fixture")).toBe(`// Generated by codegen/generate-language-types.ts from schemas/. Do not edit.
package fixture


type TtsRequest struct{}
func (TtsRequest) Value() string { return "clear" }
`);
  expect(renderLanguageTypes(type, "python", "fixture")).toBe(`# Generated by codegen/generate-language-types.ts from schemas/. Do not edit.
from collections.abc import AsyncIterable, Sequence
from enum import Enum
from typing import Literal, Never, NotRequired, ReadOnly, TypedDict, Union

type TtsRequest = Literal["clear"]
`);
});

test("rendered TypeScript strings cannot alter target type semantics", () => {
  const field: SchemaField = { name: "text", optional: false, documentation: "", typeScriptType: "string", type: { kind: "string" } };
  for (const language of ["rust", "python", "go"] as const) {
    expect(renderLanguageTypes({ kind: "object", fields: [field] }, language, "fixture"))
      .toBe(renderLanguageTypes({ kind: "object", fields: [{ ...field, typeScriptType: "never | any | malicious()" }] }, language, "fixture"));
  }
});

test("Python fractional choices remain closed enums that narrow the base numeric field", () => {
  expect(renderLanguageTypes({ kind: "literal", value: 0.2 }, "python", "fixture")).toBe(`# Generated by codegen/generate-language-types.ts from schemas/. Do not edit.
from collections.abc import AsyncIterable, Sequence
from enum import Enum
from typing import Literal, Never, NotRequired, ReadOnly, TypedDict, Union

class TtsRequest(float, Enum):
    VALUE = 0.2
`);
});

test("renamed fields and provider modules fail on collisions rather than overwriting declarations", () => {
  const fields: SchemaField[] = ["sampleRate", "sample_rate"].map(name => ({ name, optional: false, documentation: "", typeScriptType: "string", type: { kind: "string" } }));
  for (const language of ["rust", "python", "go"] as const) {
    expect(() => renderLanguageTypes({ kind: "object", fields }, language, "fixture"))
      .toThrow(new TypeError(`Generated field name collision in TtsRequest: ${language === "go" ? "SampleRate" : "sample_rate"}`));
  }
  const spec: SpeechSpec = { tts: { request: { name: "TtsRequest", documentation: "", fields: [] }, providers: [{ id: "base", request: { kind: "object", fields: [] } }] } };
  expect(() => languageTypeFiles(spec)).toThrow(new TypeError("Generated provider name collision: base"));
});

test("documentation edits do not rename anonymous variants", () => {
  const type: SchemaType = { kind: "union", anyOf: ["a", "b"].map(name => ({ kind: "object", fields: [{ name, optional: false, documentation: "before", typeScriptType: "string", type: { kind: "string" } }] })) };
  const edited = JSON.parse(JSON.stringify(type).replaceAll('"before"', '"after"')) as SchemaType;
  for (const language of ["rust", "python", "go"] as const) {
    expect(renderLanguageTypes(type, language, "fixture").replaceAll("before", "after")).toBe(renderLanguageTypes(edited, language, "fixture"));
  }
});

test("unsupported schema literal values fail closed", () => {
  for (const language of ["rust", "python", "go"] as const) {
    expect(() => renderLanguageTypes({ kind: "literal", value: Infinity }, language, "fixture")).toThrow(new TypeError("Cannot generate a non-finite schema literal"));
    expect(() => renderLanguageTypes({ kind: "literal", value: "\uD800" }, language, "fixture")).toThrow(new TypeError("Cannot generate an unpaired Unicode surrogate literal"));
    expect(() => renderLanguageTypes({ kind: "union", anyOf: [] }, language, "fixture")).toThrow(new TypeError("Cannot generate an empty union"));
  }
});

test("new unsupported base fields do not rename Python provider variants", () => {
  const field = (name: string): SchemaField => ({ name, optional: true, documentation: "", typeScriptType: "string", type: { kind: "string" } });
  const spec: SpeechSpec = { tts: { request: { name: "TtsRequest", documentation: "", fields: [field("a"), field("b")] },
    providers: [{ id: "fixture", request: { kind: "union", anyOf: ["a", "b"].map(name => ({ kind: "object", fields: [{ ...field(name), optional: false }] })) } }] } };
  const extended: SpeechSpec = { tts: { ...spec.tts, request: { ...spec.tts.request, fields: [...spec.tts.request.fields, field("newOption")] } } };
  const before = languageTypeFiles(spec).get("sdks/python/speechswitch/generated/fixture.py")!;
  const after = languageTypeFiles(extended).get("sdks/python/speechswitch/generated/fixture.py")!;
  expect(after.replaceAll("    new_option: ReadOnly[NotRequired[Never]]\n", "")).toBe(before);
});
