export interface MiniMaxContracts { readonly synthesizePath: string }

function record(value: unknown, name: string): Record<string, any> {
  if (!value || typeof value !== "object" || Array.isArray(value)) {
    throw new TypeError(`MiniMax ${name} must be an object`);
  }
  return value as Record<string, any>;
}

function reference(value: unknown, expected: string, name: string): void {
  if (record(value, name).$ref !== `#/components/schemas/${expected}`) {
    throw new TypeError(`MiniMax ${name} schema changed`);
  }
}

function properties(schemas: Record<string, any>, name: string, expected: readonly string[]): void {
  const actual = Object.keys(record(record(schemas[name], name).properties, `${name} properties`));
  if (JSON.stringify(actual) !== JSON.stringify(expected)) {
    throw new TypeError(`MiniMax ${name} properties changed`);
  }
}

export function miniMaxContracts(value: unknown): MiniMaxContracts {
  const openapi = record(value, "OpenAPI document");
  if (openapi.openapi !== "3.1.0" || record(openapi.info, "OpenAPI info").title !== "MiniMax T2A API") {
    throw new TypeError("MiniMax OpenAPI identity changed");
  }
  const synthesizePath = "/v1/t2a_v2";
  const operation = record(record(record(openapi.paths, "OpenAPI paths")[synthesizePath], synthesizePath).post,
    `POST ${synthesizePath}`);
  if (operation.operationId !== "t2aV2") throw new TypeError("MiniMax synthesis operation changed");
  const request = record(record(record(operation.requestBody, "request body").content, "request content")["application/json"],
    "JSON request");
  reference(request.schema, "T2aV2Req", "request");
  const responseContent = record(record(record(operation.responses, "responses")["200"], "response").content,
    "response content");
  reference(record(responseContent["text/event-stream"], "SSE response").schema, "T2aV2Resp", "SSE response");
  const schemas = record(record(openapi.components, "components").schemas, "schemas");
  properties(schemas, "T2aV2Req", [
    "model", "text", "stream", "stream_options", "voice_setting", "audio_setting",
    "pronunciation_dict", "timbre_weights", "language_boost", "voice_modify", "subtitle_enable",
    "subtitle_type", "output_format",
  ]);
  properties(schemas, "T2AVoiceSetting", [
    "voice_id", "speed", "vol", "pitch", "emotion", "text_normalization", "latex_read",
  ]);
  properties(schemas, "T2AAudioSetting", ["sample_rate", "bitrate", "format", "channel", "force_cbr"]);
  properties(schemas, "T2aV2Resp", ["data", "trace_id", "extra_info", "base_resp"]);
  const models = record(record(record(schemas.T2aV2Req, "T2aV2Req").properties, "request properties").model,
    "model").enum;
  if (JSON.stringify(models) !== JSON.stringify([
    "speech-2.8-hd", "speech-2.8-turbo", "speech-2.6-hd", "speech-2.6-turbo",
    "speech-02-hd", "speech-02-turbo", "speech-01-hd", "speech-01-turbo",
  ])) throw new TypeError("MiniMax model catalog changed");
  return { synthesizePath };
}

export function renderMiniMaxClient(contract: MiniMaxContracts, source: string): string {
  return `// Generated by codegen/generate-clients.ts from ${source}. Do not edit.
import type { Fetch } from "../../runtime/fetch.ts";
import { serverSentEvents } from "../../runtime/sse.ts";

export interface T2aRequest {
  readonly model: string;
  readonly text: string;
  readonly stream: true;
  readonly stream_options: { readonly exclude_aggregated_audio: true };
  readonly voice_setting?: {
    readonly voice_id: string;
    readonly speed?: number;
    readonly vol?: number;
    readonly pitch?: number;
    readonly emotion?: string;
    readonly text_normalization?: boolean;
  };
  readonly audio_setting: {
    readonly sample_rate: number;
    readonly bitrate?: number;
    readonly format: string;
    readonly channel: 1;
  };
  readonly pronunciation_dict?: { readonly tone: readonly string[] };
  readonly language_boost?: string;
  readonly output_format: "hex";
}

export interface T2aResponse {
  readonly data?: { readonly audio?: string; readonly status?: number } | null;
  readonly trace_id?: string;
  readonly base_resp?: { readonly status_code?: number; readonly status_msg?: string };
}

export interface ClientOptions {
  readonly apiKey: string;
  readonly baseUrl: string;
  readonly fetch: Fetch;
  readonly signal?: AbortSignal;
}

export async function* streamSpeech(
  input: T2aRequest,
  options: ClientOptions,
): AsyncIterableIterator<T2aResponse> {
  const response = await options.fetch(new URL(${JSON.stringify(contract.synthesizePath)}, options.baseUrl), {
    method: "POST",
    headers: {
      authorization: \`Bearer \${options.apiKey}\`,
      "content-type": "application/json",
      accept: "text/event-stream",
    },
    body: JSON.stringify(input),
    signal: options.signal,
  });
  if (!response.ok) {
    const detail = (await response.text()).trim();
    throw new TypeError(\`MiniMax returned HTTP \${response.status}\${detail ? \`: \${detail}\` : ""}\`);
  }
  if (!response.body) throw new TypeError("MiniMax returned no event stream");
  for await (const data of serverSentEvents(response.body)) {
    if (data !== "[DONE]") yield JSON.parse(data) as T2aResponse;
  }
}
`;
}
