export interface MistralContracts {
  readonly speechPath: string;
  readonly voicesPath: string;
  readonly voicePath: string;
  readonly samplePath: string;
}

function record(value: unknown, name: string): Record<string, any> {
  if (!value || typeof value !== "object" || Array.isArray(value)) {
    throw new TypeError(`Mistral ${name} must be an object`);
  }
  return value as Record<string, any>;
}

function operation(paths: Record<string, any>, path: string, method: string, id: string): Record<string, any> {
  const value = record(record(paths[path], path)[method], `${method.toUpperCase()} ${path}`);
  if (value.operationId !== id) throw new TypeError(`Mistral operation changed: ${method.toUpperCase()} ${path}`);
  return value;
}

function reference(value: unknown, expected: string, name: string): void {
  if (record(value, name).$ref !== `#/components/schemas/${expected}`) {
    throw new TypeError(`Mistral ${name} schema changed`);
  }
}

function responseReference(operation: Record<string, any>, mediaType: string, expected: string, name: string): void {
  const response = record(record(record(operation.responses, `${name} responses`)["200"], `${name} response`).content,
    `${name} response content`);
  reference(record(response[mediaType], `${name} ${mediaType}`).schema, expected, `${name} response`);
}

function properties(schemas: Record<string, any>, name: string, expected: readonly string[]): void {
  const actual = Object.keys(record(record(schemas[name], name).properties, `${name} properties`));
  if (JSON.stringify(actual) !== JSON.stringify(expected)) throw new TypeError(`Mistral ${name} properties changed`);
}

export function mistralContracts(value: unknown): MistralContracts {
  const openapi = record(value, "OpenAPI document");
  if (openapi.openapi !== "3.1.0" || record(openapi.info, "OpenAPI info").title !== "Mistral AI API") {
    throw new TypeError("Mistral OpenAPI identity changed");
  }
  const paths = record(openapi.paths, "OpenAPI paths");
  const speechPath = "/v1/audio/speech";
  const voicesPath = "/v1/audio/voices";
  const voicePath = "/v1/audio/voices/{voice_id}";
  const samplePath = "/v1/audio/voices/{voice_id}/sample";
  const speech = operation(paths, speechPath, "post", "speech_v1_audio_speech_post");
  const voices = operation(paths, voicesPath, "get", "list_voices_v1_audio_voices_get");
  const createVoice = operation(paths, voicesPath, "post", "create_voice_v1_audio_voices_post");
  const getVoice = operation(paths, voicePath, "get", "get_voice_v1_audio_voices__voice_id__get");
  operation(paths, voicePath, "patch", "update_voice_v1_audio_voices__voice_id__patch");
  operation(paths, voicePath, "delete", "delete_voice_v1_audio_voices__voice_id__delete");
  operation(paths, samplePath, "get", "get_voice_sample_audio_v1_audio_voices__voice_id__sample_get");
  const request = record(record(record(speech.requestBody, "speech request body").content,
    "speech request content")["application/json"], "speech JSON request");
  reference(request.schema, "SpeechRequest", "speech request");
  responseReference(speech, "text/event-stream", "SpeechStreamEvents", "speech");
  responseReference(voices, "application/json", "VoiceListResponse", "voices");
  responseReference(createVoice, "application/json", "VoiceResponse", "create voice");
  responseReference(getVoice, "application/json", "VoiceResponse", "get voice");
  const schemas = record(record(openapi.components, "components").schemas, "schemas");
  properties(schemas, "SpeechRequest", ["model", "stream", "voice_id", "ref_audio", "input", "response_format"]);
  properties(schemas, "SpeechStreamAudioDelta", ["type", "audio_data"]);
  properties(schemas, "SpeechStreamDone", ["type", "usage"]);
  properties(schemas, "SpeechStreamEvents", ["event", "data"]);
  properties(schemas, "VoiceCreateRequest", [
    "name", "slug", "languages", "gender", "age", "tags", "color", "retention_notice",
    "sample_audio", "sample_filename",
  ]);
  properties(schemas, "VoiceResponse", [
    "name", "slug", "languages", "gender", "age", "tags", "color", "retention_notice",
    "id", "created_at", "user_id",
  ]);
  const formats = record(schemas.SpeechOutputFormat, "SpeechOutputFormat").enum;
  if (JSON.stringify(formats) !== JSON.stringify(["pcm", "wav", "mp3", "flac", "opus"])) {
    throw new TypeError("Mistral speech output formats changed");
  }
  return { speechPath, voicesPath, voicePath, samplePath };
}

export function renderMistralClient(contract: MistralContracts, source: string): string {
  return `// Generated by codegen/generate-clients.ts from ${source}. Do not edit.
import type { Fetch } from "../../runtime/fetch.ts";
import { serverSentEvents } from "../../runtime/sse.ts";

export interface SpeechRequest {
  readonly model: string;
  readonly stream: true;
  readonly voice_id?: string;
  readonly ref_audio?: string;
  readonly input: string;
  readonly response_format: "pcm" | "wav" | "mp3" | "flac" | "opus";
}

export type SpeechStreamEvent =
  | { readonly type: "speech.audio.delta"; readonly audio_data: string }
  | { readonly type: "speech.audio.done"; readonly usage: Record<string, unknown> };

export interface Voice {
  readonly name: string;
  readonly slug?: string | null;
  readonly languages?: readonly string[];
  readonly gender?: string | null;
  readonly age?: number | null;
  readonly tags?: readonly string[] | null;
  readonly color?: string | null;
  readonly retention_notice?: number;
  readonly id: string;
  readonly created_at: string;
  readonly user_id: string | null;
}

export interface VoicePage {
  readonly items: readonly Voice[];
  readonly total: number;
  readonly page: number;
  readonly page_size: number;
  readonly total_pages: number;
}

export interface VoiceCreateRequest {
  readonly name: string;
  readonly slug?: string;
  readonly languages?: readonly string[];
  readonly gender?: string;
  readonly age?: number;
  readonly tags?: readonly string[];
  readonly color?: string;
  readonly retention_notice?: number;
  readonly sample_audio: string;
  readonly sample_filename?: string;
}

export interface VoiceUpdateRequest {
  readonly name?: string;
  readonly languages?: readonly string[];
  readonly gender?: string;
  readonly age?: number;
  readonly tags?: readonly string[];
}

export interface ClientOptions {
  readonly apiKey: string;
  readonly baseUrl: string;
  readonly fetch: Fetch;
  readonly signal?: AbortSignal;
}

function request(path: string | URL, options: ClientOptions, init: RequestInit = {}): Promise<Response> {
  return options.fetch(path instanceof URL ? path : new URL(path, options.baseUrl), {
    ...init,
    headers: { authorization: \`Bearer \${options.apiKey}\`, ...init.headers },
    signal: options.signal,
  });
}

async function error(response: Response): Promise<never> {
  const detail = (await response.text()).trim();
  throw new TypeError(\`Mistral returned HTTP \${response.status}\${detail ? \`: \${detail}\` : ""}\`);
}

export async function* streamSpeech(input: SpeechRequest, options: ClientOptions): AsyncIterableIterator<SpeechStreamEvent> {
  const response = await request(${JSON.stringify(contract.speechPath)}, options, {
    method: "POST",
    headers: { "content-type": "application/json", accept: "text/event-stream" },
    body: JSON.stringify(input),
  });
  if (!response.ok) await error(response);
  if (!response.body) throw new TypeError("Mistral returned no speech event stream");
  for await (const data of serverSentEvents(response.body)) {
    if (data !== "[DONE]") yield JSON.parse(data) as SpeechStreamEvent;
  }
}

async function json<ResponseBody>(path: string | URL, options: ClientOptions, init: RequestInit = {}): Promise<ResponseBody> {
  const response = await request(path, options, init);
  if (!response.ok) return error(response);
  return response.json() as Promise<ResponseBody>;
}

export function listVoices(input: { readonly limit?: number; readonly offset?: number }, options: ClientOptions): Promise<VoicePage> {
  const url = new URL(${JSON.stringify(contract.voicesPath)}, options.baseUrl);
  if (input.limit !== undefined) url.searchParams.set("limit", String(input.limit));
  if (input.offset !== undefined) url.searchParams.set("offset", String(input.offset));
  return json<VoicePage>(url, options);
}

export function getVoice(voiceId: string, options: ClientOptions): Promise<Voice> {
  return json<Voice>(${JSON.stringify(contract.voicePath)}.replace("{voice_id}", encodeURIComponent(voiceId)), options);
}

export function createVoice(input: VoiceCreateRequest, options: ClientOptions): Promise<Voice> {
  return json<Voice>(${JSON.stringify(contract.voicesPath)}, options, {
    method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(input),
  });
}

export function updateVoice(voiceId: string, input: VoiceUpdateRequest, options: ClientOptions): Promise<Voice> {
  return json<Voice>(${JSON.stringify(contract.voicePath)}.replace("{voice_id}", encodeURIComponent(voiceId)), options, {
    method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify(input),
  });
}

export function deleteVoice(voiceId: string, options: ClientOptions): Promise<Voice> {
  return json<Voice>(${JSON.stringify(contract.voicePath)}.replace("{voice_id}", encodeURIComponent(voiceId)), options, {
    method: "DELETE",
  });
}

export function getVoiceSample(voiceId: string, options: ClientOptions): Promise<Response> {
  return request(${JSON.stringify(contract.samplePath)}.replace("{voice_id}", encodeURIComponent(voiceId)), options, {
    headers: { accept: "audio/wav" },
  });
}
`;
}
