export interface OpenAiContracts {
  readonly baseUrl: string;
  readonly speechPath: string;
  readonly models: readonly string[];
  readonly formats: readonly string[];
}

function record(value: unknown, name: string): Record<string, any> {
  if (!value || typeof value !== "object" || Array.isArray(value)) {
    throw new TypeError(`OpenAI ${name} must be an object`);
  }
  return value as Record<string, any>;
}

function stringArray(value: unknown, name: string): string[] {
  if (!Array.isArray(value) || value.some((item) => typeof item !== "string")) {
    throw new TypeError(`OpenAI ${name} changed`);
  }
  return value;
}

export function openAiContracts(openApiValue: unknown, markdown: string): OpenAiContracts {
  const document = record(openApiValue, "OpenAPI document");
  if (document.openapi !== "3.1.0" || record(document.info, "OpenAPI info").title !== "OpenAI API") {
    throw new TypeError("OpenAI OpenAPI identity changed");
  }
  const servers = document.servers;
  if (!Array.isArray(servers) || servers.length !== 1) throw new TypeError("OpenAI servers changed");
  const baseUrl = record(servers[0], "server").url;
  if (baseUrl !== "https://api.openai.com/v1") throw new TypeError("OpenAI server changed");
  const speechPath = "/audio/speech";
  const operation = record(record(record(document.paths, "paths")[speechPath], "speech path").post, "speech operation");
  if (operation.operationId !== "createSpeech") throw new TypeError("OpenAI speech operation changed");
  const requestBody = record(operation.requestBody, "request body");
  const requestContent = record(requestBody.content, "request content");
  const requestSchema = record(record(requestContent["application/json"], "JSON request").schema, "request schema");
  if (requestSchema.$ref !== "#/components/schemas/CreateSpeechRequest") throw new TypeError("OpenAI speech request changed");
  const responses = record(operation.responses, "responses");
  const responseContent = record(record(responses["200"], "success response").content, "success content");
  if (!responseContent["application/octet-stream"] || !responseContent["text/event-stream"]) {
    throw new TypeError("OpenAI speech response formats changed");
  }
  const schemas = record(record(document.components, "components").schemas, "schemas");
  const request = record(schemas.CreateSpeechRequest, "CreateSpeechRequest");
  const properties = record(request.properties, "CreateSpeechRequest properties");
  const actualProperties = Object.keys(properties);
  const expectedProperties = ["model", "input", "instructions", "voice", "response_format", "speed", "stream_format"];
  if (JSON.stringify(actualProperties) !== JSON.stringify(expectedProperties)
    || JSON.stringify(request.required) !== JSON.stringify(["model", "input", "voice"])) {
    throw new TypeError("OpenAI CreateSpeechRequest fields changed");
  }
  const modelAlternatives = record(properties.model, "model").anyOf;
  if (!Array.isArray(modelAlternatives)) throw new TypeError("OpenAI speech models changed");
  const models = stringArray(record(modelAlternatives[1], "named models").enum, "speech models");
  const formats = stringArray(record(properties.response_format, "response format").enum, "speech formats");
  if (record(properties.input, "input").maxLength !== 4096
    || record(properties.instructions, "instructions").maxLength !== 4096
    || record(properties.speed, "speed").minimum !== 0.25
    || record(properties.speed, "speed").maximum !== 4
    || JSON.stringify(record(properties.stream_format, "stream format").enum) !== JSON.stringify(["sse", "audio"])) {
    throw new TypeError("OpenAI speech constraints changed");
  }
  const voice = record(schemas.VoiceIdsOrCustomVoice, "voice");
  if (!Array.isArray(voice.anyOf)
    || record(voice.anyOf[0], "built-in voice").$ref !== "#/components/schemas/VoiceIdsShared"
    || JSON.stringify(record(voice.anyOf[1], "custom voice").required) !== JSON.stringify(["id"])) {
    throw new TypeError("OpenAI voice selection changed");
  }
  for (const phrase of [
    "The maximum length is 4096 characters.",
    "Does not work with `tts-1` or `tts-1-hd`.",
    "You may also provide a custom voice object with an `id`",
    '`stream_format: optional "sse" or "audio"`',
  ]) if (!markdown.includes(phrase)) throw new TypeError(`OpenAI speech reference changed: ${phrase}`);
  return { baseUrl, speechPath, models, formats };
}

export function renderOpenAiClient(contract: OpenAiContracts, sources: readonly string[]): string {
  return `// Generated by codegen/generate-clients.ts from ${sources.join(", ")}. Do not edit.
import type { Fetch } from "../../runtime/fetch.ts";

export type SpeechModel = ${contract.models.map((value) => JSON.stringify(value)).join(" | ")};
export type SpeechFormat = ${contract.formats.map((value) => JSON.stringify(value)).join(" | ")};
export interface CreateSpeechRequest {
  readonly model: SpeechModel;
  readonly input: string;
  readonly voice: string | { readonly id: string };
  readonly instructions?: string;
  readonly response_format: SpeechFormat;
  readonly speed?: number;
  readonly stream_format: "audio";
}

export interface ClientOptions {
  readonly apiKey: string;
  readonly baseUrl: string;
  readonly fetch: Fetch;
  readonly signal?: AbortSignal;
}

export function createSpeech(input: CreateSpeechRequest, options: ClientOptions): Promise<Response> {
  return options.fetch(new URL(\`\${options.baseUrl.replace(/\\\/$/, "")}\${${JSON.stringify(contract.speechPath)}}\`), {
    method: "POST",
    headers: { authorization: \`Bearer \${options.apiKey}\`, "content-type": "application/json" },
    body: JSON.stringify(input),
    signal: options.signal,
  });
}

export const defaultBaseUrl = ${JSON.stringify(contract.baseUrl)};
`;
}
