export interface OpenaiContract {
  readonly document: Record<string, unknown>;
  readonly sourceUrl: string;
  readonly baseUrl: string;
  readonly path: string;
  readonly method: string;
  readonly status: number;
  readonly input: unknown;
  readonly event: unknown;
}

/** Only called after the selected graph and transport have passed contract validation. */
export function renderOpenaiPythonClient(contract: OpenaiContract): string {
  const declarations: string[] = [];
  const literal = (value: unknown): string => value === true ? "True" : value === false ? "False" : JSON.stringify(value);
  const compile = (raw: unknown, name: string, value: string, depth = 0): { type: string; check: string } => {
    if (depth > 50) throw new TypeError("OpenAI schema graph is too deep");
    const schema = raw as Record<string, unknown>;
    if (typeof schema.$ref === "string") {
      const target = schema.$ref.slice(2).split("/").reduce((node, key) => (node as Record<string, unknown>)[key.replace(/~1/g, "/").replace(/~0/g, "~")], contract.document as unknown);
      return compile(target, name, value, depth + 1);
    }
    if (Array.isArray(schema.anyOf)) {
      const parts = schema.anyOf.map((child, index) => compile(child, `${name}_Variant${index}`, value, depth + 1));
      return { type: parts.map(part => part.type).join(" | "), check: `(${parts.map(part => part.check).join(" or ")})` };
    }
    let type: string;
    const checks: string[] = [];
    if (schema.type === "object") {
      const properties = schema.properties as Record<string, unknown>;
      const required = (schema.required ?? []) as string[];
      const fields: string[] = [];
      checks.push(`is_mapping(${value})`);
      for (const [index, [key, child]] of Object.entries(properties).sort(([a], [b]) => a.localeCompare(b)).entries()) {
        const property = literal(key);
        const part = compile(child, `${name}_Field${index}`, `${value}[${property}]`, depth + 1);
        fields.push(`    ${property}: ${required.includes(key) ? part.type : `NotRequired[${part.type}]`},`);
        checks.push(required.includes(key) ? `(${property} in ${value} and ${part.check})` : `(${property} not in ${value} or ${part.check})`);
      }
      if (schema.additionalProperties === false) checks.push(`all(key in ${literal(Object.keys(properties).sort())} for key in ${value})`);
      declarations.push(`${name} = TypedDict(${literal(name)}, {\n${fields.join("\n")}\n})`);
      type = name;
    } else {
      type = schema.type === "string" ? "str" : schema.type === "boolean" ? "bool" : "float";
      checks.push(type === "float" ? `is_number(${value})` : `isinstance(${value}, ${type})`);
      if (schema.type === "integer") checks.push(`abs(${value}) <= 9007199254740991`, `(isinstance(${value}, int) or ${value}.is_integer())`);
      for (const [key, operator] of [["minimum", ">="], ["maximum", "<="], ["minLength", ">="], ["maxLength", "<="]] as const) {
        if (schema[key] !== undefined) checks.push(`${key.endsWith("Length") ? `code_point_length(${value})` : value} ${operator} ${literal(schema[key])}`);
      }
    }
    if (Array.isArray(schema.enum)) {
      if (!schema.enum.some(value => typeof value === "number" && !Number.isSafeInteger(value))) type = `Literal[${schema.enum.map(literal).join(", ")}]`;
      checks.push(`(${schema.enum.map(item => `${value} ${typeof item === "boolean" ? "is" : "=="} ${literal(item)}`).join(" or ")})`);
    }
    return { type, check: `(${checks.join(" and ")})` };
  };
  const input = compile(contract.input, "SpeechRequestValue", "value");
  const event = compile(contract.event, "SpeechEventValue", "value");
  return `# Generated by codegen/generate-clients.ts from ${contract.sourceUrl}. Do not edit.
import json
from typing import Literal, NotRequired, TypeAlias, TypedDict, TypeGuard
from urllib.parse import urlsplit, urlunsplit

from speechswitch.http import HttpRequest, HttpResponse, HttpTransport
from speechswitch.validation import code_point_length, is_mapping, is_number

DEFAULT_BASE_URL = ${literal(contract.baseUrl)}
SPEECH_STATUS = ${contract.status}

${declarations.join("\n\n")}

SpeechRequest: TypeAlias = ${input.type}
SpeechEvent: TypeAlias = ${event.type}

def is_speech_request(value: object) -> TypeGuard[SpeechRequest]:
    return ${input.check}

def _is_speech_event(value: object) -> TypeGuard[SpeechEvent]:
    return ${event.check}

def decode_speech_event(value: object) -> SpeechEvent:
    if not _is_speech_event(value):
        raise TypeError("Invalid OpenAI speech event")
    return value

def _json_container(value: object) -> object:
    if is_mapping(value):
        return dict(value)
    raise TypeError("Invalid OpenAI JSON value")

async def create_speech(value: SpeechRequest, *, api_key: str, base_url: str, transport: HttpTransport) -> HttpResponse:
    if not is_speech_request(value):
        raise TypeError("Invalid OpenAI speech wire request")
    url = urlsplit(base_url)
    if url.scheme not in ("http", "https") or not url.hostname or url.username is not None or url.password is not None or url.fragment:
        raise TypeError("Invalid OpenAI base_url")
    target = urlunsplit((url.scheme, url.netloc, url.path.rstrip("/") + ${literal(contract.path)}, url.query, ""))
    return await transport.send(HttpRequest(${literal(contract.method.toUpperCase())}, target,
        {"Authorization": f"Bearer {api_key}", "Content-Type": "application/json", "Accept": "application/octet-stream, text/event-stream"},
        json.dumps(value, allow_nan=False, default=_json_container, separators=(",", ":")).encode("utf-8")))
`;
}
