import { expect, test } from "bun:test";
import { canonicalPattern } from "./ecmascript-pattern.ts";
import { renderPythonValidator } from "./python-validator.ts";
import type { SchemaField } from "./spec-model.ts";

test("Python boundary defaults preserve zero and false without changing validation", () => {
  const fields: SchemaField[] = [
    { name: "sampleRateHz", optional: true, documentation: "", typeScriptType: "number", type: { kind: "number" }, default: 0 },
    { name: "textNormalization", optional: true, documentation: "", typeScriptType: "boolean", type: { kind: "boolean" }, default: false },
  ];
  const plain = renderPythonValidator({ id: "fixture", request: { kind: "object", fields: fields.map(({ default: _default, ...field }) => field) } });
  expect(renderPythonValidator({ id: "fixture", request: { kind: "object", fields } })).toBe(plain.replace(
    "utf16_units, code_point_length\n",
    'utf16_units, code_point_length\n\n# Unconditional defaults shared by every request variant.\nREQUEST_DEFAULTS = {"sample_rate_hz": 0, "text_normalization": False}\n',
  ));
});

test.each([
  ["^.+$", "\\A[^\\n\\r\\u2028\\u2029]+\\Z"],
  ["^[\\s\\S]{1,4000}$", "\\A[\\u0000-\\uffff]{1,4000}\\Z"],
  ["^[0-9]+$", "\\A[\\u0030-\\u0039]+\\Z"],
  ["^(tc|uc)_.+$", "\\A(?:[\\u0074][\\u0063]|[\\u0075][\\u0063])[\\u005f][^\\n\\r\\u2028\\u2029]+\\Z"],
])("translates %s without inheriting Python regex semantics", (source, expected) => {
  expect(canonicalPattern(source)).toBe(expected);
});

test.each(["(a)\\1", "\\bword\\b", "(?<=a)b", "(?<name>a)", "\\p{Letter}", "\\cA", "a{nope}"])("unsupported pattern %s fails generation", source => {
  expect(() => canonicalPattern(source)).toThrow(new TypeError(`Unsupported ECMAScript schema pattern: ${source}`));
});

test("emits a specialized Python predicate with an exact public rejection", () => {
  expect(renderPythonValidator({ id: "fixture", request: { kind: "object", fields: [
    { name: "sampleRateHz", optional: false, documentation: "", typeScriptType: "number", type: { kind: "number" }, constraints: { integer: true, minimum: 1 } },
  ] } })).toBe(`# Generated by codegen/generate-language-types.ts from schemas/. Do not edit.
import re
from speechswitch.validation import InputValidator, is_number, is_mapping, is_sequence, is_json_value, utf16_units, code_point_length



def _valid0(value: object) -> bool:
    return is_number(value) and value >= 1 and -9007199254740991 <= value <= 9007199254740991 and value % 1 == 0

def _valid1(value: object) -> bool:
    return is_mapping(value) and ("sample_rate_hz" in value and _valid0(value["sample_rate_hz"]))

def validate_request(value: object) -> InputValidator:
    """Validate without advancing input or inserting defaults; check items when consumed."""
    if not _valid1(value):
        raise TypeError("Invalid fixture TTS request")

    def validate_input(item: object, field: str = "text") -> None:
        if not (False):
            raise TypeError("Invalid fixture TTS input item")
    return validate_input
`);
});
