import { expect, test } from "bun:test";
import { canonicalPattern } from "./ecmascript-pattern.ts";
import { renderPythonValidator } from "./python-validator.ts";
import type { SchemaField } from "./spec-model.ts";

test("Python boundary defaults preserve zero and false without changing validation", () => {
  const fields: SchemaField[] = [
    { name: "sampleRateHz", optional: true, documentation: "", typeScriptType: "number", type: { kind: "number" }, default: 0 },
    { name: "textNormalization", optional: true, documentation: "", typeScriptType: "boolean", type: { kind: "boolean" }, default: false },
  ];
  const plain = renderPythonValidator({ id: "fixture", request: { kind: "object", fields: fields.map(({ default: _default, ...field }) => field) } });
  expect(renderPythonValidator({ id: "fixture", request: { kind: "object", fields } })).toBe(plain.replace(
    "utf16_units, code_point_length\n",
    'utf16_units, code_point_length\n\n# Unconditional defaults shared by every request variant.\nREQUEST_DEFAULTS = {"sample_rate_hz": 0, "text_normalization": False}\n',
  ));
});

test.each([
  ["^.+$", "\\A[^\\n\\r\\u2028\\u2029]+\\Z"],
  ["^[\\s\\S]{1,4000}$", "\\A[\\u0000-\\uffff]{1,4000}\\Z"],
  ["^[0-9]+$", "\\A[\\u0030-\\u0039]+\\Z"],
  ["^(tc|uc)_.+$", "\\A(?:[\\u0074][\\u0063]|[\\u0075][\\u0063])[\\u005f][^\\n\\r\\u2028\\u2029]+\\Z"],
])("translates %s without inheriting Python regex semantics", (source, expected) => {
  expect(canonicalPattern(source)).toBe(expected);
});

test.each(["(a)\\1", "\\bword\\b", "(?<=a)b", "(?<name>a)", "\\p{Letter}", "\\cA", "a{nope}"])("unsupported pattern %s fails generation", source => {
  expect(() => canonicalPattern(source)).toThrow(new TypeError(`Unsupported ECMAScript schema pattern: ${source}`));
});

test("emits specialized Python checks with accumulated canonical field diagnostics", () => {
  expect(renderPythonValidator({ id: "fixture", request: { kind: "object", fields: [
    { name: "sampleRateHz", optional: false, documentation: "", typeScriptType: "number", type: { kind: "number" }, constraints: { integer: true, minimum: 1 } },
  ] } })).toBe(`# Generated by codegen/generate-language-types.ts from schemas/. Do not edit.
import json
import re
from speechswitch.validation import InputValidator, is_number, is_mapping, is_sequence, is_json_value, utf16_units, code_point_length



def _validate0(value: object, path: str, errors: list[str]) -> None:
    if not (is_number(value)):
        errors.append(path + ": expected finite number")
        return
    if not (is_number(value) and value >= 1):
        errors.append(path + ": expected number >= 1")
    if not (is_number(value) and -9007199254740991 <= value <= 9007199254740991 and value % 1 == 0):
        errors.append(path + ": expected safe integer")

def _validate1(value: object, path: str, errors: list[str]) -> None:
    if not (is_mapping(value)):
        errors.append(path + ": expected object")
        return
    if "sample_rate_hz" in value:
        _validate0(value["sample_rate_hz"], path + "[\\\"sampleRateHz\\\"]", errors)
    else:
        errors.append(path + "[\\\"sampleRateHz\\\"]" + ": required field")

def validate_request(value: object) -> InputValidator:
    """Validate without advancing input or inserting defaults; paths use canonical schema names."""
    errors: list[str] = []
    _validate1(value, "request", errors)
    if errors:
        raise TypeError("Invalid fixture TTS request:\\n" + "\\n".join(errors))

    def validate_input(item: object, field: str = "text") -> None:
        errors: list[str] = []

        if not errors:
            errors.append("text item: streaming input is not supported by this request")
        raise TypeError("Invalid fixture TTS input item:\\n" + "\\n".join(errors))
    return validate_input
`);
});
