import { access, readdir } from "node:fs/promises";
import path from "node:path";

export interface ProviderEntry {
  readonly name: string;
  readonly module: string;
}

export async function discoverProviders(directory: string): Promise<ProviderEntry[]> {
  try {
    const directoryEntries = await readdir(directory, { withFileTypes: true });
    const entries = (await Promise.all(directoryEntries.map(async (entry): Promise<ProviderEntry | undefined> => {
      if (entry.isFile() && entry.name.endsWith(".ts")) {
        const name = entry.name.slice(0, -3);
        return { name, module: `../providers/${name}.ts` };
      }
      if (!entry.isDirectory()) return undefined;
      try {
        await access(path.join(directory, entry.name, "index.ts"));
        return { name: entry.name, module: `../providers/${entry.name}/index.ts` };
      } catch {
        throw new TypeError(`Integration directory is missing index.ts: ${entry.name}`);
      }
    }))).filter((entry): entry is ProviderEntry => entry !== undefined);
    const duplicates = entries.filter((entry, index) => entries.findIndex((candidate) => candidate.name === entry.name) !== index);
    if (duplicates.length) {
      throw new TypeError(`Integration cannot use both file and directory layouts: ${duplicates.map(({ name }) => name).join(", ")}`);
    }
    return entries.sort((left, right) => left.name.localeCompare(right.name));
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === "ENOENT") return [];
    throw error;
  }
}

function identifier(value: string): string {
  const result = value.replace(/[^A-Za-z0-9_$]/g, "_");
  return /^\d/.test(result) ? `provider_${result}` : result;
}

export function renderProviderRegistry(providers: readonly ProviderEntry[]): string {
  const imports = providers.map(({ name, module }) => `import * as ${identifier(name)} from ${JSON.stringify(module)};`);
  const entries = providers.map(({ name }) => `  ${JSON.stringify(name)}: ${identifier(name)},`);
  return [
    "// Generated by codegen/generate-registry.ts. Do not edit.",
    ...imports,
    ...(imports.length ? [""] : []),
    "export const providers = {",
    ...entries,
    "} as const;",
    "",
  ].join("\n");
}
