import type { SchemaConstraints, SchemaType, TtsProviderSpec } from "./spec-model.ts";

/** Compile our normalized authored types, not the provider's wire documentation. */
export function renderRequestValidator(provider: TtsProviderSpec): string {
  const declarations: string[] = [];
  const predicates = new Map<string, string>();
  function compile(type: SchemaType, constraints?: SchemaConstraints): string {
    let expression: string;
    switch (type.kind) {
      case "literal": expression = `value === ${JSON.stringify(type.value)}`; break;
      case "string": expression = 'typeof value === "string"'; break;
      case "number": expression = 'typeof value === "number" && Number.isFinite(value)'; break;
      case "boolean": expression = 'typeof value === "boolean"'; break;
      case "bigint": expression = 'typeof value === "bigint"'; break;
      case "bytes": expression = "value instanceof Uint8Array"; break;
      case "array": expression = `Array.isArray(value) && value.every(${compile(type.items)})`; break;
      case "async-iterable": expression = '(typeof value === "object" || typeof value === "function") && value !== null && Symbol.asyncIterator in value && typeof value[Symbol.asyncIterator] === "function"'; break;
      case "union": expression = `(${type.anyOf.map(part => `${compile(part, constraints)}(value)`).join(" || ") || "false"})`; break;
      case "object": {
        const fields = type.fields.map(field => {
          const name = JSON.stringify(field.name);
          const check = `${compile(field.type, field.constraints)}(value[${name}])`;
          return field.optional ? `(!(${name} in value) || value[${name}] === undefined || ${check})` : `(${name} in value && ${check})`;
        });
        const forbidden = (type.forbidden ?? []).map(name => `(!(${JSON.stringify(name)} in value) || value[${JSON.stringify(name)}] === undefined)`);
        expression = ['typeof value === "object"', 'value !== null', '!Array.isArray(value)', ...fields, ...forbidden].join(" && ");
        break;
      }
    }
    if (constraints && type.kind !== "union") {
      if (constraints.minimum !== undefined || constraints.maximum !== undefined) {
        expression += ' && typeof value === "number"';
        if (constraints.minimum !== undefined) expression += ` && value >= ${constraints.minimum}`;
        if (constraints.maximum !== undefined) expression += ` && value <= ${constraints.maximum}`;
      }
      if (constraints.pattern !== undefined) expression += ` && typeof value === "string" && new RegExp(${JSON.stringify(constraints.pattern)}).test(value)`;
    }
    const cached = predicates.get(expression);
    if (cached) return cached;
    const name = `valid${predicates.size}`;
    predicates.set(expression, name);
    declarations.push(`function ${name}(value: unknown): boolean {\n  return ${expression};\n}`);
    return name;
  }
  const request = compile(provider.request);
  const alternatives = provider.request.kind === "union" ? provider.request.anyOf : [provider.request];
  const itemGroups = new Map<string, Set<string>>();
  for (const branch of alternatives) {
    if (branch.kind !== "object") throw new TypeError("Request validators require object variants");
    const text = branch.fields.find(field => field.name === "text")?.type;
    for (const part of text?.kind === "union" ? text.anyOf : text ? [text] : []) {
      if (part.kind !== "async-iterable") continue;
      const item = compile(part.items);
      const matches = itemGroups.get(item) ?? new Set<string>();
      matches.add(compile(branch)); itemGroups.set(item, matches);
    }
  }
  const groups = [...itemGroups];
  // Only unconditional, top-level defaults can be resolved before choosing a variant.
  const defaults = alternatives[0]?.kind === "object" ? alternatives[0].fields.filter(field =>
    field.default !== undefined && alternatives.every(branch => branch.kind === "object"
      && branch.fields.some(other => other.name === field.name && other.default === field.default)),
  ) : [];
  return `// Generated by codegen/generate-spec.ts from schemas/providers/${provider.id}/index.ts. Do not edit.
${defaults.length ? `/** Defaults shared by every request variant. */\nexport const requestDefaults = ${JSON.stringify(Object.fromEntries(defaults.map(field => [field.name, field.default])))} as const;\n` : ""}
${declarations.join("\n\n")}

/** Validate without advancing async input; the returned check validates each item when consumed. */
export function validateRequest(value: unknown): (item: unknown) => void {
  if (!${request}(value)) throw new TypeError(${JSON.stringify(`Invalid ${provider.id} TTS request`)});
${groups.map(([, matches], index) => `  const accepts${index} = ${[...matches].map(name => `${name}(value)`).join(" || ")};`).join("\n")}
  return (item: unknown): void => {
    if (!(${groups.map(([name], index) => `(accepts${index} && ${name}(item))`).join(" || ") || "false"})) throw new TypeError(${JSON.stringify(`Invalid ${provider.id} TTS input item`)});
  };
}
`;
}
