import { reactFlightRecords, resolveReactFlightValue } from "./react-flight.ts";

interface Endpoint {
  readonly path: string;
  readonly method: string;
  readonly servers: readonly { readonly url: string }[];
  readonly request: { readonly body: { readonly "application/json": { readonly schemaArray: readonly { readonly properties: Readonly<Record<string, unknown>> }[] } } };
}
export interface RimeContracts { readonly httpServer: string; readonly httpPath: string; readonly webSocketServer: string; readonly modernPath: string; readonly legacyPath: string }

function embeddedEndpoint(html: string, expectedPath: string): Endpoint {
  const records = reactFlightRecords(html);
  const matches: unknown[] = [];
  const visit = (value: unknown): void => {
    if (Array.isArray(value)) { for (const item of value) visit(item); return; }
    if (!value || typeof value !== "object") return;
    const endpoint = (value as { readonly endpoint?: unknown }).endpoint;
    if (endpoint && typeof endpoint === "object" && (endpoint as { readonly path?: unknown }).path === expectedPath) matches.push(endpoint);
    else for (const item of Object.values(value)) visit(item);
  };
  for (const record of records) if (record.kind === "json") visit(record.value);
  if (matches.length !== 1) throw new TypeError(`Expected one Rime ${expectedPath} endpoint, found ${matches.length}`);
  return resolveReactFlightValue(records, matches[0]) as Endpoint;
}

function keys(endpoint: Endpoint): string[] {
  return Object.keys(endpoint.request.body["application/json"].schemaArray[0]!.properties);
}

function validate(endpoint: Endpoint, path: string, expected: readonly string[]): void {
  if (endpoint.path !== path || endpoint.method.toLowerCase() !== (path.startsWith("/ws") ? "get" : "post")) throw new TypeError(`Rime ${path} operation changed`);
  if (JSON.stringify(keys(endpoint)) !== JSON.stringify(expected)) throw new TypeError(`Rime ${path} parameters changed: ${keys(endpoint).join(", ")}`);
}

export function rimeContracts(html: readonly string[], codaHttp: string, codaWebSocket: string): RimeContracts {
  if (html.length !== 6) throw new TypeError("Rime requires six production endpoint pages");
  const coda = embeddedEndpoint(html[0]!, "/v1/rime-tts");
  const codaWs = embeddedEndpoint(html[1]!, "/ws3");
  const mist3 = embeddedEndpoint(html[2]!, "/v1/rime-tts");
  const mist3Ws = embeddedEndpoint(html[3]!, "/ws3");
  const mist2 = embeddedEndpoint(html[4]!, "/v1/rime-tts");
  const mist2Ws = embeddedEndpoint(html[5]!, "/ws2");
  validate(coda, "/v1/rime-tts", ["speaker", "text", "modelId", "lang", "samplingRate", "timeScaleFactor"]);
  validate(mist3, "/v1/rime-tts", ["speaker", "text", "modelId", "samplingRate", "timeScaleFactor", "lang", "pauseBetweenBrackets", "inlineSpeedAlpha"]);
  validate(mist2, "/v1/rime-tts", ["speaker", "text", "modelId", "lang", "pauseBetweenBrackets", "phonemizeBetweenBrackets", "inlineSpeedAlpha", "samplingRate", "speedAlpha", "noTextNormalization"]);
  validate(codaWs, "/ws3", ["speaker", "text", "modelId", "audioFormat", "lang", "samplingRate", "segment"]);
  validate(mist3Ws, "/ws3", ["speaker", "modelId", "audioFormat", "lang", "pauseBetweenBrackets", "samplingRate", "inlineSpeedAlpha", "speedAlpha", "segment"]);
  validate(mist2Ws, "/ws2", ["speaker", "text", "modelId", "audioFormat", "lang", "pauseBetweenBrackets", "phonemizeBetweenBrackets", "inlineSpeedAlpha", "samplingRate", "speedAlpha", "noTextNormalization", "segment"]);
  for (const page of [html[1]!, html[3]!, html[5]!]) for (const value of ["AudioChunkEvent", "TimestampsEvent", "DoneEvent", "ErrorEvent", "&quot;clear&quot;", "&quot;flush&quot;", "&quot;eos&quot;"]) if (!page.includes(value)) throw new TypeError(`Rime JSON WebSocket message changed: ${value}`);
  if (!codaHttp.includes("audio/webm;codecs=opus") || !codaHttp.includes("audio/ogg;codecs=opus") || !codaHttp.includes("audio/PCMU")
    || !codaWebSocket.includes("three arrays inside `word_timestamps` are the same length and index-aligned")
    || !codaWebSocket.includes("Times are in seconds")) throw new TypeError("Rime audio or timestamp documentation changed");
  const httpServer = coda.servers[0]?.url;
  const webSocketServer = codaWs.servers[0]?.url;
  if (httpServer !== "https://users.rime.ai" || webSocketServer !== "wss://users-ws.rime.ai" || mist3.servers[0]?.url !== httpServer || mist2.servers[0]?.url !== httpServer) throw new TypeError("Rime servers changed");
  return { httpServer, httpPath: coda.path, webSocketServer, modernPath: codaWs.path, legacyPath: mist2Ws.path };
}

export function renderRimeClient(contract: RimeContracts, sources: readonly string[]): string {
  return `// Generated by codegen/generate-clients.ts from ${sources.join(", ")}. Do not edit.
import type { Fetch } from "../../runtime/fetch.ts";
export type RimeModel = "coda" | "mist-v3" | "mist-v2";
export type AudioFormat = "mp3" | "wav" | "ogg" | "webm" | "pcm" | "mulaw";
export interface HttpRequest { readonly speaker: string; readonly text: string; readonly modelId: "coda" | "mistv3" | "mistv2"; readonly lang?: string; readonly samplingRate: number; readonly timeScaleFactor?: number; readonly speedAlpha?: number; readonly pauseBetweenBrackets?: boolean; readonly phonemizeBetweenBrackets?: boolean; readonly inlineSpeedAlpha?: string; readonly noTextNormalization?: boolean }
export type ClientMessage = { readonly text: string; readonly contextId?: string } | { readonly operation: "clear" | "flush" | "eos" };
export type ServerMessage = { readonly type: "chunk"; readonly data: string; readonly contextId: string | null } | { readonly type: "timestamps"; readonly word_timestamps: { readonly words: readonly string[]; readonly start: readonly number[]; readonly end: readonly number[] }; readonly contextId: string | null } | { readonly type: "done"; readonly contextId: string | null } | { readonly type: "error"; readonly message: string };
export interface ClientOptions { readonly apiKey: string; readonly fetch: Fetch; readonly baseUrl: string; readonly signal?: AbortSignal }
export const defaultHttpUrl = ${JSON.stringify(`${contract.httpServer}${contract.httpPath}`)};
export const defaultWebSocketServer = ${JSON.stringify(contract.webSocketServer)};
export const modernWebSocketPath = ${JSON.stringify(contract.modernPath)};
export const legacyWebSocketPath = ${JSON.stringify(contract.legacyPath)};
export function synthesizeHttp(input: HttpRequest, accept: string, options: ClientOptions): Promise<Response> { return options.fetch(options.baseUrl, { method: "POST", headers: { authorization: \`Bearer \${options.apiKey}\`, accept, "content-type": "application/json" }, body: JSON.stringify(input), signal: options.signal }); }
`;
}
