import type { SchemaField, SchemaType, SpeechSpec } from "./spec-model.ts";

function applyConstraints(expression: string, field: SchemaField): string {
  let result = expression;
  if (field.constraints?.minimum !== undefined) {
    result += `.refine((value) => value >= ${field.constraints.minimum}, { message: "Must be at least ${field.constraints.minimum}" })`;
  }
  if (field.constraints?.maximum !== undefined) {
    result += `.refine((value) => value <= ${field.constraints.maximum}, { message: "Must be at most ${field.constraints.maximum}" })`;
  }
  if (field.constraints?.pattern !== undefined) {
    result += `.refine((value) => new RegExp(${JSON.stringify(field.constraints.pattern)}).test(value), { message: "Must match the documented pattern" })`;
  }
  if (field.documentation) result += `.describe(${JSON.stringify(field.documentation)})`;
  if (field.optional) result += ".optional()";
  return result;
}

function renderType(type: SchemaType): string {
  switch (type.kind) {
    case "string": return "z.string()";
    case "number": return "z.number()";
    case "boolean": return "z.boolean()";
    case "bigint": return "z.bigint()";
    case "literal": return `z.literal(${JSON.stringify(type.value)})`;
    case "bytes": return "z.instanceof(Uint8Array)";
    case "array": return `z.array(${renderType(type.items)})`;
    case "async-iterable": return `asyncIterableSchema(${renderType(type.items)})`;
    case "object": return renderObject(type.fields);
    case "union": return `z.union([${type.anyOf.map(renderType).join(", ")}])`;
  }
}

function renderObject(fields: readonly SchemaField[]): string {
  const entries = fields.map((field) => `  ${JSON.stringify(field.name)}: ${applyConstraints(renderType(field.type), field)},`);
  return ["z.object({", ...entries, "}).strict()"].join("\n");
}

export function renderZodSchemas(spec: SpeechSpec): string {
  const lines = [
    "// Generated by codegen/generate-spec.ts. Do not edit.",
    'import { z } from "zod";',
    "",
    "function asyncIterableSchema<Item>(_item: z.ZodType<Item>) {",
    "  return z.custom<AsyncIterable<Item>>((value) =>",
    '    typeof value === "object" && value !== null && Symbol.asyncIterator in value,',
    "  );",
    "}",
    "",
    `export const ttsRequestBaseSchema = ${renderObject(spec.tts.request.fields)};`,
    "",
  ];
  lines.push("export const ttsProviderSchemas = {");
  for (const provider of spec.tts.providers) {
    lines.push(`  ${JSON.stringify(provider.id)}: {`);
    for (const model of provider.models) {
      lines.push(`    ${JSON.stringify(model.id)}: ${renderType(model.request)},`);
    }
    lines.push("  },");
  }
  lines.push("} as const;", "");
  return lines.join("\n");
}

export function renderSpecMarkdown(spec: SpeechSpec): string {
  const lines = ["# Normalized speech API", "", spec.tts.request.documentation, "", "## TTS request", ""];
  for (const field of spec.tts.request.fields) {
    lines.push(`### \`${field.name}\``, "", field.documentation, "", `Type: \`${field.typeScriptType}\`${field.optional ? " (optional)" : ""}.`, "");
  }
  for (const provider of spec.tts.providers) {
    lines.push(`## ${provider.id}`, "");
    for (const model of provider.models) {
      lines.push(`### \`${model.id}\``, "", ...(model.documentation ? [model.documentation, ""] : []));
      const alternatives = model.request.kind === "union" ? model.request.anyOf : [model.request];
      alternatives.forEach((alternative, index) => {
        if (alternative.kind !== "object") return;
        if (alternatives.length > 1) lines.push(`Request variant ${index + 1}:`, "");
        for (const field of alternative.fields) lines.push(`- \`${field.name}\`: \`${field.typeScriptType}\``);
        if (alternatives.length > 1) lines.push("");
      });
      lines.push("");
    }
  }
  return `${lines.join("\n").trim()}\n`;
}
