interface OpenApi { readonly openapi?: string; readonly servers?: readonly { readonly url?: string }[]; readonly paths?: Readonly<Record<string, { readonly get?: { readonly operationId?: string }; readonly post?: { readonly operationId?: string } }>>; readonly components?: { readonly schemas?: Readonly<Record<string, { readonly enum?: readonly string[]; readonly properties?: Readonly<Record<string, unknown>>; readonly required?: readonly string[] }>> } }
export interface TypecastContract { readonly server: string; readonly models: readonly string[] }
export function typecastContract(value: unknown, skill: string, documentation: string): TypecastContract {
  const api = value as OpenApi;
  if (api.openapi !== "3.1.0" || api.servers?.[0]?.url !== "https://api.typecast.ai") throw new TypeError("Typecast OpenAPI metadata changed");
  const operations = { "/v1/text-to-speech": "text_to_speech_v1_text_to_speech_post", "/v1/text-to-speech/stream": "text_to_speech_stream_v1_text_to_speech_stream_post", "/v1/text-to-speech/compose": "text_to_speech_compose_v1_text_to_speech_compose_post", "/v1/text-to-speech/with-timestamps": "text_to_speech_with_timestamps_v1_text_to_speech_with_timestamps_post" } as const;
  for (const [path, operation] of Object.entries(operations)) if (api.paths?.[path]?.post?.operationId !== operation) throw new TypeError(`Typecast operation changed: ${path}`);
  if (api.paths?.["/v3/voices"]?.get?.operationId !== "get_voices_v3_v3_voices_get" || api.paths?.["/v1/custom-voices"]?.get?.operationId !== "list_custom_voices_v1_custom_voices_get" || api.paths?.["/v1/custom-voices/instant-clone"]?.post?.operationId !== "create_instant_clone_v1_custom_voices_instant_clone_post" || api.paths?.["/v1/custom-voices/professional-clone"]?.post?.operationId !== "create_professional_clone_v1_custom_voices_professional_clone_post") throw new TypeError("Typecast voice operations changed");
  const request = api.components?.schemas?.TTSRequest;
  if (JSON.stringify(request?.required) !== JSON.stringify(["voice_id", "text", "model"]) || JSON.stringify(Object.keys(request?.properties ?? {})) !== JSON.stringify(["seed", "text", "model", "output", "prompt", "language", "voice_id"])) throw new TypeError("Typecast TTS request changed");
  const models = api.components?.schemas?.TTSModel?.enum;
  if (!models || !skill.includes("openapi.json") || !documentation.includes("text-to-speech")) throw new TypeError("Typecast discovery documents changed");
  return { server: api.servers[0]!.url!, models };
}
export function renderTypecastClient(contract: TypecastContract, sources: readonly string[]): string {
  return `// Generated by codegen/generate-clients.ts from ${sources.join(", ")}. Do not edit.
import type { Fetch } from "../../runtime/fetch.ts";
export type Model = ${contract.models.map((value) => JSON.stringify(value)).join(" | ")};
export type AudioFormat = "wav" | "mp3";
export type Prompt = { readonly emotion_type: "smart"; readonly previous_text?: string; readonly next_text?: string } | { readonly emotion_type: "preset"; readonly emotion_preset: string; readonly emotion_intensity?: number } | { readonly emotion_preset: string; readonly emotion_intensity?: number };
export interface Output { readonly audio_format: AudioFormat; readonly audio_tempo?: number; readonly audio_pitch?: number; readonly volume?: number; readonly target_lufs?: number }
export interface TtsInput { readonly voice_id: string; readonly text: string; readonly model: Model; readonly language?: string; readonly prompt?: Prompt; readonly output: Output; readonly seed?: number }
export type ComposeSegment = ({ readonly type: "tts" } & TtsInput) | { readonly type: "pause"; readonly duration_seconds: number };
export interface TimestampResponse { readonly audio: string; readonly audio_format: AudioFormat; readonly audio_duration: number; readonly words: readonly Alignment[] | null; readonly characters: readonly Alignment[] | null }
export interface Alignment { readonly text: string; readonly start: number; readonly end: number }
export interface Voice { readonly voice_id: string; readonly voice_name: Readonly<Record<string, string>>; readonly voice_type: "original" | "custom"; readonly models: readonly { readonly version: string; readonly emotions: readonly string[] }[]; readonly preview_url?: string | null; readonly age?: string | null; readonly gender?: string | null; readonly use_cases?: readonly string[] }
export interface CustomVoice { readonly voice_id: string; readonly name: string; readonly model: string; readonly source: string; readonly status: string; readonly created_at: string; readonly error?: string | null }
export interface ClientOptions { readonly apiKey: string; readonly fetch: Fetch; readonly baseUrl: string; readonly signal?: AbortSignal }
export const defaultBaseUrl = ${JSON.stringify(contract.server)};
function post(path: string, body: unknown, options: ClientOptions): Promise<Response> { return options.fetch(\`${"${options.baseUrl}"}\${path}\`, { method: "POST", headers: { "x-api-key": options.apiKey, "content-type": "application/json" }, body: JSON.stringify(body), signal: options.signal }); }
function request(path: string, method: string, body: BodyInit | undefined, options: ClientOptions): Promise<Response> { return options.fetch(\`${"${options.baseUrl}"}\${path}\`, { method, headers: { "x-api-key": options.apiKey }, body, signal: options.signal }); }
export function synthesize(input: TtsInput, streaming: boolean, options: ClientOptions): Promise<Response> { return post(streaming ? "/v1/text-to-speech/stream" : "/v1/text-to-speech", input, options); }
export function synthesizeComposed(segments: readonly ComposeSegment[], options: ClientOptions): Promise<Response> { return post("/v1/text-to-speech/compose", { segments }, options); }
export function synthesizeTimestamped(input: TtsInput, granularity: "word" | "char", options: ClientOptions): Promise<Response> { return post(\`/v1/text-to-speech/with-timestamps?granularity=\${granularity}\`, input, options); }
export function getVoices(query: URLSearchParams, options: ClientOptions): Promise<Response> { return request(\`/v3/voices?\${query}\`, "GET", undefined, options); }
export function getCustomVoices(options: ClientOptions): Promise<Response> { return request("/v1/custom-voices", "GET", undefined, options); }
export function createCustomVoice(professional: boolean, form: FormData, options: ClientOptions): Promise<Response> { return request(professional ? "/v1/custom-voices/professional-clone" : "/v1/custom-voices/instant-clone", "POST", form, options); }
export function deleteCustomVoice(voiceId: string, options: ClientOptions): Promise<Response> { return request(\`/v1/custom-voices/\${encodeURIComponent(voiceId)}\`, "DELETE", undefined, options); }
`;
}
