interface Api { readonly openapi?: string; readonly servers?: readonly { readonly url?: string }[]; readonly paths?: Readonly<Record<string, Record<string, { readonly summary?: string; readonly requestBody?: { readonly content?: { readonly "application/json"?: { readonly schema?: { readonly properties?: Readonly<Record<string, unknown>> } } } } }>>> }
export interface VocuContract { readonly server: string; readonly simpleFields: readonly string[] }
export function vocuContract(value: unknown, docs: string, html: string): VocuContract {
  const api = value as Api; const simple = api.paths?.["/api/tts/simple-generate"]?.post; const direct = api.paths?.["/api/tts/simple-generate.mp3"]?.get; const create = api.paths?.["/api/tts/generate"]?.post; const task = api.paths?.["/api/tts/generate/{id}"];
  if (api.openapi !== "3.1.0" || api.servers?.[0]?.url !== "https://v1.vocu.ai" || simple?.summary !== "Synchronous real-time voice generation" || direct?.summary !== "One-shot synthesis returning an MP3 stream directly" || create?.summary !== "Create Asynchronous Voice Generation Task" || !task?.get || !task.delete) throw new TypeError("Vocu TTS contract changed");
  const fields = Object.keys(simple.requestBody?.content?.["application/json"]?.schema?.properties ?? {});
  const expected = ["voiceId", "text", "promptId", "preset", "break_clone", "language", "vivid", "emo_switch", "speechRate", "flash", "stream", "seed", "srt", "input_audio", "vc_mode", "high_quality"];
  if (JSON.stringify(fields) !== JSON.stringify(expected) || !docs.includes("There is no \"cancel\" semantics") || !html.includes("documentation is being gradually improved")) throw new TypeError("Vocu published documentation changed");
  return { server: api.servers[0]!.url!, simpleFields: fields };
}
export function renderVocuClient(contract: VocuContract, sources: readonly string[]): string { return `// Generated by codegen/generate-clients.ts from ${sources.join(", ")}. Do not edit.
import type { Fetch } from "../../runtime/fetch.ts";
export type Language = "auto" | "zh" | "en-us" | "ja" | "ko" | "fr-fr" | "pt" | "de" | "es" | "yue";
export interface SpeechInput { readonly voiceId: string; readonly text: string; readonly promptId?: string; readonly preset?: "creative" | "balance" | "stable"; readonly break_clone?: boolean; readonly language?: Language; readonly vivid?: boolean; readonly emo_switch?: readonly [number, number, number, number, number]; readonly speechRate?: number; readonly flash?: boolean; readonly seed?: number }
export interface Job { readonly id: string; readonly status: "pending" | "processing" | "generated" | "failed"; readonly metadata: { readonly audio?: string } }
export interface Options { readonly fetch: Fetch; readonly baseUrl: string; readonly signal?: AbortSignal; readonly apiKey?: string }
export const defaultBaseUrl = ${JSON.stringify(contract.server)};
function json(path: string, method: string, body: unknown, options: Options): Promise<Response> { return options.fetch(\`${"${options.baseUrl}"}\${path}\`, { method, headers: { ...(options.apiKey ? { authorization: \`Bearer \${options.apiKey}\` } : {}), "content-type": "application/json" }, body: body === undefined ? undefined : JSON.stringify(body), signal: options.signal }); }
export function synthesizeDirect(input: SpeechInput, options: Options): Promise<Response> { const query = new URLSearchParams(); for (const [key, value] of Object.entries(input)) if (value !== undefined) query.set(key, Array.isArray(value) ? value.join(",") : String(value)); return options.fetch(\`${"${options.baseUrl}"}/api/tts/simple-generate.mp3?\${query}\`, { headers: { authorization: \`Bearer \${options.apiKey}\` }, signal: options.signal }); }
export function createJob(contents: readonly SpeechInput[], options: Options): Promise<Response> { return json("/api/tts/generate", "POST", { contents: contents.map((value) => ({ type: "text", ...value })) }, options); }
export function getJob(id: string, options: Options): Promise<Response> { return json(\`/api/tts/generate/\${encodeURIComponent(id)}\`, "GET", undefined, options); }
` }
