interface Schema {
  readonly type?: string;
  readonly format?: string;
  readonly properties?: Readonly<Record<string, Schema>>;
  readonly required?: readonly string[];
  readonly items?: Schema;
  readonly minItems?: number;
  readonly maxItems?: number;
}

interface Message {
  readonly type: string;
  readonly schema: Schema;
}

interface Parameter {
  readonly name: string;
  readonly type: string;
  readonly required: boolean;
  readonly enum?: readonly (string | number)[];
}

interface StreamingContract {
  readonly endpoint: string;
  readonly queryParameters: readonly Parameter[];
  readonly clientMessages: readonly Message[];
  readonly serverMessages: readonly Message[];
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function contract(value: unknown): StreamingContract {
  if (!isRecord(value) || value.endpoint !== "wss://api.x.ai/v1/tts") {
    throw new TypeError("Invalid xAI streaming TTS contract");
  }
  if (!Array.isArray(value.queryParameters) || !Array.isArray(value.clientMessages) || !Array.isArray(value.serverMessages)) {
    throw new TypeError("xAI streaming TTS contract is missing protocol definitions");
  }
  return value as unknown as StreamingContract;
}

function scalar(schema: Schema): string {
  if (schema.type === "string") return "string";
  if (schema.type === "number" || schema.type === "integer") return "number";
  if (schema.type === "boolean") return "boolean";
  if (schema.type === "array") {
    if (!schema.items) throw new TypeError("xAI array schema has no items");
    const item = scalar(schema.items);
    return schema.minItems === schema.maxItems && schema.minItems === 2
      ? `readonly [${item}, ${item}]`
      : `readonly (${item})[]`;
  }
  if (schema.type === "object") {
    const required = new Set(schema.required ?? []);
    return `{ readonly ${Object.entries(schema.properties ?? {}).map(([name, property]) =>
      `${JSON.stringify(name)}${required.has(name) ? "" : "?"}: ${scalar(property)}`
    ).join("; readonly ")} }`;
  }
  throw new TypeError(`Unsupported xAI schema type: ${String(schema.type)}`);
}

function messageType(message: Message): string {
  if (message.schema.type !== "object") throw new TypeError(`xAI ${message.type} message is not an object`);
  const required = new Set(message.schema.required ?? []);
  const fields = Object.entries(message.schema.properties ?? {}).map(([name, schema]) =>
    `readonly ${JSON.stringify(name)}${name === "type" || required.has(name) ? "" : "?"}: ${name === "type" ? JSON.stringify(message.type) : scalar(schema)}`
  );
  return `{ ${fields.join("; ")} }`;
}

export function renderXaiStreamingClient(value: unknown, sourceUrl: string): string {
  const specification = contract(value);
  const clientMessages = specification.clientMessages.map(messageType).join("\n  | ");
  const serverMessages = specification.serverMessages.map(messageType).join("\n  | ");
  const parameters = specification.queryParameters.map((parameter) => {
    const type = parameter.enum?.map((item) => JSON.stringify(item)).join(" | ")
      ?? (parameter.type === "integer" ? "number" : parameter.type);
    return `readonly ${JSON.stringify(parameter.name)}${parameter.required ? "" : "?"}: ${type}`;
  }).join(";\n  ");
  return `// Generated by codegen/generate-clients.ts from ${sourceUrl}. Do not edit.
export interface QueryParameters {
  ${parameters};
}

export type ClientMessage =
  | ${clientMessages};

export type ServerMessage =
  | ${serverMessages};

export function encodeMessage(message: ClientMessage): string {
  return JSON.stringify(message);
}

export function decodeMessage(data: unknown): ServerMessage {
  if (typeof data !== "string") throw new TypeError("xAI returned a non-text WebSocket message");
  const value: unknown = JSON.parse(data);
  if (!value || typeof value !== "object") throw new TypeError("xAI returned an invalid WebSocket event");
  const type = (value as { readonly type?: unknown }).type;
  if (!${JSON.stringify(specification.serverMessages.map(({ type }) => type))}.includes(type as string)) {
    throw new TypeError(\`xAI returned unknown WebSocket event: \${String(type)}\`);
  }
  return value as ServerMessage;
}
`;
}
