import { describe, expect, expectTypeOf, test } from "bun:test";
import type { Fetch } from "../../runtime/fetch.ts";
import type { WebSocketLike } from "../../websocket.ts";
import { synthesize, synthesizeWithTimestamps } from "./index.ts";

class FakeWebSocket implements WebSocketLike { readyState=1; binaryType=""; sent: unknown[]=[]; private listeners=new Map<string,Array<(event:any)=>void>>(); send(data:string|ArrayBuffer|ArrayBufferView|Blob){if(typeof data!=="string")throw new TypeError();const value=JSON.parse(data);this.sent.push(value);if(value.operation==="eos")queueMicrotask(()=>{this.emit("message",{data:JSON.stringify({type:"chunk",data:"AQI=",contextId:null})});this.emit("message",{data:JSON.stringify({type:"timestamps",word_timestamps:{words:["hi"],start:[0],end:[0.5]},contextId:null})});this.emit("message",{data:JSON.stringify({type:"done",contextId:null})});});} close(){} addEventListener(type:"open"|"message"|"error"|"close",listener:(event:any)=>void){const values=this.listeners.get(type)??[];values.push(listener);this.listeners.set(type,values);if(type==="open")queueMicrotask(listener)} removeEventListener(type:"open"|"message"|"error"|"close",listener:(event:any)=>void){this.listeners.set(type,(this.listeners.get(type)??[]).filter(v=>v!==listener))} private emit(type:string,event:unknown){for(const listener of this.listeners.get(type)??[])listener(event)} }
const auth={rime:{apiKey:"key"}} as const;

describe("Rime",()=>{
  test("streams HTTP bytes with explicit current model and format",async()=>{let url="",init:RequestInit|undefined;const fetch:Fetch=async(input,request)=>{url=String(input);init=request;return new Response(Uint8Array.of(3))};expect(await Array.fromAsync(synthesize({text:"hello",voice:"astra",model:"coda",language:"en",output:{format:"webm_opus",sampleRateHz:24000},speed:2},{auth,fetch}))).toEqual([Uint8Array.of(3)]);expect(url).toBe("https://users.rime.ai/v1/rime-tts");expect(new Headers(init?.headers).get("accept")).toBe("audio/webm;codecs=opus");expect(JSON.parse(String(init?.body))).toMatchObject({modelId:"coda",timeScaleFactor:0.5});});
  test("maps text, clear, flush, and eos to JSON WebSocket messages",async()=>{const socket=new FakeWebSocket();expect(await Array.fromAsync(synthesize({text:(async function*(){yield "hi";yield {command:"clear"} as const;yield {command:"flush"} as const})(),voice:"cove",model:"mist-v2",output:{format:"mp3",sampleRateHz:22050}},{auth,webSocket:socket}))).toEqual([Uint8Array.of(1,2)]);expect(socket.sent).toEqual([{text:"hi"},{operation:"clear"},{operation:"flush"},{operation:"eos"}]);});
  test("keeps independent timestamp and audio events on one timeline",async()=>{const socket=new FakeWebSocket();expect(await Array.fromAsync(synthesizeWithTimestamps({text:(async function*(){yield "hi"})(),voice:"astra",model:"coda",language:"en",output:{format:"pcm",sampleRateHz:24000},timestampGranularity:"word"},{auth,webSocket:socket}))).toEqual([{correlation:"timeline",audio:Uint8Array.of(1,2),timestamps:[]},{correlation:"timeline",timestamps:[{kind:"word",value:"hi",startTimeMs:0,endTimeMs:500}]}]);});
  test("keeps static input non-command",()=>{type Request=Parameters<typeof synthesize>[0];expectTypeOf<Extract<Request,{readonly text:string}>["text"]>().toEqualTypeOf<string>();});
});
