//! Scalar protobuf operations. Generated clients own message shapes and field tags.
#![allow(dead_code)]

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Error(pub String);
impl std::fmt::Display for Error {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(&self.0)
    }
}
impl std::error::Error for Error {}

#[derive(Default)]
pub struct Writer {
    data: Vec<u8>,
    error: Option<Error>,
}
impl Writer {
    fn varint(&mut self, mut value: u64) -> &mut Self {
        if self.error.is_none() {
            while value >= 128 {
                self.data.push(value as u8 | 128);
                value >>= 7;
            }
            self.data.push(value as u8);
        }
        self
    }
    pub fn uint32(&mut self, value: u32) -> &mut Self {
        self.varint(value as u64)
    }
    pub fn int32(&mut self, value: i32) -> &mut Self {
        self.varint(value as i64 as u64)
    }
    pub fn bool(&mut self, value: bool) -> &mut Self {
        self.uint32(u32::from(value))
    }
    pub fn double(&mut self, value: f64) -> &mut Self {
        if self.error.is_none() {
            if value.is_finite() {
                self.data.extend_from_slice(&value.to_le_bytes());
            } else {
                self.error = Some(Error("Invalid protobuf double".into()));
            }
        }
        self
    }
    pub fn bytes(&mut self, value: &[u8]) -> &mut Self {
        if self.error.is_none() {
            match u32::try_from(value.len()) {
                Ok(length) => {
                    self.uint32(length);
                    self.data.extend_from_slice(value);
                }
                Err(_) => self.error = Some(Error("Invalid protobuf uint32".into())),
            }
        }
        self
    }
    pub fn string(&mut self, value: &str) -> &mut Self {
        self.bytes(value.as_bytes())
    }
    pub fn finish(self) -> Result<Vec<u8>, Error> {
        match self.error {
            Some(error) => Err(error),
            None => Ok(self.data),
        }
    }
}

pub struct Reader<'a> {
    data: &'a [u8],
    offset: usize,
}
impl<'a> Reader<'a> {
    pub fn new(data: &'a [u8]) -> Self {
        Self { data, offset: 0 }
    }
    pub fn done(&self) -> bool {
        self.offset == self.data.len()
    }
    fn take(&mut self, length: usize) -> Result<&'a [u8], Error> {
        if length > self.data.len() - self.offset {
            return Err(Error("Truncated protobuf message".into()));
        }
        let result = &self.data[self.offset..self.offset + length];
        self.offset += length;
        Ok(result)
    }
    fn varint(&mut self) -> Result<u64, Error> {
        let mut result = 0u64;
        for index in 0..10 {
            let byte = self.take(1)?[0];
            if index == 9 && byte > 1 {
                return Err(Error("Invalid protobuf varint".into()));
            }
            result |= u64::from(byte & 127) << (index * 7);
            if byte & 128 == 0 {
                return Ok(result);
            }
        }
        Err(Error("Invalid protobuf varint".into()))
    }
    pub fn uint32(&mut self) -> Result<u32, Error> {
        u32::try_from(self.varint()?).map_err(|_| Error("Invalid protobuf uint32".into()))
    }
    pub fn int32(&mut self) -> Result<i32, Error> {
        Ok(self.varint()? as i32)
    }
    pub fn bool(&mut self) -> Result<bool, Error> {
        Ok(self.varint()? != 0)
    }
    pub fn double(&mut self) -> Result<f64, Error> {
        let mut data = [0u8; 8];
        data.copy_from_slice(self.take(8)?);
        Ok(f64::from_le_bytes(data))
    }
    /// Nested messages borrow; generated byte-valued response fields copy to Vec.
    pub fn bytes(&mut self) -> Result<&'a [u8], Error> {
        let length = usize::try_from(self.uint32()?)
            .map_err(|_| Error("Truncated protobuf message".into()))?;
        self.take(length)
    }
    pub fn string(&mut self) -> Result<String, Error> {
        std::str::from_utf8(self.bytes()?)
            .map(str::to_owned)
            .map_err(|_| Error("Invalid protobuf UTF-8 string".into()))
    }
    pub fn skip(&mut self, wire: u32) -> Result<(), Error> {
        match wire {
            0 => {
                self.varint()?;
            }
            1 => {
                self.take(8)?;
            }
            2 => {
                self.bytes()?;
            }
            5 => {
                self.take(4)?;
            }
            _ => return Err(Error(format!("Unsupported protobuf wire type: {wire}"))),
        }
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn scalar_boundaries_and_owned_encoding() {
        let mut writer = Writer::default();
        writer
            .uint32(u32::MAX)
            .int32(-1)
            .int32(i32::MIN)
            .bool(false)
            .bool(true)
            .double(1.25)
            .string("😀")
            .bytes(&[0, 255]);
        let data = writer.finish().unwrap();
        assert_eq!(
            &data[..15],
            &[255, 255, 255, 255, 15, 255, 255, 255, 255, 255, 255, 255, 255, 255, 1]
        );
        let mut reader = Reader::new(&data);
        assert_eq!(reader.uint32(), Ok(u32::MAX));
        assert_eq!(reader.int32(), Ok(-1));
        assert_eq!(reader.int32(), Ok(i32::MIN));
        assert_eq!(reader.bool(), Ok(false));
        assert_eq!(reader.bool(), Ok(true));
        assert_eq!(reader.double(), Ok(1.25));
        assert_eq!(reader.string(), Ok("😀".into()));
        assert_eq!(reader.bytes(), Ok(&[0, 255][..]));
        assert!(reader.done());
        let mut negative_zero = Writer::default();
        negative_zero.double(-0.0);
        assert_eq!(negative_zero.finish(), Ok(vec![0, 0, 0, 0, 0, 0, 0, 128]));
        assert_eq!(Reader::new(&[2]).bool(), Ok(true));
    }
    #[test]
    fn exact_scalar_rejections_and_unknown_fields() {
        for number in [f64::NAN, f64::INFINITY, f64::NEG_INFINITY] {
            let mut writer = Writer::default();
            writer.double(number).uint32(1);
            assert_eq!(
                writer.finish(),
                Err(Error("Invalid protobuf double".into()))
            );
        }
        for (bytes, message) in [
            (&[128][..], "Truncated protobuf message"),
            (
                &[255, 255, 255, 255, 255, 255, 255, 255, 255, 2][..],
                "Invalid protobuf varint",
            ),
            (&[255, 255, 255, 255, 16][..], "Invalid protobuf uint32"),
        ] {
            assert_eq!(Reader::new(bytes).uint32(), Err(Error(message.into())));
        }
        assert_eq!(
            Reader::new(&[1, 255]).string(),
            Err(Error("Invalid protobuf UTF-8 string".into()))
        );
        assert_eq!(
            Reader::new(&[3, 1]).bytes(),
            Err(Error("Truncated protobuf message".into()))
        );
        assert_eq!(
            Reader::new(&[]).double(),
            Err(Error("Truncated protobuf message".into()))
        );
        for wire in [3, 4, 6, 7] {
            assert_eq!(
                Reader::new(&[]).skip(wire),
                Err(Error(format!("Unsupported protobuf wire type: {wire}")))
            );
        }
        for (wire, bytes) in [
            (0, vec![128, 1]),
            (1, vec![0; 8]),
            (2, vec![2, 0, 255]),
            (5, vec![0; 4]),
        ] {
            let mut reader = Reader::new(&bytes);
            assert_eq!(reader.skip(wire), Ok(()));
            assert!(reader.done());
        }
    }
}
