# Generated by codegen/generate-clients.ts from https://raw.githubusercontent.com/openai/openai-node/main/api_reference/openapi.transformed.yml. Do not edit.
import json
from typing import Literal, NotRequired, TypeAlias, TypedDict, TypeGuard
from urllib.parse import urlsplit, urlunsplit

from speechswitch.http import HttpRequest, HttpResponse, HttpTransport
from speechswitch.validation import code_point_length, is_mapping, is_number

DEFAULT_BASE_URL = "https://api.openai.com/v1"
SPEECH_STATUS = 200

SpeechRequestValue_Field6_Variant1 = TypedDict("SpeechRequestValue_Field6_Variant1", {
    "id": str,
})

SpeechRequestValue = TypedDict("SpeechRequestValue", {
    "input": str,
    "instructions": NotRequired[str],
    "model": str | Literal["tts-1", "tts-1-hd", "gpt-4o-mini-tts", "gpt-4o-mini-tts-2025-12-15"],
    "response_format": NotRequired[Literal["mp3", "opus", "aac", "flac", "wav", "pcm"]],
    "speed": NotRequired[float],
    "stream_format": NotRequired[Literal["sse", "audio"]],
    "voice": str | Literal["alloy", "ash", "ballad", "coral", "echo", "sage", "shimmer", "verse", "marin", "cedar"] | SpeechRequestValue_Field6_Variant1,
})

SpeechEventValue_Variant0 = TypedDict("SpeechEventValue_Variant0", {
    "audio": str,
    "type": Literal["speech.audio.delta"],
})

SpeechEventValue_Variant1_Field1 = TypedDict("SpeechEventValue_Variant1_Field1", {
    "input_tokens": float,
    "output_tokens": float,
    "total_tokens": float,
})

SpeechEventValue_Variant1 = TypedDict("SpeechEventValue_Variant1", {
    "type": Literal["speech.audio.done"],
    "usage": SpeechEventValue_Variant1_Field1,
})

SpeechRequest: TypeAlias = SpeechRequestValue
SpeechEvent: TypeAlias = SpeechEventValue_Variant0 | SpeechEventValue_Variant1

def is_speech_request(value: object) -> TypeGuard[SpeechRequest]:
    return (is_mapping(value) and ("input" in value and (isinstance(value["input"], str) and code_point_length(value["input"]) <= 4096)) and ("instructions" not in value or (isinstance(value["instructions"], str) and code_point_length(value["instructions"]) <= 4096)) and ("model" in value and ((isinstance(value["model"], str)) or (isinstance(value["model"], str) and (value["model"] == "tts-1" or value["model"] == "tts-1-hd" or value["model"] == "gpt-4o-mini-tts" or value["model"] == "gpt-4o-mini-tts-2025-12-15")))) and ("response_format" not in value or (isinstance(value["response_format"], str) and (value["response_format"] == "mp3" or value["response_format"] == "opus" or value["response_format"] == "aac" or value["response_format"] == "flac" or value["response_format"] == "wav" or value["response_format"] == "pcm"))) and ("speed" not in value or (is_number(value["speed"]) and value["speed"] >= 0.25 and value["speed"] <= 4)) and ("stream_format" not in value or (isinstance(value["stream_format"], str) and (value["stream_format"] == "sse" or value["stream_format"] == "audio"))) and ("voice" in value and (((isinstance(value["voice"], str)) or (isinstance(value["voice"], str) and (value["voice"] == "alloy" or value["voice"] == "ash" or value["voice"] == "ballad" or value["voice"] == "coral" or value["voice"] == "echo" or value["voice"] == "sage" or value["voice"] == "shimmer" or value["voice"] == "verse" or value["voice"] == "marin" or value["voice"] == "cedar"))) or (is_mapping(value["voice"]) and ("id" in value["voice"] and (isinstance(value["voice"]["id"], str))) and all(key in ["id"] for key in value["voice"])))) and all(key in ["input","instructions","model","response_format","speed","stream_format","voice"] for key in value))

def _is_speech_event(value: object) -> TypeGuard[SpeechEvent]:
    return ((is_mapping(value) and ("audio" in value and (isinstance(value["audio"], str))) and ("type" in value and (isinstance(value["type"], str) and (value["type"] == "speech.audio.delta")))) or (is_mapping(value) and ("type" in value and (isinstance(value["type"], str) and (value["type"] == "speech.audio.done"))) and ("usage" in value and (is_mapping(value["usage"]) and ("input_tokens" in value["usage"] and (is_number(value["usage"]["input_tokens"]) and abs(value["usage"]["input_tokens"]) <= 9007199254740991 and (isinstance(value["usage"]["input_tokens"], int) or value["usage"]["input_tokens"].is_integer()))) and ("output_tokens" in value["usage"] and (is_number(value["usage"]["output_tokens"]) and abs(value["usage"]["output_tokens"]) <= 9007199254740991 and (isinstance(value["usage"]["output_tokens"], int) or value["usage"]["output_tokens"].is_integer()))) and ("total_tokens" in value["usage"] and (is_number(value["usage"]["total_tokens"]) and abs(value["usage"]["total_tokens"]) <= 9007199254740991 and (isinstance(value["usage"]["total_tokens"], int) or value["usage"]["total_tokens"].is_integer())))))))

def decode_speech_event(value: object) -> SpeechEvent:
    if not _is_speech_event(value):
        raise TypeError("Invalid OpenAI speech event")
    return value

def _json_container(value: object) -> object:
    if is_mapping(value):
        return dict(value)
    raise TypeError("Invalid OpenAI JSON value")

async def create_speech(value: SpeechRequest, *, api_key: str, base_url: str, transport: HttpTransport) -> HttpResponse:
    if not is_speech_request(value):
        raise TypeError("Invalid OpenAI speech wire request")
    url = urlsplit(base_url)
    if url.scheme not in ("http", "https") or not url.hostname or url.username is not None or url.password is not None or url.fragment:
        raise TypeError("Invalid OpenAI base_url")
    target = urlunsplit((url.scheme, url.netloc, url.path.rstrip("/") + "/audio/speech", url.query, ""))
    return await transport.send(HttpRequest("POST", target,
        {"Authorization": f"Bearer {api_key}", "Content-Type": "application/json", "Accept": "application/octet-stream, text/event-stream"},
        json.dumps(value, allow_nan=False, default=_json_container, separators=(",", ":")).encode("utf-8")))
