// Generated by codegen/generate-clients.ts from https://api.genny.lovo.ai/api/docs-json. Do not edit.
#![allow(dead_code)]
use crate::{endpoint, http::{HttpRequest, HttpResponse, HttpTransport, TransportError}, json::{self, Error, Raw}};
pub const DEFAULT_BASE_URL: &str = "https://api.genny.lovo.ai";
fn failure(message: &str) -> TransportError { std::io::Error::new(std::io::ErrorKind::InvalidData, message).into() }
fn segment(value: &str) -> String {
let mut result = String::new();
for byte in value.bytes() { match byte {
b'A'..=b'Z' | b'a'..=b'z' | b'0'..=b'9' | b'-' | b'_' | b'.' | b'~' => result.push(byte as char),
_ => { use std::fmt::Write; write!(&mut result, "%{byte:02X}").unwrap(); }
} } result
}
pub type TextToSpeechSyncRequestSpeaker = String;

pub type TextToSpeechSyncRequestSpeakerStyle = String;

pub type TextToSpeechSyncRequestSpeed = f64;

pub type TextToSpeechSyncRequestText = String;

#[derive(Debug, Clone, Default, PartialEq)]
pub struct TextToSpeechSyncRequest {
pub speaker: TextToSpeechSyncRequestSpeaker,
pub speaker_style: Option<TextToSpeechSyncRequestSpeakerStyle>,
pub speed: Option<TextToSpeechSyncRequestSpeed>,
pub text: TextToSpeechSyncRequestText,
/// Additional properties retain their validated raw JSON.
pub extra: std::collections::BTreeMap<String, String>,
}

pub type TextToSpeechSyncResponseCreatedAt = String;

pub type EmphasisPosition = f64;

pub type EmphasisValue = f64;

#[derive(Debug, Clone, Default, PartialEq)]
pub struct Emphasis {
pub position: EmphasisPosition,
pub value: EmphasisValue,
/// Additional properties retain their validated raw JSON.
pub extra: std::collections::BTreeMap<String, String>,
}

pub type TextToSpeechOutputEmphasis = Vec<Emphasis>;

pub type JobErrorResponseCode = String;

pub type JobErrorResponseMessage = String;

#[derive(Debug, Clone, Default, PartialEq)]
pub struct JobErrorResponse {
pub code: JobErrorResponseCode,
pub message: JobErrorResponseMessage,
/// Additional properties retain their validated raw JSON.
pub extra: std::collections::BTreeMap<String, String>,
}

pub type PausePosition = f64;

pub type PauseValue = f64;

#[derive(Debug, Clone, Default, PartialEq)]
pub struct Pause {
pub position: PausePosition,
pub value: PauseValue,
/// Additional properties retain their validated raw JSON.
pub extra: std::collections::BTreeMap<String, String>,
}

pub type TextToSpeechOutputPause = Vec<Pause>;

pub type PronunciationIsReplaced = bool;

pub type PronunciationSourceWord = String;

pub type PronunciationTargetWord = String;

#[derive(Debug, Clone, Default, PartialEq)]
pub struct Pronunciation {
pub is_replaced: PronunciationIsReplaced,
pub source_word: PronunciationSourceWord,
pub target_word: PronunciationTargetWord,
/// Additional properties retain their validated raw JSON.
pub extra: std::collections::BTreeMap<String, String>,
}

pub type TextToSpeechOutputPronunciations = Vec<Pronunciation>;

pub type TextToSpeechOutputSpeaker = String;

pub type TextToSpeechOutputSpeakerStyle = String;

pub type TextToSpeechOutputSpeed = f64;

pub type TextToSpeechOutputStatus = String;

pub type TextToSpeechOutputText = String;

pub type TextToSpeechOutputUrlsItem = String;

pub type TextToSpeechOutputUrls = Vec<TextToSpeechOutputUrlsItem>;

#[derive(Debug, Clone, Default, PartialEq)]
pub struct TextToSpeechOutput {
pub emphasis: TextToSpeechOutputEmphasis,
pub error: Option<JobErrorResponse>,
pub pause: TextToSpeechOutputPause,
pub pronunciations: TextToSpeechOutputPronunciations,
pub speaker: TextToSpeechOutputSpeaker,
pub speaker_style: TextToSpeechOutputSpeakerStyle,
pub speed: TextToSpeechOutputSpeed,
pub status: TextToSpeechOutputStatus,
pub text: TextToSpeechOutputText,
pub urls: Option<TextToSpeechOutputUrls>,
/// Additional properties retain their validated raw JSON.
pub extra: std::collections::BTreeMap<String, String>,
}

pub type TextToSpeechSyncResponseData = Vec<TextToSpeechOutput>;

pub type TextToSpeechSyncResponseEstimatedTimeAt = String;

pub type TextToSpeechSyncResponseEstimatedTimeMs = f64;

pub type TextToSpeechSyncResponseId = String;

pub type TextToSpeechSyncResponseProgress = f64;

pub type TextToSpeechSyncResponseProject = String;

pub type TextToSpeechSyncResponseStatus = String;

pub type TextToSpeechSyncResponseTeam = String;

pub type TextToSpeechSyncResponseType = String;

pub type TextToSpeechSyncResponseWorkspace = String;

#[derive(Debug, Clone, Default, PartialEq)]
pub struct TextToSpeechSyncResponse {
pub created_at: TextToSpeechSyncResponseCreatedAt,
pub data: TextToSpeechSyncResponseData,
pub error: Option<JobErrorResponse>,
pub estimated_time_at: Option<TextToSpeechSyncResponseEstimatedTimeAt>,
pub estimated_time_ms: Option<TextToSpeechSyncResponseEstimatedTimeMs>,
pub id: TextToSpeechSyncResponseId,
pub progress: TextToSpeechSyncResponseProgress,
pub project: Option<TextToSpeechSyncResponseProject>,
pub status: TextToSpeechSyncResponseStatus,
pub team: TextToSpeechSyncResponseTeam,
pub type_: TextToSpeechSyncResponseType,
pub workspace: Option<TextToSpeechSyncResponseWorkspace>,
/// Additional properties retain their validated raw JSON.
pub extra: std::collections::BTreeMap<String, String>,
}

pub type CreateSpeechInput = TextToSpeechSyncRequest;

pub type CreateSpeechResponse = TextToSpeechSyncResponse;

pub type TextToSpeechRequestCallbackUrlsItem = String;

pub type TextToSpeechRequestCallbackUrls = Vec<TextToSpeechRequestCallbackUrlsItem>;

pub type TextToSpeechRequestSpeaker = String;

pub type TextToSpeechRequestSpeakerStyle = String;

pub type TextToSpeechRequestSpeed = f64;

pub type TextToSpeechRequestText = String;

#[derive(Debug, Clone, Default, PartialEq)]
pub struct TextToSpeechRequest {
pub callback_urls: Option<TextToSpeechRequestCallbackUrls>,
pub speaker: TextToSpeechRequestSpeaker,
pub speaker_style: Option<TextToSpeechRequestSpeakerStyle>,
pub speed: Option<TextToSpeechRequestSpeed>,
pub text: TextToSpeechRequestText,
/// Additional properties retain their validated raw JSON.
pub extra: std::collections::BTreeMap<String, String>,
}

pub type GetJobResponseCallbackUrlsItem = String;

pub type GetJobResponseCallbackUrls = Vec<GetJobResponseCallbackUrlsItem>;

pub type GetJobResponseCreatedAt = String;

pub type GetJobResponseEstimatedTimeAt = String;

pub type GetJobResponseEstimatedTimeMs = f64;

pub type GetJobResponseId = String;

pub type GetJobResponseProgress = f64;

pub type GetJobResponseProject = String;

pub type GetJobResponseStatus = String;

pub type GetJobResponseTeam = String;

pub type GetJobResponseType = String;

pub type GetJobResponseWorkspace = String;

#[derive(Debug, Clone, Default, PartialEq)]
pub struct GetJobResponse {
pub callback_urls: GetJobResponseCallbackUrls,
pub created_at: GetJobResponseCreatedAt,
pub error: Option<JobErrorResponse>,
pub estimated_time_at: Option<GetJobResponseEstimatedTimeAt>,
pub estimated_time_ms: Option<GetJobResponseEstimatedTimeMs>,
pub id: GetJobResponseId,
pub progress: GetJobResponseProgress,
pub project: Option<GetJobResponseProject>,
pub status: GetJobResponseStatus,
pub team: GetJobResponseTeam,
pub type_: GetJobResponseType,
pub workspace: Option<GetJobResponseWorkspace>,
/// Additional properties retain their validated raw JSON.
pub extra: std::collections::BTreeMap<String, String>,
}

pub type CreateSpeechJobInput = TextToSpeechRequest;

pub type CreateSpeechJobResponse = GetJobResponse;

pub type GetSpeechJobInputJobId = String;

#[derive(Debug, Clone, Default, PartialEq)]
pub struct GetSpeechJobInput {
pub job_id: GetSpeechJobInputJobId,
/// Additional properties retain their validated raw JSON.
pub extra: std::collections::BTreeMap<String, String>,
}

pub type TextToSpeechResponseCallbackUrlsItem = String;

pub type TextToSpeechResponseCallbackUrls = Vec<TextToSpeechResponseCallbackUrlsItem>;

pub type TextToSpeechResponseCreatedAt = String;

pub type TextToSpeechResponseData = Vec<TextToSpeechOutput>;

pub type TextToSpeechResponseEstimatedTimeAt = String;

pub type TextToSpeechResponseEstimatedTimeMs = f64;

pub type TextToSpeechResponseId = String;

pub type TextToSpeechResponseProgress = f64;

pub type TextToSpeechResponseProject = String;

pub type TextToSpeechResponseStatus = String;

pub type TextToSpeechResponseTeam = String;

pub type TextToSpeechResponseType = String;

pub type TextToSpeechResponseWorkspace = String;

#[derive(Debug, Clone, Default, PartialEq)]
pub struct TextToSpeechResponse {
pub callback_urls: TextToSpeechResponseCallbackUrls,
pub created_at: TextToSpeechResponseCreatedAt,
pub data: TextToSpeechResponseData,
pub error: Option<JobErrorResponse>,
pub estimated_time_at: Option<TextToSpeechResponseEstimatedTimeAt>,
pub estimated_time_ms: Option<TextToSpeechResponseEstimatedTimeMs>,
pub id: TextToSpeechResponseId,
pub progress: TextToSpeechResponseProgress,
pub project: Option<TextToSpeechResponseProject>,
pub status: TextToSpeechResponseStatus,
pub team: TextToSpeechResponseTeam,
pub type_: TextToSpeechResponseType,
pub workspace: Option<TextToSpeechResponseWorkspace>,
/// Additional properties retain their validated raw JSON.
pub extra: std::collections::BTreeMap<String, String>,
}

pub type GetSpeechJobResponse = TextToSpeechResponse;
fn check_text_to_speech_sync_request_speaker(value: &TextToSpeechSyncRequestSpeaker) -> Result<(), Error> { let _ = value; Ok(()) }

fn read_text_to_speech_sync_request_speaker(value: Raw<'_>) -> Result<TextToSpeechSyncRequestSpeaker, Error> {
let result = value.string()?; check_text_to_speech_sync_request_speaker(&result)?; Ok(result)
}
fn write_text_to_speech_sync_request_speaker(value: &TextToSpeechSyncRequestSpeaker, output: &mut String) -> Result<(), Error> {
check_text_to_speech_sync_request_speaker(value)?; json::quote(value, output); Ok(())
}

fn check_text_to_speech_sync_request_speaker_style(value: &TextToSpeechSyncRequestSpeakerStyle) -> Result<(), Error> { let _ = value; Ok(()) }

fn read_text_to_speech_sync_request_speaker_style(value: Raw<'_>) -> Result<TextToSpeechSyncRequestSpeakerStyle, Error> {
let result = value.string()?; check_text_to_speech_sync_request_speaker_style(&result)?; Ok(result)
}
fn write_text_to_speech_sync_request_speaker_style(value: &TextToSpeechSyncRequestSpeakerStyle, output: &mut String) -> Result<(), Error> {
check_text_to_speech_sync_request_speaker_style(value)?; json::quote(value, output); Ok(())
}

fn check_text_to_speech_sync_request_speed(value: &TextToSpeechSyncRequestSpeed) -> Result<(), Error> { if !(value.is_finite() && *value >= 0.05_f64 && *value <= 3_f64) { return Err(Error); } Ok(()) }

fn read_text_to_speech_sync_request_speed(value: Raw<'_>) -> Result<TextToSpeechSyncRequestSpeed, Error> {
let result = value.number()?; check_text_to_speech_sync_request_speed(&result)?; Ok(result)
}
fn write_text_to_speech_sync_request_speed(value: &TextToSpeechSyncRequestSpeed, output: &mut String) -> Result<(), Error> {
check_text_to_speech_sync_request_speed(value)?; output.push_str(&value.to_string()); Ok(())
}

fn check_text_to_speech_sync_request_text(value: &TextToSpeechSyncRequestText) -> Result<(), Error> { if !(value.chars().count() >= 1 && value.chars().count() <= 500) { return Err(Error); } Ok(()) }

fn read_text_to_speech_sync_request_text(value: Raw<'_>) -> Result<TextToSpeechSyncRequestText, Error> {
let result = value.string()?; check_text_to_speech_sync_request_text(&result)?; Ok(result)
}
fn write_text_to_speech_sync_request_text(value: &TextToSpeechSyncRequestText, output: &mut String) -> Result<(), Error> {
check_text_to_speech_sync_request_text(value)?; json::quote(value, output); Ok(())
}

fn read_text_to_speech_sync_request(value: Raw<'_>) -> Result<TextToSpeechSyncRequest, Error> {
let mut fields = value.object()?;
let result = TextToSpeechSyncRequest {
speaker: read_text_to_speech_sync_request_speaker(fields.remove("speaker").ok_or(Error)?)?,
speaker_style: fields.remove("speakerStyle").map(read_text_to_speech_sync_request_speaker_style).transpose()?,
speed: fields.remove("speed").map(read_text_to_speech_sync_request_speed).transpose()?,
text: read_text_to_speech_sync_request_text(fields.remove("text").ok_or(Error)?)?,
extra: fields.into_iter().map(|(key, value)| (key, value.text().to_owned())).collect(),
};

Ok(result)
}
fn write_text_to_speech_sync_request(value: &TextToSpeechSyncRequest, output: &mut String) -> Result<(), Error> {
output.push('{');
if !output.ends_with('{') { output.push(','); } json::quote("speaker", output); output.push(':'); write_text_to_speech_sync_request_speaker(&value.speaker, output)?;
if let Some(item) = &value.speaker_style { if !output.ends_with('{') { output.push(','); } json::quote("speakerStyle", output); output.push(':'); write_text_to_speech_sync_request_speaker_style(item, output)?; }
if let Some(item) = &value.speed { if !output.ends_with('{') { output.push(','); } json::quote("speed", output); output.push(':'); write_text_to_speech_sync_request_speed(item, output)?; }
if !output.ends_with('{') { output.push(','); } json::quote("text", output); output.push(':'); write_text_to_speech_sync_request_text(&value.text, output)?;
for (key, item) in &value.extra {
if matches!(key.as_str(), "speaker" | "speakerStyle" | "speed" | "text") { return Err(Error); }
Raw::parse_exact(item)?; if !output.ends_with('{') { output.push(','); } json::quote(key, output); output.push(':'); output.push_str(item);
}
output.push('}'); Ok(())
}

fn check_text_to_speech_sync_response_created_at(value: &TextToSpeechSyncResponseCreatedAt) -> Result<(), Error> { let _ = value; Ok(()) }

fn read_text_to_speech_sync_response_created_at(value: Raw<'_>) -> Result<TextToSpeechSyncResponseCreatedAt, Error> {
let result = value.string()?; check_text_to_speech_sync_response_created_at(&result)?; Ok(result)
}
fn write_text_to_speech_sync_response_created_at(value: &TextToSpeechSyncResponseCreatedAt, output: &mut String) -> Result<(), Error> {
check_text_to_speech_sync_response_created_at(value)?; json::quote(value, output); Ok(())
}

fn check_emphasis_position(value: &EmphasisPosition) -> Result<(), Error> { if !(value.is_finite()) { return Err(Error); } Ok(()) }

fn read_emphasis_position(value: Raw<'_>) -> Result<EmphasisPosition, Error> {
let result = value.number()?; check_emphasis_position(&result)?; Ok(result)
}
fn write_emphasis_position(value: &EmphasisPosition, output: &mut String) -> Result<(), Error> {
check_emphasis_position(value)?; output.push_str(&value.to_string()); Ok(())
}

fn check_emphasis_value(value: &EmphasisValue) -> Result<(), Error> { if !(value.is_finite() && (*value == 0.25_f64 || *value == 0.5_f64 || *value == 0.75_f64)) { return Err(Error); } Ok(()) }

fn read_emphasis_value(value: Raw<'_>) -> Result<EmphasisValue, Error> {
let result = value.number()?; check_emphasis_value(&result)?; Ok(result)
}
fn write_emphasis_value(value: &EmphasisValue, output: &mut String) -> Result<(), Error> {
check_emphasis_value(value)?; output.push_str(&value.to_string()); Ok(())
}

fn read_emphasis(value: Raw<'_>) -> Result<Emphasis, Error> {
let mut fields = value.object()?;
let result = Emphasis {
position: read_emphasis_position(fields.remove("position").ok_or(Error)?)?,
value: read_emphasis_value(fields.remove("value").ok_or(Error)?)?,
extra: fields.into_iter().map(|(key, value)| (key, value.text().to_owned())).collect(),
};

Ok(result)
}
fn write_emphasis(value: &Emphasis, output: &mut String) -> Result<(), Error> {
output.push('{');
if !output.ends_with('{') { output.push(','); } json::quote("position", output); output.push(':'); write_emphasis_position(&value.position, output)?;
if !output.ends_with('{') { output.push(','); } json::quote("value", output); output.push(':'); write_emphasis_value(&value.value, output)?;
for (key, item) in &value.extra {
if matches!(key.as_str(), "position" | "value") { return Err(Error); }
Raw::parse_exact(item)?; if !output.ends_with('{') { output.push(','); } json::quote(key, output); output.push(':'); output.push_str(item);
}
output.push('}'); Ok(())
}

fn read_text_to_speech_output_emphasis(value: Raw<'_>) -> Result<TextToSpeechOutputEmphasis, Error> {
value.array()?.into_iter().map(read_emphasis).collect()
}
fn write_text_to_speech_output_emphasis(value: &TextToSpeechOutputEmphasis, output: &mut String) -> Result<(), Error> {
output.push('['); for (index, item) in value.iter().enumerate() { if index != 0 { output.push(','); } write_emphasis(item, output)?; } output.push(']'); Ok(())
}

fn check_job_error_response_code(value: &JobErrorResponseCode) -> Result<(), Error> { let _ = value; Ok(()) }

fn read_job_error_response_code(value: Raw<'_>) -> Result<JobErrorResponseCode, Error> {
let result = value.string()?; check_job_error_response_code(&result)?; Ok(result)
}
fn write_job_error_response_code(value: &JobErrorResponseCode, output: &mut String) -> Result<(), Error> {
check_job_error_response_code(value)?; json::quote(value, output); Ok(())
}

fn check_job_error_response_message(value: &JobErrorResponseMessage) -> Result<(), Error> { let _ = value; Ok(()) }

fn read_job_error_response_message(value: Raw<'_>) -> Result<JobErrorResponseMessage, Error> {
let result = value.string()?; check_job_error_response_message(&result)?; Ok(result)
}
fn write_job_error_response_message(value: &JobErrorResponseMessage, output: &mut String) -> Result<(), Error> {
check_job_error_response_message(value)?; json::quote(value, output); Ok(())
}

fn read_job_error_response(value: Raw<'_>) -> Result<JobErrorResponse, Error> {
let mut fields = value.object()?;
let result = JobErrorResponse {
code: read_job_error_response_code(fields.remove("code").ok_or(Error)?)?,
message: read_job_error_response_message(fields.remove("message").ok_or(Error)?)?,
extra: fields.into_iter().map(|(key, value)| (key, value.text().to_owned())).collect(),
};

Ok(result)
}
fn write_job_error_response(value: &JobErrorResponse, output: &mut String) -> Result<(), Error> {
output.push('{');
if !output.ends_with('{') { output.push(','); } json::quote("code", output); output.push(':'); write_job_error_response_code(&value.code, output)?;
if !output.ends_with('{') { output.push(','); } json::quote("message", output); output.push(':'); write_job_error_response_message(&value.message, output)?;
for (key, item) in &value.extra {
if matches!(key.as_str(), "code" | "message") { return Err(Error); }
Raw::parse_exact(item)?; if !output.ends_with('{') { output.push(','); } json::quote(key, output); output.push(':'); output.push_str(item);
}
output.push('}'); Ok(())
}

fn check_pause_position(value: &PausePosition) -> Result<(), Error> { if !(value.is_finite()) { return Err(Error); } Ok(()) }

fn read_pause_position(value: Raw<'_>) -> Result<PausePosition, Error> {
let result = value.number()?; check_pause_position(&result)?; Ok(result)
}
fn write_pause_position(value: &PausePosition, output: &mut String) -> Result<(), Error> {
check_pause_position(value)?; output.push_str(&value.to_string()); Ok(())
}

fn check_pause_value(value: &PauseValue) -> Result<(), Error> { if !(value.is_finite() && *value >= 0_f64 && *value <= 2_f64) { return Err(Error); } Ok(()) }

fn read_pause_value(value: Raw<'_>) -> Result<PauseValue, Error> {
let result = value.number()?; check_pause_value(&result)?; Ok(result)
}
fn write_pause_value(value: &PauseValue, output: &mut String) -> Result<(), Error> {
check_pause_value(value)?; output.push_str(&value.to_string()); Ok(())
}

fn read_pause(value: Raw<'_>) -> Result<Pause, Error> {
let mut fields = value.object()?;
let result = Pause {
position: read_pause_position(fields.remove("position").ok_or(Error)?)?,
value: read_pause_value(fields.remove("value").ok_or(Error)?)?,
extra: fields.into_iter().map(|(key, value)| (key, value.text().to_owned())).collect(),
};

Ok(result)
}
fn write_pause(value: &Pause, output: &mut String) -> Result<(), Error> {
output.push('{');
if !output.ends_with('{') { output.push(','); } json::quote("position", output); output.push(':'); write_pause_position(&value.position, output)?;
if !output.ends_with('{') { output.push(','); } json::quote("value", output); output.push(':'); write_pause_value(&value.value, output)?;
for (key, item) in &value.extra {
if matches!(key.as_str(), "position" | "value") { return Err(Error); }
Raw::parse_exact(item)?; if !output.ends_with('{') { output.push(','); } json::quote(key, output); output.push(':'); output.push_str(item);
}
output.push('}'); Ok(())
}

fn read_text_to_speech_output_pause(value: Raw<'_>) -> Result<TextToSpeechOutputPause, Error> {
value.array()?.into_iter().map(read_pause).collect()
}
fn write_text_to_speech_output_pause(value: &TextToSpeechOutputPause, output: &mut String) -> Result<(), Error> {
output.push('['); for (index, item) in value.iter().enumerate() { if index != 0 { output.push(','); } write_pause(item, output)?; } output.push(']'); Ok(())
}

fn check_pronunciation_is_replaced(value: &PronunciationIsReplaced) -> Result<(), Error> { let _ = value; Ok(()) }

fn read_pronunciation_is_replaced(value: Raw<'_>) -> Result<PronunciationIsReplaced, Error> {
let result = value.boolean()?; check_pronunciation_is_replaced(&result)?; Ok(result)
}
fn write_pronunciation_is_replaced(value: &PronunciationIsReplaced, output: &mut String) -> Result<(), Error> {
check_pronunciation_is_replaced(value)?; output.push_str(&value.to_string()); Ok(())
}

fn check_pronunciation_source_word(value: &PronunciationSourceWord) -> Result<(), Error> { let _ = value; Ok(()) }

fn read_pronunciation_source_word(value: Raw<'_>) -> Result<PronunciationSourceWord, Error> {
let result = value.string()?; check_pronunciation_source_word(&result)?; Ok(result)
}
fn write_pronunciation_source_word(value: &PronunciationSourceWord, output: &mut String) -> Result<(), Error> {
check_pronunciation_source_word(value)?; json::quote(value, output); Ok(())
}

fn check_pronunciation_target_word(value: &PronunciationTargetWord) -> Result<(), Error> { let _ = value; Ok(()) }

fn read_pronunciation_target_word(value: Raw<'_>) -> Result<PronunciationTargetWord, Error> {
let result = value.string()?; check_pronunciation_target_word(&result)?; Ok(result)
}
fn write_pronunciation_target_word(value: &PronunciationTargetWord, output: &mut String) -> Result<(), Error> {
check_pronunciation_target_word(value)?; json::quote(value, output); Ok(())
}

fn read_pronunciation(value: Raw<'_>) -> Result<Pronunciation, Error> {
let mut fields = value.object()?;
let result = Pronunciation {
is_replaced: read_pronunciation_is_replaced(fields.remove("isReplaced").ok_or(Error)?)?,
source_word: read_pronunciation_source_word(fields.remove("sourceWord").ok_or(Error)?)?,
target_word: read_pronunciation_target_word(fields.remove("targetWord").ok_or(Error)?)?,
extra: fields.into_iter().map(|(key, value)| (key, value.text().to_owned())).collect(),
};

Ok(result)
}
fn write_pronunciation(value: &Pronunciation, output: &mut String) -> Result<(), Error> {
output.push('{');
if !output.ends_with('{') { output.push(','); } json::quote("isReplaced", output); output.push(':'); write_pronunciation_is_replaced(&value.is_replaced, output)?;
if !output.ends_with('{') { output.push(','); } json::quote("sourceWord", output); output.push(':'); write_pronunciation_source_word(&value.source_word, output)?;
if !output.ends_with('{') { output.push(','); } json::quote("targetWord", output); output.push(':'); write_pronunciation_target_word(&value.target_word, output)?;
for (key, item) in &value.extra {
if matches!(key.as_str(), "isReplaced" | "sourceWord" | "targetWord") { return Err(Error); }
Raw::parse_exact(item)?; if !output.ends_with('{') { output.push(','); } json::quote(key, output); output.push(':'); output.push_str(item);
}
output.push('}'); Ok(())
}

fn read_text_to_speech_output_pronunciations(value: Raw<'_>) -> Result<TextToSpeechOutputPronunciations, Error> {
value.array()?.into_iter().map(read_pronunciation).collect()
}
fn write_text_to_speech_output_pronunciations(value: &TextToSpeechOutputPronunciations, output: &mut String) -> Result<(), Error> {
output.push('['); for (index, item) in value.iter().enumerate() { if index != 0 { output.push(','); } write_pronunciation(item, output)?; } output.push(']'); Ok(())
}

fn check_text_to_speech_output_speaker(value: &TextToSpeechOutputSpeaker) -> Result<(), Error> { let _ = value; Ok(()) }

fn read_text_to_speech_output_speaker(value: Raw<'_>) -> Result<TextToSpeechOutputSpeaker, Error> {
let result = value.string()?; check_text_to_speech_output_speaker(&result)?; Ok(result)
}
fn write_text_to_speech_output_speaker(value: &TextToSpeechOutputSpeaker, output: &mut String) -> Result<(), Error> {
check_text_to_speech_output_speaker(value)?; json::quote(value, output); Ok(())
}

fn check_text_to_speech_output_speaker_style(value: &TextToSpeechOutputSpeakerStyle) -> Result<(), Error> { let _ = value; Ok(()) }

fn read_text_to_speech_output_speaker_style(value: Raw<'_>) -> Result<TextToSpeechOutputSpeakerStyle, Error> {
let result = value.string()?; check_text_to_speech_output_speaker_style(&result)?; Ok(result)
}
fn write_text_to_speech_output_speaker_style(value: &TextToSpeechOutputSpeakerStyle, output: &mut String) -> Result<(), Error> {
check_text_to_speech_output_speaker_style(value)?; json::quote(value, output); Ok(())
}

fn check_text_to_speech_output_speed(value: &TextToSpeechOutputSpeed) -> Result<(), Error> { if !(value.is_finite()) { return Err(Error); } Ok(()) }

fn read_text_to_speech_output_speed(value: Raw<'_>) -> Result<TextToSpeechOutputSpeed, Error> {
let result = value.number()?; check_text_to_speech_output_speed(&result)?; Ok(result)
}
fn write_text_to_speech_output_speed(value: &TextToSpeechOutputSpeed, output: &mut String) -> Result<(), Error> {
check_text_to_speech_output_speed(value)?; output.push_str(&value.to_string()); Ok(())
}

fn check_text_to_speech_output_status(value: &TextToSpeechOutputStatus) -> Result<(), Error> { if !((value == "pending" || value == "succeeded" || value == "failed")) { return Err(Error); } Ok(()) }

fn read_text_to_speech_output_status(value: Raw<'_>) -> Result<TextToSpeechOutputStatus, Error> {
let result = value.string()?; check_text_to_speech_output_status(&result)?; Ok(result)
}
fn write_text_to_speech_output_status(value: &TextToSpeechOutputStatus, output: &mut String) -> Result<(), Error> {
check_text_to_speech_output_status(value)?; json::quote(value, output); Ok(())
}

fn check_text_to_speech_output_text(value: &TextToSpeechOutputText) -> Result<(), Error> { let _ = value; Ok(()) }

fn read_text_to_speech_output_text(value: Raw<'_>) -> Result<TextToSpeechOutputText, Error> {
let result = value.string()?; check_text_to_speech_output_text(&result)?; Ok(result)
}
fn write_text_to_speech_output_text(value: &TextToSpeechOutputText, output: &mut String) -> Result<(), Error> {
check_text_to_speech_output_text(value)?; json::quote(value, output); Ok(())
}

fn check_text_to_speech_output_urls_item(value: &TextToSpeechOutputUrlsItem) -> Result<(), Error> { let _ = value; Ok(()) }

fn read_text_to_speech_output_urls_item(value: Raw<'_>) -> Result<TextToSpeechOutputUrlsItem, Error> {
let result = value.string()?; check_text_to_speech_output_urls_item(&result)?; Ok(result)
}
fn write_text_to_speech_output_urls_item(value: &TextToSpeechOutputUrlsItem, output: &mut String) -> Result<(), Error> {
check_text_to_speech_output_urls_item(value)?; json::quote(value, output); Ok(())
}

fn read_text_to_speech_output_urls(value: Raw<'_>) -> Result<TextToSpeechOutputUrls, Error> {
value.array()?.into_iter().map(read_text_to_speech_output_urls_item).collect()
}
fn write_text_to_speech_output_urls(value: &TextToSpeechOutputUrls, output: &mut String) -> Result<(), Error> {
output.push('['); for (index, item) in value.iter().enumerate() { if index != 0 { output.push(','); } write_text_to_speech_output_urls_item(item, output)?; } output.push(']'); Ok(())
}

fn read_text_to_speech_output(value: Raw<'_>) -> Result<TextToSpeechOutput, Error> {
let mut fields = value.object()?;
let result = TextToSpeechOutput {
emphasis: read_text_to_speech_output_emphasis(fields.remove("emphasis").ok_or(Error)?)?,
error: fields.remove("error").map(read_job_error_response).transpose()?,
pause: read_text_to_speech_output_pause(fields.remove("pause").ok_or(Error)?)?,
pronunciations: read_text_to_speech_output_pronunciations(fields.remove("pronunciations").ok_or(Error)?)?,
speaker: read_text_to_speech_output_speaker(fields.remove("speaker").ok_or(Error)?)?,
speaker_style: read_text_to_speech_output_speaker_style(fields.remove("speakerStyle").ok_or(Error)?)?,
speed: read_text_to_speech_output_speed(fields.remove("speed").ok_or(Error)?)?,
status: read_text_to_speech_output_status(fields.remove("status").ok_or(Error)?)?,
text: read_text_to_speech_output_text(fields.remove("text").ok_or(Error)?)?,
urls: fields.remove("urls").map(read_text_to_speech_output_urls).transpose()?,
extra: fields.into_iter().map(|(key, value)| (key, value.text().to_owned())).collect(),
};

Ok(result)
}
fn write_text_to_speech_output(value: &TextToSpeechOutput, output: &mut String) -> Result<(), Error> {
output.push('{');
if !output.ends_with('{') { output.push(','); } json::quote("emphasis", output); output.push(':'); write_text_to_speech_output_emphasis(&value.emphasis, output)?;
if let Some(item) = &value.error { if !output.ends_with('{') { output.push(','); } json::quote("error", output); output.push(':'); write_job_error_response(item, output)?; }
if !output.ends_with('{') { output.push(','); } json::quote("pause", output); output.push(':'); write_text_to_speech_output_pause(&value.pause, output)?;
if !output.ends_with('{') { output.push(','); } json::quote("pronunciations", output); output.push(':'); write_text_to_speech_output_pronunciations(&value.pronunciations, output)?;
if !output.ends_with('{') { output.push(','); } json::quote("speaker", output); output.push(':'); write_text_to_speech_output_speaker(&value.speaker, output)?;
if !output.ends_with('{') { output.push(','); } json::quote("speakerStyle", output); output.push(':'); write_text_to_speech_output_speaker_style(&value.speaker_style, output)?;
if !output.ends_with('{') { output.push(','); } json::quote("speed", output); output.push(':'); write_text_to_speech_output_speed(&value.speed, output)?;
if !output.ends_with('{') { output.push(','); } json::quote("status", output); output.push(':'); write_text_to_speech_output_status(&value.status, output)?;
if !output.ends_with('{') { output.push(','); } json::quote("text", output); output.push(':'); write_text_to_speech_output_text(&value.text, output)?;
if let Some(item) = &value.urls { if !output.ends_with('{') { output.push(','); } json::quote("urls", output); output.push(':'); write_text_to_speech_output_urls(item, output)?; }
for (key, item) in &value.extra {
if matches!(key.as_str(), "emphasis" | "error" | "pause" | "pronunciations" | "speaker" | "speakerStyle" | "speed" | "status" | "text" | "urls") { return Err(Error); }
Raw::parse_exact(item)?; if !output.ends_with('{') { output.push(','); } json::quote(key, output); output.push(':'); output.push_str(item);
}
output.push('}'); Ok(())
}

fn read_text_to_speech_sync_response_data(value: Raw<'_>) -> Result<TextToSpeechSyncResponseData, Error> {
value.array()?.into_iter().map(read_text_to_speech_output).collect()
}
fn write_text_to_speech_sync_response_data(value: &TextToSpeechSyncResponseData, output: &mut String) -> Result<(), Error> {
output.push('['); for (index, item) in value.iter().enumerate() { if index != 0 { output.push(','); } write_text_to_speech_output(item, output)?; } output.push(']'); Ok(())
}

fn check_text_to_speech_sync_response_estimated_time_at(value: &TextToSpeechSyncResponseEstimatedTimeAt) -> Result<(), Error> { let _ = value; Ok(()) }

fn read_text_to_speech_sync_response_estimated_time_at(value: Raw<'_>) -> Result<TextToSpeechSyncResponseEstimatedTimeAt, Error> {
let result = value.string()?; check_text_to_speech_sync_response_estimated_time_at(&result)?; Ok(result)
}
fn write_text_to_speech_sync_response_estimated_time_at(value: &TextToSpeechSyncResponseEstimatedTimeAt, output: &mut String) -> Result<(), Error> {
check_text_to_speech_sync_response_estimated_time_at(value)?; json::quote(value, output); Ok(())
}

fn check_text_to_speech_sync_response_estimated_time_ms(value: &TextToSpeechSyncResponseEstimatedTimeMs) -> Result<(), Error> { if !(value.is_finite()) { return Err(Error); } Ok(()) }

fn read_text_to_speech_sync_response_estimated_time_ms(value: Raw<'_>) -> Result<TextToSpeechSyncResponseEstimatedTimeMs, Error> {
let result = value.number()?; check_text_to_speech_sync_response_estimated_time_ms(&result)?; Ok(result)
}
fn write_text_to_speech_sync_response_estimated_time_ms(value: &TextToSpeechSyncResponseEstimatedTimeMs, output: &mut String) -> Result<(), Error> {
check_text_to_speech_sync_response_estimated_time_ms(value)?; output.push_str(&value.to_string()); Ok(())
}

fn check_text_to_speech_sync_response_id(value: &TextToSpeechSyncResponseId) -> Result<(), Error> { let _ = value; Ok(()) }

fn read_text_to_speech_sync_response_id(value: Raw<'_>) -> Result<TextToSpeechSyncResponseId, Error> {
let result = value.string()?; check_text_to_speech_sync_response_id(&result)?; Ok(result)
}
fn write_text_to_speech_sync_response_id(value: &TextToSpeechSyncResponseId, output: &mut String) -> Result<(), Error> {
check_text_to_speech_sync_response_id(value)?; json::quote(value, output); Ok(())
}

fn check_text_to_speech_sync_response_progress(value: &TextToSpeechSyncResponseProgress) -> Result<(), Error> { if !(value.is_finite()) { return Err(Error); } Ok(()) }

fn read_text_to_speech_sync_response_progress(value: Raw<'_>) -> Result<TextToSpeechSyncResponseProgress, Error> {
let result = value.number()?; check_text_to_speech_sync_response_progress(&result)?; Ok(result)
}
fn write_text_to_speech_sync_response_progress(value: &TextToSpeechSyncResponseProgress, output: &mut String) -> Result<(), Error> {
check_text_to_speech_sync_response_progress(value)?; output.push_str(&value.to_string()); Ok(())
}

fn check_text_to_speech_sync_response_project(value: &TextToSpeechSyncResponseProject) -> Result<(), Error> { let _ = value; Ok(()) }

fn read_text_to_speech_sync_response_project(value: Raw<'_>) -> Result<TextToSpeechSyncResponseProject, Error> {
let result = value.string()?; check_text_to_speech_sync_response_project(&result)?; Ok(result)
}
fn write_text_to_speech_sync_response_project(value: &TextToSpeechSyncResponseProject, output: &mut String) -> Result<(), Error> {
check_text_to_speech_sync_response_project(value)?; json::quote(value, output); Ok(())
}

fn check_text_to_speech_sync_response_status(value: &TextToSpeechSyncResponseStatus) -> Result<(), Error> { if !((value == "in_progress" || value == "done")) { return Err(Error); } Ok(()) }

fn read_text_to_speech_sync_response_status(value: Raw<'_>) -> Result<TextToSpeechSyncResponseStatus, Error> {
let result = value.string()?; check_text_to_speech_sync_response_status(&result)?; Ok(result)
}
fn write_text_to_speech_sync_response_status(value: &TextToSpeechSyncResponseStatus, output: &mut String) -> Result<(), Error> {
check_text_to_speech_sync_response_status(value)?; json::quote(value, output); Ok(())
}

fn check_text_to_speech_sync_response_team(value: &TextToSpeechSyncResponseTeam) -> Result<(), Error> { let _ = value; Ok(()) }

fn read_text_to_speech_sync_response_team(value: Raw<'_>) -> Result<TextToSpeechSyncResponseTeam, Error> {
let result = value.string()?; check_text_to_speech_sync_response_team(&result)?; Ok(result)
}
fn write_text_to_speech_sync_response_team(value: &TextToSpeechSyncResponseTeam, output: &mut String) -> Result<(), Error> {
check_text_to_speech_sync_response_team(value)?; json::quote(value, output); Ok(())
}

fn check_text_to_speech_sync_response_type(value: &TextToSpeechSyncResponseType) -> Result<(), Error> { if !((value == "tts" || value == "simple_tts" || value == "dubbing" || value == "localization" || value == "subtitles")) { return Err(Error); } Ok(()) }

fn read_text_to_speech_sync_response_type(value: Raw<'_>) -> Result<TextToSpeechSyncResponseType, Error> {
let result = value.string()?; check_text_to_speech_sync_response_type(&result)?; Ok(result)
}
fn write_text_to_speech_sync_response_type(value: &TextToSpeechSyncResponseType, output: &mut String) -> Result<(), Error> {
check_text_to_speech_sync_response_type(value)?; json::quote(value, output); Ok(())
}

fn check_text_to_speech_sync_response_workspace(value: &TextToSpeechSyncResponseWorkspace) -> Result<(), Error> { let _ = value; Ok(()) }

fn read_text_to_speech_sync_response_workspace(value: Raw<'_>) -> Result<TextToSpeechSyncResponseWorkspace, Error> {
let result = value.string()?; check_text_to_speech_sync_response_workspace(&result)?; Ok(result)
}
fn write_text_to_speech_sync_response_workspace(value: &TextToSpeechSyncResponseWorkspace, output: &mut String) -> Result<(), Error> {
check_text_to_speech_sync_response_workspace(value)?; json::quote(value, output); Ok(())
}

fn read_text_to_speech_sync_response(value: Raw<'_>) -> Result<TextToSpeechSyncResponse, Error> {
let mut fields = value.object()?;
let result = TextToSpeechSyncResponse {
created_at: read_text_to_speech_sync_response_created_at(fields.remove("createdAt").ok_or(Error)?)?,
data: read_text_to_speech_sync_response_data(fields.remove("data").ok_or(Error)?)?,
error: fields.remove("error").map(read_job_error_response).transpose()?,
estimated_time_at: fields.remove("estimatedTimeAt").map(read_text_to_speech_sync_response_estimated_time_at).transpose()?,
estimated_time_ms: fields.remove("estimatedTimeMs").map(read_text_to_speech_sync_response_estimated_time_ms).transpose()?,
id: read_text_to_speech_sync_response_id(fields.remove("id").ok_or(Error)?)?,
progress: read_text_to_speech_sync_response_progress(fields.remove("progress").ok_or(Error)?)?,
project: fields.remove("project").map(read_text_to_speech_sync_response_project).transpose()?,
status: read_text_to_speech_sync_response_status(fields.remove("status").ok_or(Error)?)?,
team: read_text_to_speech_sync_response_team(fields.remove("team").ok_or(Error)?)?,
type_: read_text_to_speech_sync_response_type(fields.remove("type").ok_or(Error)?)?,
workspace: fields.remove("workspace").map(read_text_to_speech_sync_response_workspace).transpose()?,
extra: fields.into_iter().map(|(key, value)| (key, value.text().to_owned())).collect(),
};

Ok(result)
}
fn write_text_to_speech_sync_response(value: &TextToSpeechSyncResponse, output: &mut String) -> Result<(), Error> {
output.push('{');
if !output.ends_with('{') { output.push(','); } json::quote("createdAt", output); output.push(':'); write_text_to_speech_sync_response_created_at(&value.created_at, output)?;
if !output.ends_with('{') { output.push(','); } json::quote("data", output); output.push(':'); write_text_to_speech_sync_response_data(&value.data, output)?;
if let Some(item) = &value.error { if !output.ends_with('{') { output.push(','); } json::quote("error", output); output.push(':'); write_job_error_response(item, output)?; }
if let Some(item) = &value.estimated_time_at { if !output.ends_with('{') { output.push(','); } json::quote("estimatedTimeAt", output); output.push(':'); write_text_to_speech_sync_response_estimated_time_at(item, output)?; }
if let Some(item) = &value.estimated_time_ms { if !output.ends_with('{') { output.push(','); } json::quote("estimatedTimeMs", output); output.push(':'); write_text_to_speech_sync_response_estimated_time_ms(item, output)?; }
if !output.ends_with('{') { output.push(','); } json::quote("id", output); output.push(':'); write_text_to_speech_sync_response_id(&value.id, output)?;
if !output.ends_with('{') { output.push(','); } json::quote("progress", output); output.push(':'); write_text_to_speech_sync_response_progress(&value.progress, output)?;
if let Some(item) = &value.project { if !output.ends_with('{') { output.push(','); } json::quote("project", output); output.push(':'); write_text_to_speech_sync_response_project(item, output)?; }
if !output.ends_with('{') { output.push(','); } json::quote("status", output); output.push(':'); write_text_to_speech_sync_response_status(&value.status, output)?;
if !output.ends_with('{') { output.push(','); } json::quote("team", output); output.push(':'); write_text_to_speech_sync_response_team(&value.team, output)?;
if !output.ends_with('{') { output.push(','); } json::quote("type", output); output.push(':'); write_text_to_speech_sync_response_type(&value.type_, output)?;
if let Some(item) = &value.workspace { if !output.ends_with('{') { output.push(','); } json::quote("workspace", output); output.push(':'); write_text_to_speech_sync_response_workspace(item, output)?; }
for (key, item) in &value.extra {
if matches!(key.as_str(), "createdAt" | "data" | "error" | "estimatedTimeAt" | "estimatedTimeMs" | "id" | "progress" | "project" | "status" | "team" | "type" | "workspace") { return Err(Error); }
Raw::parse_exact(item)?; if !output.ends_with('{') { output.push(','); } json::quote(key, output); output.push(':'); output.push_str(item);
}
output.push('}'); Ok(())
}

fn check_text_to_speech_request_callback_urls_item(value: &TextToSpeechRequestCallbackUrlsItem) -> Result<(), Error> { let _ = value; Ok(()) }

fn read_text_to_speech_request_callback_urls_item(value: Raw<'_>) -> Result<TextToSpeechRequestCallbackUrlsItem, Error> {
let result = value.string()?; check_text_to_speech_request_callback_urls_item(&result)?; Ok(result)
}
fn write_text_to_speech_request_callback_urls_item(value: &TextToSpeechRequestCallbackUrlsItem, output: &mut String) -> Result<(), Error> {
check_text_to_speech_request_callback_urls_item(value)?; json::quote(value, output); Ok(())
}

fn read_text_to_speech_request_callback_urls(value: Raw<'_>) -> Result<TextToSpeechRequestCallbackUrls, Error> {
value.array()?.into_iter().map(read_text_to_speech_request_callback_urls_item).collect()
}
fn write_text_to_speech_request_callback_urls(value: &TextToSpeechRequestCallbackUrls, output: &mut String) -> Result<(), Error> {
output.push('['); for (index, item) in value.iter().enumerate() { if index != 0 { output.push(','); } write_text_to_speech_request_callback_urls_item(item, output)?; } output.push(']'); Ok(())
}

fn check_text_to_speech_request_speaker(value: &TextToSpeechRequestSpeaker) -> Result<(), Error> { let _ = value; Ok(()) }

fn read_text_to_speech_request_speaker(value: Raw<'_>) -> Result<TextToSpeechRequestSpeaker, Error> {
let result = value.string()?; check_text_to_speech_request_speaker(&result)?; Ok(result)
}
fn write_text_to_speech_request_speaker(value: &TextToSpeechRequestSpeaker, output: &mut String) -> Result<(), Error> {
check_text_to_speech_request_speaker(value)?; json::quote(value, output); Ok(())
}

fn check_text_to_speech_request_speaker_style(value: &TextToSpeechRequestSpeakerStyle) -> Result<(), Error> { let _ = value; Ok(()) }

fn read_text_to_speech_request_speaker_style(value: Raw<'_>) -> Result<TextToSpeechRequestSpeakerStyle, Error> {
let result = value.string()?; check_text_to_speech_request_speaker_style(&result)?; Ok(result)
}
fn write_text_to_speech_request_speaker_style(value: &TextToSpeechRequestSpeakerStyle, output: &mut String) -> Result<(), Error> {
check_text_to_speech_request_speaker_style(value)?; json::quote(value, output); Ok(())
}

fn check_text_to_speech_request_speed(value: &TextToSpeechRequestSpeed) -> Result<(), Error> { if !(value.is_finite() && *value >= 0.05_f64 && *value <= 3_f64) { return Err(Error); } Ok(()) }

fn read_text_to_speech_request_speed(value: Raw<'_>) -> Result<TextToSpeechRequestSpeed, Error> {
let result = value.number()?; check_text_to_speech_request_speed(&result)?; Ok(result)
}
fn write_text_to_speech_request_speed(value: &TextToSpeechRequestSpeed, output: &mut String) -> Result<(), Error> {
check_text_to_speech_request_speed(value)?; output.push_str(&value.to_string()); Ok(())
}

fn check_text_to_speech_request_text(value: &TextToSpeechRequestText) -> Result<(), Error> { if !(value.chars().count() >= 1 && value.chars().count() <= 500) { return Err(Error); } Ok(()) }

fn read_text_to_speech_request_text(value: Raw<'_>) -> Result<TextToSpeechRequestText, Error> {
let result = value.string()?; check_text_to_speech_request_text(&result)?; Ok(result)
}
fn write_text_to_speech_request_text(value: &TextToSpeechRequestText, output: &mut String) -> Result<(), Error> {
check_text_to_speech_request_text(value)?; json::quote(value, output); Ok(())
}

fn read_text_to_speech_request(value: Raw<'_>) -> Result<TextToSpeechRequest, Error> {
let mut fields = value.object()?;
let result = TextToSpeechRequest {
callback_urls: fields.remove("callbackUrls").map(read_text_to_speech_request_callback_urls).transpose()?,
speaker: read_text_to_speech_request_speaker(fields.remove("speaker").ok_or(Error)?)?,
speaker_style: fields.remove("speakerStyle").map(read_text_to_speech_request_speaker_style).transpose()?,
speed: fields.remove("speed").map(read_text_to_speech_request_speed).transpose()?,
text: read_text_to_speech_request_text(fields.remove("text").ok_or(Error)?)?,
extra: fields.into_iter().map(|(key, value)| (key, value.text().to_owned())).collect(),
};

Ok(result)
}
fn write_text_to_speech_request(value: &TextToSpeechRequest, output: &mut String) -> Result<(), Error> {
output.push('{');
if let Some(item) = &value.callback_urls { if !output.ends_with('{') { output.push(','); } json::quote("callbackUrls", output); output.push(':'); write_text_to_speech_request_callback_urls(item, output)?; }
if !output.ends_with('{') { output.push(','); } json::quote("speaker", output); output.push(':'); write_text_to_speech_request_speaker(&value.speaker, output)?;
if let Some(item) = &value.speaker_style { if !output.ends_with('{') { output.push(','); } json::quote("speakerStyle", output); output.push(':'); write_text_to_speech_request_speaker_style(item, output)?; }
if let Some(item) = &value.speed { if !output.ends_with('{') { output.push(','); } json::quote("speed", output); output.push(':'); write_text_to_speech_request_speed(item, output)?; }
if !output.ends_with('{') { output.push(','); } json::quote("text", output); output.push(':'); write_text_to_speech_request_text(&value.text, output)?;
for (key, item) in &value.extra {
if matches!(key.as_str(), "callbackUrls" | "speaker" | "speakerStyle" | "speed" | "text") { return Err(Error); }
Raw::parse_exact(item)?; if !output.ends_with('{') { output.push(','); } json::quote(key, output); output.push(':'); output.push_str(item);
}
output.push('}'); Ok(())
}

fn check_get_job_response_callback_urls_item(value: &GetJobResponseCallbackUrlsItem) -> Result<(), Error> { let _ = value; Ok(()) }

fn read_get_job_response_callback_urls_item(value: Raw<'_>) -> Result<GetJobResponseCallbackUrlsItem, Error> {
let result = value.string()?; check_get_job_response_callback_urls_item(&result)?; Ok(result)
}
fn write_get_job_response_callback_urls_item(value: &GetJobResponseCallbackUrlsItem, output: &mut String) -> Result<(), Error> {
check_get_job_response_callback_urls_item(value)?; json::quote(value, output); Ok(())
}

fn read_get_job_response_callback_urls(value: Raw<'_>) -> Result<GetJobResponseCallbackUrls, Error> {
value.array()?.into_iter().map(read_get_job_response_callback_urls_item).collect()
}
fn write_get_job_response_callback_urls(value: &GetJobResponseCallbackUrls, output: &mut String) -> Result<(), Error> {
output.push('['); for (index, item) in value.iter().enumerate() { if index != 0 { output.push(','); } write_get_job_response_callback_urls_item(item, output)?; } output.push(']'); Ok(())
}

fn check_get_job_response_created_at(value: &GetJobResponseCreatedAt) -> Result<(), Error> { let _ = value; Ok(()) }

fn read_get_job_response_created_at(value: Raw<'_>) -> Result<GetJobResponseCreatedAt, Error> {
let result = value.string()?; check_get_job_response_created_at(&result)?; Ok(result)
}
fn write_get_job_response_created_at(value: &GetJobResponseCreatedAt, output: &mut String) -> Result<(), Error> {
check_get_job_response_created_at(value)?; json::quote(value, output); Ok(())
}

fn check_get_job_response_estimated_time_at(value: &GetJobResponseEstimatedTimeAt) -> Result<(), Error> { let _ = value; Ok(()) }

fn read_get_job_response_estimated_time_at(value: Raw<'_>) -> Result<GetJobResponseEstimatedTimeAt, Error> {
let result = value.string()?; check_get_job_response_estimated_time_at(&result)?; Ok(result)
}
fn write_get_job_response_estimated_time_at(value: &GetJobResponseEstimatedTimeAt, output: &mut String) -> Result<(), Error> {
check_get_job_response_estimated_time_at(value)?; json::quote(value, output); Ok(())
}

fn check_get_job_response_estimated_time_ms(value: &GetJobResponseEstimatedTimeMs) -> Result<(), Error> { if !(value.is_finite()) { return Err(Error); } Ok(()) }

fn read_get_job_response_estimated_time_ms(value: Raw<'_>) -> Result<GetJobResponseEstimatedTimeMs, Error> {
let result = value.number()?; check_get_job_response_estimated_time_ms(&result)?; Ok(result)
}
fn write_get_job_response_estimated_time_ms(value: &GetJobResponseEstimatedTimeMs, output: &mut String) -> Result<(), Error> {
check_get_job_response_estimated_time_ms(value)?; output.push_str(&value.to_string()); Ok(())
}

fn check_get_job_response_id(value: &GetJobResponseId) -> Result<(), Error> { let _ = value; Ok(()) }

fn read_get_job_response_id(value: Raw<'_>) -> Result<GetJobResponseId, Error> {
let result = value.string()?; check_get_job_response_id(&result)?; Ok(result)
}
fn write_get_job_response_id(value: &GetJobResponseId, output: &mut String) -> Result<(), Error> {
check_get_job_response_id(value)?; json::quote(value, output); Ok(())
}

fn check_get_job_response_progress(value: &GetJobResponseProgress) -> Result<(), Error> { if !(value.is_finite()) { return Err(Error); } Ok(()) }

fn read_get_job_response_progress(value: Raw<'_>) -> Result<GetJobResponseProgress, Error> {
let result = value.number()?; check_get_job_response_progress(&result)?; Ok(result)
}
fn write_get_job_response_progress(value: &GetJobResponseProgress, output: &mut String) -> Result<(), Error> {
check_get_job_response_progress(value)?; output.push_str(&value.to_string()); Ok(())
}

fn check_get_job_response_project(value: &GetJobResponseProject) -> Result<(), Error> { let _ = value; Ok(()) }

fn read_get_job_response_project(value: Raw<'_>) -> Result<GetJobResponseProject, Error> {
let result = value.string()?; check_get_job_response_project(&result)?; Ok(result)
}
fn write_get_job_response_project(value: &GetJobResponseProject, output: &mut String) -> Result<(), Error> {
check_get_job_response_project(value)?; json::quote(value, output); Ok(())
}

fn check_get_job_response_status(value: &GetJobResponseStatus) -> Result<(), Error> { if !((value == "in_progress" || value == "done")) { return Err(Error); } Ok(()) }

fn read_get_job_response_status(value: Raw<'_>) -> Result<GetJobResponseStatus, Error> {
let result = value.string()?; check_get_job_response_status(&result)?; Ok(result)
}
fn write_get_job_response_status(value: &GetJobResponseStatus, output: &mut String) -> Result<(), Error> {
check_get_job_response_status(value)?; json::quote(value, output); Ok(())
}

fn check_get_job_response_team(value: &GetJobResponseTeam) -> Result<(), Error> { let _ = value; Ok(()) }

fn read_get_job_response_team(value: Raw<'_>) -> Result<GetJobResponseTeam, Error> {
let result = value.string()?; check_get_job_response_team(&result)?; Ok(result)
}
fn write_get_job_response_team(value: &GetJobResponseTeam, output: &mut String) -> Result<(), Error> {
check_get_job_response_team(value)?; json::quote(value, output); Ok(())
}

fn check_get_job_response_type(value: &GetJobResponseType) -> Result<(), Error> { if !((value == "tts" || value == "simple_tts" || value == "dubbing" || value == "localization" || value == "subtitles")) { return Err(Error); } Ok(()) }

fn read_get_job_response_type(value: Raw<'_>) -> Result<GetJobResponseType, Error> {
let result = value.string()?; check_get_job_response_type(&result)?; Ok(result)
}
fn write_get_job_response_type(value: &GetJobResponseType, output: &mut String) -> Result<(), Error> {
check_get_job_response_type(value)?; json::quote(value, output); Ok(())
}

fn check_get_job_response_workspace(value: &GetJobResponseWorkspace) -> Result<(), Error> { let _ = value; Ok(()) }

fn read_get_job_response_workspace(value: Raw<'_>) -> Result<GetJobResponseWorkspace, Error> {
let result = value.string()?; check_get_job_response_workspace(&result)?; Ok(result)
}
fn write_get_job_response_workspace(value: &GetJobResponseWorkspace, output: &mut String) -> Result<(), Error> {
check_get_job_response_workspace(value)?; json::quote(value, output); Ok(())
}

fn read_get_job_response(value: Raw<'_>) -> Result<GetJobResponse, Error> {
let mut fields = value.object()?;
let result = GetJobResponse {
callback_urls: read_get_job_response_callback_urls(fields.remove("callbackUrls").ok_or(Error)?)?,
created_at: read_get_job_response_created_at(fields.remove("createdAt").ok_or(Error)?)?,
error: fields.remove("error").map(read_job_error_response).transpose()?,
estimated_time_at: fields.remove("estimatedTimeAt").map(read_get_job_response_estimated_time_at).transpose()?,
estimated_time_ms: fields.remove("estimatedTimeMs").map(read_get_job_response_estimated_time_ms).transpose()?,
id: read_get_job_response_id(fields.remove("id").ok_or(Error)?)?,
progress: read_get_job_response_progress(fields.remove("progress").ok_or(Error)?)?,
project: fields.remove("project").map(read_get_job_response_project).transpose()?,
status: read_get_job_response_status(fields.remove("status").ok_or(Error)?)?,
team: read_get_job_response_team(fields.remove("team").ok_or(Error)?)?,
type_: read_get_job_response_type(fields.remove("type").ok_or(Error)?)?,
workspace: fields.remove("workspace").map(read_get_job_response_workspace).transpose()?,
extra: fields.into_iter().map(|(key, value)| (key, value.text().to_owned())).collect(),
};

Ok(result)
}
fn write_get_job_response(value: &GetJobResponse, output: &mut String) -> Result<(), Error> {
output.push('{');
if !output.ends_with('{') { output.push(','); } json::quote("callbackUrls", output); output.push(':'); write_get_job_response_callback_urls(&value.callback_urls, output)?;
if !output.ends_with('{') { output.push(','); } json::quote("createdAt", output); output.push(':'); write_get_job_response_created_at(&value.created_at, output)?;
if let Some(item) = &value.error { if !output.ends_with('{') { output.push(','); } json::quote("error", output); output.push(':'); write_job_error_response(item, output)?; }
if let Some(item) = &value.estimated_time_at { if !output.ends_with('{') { output.push(','); } json::quote("estimatedTimeAt", output); output.push(':'); write_get_job_response_estimated_time_at(item, output)?; }
if let Some(item) = &value.estimated_time_ms { if !output.ends_with('{') { output.push(','); } json::quote("estimatedTimeMs", output); output.push(':'); write_get_job_response_estimated_time_ms(item, output)?; }
if !output.ends_with('{') { output.push(','); } json::quote("id", output); output.push(':'); write_get_job_response_id(&value.id, output)?;
if !output.ends_with('{') { output.push(','); } json::quote("progress", output); output.push(':'); write_get_job_response_progress(&value.progress, output)?;
if let Some(item) = &value.project { if !output.ends_with('{') { output.push(','); } json::quote("project", output); output.push(':'); write_get_job_response_project(item, output)?; }
if !output.ends_with('{') { output.push(','); } json::quote("status", output); output.push(':'); write_get_job_response_status(&value.status, output)?;
if !output.ends_with('{') { output.push(','); } json::quote("team", output); output.push(':'); write_get_job_response_team(&value.team, output)?;
if !output.ends_with('{') { output.push(','); } json::quote("type", output); output.push(':'); write_get_job_response_type(&value.type_, output)?;
if let Some(item) = &value.workspace { if !output.ends_with('{') { output.push(','); } json::quote("workspace", output); output.push(':'); write_get_job_response_workspace(item, output)?; }
for (key, item) in &value.extra {
if matches!(key.as_str(), "callbackUrls" | "createdAt" | "error" | "estimatedTimeAt" | "estimatedTimeMs" | "id" | "progress" | "project" | "status" | "team" | "type" | "workspace") { return Err(Error); }
Raw::parse_exact(item)?; if !output.ends_with('{') { output.push(','); } json::quote(key, output); output.push(':'); output.push_str(item);
}
output.push('}'); Ok(())
}

fn check_get_speech_job_input_job_id(value: &GetSpeechJobInputJobId) -> Result<(), Error> { let _ = value; Ok(()) }

fn read_get_speech_job_input_job_id(value: Raw<'_>) -> Result<GetSpeechJobInputJobId, Error> {
let result = value.string()?; check_get_speech_job_input_job_id(&result)?; Ok(result)
}
fn write_get_speech_job_input_job_id(value: &GetSpeechJobInputJobId, output: &mut String) -> Result<(), Error> {
check_get_speech_job_input_job_id(value)?; json::quote(value, output); Ok(())
}

fn read_get_speech_job_input(value: Raw<'_>) -> Result<GetSpeechJobInput, Error> {
let mut fields = value.object()?;
let result = GetSpeechJobInput {
job_id: read_get_speech_job_input_job_id(fields.remove("jobId").ok_or(Error)?)?,
extra: fields.into_iter().map(|(key, value)| (key, value.text().to_owned())).collect(),
};

Ok(result)
}
fn write_get_speech_job_input(value: &GetSpeechJobInput, output: &mut String) -> Result<(), Error> {
output.push('{');
if !output.ends_with('{') { output.push(','); } json::quote("jobId", output); output.push(':'); write_get_speech_job_input_job_id(&value.job_id, output)?;
for (key, item) in &value.extra {
if matches!(key.as_str(), "jobId") { return Err(Error); }
Raw::parse_exact(item)?; if !output.ends_with('{') { output.push(','); } json::quote(key, output); output.push(':'); output.push_str(item);
}
output.push('}'); Ok(())
}

fn check_text_to_speech_response_callback_urls_item(value: &TextToSpeechResponseCallbackUrlsItem) -> Result<(), Error> { let _ = value; Ok(()) }

fn read_text_to_speech_response_callback_urls_item(value: Raw<'_>) -> Result<TextToSpeechResponseCallbackUrlsItem, Error> {
let result = value.string()?; check_text_to_speech_response_callback_urls_item(&result)?; Ok(result)
}
fn write_text_to_speech_response_callback_urls_item(value: &TextToSpeechResponseCallbackUrlsItem, output: &mut String) -> Result<(), Error> {
check_text_to_speech_response_callback_urls_item(value)?; json::quote(value, output); Ok(())
}

fn read_text_to_speech_response_callback_urls(value: Raw<'_>) -> Result<TextToSpeechResponseCallbackUrls, Error> {
value.array()?.into_iter().map(read_text_to_speech_response_callback_urls_item).collect()
}
fn write_text_to_speech_response_callback_urls(value: &TextToSpeechResponseCallbackUrls, output: &mut String) -> Result<(), Error> {
output.push('['); for (index, item) in value.iter().enumerate() { if index != 0 { output.push(','); } write_text_to_speech_response_callback_urls_item(item, output)?; } output.push(']'); Ok(())
}

fn check_text_to_speech_response_created_at(value: &TextToSpeechResponseCreatedAt) -> Result<(), Error> { let _ = value; Ok(()) }

fn read_text_to_speech_response_created_at(value: Raw<'_>) -> Result<TextToSpeechResponseCreatedAt, Error> {
let result = value.string()?; check_text_to_speech_response_created_at(&result)?; Ok(result)
}
fn write_text_to_speech_response_created_at(value: &TextToSpeechResponseCreatedAt, output: &mut String) -> Result<(), Error> {
check_text_to_speech_response_created_at(value)?; json::quote(value, output); Ok(())
}

fn read_text_to_speech_response_data(value: Raw<'_>) -> Result<TextToSpeechResponseData, Error> {
value.array()?.into_iter().map(read_text_to_speech_output).collect()
}
fn write_text_to_speech_response_data(value: &TextToSpeechResponseData, output: &mut String) -> Result<(), Error> {
output.push('['); for (index, item) in value.iter().enumerate() { if index != 0 { output.push(','); } write_text_to_speech_output(item, output)?; } output.push(']'); Ok(())
}

fn check_text_to_speech_response_estimated_time_at(value: &TextToSpeechResponseEstimatedTimeAt) -> Result<(), Error> { let _ = value; Ok(()) }

fn read_text_to_speech_response_estimated_time_at(value: Raw<'_>) -> Result<TextToSpeechResponseEstimatedTimeAt, Error> {
let result = value.string()?; check_text_to_speech_response_estimated_time_at(&result)?; Ok(result)
}
fn write_text_to_speech_response_estimated_time_at(value: &TextToSpeechResponseEstimatedTimeAt, output: &mut String) -> Result<(), Error> {
check_text_to_speech_response_estimated_time_at(value)?; json::quote(value, output); Ok(())
}

fn check_text_to_speech_response_estimated_time_ms(value: &TextToSpeechResponseEstimatedTimeMs) -> Result<(), Error> { if !(value.is_finite()) { return Err(Error); } Ok(()) }

fn read_text_to_speech_response_estimated_time_ms(value: Raw<'_>) -> Result<TextToSpeechResponseEstimatedTimeMs, Error> {
let result = value.number()?; check_text_to_speech_response_estimated_time_ms(&result)?; Ok(result)
}
fn write_text_to_speech_response_estimated_time_ms(value: &TextToSpeechResponseEstimatedTimeMs, output: &mut String) -> Result<(), Error> {
check_text_to_speech_response_estimated_time_ms(value)?; output.push_str(&value.to_string()); Ok(())
}

fn check_text_to_speech_response_id(value: &TextToSpeechResponseId) -> Result<(), Error> { let _ = value; Ok(()) }

fn read_text_to_speech_response_id(value: Raw<'_>) -> Result<TextToSpeechResponseId, Error> {
let result = value.string()?; check_text_to_speech_response_id(&result)?; Ok(result)
}
fn write_text_to_speech_response_id(value: &TextToSpeechResponseId, output: &mut String) -> Result<(), Error> {
check_text_to_speech_response_id(value)?; json::quote(value, output); Ok(())
}

fn check_text_to_speech_response_progress(value: &TextToSpeechResponseProgress) -> Result<(), Error> { if !(value.is_finite()) { return Err(Error); } Ok(()) }

fn read_text_to_speech_response_progress(value: Raw<'_>) -> Result<TextToSpeechResponseProgress, Error> {
let result = value.number()?; check_text_to_speech_response_progress(&result)?; Ok(result)
}
fn write_text_to_speech_response_progress(value: &TextToSpeechResponseProgress, output: &mut String) -> Result<(), Error> {
check_text_to_speech_response_progress(value)?; output.push_str(&value.to_string()); Ok(())
}

fn check_text_to_speech_response_project(value: &TextToSpeechResponseProject) -> Result<(), Error> { let _ = value; Ok(()) }

fn read_text_to_speech_response_project(value: Raw<'_>) -> Result<TextToSpeechResponseProject, Error> {
let result = value.string()?; check_text_to_speech_response_project(&result)?; Ok(result)
}
fn write_text_to_speech_response_project(value: &TextToSpeechResponseProject, output: &mut String) -> Result<(), Error> {
check_text_to_speech_response_project(value)?; json::quote(value, output); Ok(())
}

fn check_text_to_speech_response_status(value: &TextToSpeechResponseStatus) -> Result<(), Error> { if !((value == "in_progress" || value == "done")) { return Err(Error); } Ok(()) }

fn read_text_to_speech_response_status(value: Raw<'_>) -> Result<TextToSpeechResponseStatus, Error> {
let result = value.string()?; check_text_to_speech_response_status(&result)?; Ok(result)
}
fn write_text_to_speech_response_status(value: &TextToSpeechResponseStatus, output: &mut String) -> Result<(), Error> {
check_text_to_speech_response_status(value)?; json::quote(value, output); Ok(())
}

fn check_text_to_speech_response_team(value: &TextToSpeechResponseTeam) -> Result<(), Error> { let _ = value; Ok(()) }

fn read_text_to_speech_response_team(value: Raw<'_>) -> Result<TextToSpeechResponseTeam, Error> {
let result = value.string()?; check_text_to_speech_response_team(&result)?; Ok(result)
}
fn write_text_to_speech_response_team(value: &TextToSpeechResponseTeam, output: &mut String) -> Result<(), Error> {
check_text_to_speech_response_team(value)?; json::quote(value, output); Ok(())
}

fn check_text_to_speech_response_type(value: &TextToSpeechResponseType) -> Result<(), Error> { if !((value == "tts" || value == "simple_tts" || value == "dubbing" || value == "localization" || value == "subtitles")) { return Err(Error); } Ok(()) }

fn read_text_to_speech_response_type(value: Raw<'_>) -> Result<TextToSpeechResponseType, Error> {
let result = value.string()?; check_text_to_speech_response_type(&result)?; Ok(result)
}
fn write_text_to_speech_response_type(value: &TextToSpeechResponseType, output: &mut String) -> Result<(), Error> {
check_text_to_speech_response_type(value)?; json::quote(value, output); Ok(())
}

fn check_text_to_speech_response_workspace(value: &TextToSpeechResponseWorkspace) -> Result<(), Error> { let _ = value; Ok(()) }

fn read_text_to_speech_response_workspace(value: Raw<'_>) -> Result<TextToSpeechResponseWorkspace, Error> {
let result = value.string()?; check_text_to_speech_response_workspace(&result)?; Ok(result)
}
fn write_text_to_speech_response_workspace(value: &TextToSpeechResponseWorkspace, output: &mut String) -> Result<(), Error> {
check_text_to_speech_response_workspace(value)?; json::quote(value, output); Ok(())
}

fn read_text_to_speech_response(value: Raw<'_>) -> Result<TextToSpeechResponse, Error> {
let mut fields = value.object()?;
let result = TextToSpeechResponse {
callback_urls: read_text_to_speech_response_callback_urls(fields.remove("callbackUrls").ok_or(Error)?)?,
created_at: read_text_to_speech_response_created_at(fields.remove("createdAt").ok_or(Error)?)?,
data: read_text_to_speech_response_data(fields.remove("data").ok_or(Error)?)?,
error: fields.remove("error").map(read_job_error_response).transpose()?,
estimated_time_at: fields.remove("estimatedTimeAt").map(read_text_to_speech_response_estimated_time_at).transpose()?,
estimated_time_ms: fields.remove("estimatedTimeMs").map(read_text_to_speech_response_estimated_time_ms).transpose()?,
id: read_text_to_speech_response_id(fields.remove("id").ok_or(Error)?)?,
progress: read_text_to_speech_response_progress(fields.remove("progress").ok_or(Error)?)?,
project: fields.remove("project").map(read_text_to_speech_response_project).transpose()?,
status: read_text_to_speech_response_status(fields.remove("status").ok_or(Error)?)?,
team: read_text_to_speech_response_team(fields.remove("team").ok_or(Error)?)?,
type_: read_text_to_speech_response_type(fields.remove("type").ok_or(Error)?)?,
workspace: fields.remove("workspace").map(read_text_to_speech_response_workspace).transpose()?,
extra: fields.into_iter().map(|(key, value)| (key, value.text().to_owned())).collect(),
};

Ok(result)
}
fn write_text_to_speech_response(value: &TextToSpeechResponse, output: &mut String) -> Result<(), Error> {
output.push('{');
if !output.ends_with('{') { output.push(','); } json::quote("callbackUrls", output); output.push(':'); write_text_to_speech_response_callback_urls(&value.callback_urls, output)?;
if !output.ends_with('{') { output.push(','); } json::quote("createdAt", output); output.push(':'); write_text_to_speech_response_created_at(&value.created_at, output)?;
if !output.ends_with('{') { output.push(','); } json::quote("data", output); output.push(':'); write_text_to_speech_response_data(&value.data, output)?;
if let Some(item) = &value.error { if !output.ends_with('{') { output.push(','); } json::quote("error", output); output.push(':'); write_job_error_response(item, output)?; }
if let Some(item) = &value.estimated_time_at { if !output.ends_with('{') { output.push(','); } json::quote("estimatedTimeAt", output); output.push(':'); write_text_to_speech_response_estimated_time_at(item, output)?; }
if let Some(item) = &value.estimated_time_ms { if !output.ends_with('{') { output.push(','); } json::quote("estimatedTimeMs", output); output.push(':'); write_text_to_speech_response_estimated_time_ms(item, output)?; }
if !output.ends_with('{') { output.push(','); } json::quote("id", output); output.push(':'); write_text_to_speech_response_id(&value.id, output)?;
if !output.ends_with('{') { output.push(','); } json::quote("progress", output); output.push(':'); write_text_to_speech_response_progress(&value.progress, output)?;
if let Some(item) = &value.project { if !output.ends_with('{') { output.push(','); } json::quote("project", output); output.push(':'); write_text_to_speech_response_project(item, output)?; }
if !output.ends_with('{') { output.push(','); } json::quote("status", output); output.push(':'); write_text_to_speech_response_status(&value.status, output)?;
if !output.ends_with('{') { output.push(','); } json::quote("team", output); output.push(':'); write_text_to_speech_response_team(&value.team, output)?;
if !output.ends_with('{') { output.push(','); } json::quote("type", output); output.push(':'); write_text_to_speech_response_type(&value.type_, output)?;
if let Some(item) = &value.workspace { if !output.ends_with('{') { output.push(','); } json::quote("workspace", output); output.push(':'); write_text_to_speech_response_workspace(item, output)?; }
for (key, item) in &value.extra {
if matches!(key.as_str(), "callbackUrls" | "createdAt" | "data" | "error" | "estimatedTimeAt" | "estimatedTimeMs" | "id" | "progress" | "project" | "status" | "team" | "type" | "workspace") { return Err(Error); }
Raw::parse_exact(item)?; if !output.ends_with('{') { output.push(','); } json::quote(key, output); output.push(':'); output.push_str(item);
}
output.push('}'); Ok(())
}
pub const CREATE_SPEECH_STATUS: u16 = 201;
pub fn decode_create_speech(text: &str) -> Result<CreateSpeechResponse, TransportError> {
Raw::parse_exact(text).and_then(read_text_to_speech_sync_response).map_err(|_| failure("Invalid LOVO sync-tts response"))
}
pub async fn create_speech(value: &CreateSpeechInput, api_key: &str, base_url: &str, transport: &dyn HttpTransport) -> Result<HttpResponse, TransportError> {
let mut body = String::new();
write_text_to_speech_sync_request(value, &mut body).map_err(|_| failure("Invalid LOVO sync-tts request"))?;
let url = endpoint::append(base_url, &("/api/v1/tts/sync")).ok_or_else(|| failure("Invalid LOVO BaseURL"))?;
transport.send(HttpRequest { method: "POST".into(), url,
headers: vec![("X-API-KEY".into(), api_key.into()), ("content-type".into(), "application/json".into())],
body: body.into_bytes() }).await
}

pub const CREATE_SPEECH_JOB_STATUS: u16 = 201;
pub fn decode_create_speech_job(text: &str) -> Result<CreateSpeechJobResponse, TransportError> {
Raw::parse_exact(text).and_then(read_get_job_response).map_err(|_| failure("Invalid LOVO async-tts response"))
}
pub async fn create_speech_job(value: &CreateSpeechJobInput, api_key: &str, base_url: &str, transport: &dyn HttpTransport) -> Result<HttpResponse, TransportError> {
let mut body = String::new();
write_text_to_speech_request(value, &mut body).map_err(|_| failure("Invalid LOVO async-tts request"))?;
let url = endpoint::append(base_url, &("/api/v1/tts")).ok_or_else(|| failure("Invalid LOVO BaseURL"))?;
transport.send(HttpRequest { method: "POST".into(), url,
headers: vec![("X-API-KEY".into(), api_key.into()), ("content-type".into(), "application/json".into())],
body: body.into_bytes() }).await
}

pub const GET_SPEECH_JOB_STATUS: u16 = 200;
pub fn decode_get_speech_job(text: &str) -> Result<GetSpeechJobResponse, TransportError> {
Raw::parse_exact(text).and_then(read_text_to_speech_response).map_err(|_| failure("Invalid LOVO async-retrieve-job response"))
}
pub async fn get_speech_job(value: &GetSpeechJobInput, api_key: &str, base_url: &str, transport: &dyn HttpTransport) -> Result<HttpResponse, TransportError> {
let mut body = String::new();
write_get_speech_job_input(value, &mut body).map_err(|_| failure("Invalid LOVO async-retrieve-job request"))?;
let url = endpoint::append(base_url, &("/api/v1/tts/{jobId}".replace("{jobId}", &segment(&value.job_id)))).ok_or_else(|| failure("Invalid LOVO BaseURL"))?;
transport.send(HttpRequest { method: "GET".into(), url,
headers: vec![("X-API-KEY".into(), api_key.into())],
body: Vec::new() }).await
}
