// Generated by codegen/generate-clients.ts from https://raw.githubusercontent.com/openai/openai-node/main/api_reference/openapi.transformed.yml. Do not edit.
#![allow(dead_code)]
use crate::{endpoint, http::{HttpRequest, HttpResponse, HttpTransport, TransportError}, json::{self, Error, Raw}};
pub const DEFAULT_BASE_URL: &str = "https://api.openai.com/v1";
pub const SPEECH_STATUS: u16 = 200;
fn failure(message: &str) -> TransportError { std::io::Error::new(std::io::ErrorKind::InvalidData, message).into() }

pub type CreateSpeechRequestInput = String;

pub type CreateSpeechRequestInstructions = String;

pub type CreateSpeechRequestModelVariant0 = String;

pub type CreateSpeechRequestModelVariant1 = String;

#[derive(Debug, Clone, PartialEq)]
pub enum CreateSpeechRequestModel { Variant0(CreateSpeechRequestModelVariant0), Variant1(CreateSpeechRequestModelVariant1), }
impl Default for CreateSpeechRequestModel { fn default() -> Self { Self::Variant0(Default::default()) } }

pub type CreateSpeechRequestResponseFormat = String;

pub type CreateSpeechRequestSpeed = f64;

pub type CreateSpeechRequestStreamFormat = String;

pub type VoiceIdsSharedVariant0 = String;

pub type VoiceIdsSharedVariant1 = String;

#[derive(Debug, Clone, PartialEq)]
pub enum VoiceIdsShared { Variant0(VoiceIdsSharedVariant0), Variant1(VoiceIdsSharedVariant1), }
impl Default for VoiceIdsShared { fn default() -> Self { Self::Variant0(Default::default()) } }

pub type VoiceIdsOrCustomVoiceVariant1Id = String;

#[derive(Debug, Clone, Default, PartialEq)]
pub struct VoiceIdsOrCustomVoiceVariant1 {
pub id: VoiceIdsOrCustomVoiceVariant1Id,

}

#[derive(Debug, Clone, PartialEq)]
pub enum VoiceIdsOrCustomVoice { Variant0(VoiceIdsShared), Variant1(VoiceIdsOrCustomVoiceVariant1), }
impl Default for VoiceIdsOrCustomVoice { fn default() -> Self { Self::Variant0(Default::default()) } }

#[derive(Debug, Clone, Default, PartialEq)]
pub struct CreateSpeechRequest {
pub input: CreateSpeechRequestInput,
pub instructions: Option<CreateSpeechRequestInstructions>,
pub model: CreateSpeechRequestModel,
pub response_format: Option<CreateSpeechRequestResponseFormat>,
pub speed: Option<CreateSpeechRequestSpeed>,
pub stream_format: Option<CreateSpeechRequestStreamFormat>,
pub voice: VoiceIdsOrCustomVoice,

}

pub type SpeechAudioDeltaEventAudio = String;

pub type SpeechAudioDeltaEventType = String;

#[derive(Debug, Clone, Default, PartialEq)]
pub struct SpeechAudioDeltaEvent {
pub audio: SpeechAudioDeltaEventAudio,
pub type_: SpeechAudioDeltaEventType,
/// Additional fields preserve validated raw JSON.
pub extra: std::collections::BTreeMap<String, String>,
}

pub type SpeechAudioDoneEventType = String;

pub type SpeechAudioDoneEventUsageInputTokens = f64;

pub type SpeechAudioDoneEventUsageOutputTokens = f64;

pub type SpeechAudioDoneEventUsageTotalTokens = f64;

#[derive(Debug, Clone, Default, PartialEq)]
pub struct SpeechAudioDoneEventUsage {
pub input_tokens: SpeechAudioDoneEventUsageInputTokens,
pub output_tokens: SpeechAudioDoneEventUsageOutputTokens,
pub total_tokens: SpeechAudioDoneEventUsageTotalTokens,
/// Additional fields preserve validated raw JSON.
pub extra: std::collections::BTreeMap<String, String>,
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct SpeechAudioDoneEvent {
pub type_: SpeechAudioDoneEventType,
pub usage: SpeechAudioDoneEventUsage,
/// Additional fields preserve validated raw JSON.
pub extra: std::collections::BTreeMap<String, String>,
}

#[derive(Debug, Clone, PartialEq)]
pub enum CreateSpeechResponseStreamEvent { Variant0(SpeechAudioDeltaEvent), Variant1(SpeechAudioDoneEvent), }
impl Default for CreateSpeechResponseStreamEvent { fn default() -> Self { Self::Variant0(Default::default()) } }

pub type SpeechRequest = CreateSpeechRequest;

pub type SpeechEvent = CreateSpeechResponseStreamEvent;
fn check_create_speech_request_input(value: &CreateSpeechRequestInput) -> Result<(), Error> { if !(value.chars().count() <= 4096) { return Err(Error); } Ok(()) }

fn read_create_speech_request_input(value: Raw<'_>) -> Result<CreateSpeechRequestInput, Error> {
let result = value.string()?; check_create_speech_request_input(&result)?; Ok(result)
}
fn write_create_speech_request_input(value: &CreateSpeechRequestInput, output: &mut String) -> Result<(), Error> {
check_create_speech_request_input(value)?; json::quote(value, output); Ok(())
}

fn check_create_speech_request_instructions(value: &CreateSpeechRequestInstructions) -> Result<(), Error> { if !(value.chars().count() <= 4096) { return Err(Error); } Ok(()) }

fn read_create_speech_request_instructions(value: Raw<'_>) -> Result<CreateSpeechRequestInstructions, Error> {
let result = value.string()?; check_create_speech_request_instructions(&result)?; Ok(result)
}
fn write_create_speech_request_instructions(value: &CreateSpeechRequestInstructions, output: &mut String) -> Result<(), Error> {
check_create_speech_request_instructions(value)?; json::quote(value, output); Ok(())
}

fn check_create_speech_request_model_variant0(value: &CreateSpeechRequestModelVariant0) -> Result<(), Error> { let _ = value; Ok(()) }

fn read_create_speech_request_model_variant0(value: Raw<'_>) -> Result<CreateSpeechRequestModelVariant0, Error> {
let result = value.string()?; check_create_speech_request_model_variant0(&result)?; Ok(result)
}
fn write_create_speech_request_model_variant0(value: &CreateSpeechRequestModelVariant0, output: &mut String) -> Result<(), Error> {
check_create_speech_request_model_variant0(value)?; json::quote(value, output); Ok(())
}

fn check_create_speech_request_model_variant1(value: &CreateSpeechRequestModelVariant1) -> Result<(), Error> { if !((value == "tts-1" || value == "tts-1-hd" || value == "gpt-4o-mini-tts" || value == "gpt-4o-mini-tts-2025-12-15")) { return Err(Error); } Ok(()) }

fn read_create_speech_request_model_variant1(value: Raw<'_>) -> Result<CreateSpeechRequestModelVariant1, Error> {
let result = value.string()?; check_create_speech_request_model_variant1(&result)?; Ok(result)
}
fn write_create_speech_request_model_variant1(value: &CreateSpeechRequestModelVariant1, output: &mut String) -> Result<(), Error> {
check_create_speech_request_model_variant1(value)?; json::quote(value, output); Ok(())
}

fn read_create_speech_request_model(value: Raw<'_>) -> Result<CreateSpeechRequestModel, Error> {
if let Ok(item) = read_create_speech_request_model_variant0(value) { return Ok(CreateSpeechRequestModel::Variant0(item)); }
if let Ok(item) = read_create_speech_request_model_variant1(value) { return Ok(CreateSpeechRequestModel::Variant1(item)); }
Err(Error)
}
fn write_create_speech_request_model(value: &CreateSpeechRequestModel, output: &mut String) -> Result<(), Error> {
match value { CreateSpeechRequestModel::Variant0(item) => write_create_speech_request_model_variant0(item, output),
CreateSpeechRequestModel::Variant1(item) => write_create_speech_request_model_variant1(item, output), }
}

fn check_create_speech_request_response_format(value: &CreateSpeechRequestResponseFormat) -> Result<(), Error> { if !((value == "mp3" || value == "opus" || value == "aac" || value == "flac" || value == "wav" || value == "pcm")) { return Err(Error); } Ok(()) }

fn read_create_speech_request_response_format(value: Raw<'_>) -> Result<CreateSpeechRequestResponseFormat, Error> {
let result = value.string()?; check_create_speech_request_response_format(&result)?; Ok(result)
}
fn write_create_speech_request_response_format(value: &CreateSpeechRequestResponseFormat, output: &mut String) -> Result<(), Error> {
check_create_speech_request_response_format(value)?; json::quote(value, output); Ok(())
}

fn check_create_speech_request_speed(value: &CreateSpeechRequestSpeed) -> Result<(), Error> { if !(value.is_finite() && *value >= 0.25_f64 && *value <= 4_f64) { return Err(Error); } Ok(()) }

fn read_create_speech_request_speed(value: Raw<'_>) -> Result<CreateSpeechRequestSpeed, Error> {
let result = value.number()?; check_create_speech_request_speed(&result)?; Ok(result)
}
fn write_create_speech_request_speed(value: &CreateSpeechRequestSpeed, output: &mut String) -> Result<(), Error> {
check_create_speech_request_speed(value)?; output.push_str(&value.to_string()); Ok(())
}

fn check_create_speech_request_stream_format(value: &CreateSpeechRequestStreamFormat) -> Result<(), Error> { if !((value == "sse" || value == "audio")) { return Err(Error); } Ok(()) }

fn read_create_speech_request_stream_format(value: Raw<'_>) -> Result<CreateSpeechRequestStreamFormat, Error> {
let result = value.string()?; check_create_speech_request_stream_format(&result)?; Ok(result)
}
fn write_create_speech_request_stream_format(value: &CreateSpeechRequestStreamFormat, output: &mut String) -> Result<(), Error> {
check_create_speech_request_stream_format(value)?; json::quote(value, output); Ok(())
}

fn check_voice_ids_shared_variant0(value: &VoiceIdsSharedVariant0) -> Result<(), Error> { let _ = value; Ok(()) }

fn read_voice_ids_shared_variant0(value: Raw<'_>) -> Result<VoiceIdsSharedVariant0, Error> {
let result = value.string()?; check_voice_ids_shared_variant0(&result)?; Ok(result)
}
fn write_voice_ids_shared_variant0(value: &VoiceIdsSharedVariant0, output: &mut String) -> Result<(), Error> {
check_voice_ids_shared_variant0(value)?; json::quote(value, output); Ok(())
}

fn check_voice_ids_shared_variant1(value: &VoiceIdsSharedVariant1) -> Result<(), Error> { if !((value == "alloy" || value == "ash" || value == "ballad" || value == "coral" || value == "echo" || value == "sage" || value == "shimmer" || value == "verse" || value == "marin" || value == "cedar")) { return Err(Error); } Ok(()) }

fn read_voice_ids_shared_variant1(value: Raw<'_>) -> Result<VoiceIdsSharedVariant1, Error> {
let result = value.string()?; check_voice_ids_shared_variant1(&result)?; Ok(result)
}
fn write_voice_ids_shared_variant1(value: &VoiceIdsSharedVariant1, output: &mut String) -> Result<(), Error> {
check_voice_ids_shared_variant1(value)?; json::quote(value, output); Ok(())
}

fn read_voice_ids_shared(value: Raw<'_>) -> Result<VoiceIdsShared, Error> {
if let Ok(item) = read_voice_ids_shared_variant0(value) { return Ok(VoiceIdsShared::Variant0(item)); }
if let Ok(item) = read_voice_ids_shared_variant1(value) { return Ok(VoiceIdsShared::Variant1(item)); }
Err(Error)
}
fn write_voice_ids_shared(value: &VoiceIdsShared, output: &mut String) -> Result<(), Error> {
match value { VoiceIdsShared::Variant0(item) => write_voice_ids_shared_variant0(item, output),
VoiceIdsShared::Variant1(item) => write_voice_ids_shared_variant1(item, output), }
}

fn check_voice_ids_or_custom_voice_variant1_id(value: &VoiceIdsOrCustomVoiceVariant1Id) -> Result<(), Error> { let _ = value; Ok(()) }

fn read_voice_ids_or_custom_voice_variant1_id(value: Raw<'_>) -> Result<VoiceIdsOrCustomVoiceVariant1Id, Error> {
let result = value.string()?; check_voice_ids_or_custom_voice_variant1_id(&result)?; Ok(result)
}
fn write_voice_ids_or_custom_voice_variant1_id(value: &VoiceIdsOrCustomVoiceVariant1Id, output: &mut String) -> Result<(), Error> {
check_voice_ids_or_custom_voice_variant1_id(value)?; json::quote(value, output); Ok(())
}

fn read_voice_ids_or_custom_voice_variant1(value: Raw<'_>) -> Result<VoiceIdsOrCustomVoiceVariant1, Error> {
let mut fields = value.object()?;
let result = VoiceIdsOrCustomVoiceVariant1 {
id: read_voice_ids_or_custom_voice_variant1_id(fields.remove("id").ok_or(Error)?)?,

};
if !fields.is_empty() { return Err(Error); }
Ok(result)
}
fn write_voice_ids_or_custom_voice_variant1(value: &VoiceIdsOrCustomVoiceVariant1, output: &mut String) -> Result<(), Error> {
output.push('{');
if !output.ends_with('{') { output.push(','); } json::quote("id", output); output.push(':'); write_voice_ids_or_custom_voice_variant1_id(&value.id, output)?;

output.push('}'); Ok(())
}

fn read_voice_ids_or_custom_voice(value: Raw<'_>) -> Result<VoiceIdsOrCustomVoice, Error> {
if let Ok(item) = read_voice_ids_shared(value) { return Ok(VoiceIdsOrCustomVoice::Variant0(item)); }
if let Ok(item) = read_voice_ids_or_custom_voice_variant1(value) { return Ok(VoiceIdsOrCustomVoice::Variant1(item)); }
Err(Error)
}
fn write_voice_ids_or_custom_voice(value: &VoiceIdsOrCustomVoice, output: &mut String) -> Result<(), Error> {
match value { VoiceIdsOrCustomVoice::Variant0(item) => write_voice_ids_shared(item, output),
VoiceIdsOrCustomVoice::Variant1(item) => write_voice_ids_or_custom_voice_variant1(item, output), }
}

fn read_create_speech_request(value: Raw<'_>) -> Result<CreateSpeechRequest, Error> {
let mut fields = value.object()?;
let result = CreateSpeechRequest {
input: read_create_speech_request_input(fields.remove("input").ok_or(Error)?)?,
instructions: fields.remove("instructions").map(read_create_speech_request_instructions).transpose()?,
model: read_create_speech_request_model(fields.remove("model").ok_or(Error)?)?,
response_format: fields.remove("response_format").map(read_create_speech_request_response_format).transpose()?,
speed: fields.remove("speed").map(read_create_speech_request_speed).transpose()?,
stream_format: fields.remove("stream_format").map(read_create_speech_request_stream_format).transpose()?,
voice: read_voice_ids_or_custom_voice(fields.remove("voice").ok_or(Error)?)?,

};
if !fields.is_empty() { return Err(Error); }
Ok(result)
}
fn write_create_speech_request(value: &CreateSpeechRequest, output: &mut String) -> Result<(), Error> {
output.push('{');
if !output.ends_with('{') { output.push(','); } json::quote("input", output); output.push(':'); write_create_speech_request_input(&value.input, output)?;
if let Some(item) = &value.instructions { if !output.ends_with('{') { output.push(','); } json::quote("instructions", output); output.push(':'); write_create_speech_request_instructions(item, output)?; }
if !output.ends_with('{') { output.push(','); } json::quote("model", output); output.push(':'); write_create_speech_request_model(&value.model, output)?;
if let Some(item) = &value.response_format { if !output.ends_with('{') { output.push(','); } json::quote("response_format", output); output.push(':'); write_create_speech_request_response_format(item, output)?; }
if let Some(item) = &value.speed { if !output.ends_with('{') { output.push(','); } json::quote("speed", output); output.push(':'); write_create_speech_request_speed(item, output)?; }
if let Some(item) = &value.stream_format { if !output.ends_with('{') { output.push(','); } json::quote("stream_format", output); output.push(':'); write_create_speech_request_stream_format(item, output)?; }
if !output.ends_with('{') { output.push(','); } json::quote("voice", output); output.push(':'); write_voice_ids_or_custom_voice(&value.voice, output)?;

output.push('}'); Ok(())
}

fn check_speech_audio_delta_event_audio(value: &SpeechAudioDeltaEventAudio) -> Result<(), Error> { let _ = value; Ok(()) }

fn read_speech_audio_delta_event_audio(value: Raw<'_>) -> Result<SpeechAudioDeltaEventAudio, Error> {
let result = value.string()?; check_speech_audio_delta_event_audio(&result)?; Ok(result)
}
fn write_speech_audio_delta_event_audio(value: &SpeechAudioDeltaEventAudio, output: &mut String) -> Result<(), Error> {
check_speech_audio_delta_event_audio(value)?; json::quote(value, output); Ok(())
}

fn check_speech_audio_delta_event_type(value: &SpeechAudioDeltaEventType) -> Result<(), Error> { if !((value == "speech.audio.delta")) { return Err(Error); } Ok(()) }

fn read_speech_audio_delta_event_type(value: Raw<'_>) -> Result<SpeechAudioDeltaEventType, Error> {
let result = value.string()?; check_speech_audio_delta_event_type(&result)?; Ok(result)
}
fn write_speech_audio_delta_event_type(value: &SpeechAudioDeltaEventType, output: &mut String) -> Result<(), Error> {
check_speech_audio_delta_event_type(value)?; json::quote(value, output); Ok(())
}

fn read_speech_audio_delta_event(value: Raw<'_>) -> Result<SpeechAudioDeltaEvent, Error> {
let mut fields = value.object()?;
let result = SpeechAudioDeltaEvent {
audio: read_speech_audio_delta_event_audio(fields.remove("audio").ok_or(Error)?)?,
type_: read_speech_audio_delta_event_type(fields.remove("type").ok_or(Error)?)?,
extra: fields.into_iter().map(|(key, value)| (key, value.text().to_owned())).collect(),
};

Ok(result)
}
fn write_speech_audio_delta_event(value: &SpeechAudioDeltaEvent, output: &mut String) -> Result<(), Error> {
output.push('{');
if !output.ends_with('{') { output.push(','); } json::quote("audio", output); output.push(':'); write_speech_audio_delta_event_audio(&value.audio, output)?;
if !output.ends_with('{') { output.push(','); } json::quote("type", output); output.push(':'); write_speech_audio_delta_event_type(&value.type_, output)?;
for (key, item) in &value.extra {
if matches!(key.as_str(), "audio" | "type") { return Err(Error); }
Raw::parse_exact(item)?; if !output.ends_with('{') { output.push(','); } json::quote(key, output); output.push(':'); output.push_str(item);
}
output.push('}'); Ok(())
}

fn check_speech_audio_done_event_type(value: &SpeechAudioDoneEventType) -> Result<(), Error> { if !((value == "speech.audio.done")) { return Err(Error); } Ok(()) }

fn read_speech_audio_done_event_type(value: Raw<'_>) -> Result<SpeechAudioDoneEventType, Error> {
let result = value.string()?; check_speech_audio_done_event_type(&result)?; Ok(result)
}
fn write_speech_audio_done_event_type(value: &SpeechAudioDoneEventType, output: &mut String) -> Result<(), Error> {
check_speech_audio_done_event_type(value)?; json::quote(value, output); Ok(())
}

fn check_speech_audio_done_event_usage_input_tokens(value: &SpeechAudioDoneEventUsageInputTokens) -> Result<(), Error> { if !(value.is_finite() && value.fract() == 0.0 && value.abs() <= 9007199254740991_f64) { return Err(Error); } Ok(()) }

fn read_speech_audio_done_event_usage_input_tokens(value: Raw<'_>) -> Result<SpeechAudioDoneEventUsageInputTokens, Error> {
let result = value.number()?; check_speech_audio_done_event_usage_input_tokens(&result)?; Ok(result)
}
fn write_speech_audio_done_event_usage_input_tokens(value: &SpeechAudioDoneEventUsageInputTokens, output: &mut String) -> Result<(), Error> {
check_speech_audio_done_event_usage_input_tokens(value)?; output.push_str(&value.to_string()); Ok(())
}

fn check_speech_audio_done_event_usage_output_tokens(value: &SpeechAudioDoneEventUsageOutputTokens) -> Result<(), Error> { if !(value.is_finite() && value.fract() == 0.0 && value.abs() <= 9007199254740991_f64) { return Err(Error); } Ok(()) }

fn read_speech_audio_done_event_usage_output_tokens(value: Raw<'_>) -> Result<SpeechAudioDoneEventUsageOutputTokens, Error> {
let result = value.number()?; check_speech_audio_done_event_usage_output_tokens(&result)?; Ok(result)
}
fn write_speech_audio_done_event_usage_output_tokens(value: &SpeechAudioDoneEventUsageOutputTokens, output: &mut String) -> Result<(), Error> {
check_speech_audio_done_event_usage_output_tokens(value)?; output.push_str(&value.to_string()); Ok(())
}

fn check_speech_audio_done_event_usage_total_tokens(value: &SpeechAudioDoneEventUsageTotalTokens) -> Result<(), Error> { if !(value.is_finite() && value.fract() == 0.0 && value.abs() <= 9007199254740991_f64) { return Err(Error); } Ok(()) }

fn read_speech_audio_done_event_usage_total_tokens(value: Raw<'_>) -> Result<SpeechAudioDoneEventUsageTotalTokens, Error> {
let result = value.number()?; check_speech_audio_done_event_usage_total_tokens(&result)?; Ok(result)
}
fn write_speech_audio_done_event_usage_total_tokens(value: &SpeechAudioDoneEventUsageTotalTokens, output: &mut String) -> Result<(), Error> {
check_speech_audio_done_event_usage_total_tokens(value)?; output.push_str(&value.to_string()); Ok(())
}

fn read_speech_audio_done_event_usage(value: Raw<'_>) -> Result<SpeechAudioDoneEventUsage, Error> {
let mut fields = value.object()?;
let result = SpeechAudioDoneEventUsage {
input_tokens: read_speech_audio_done_event_usage_input_tokens(fields.remove("input_tokens").ok_or(Error)?)?,
output_tokens: read_speech_audio_done_event_usage_output_tokens(fields.remove("output_tokens").ok_or(Error)?)?,
total_tokens: read_speech_audio_done_event_usage_total_tokens(fields.remove("total_tokens").ok_or(Error)?)?,
extra: fields.into_iter().map(|(key, value)| (key, value.text().to_owned())).collect(),
};

Ok(result)
}
fn write_speech_audio_done_event_usage(value: &SpeechAudioDoneEventUsage, output: &mut String) -> Result<(), Error> {
output.push('{');
if !output.ends_with('{') { output.push(','); } json::quote("input_tokens", output); output.push(':'); write_speech_audio_done_event_usage_input_tokens(&value.input_tokens, output)?;
if !output.ends_with('{') { output.push(','); } json::quote("output_tokens", output); output.push(':'); write_speech_audio_done_event_usage_output_tokens(&value.output_tokens, output)?;
if !output.ends_with('{') { output.push(','); } json::quote("total_tokens", output); output.push(':'); write_speech_audio_done_event_usage_total_tokens(&value.total_tokens, output)?;
for (key, item) in &value.extra {
if matches!(key.as_str(), "input_tokens" | "output_tokens" | "total_tokens") { return Err(Error); }
Raw::parse_exact(item)?; if !output.ends_with('{') { output.push(','); } json::quote(key, output); output.push(':'); output.push_str(item);
}
output.push('}'); Ok(())
}

fn read_speech_audio_done_event(value: Raw<'_>) -> Result<SpeechAudioDoneEvent, Error> {
let mut fields = value.object()?;
let result = SpeechAudioDoneEvent {
type_: read_speech_audio_done_event_type(fields.remove("type").ok_or(Error)?)?,
usage: read_speech_audio_done_event_usage(fields.remove("usage").ok_or(Error)?)?,
extra: fields.into_iter().map(|(key, value)| (key, value.text().to_owned())).collect(),
};

Ok(result)
}
fn write_speech_audio_done_event(value: &SpeechAudioDoneEvent, output: &mut String) -> Result<(), Error> {
output.push('{');
if !output.ends_with('{') { output.push(','); } json::quote("type", output); output.push(':'); write_speech_audio_done_event_type(&value.type_, output)?;
if !output.ends_with('{') { output.push(','); } json::quote("usage", output); output.push(':'); write_speech_audio_done_event_usage(&value.usage, output)?;
for (key, item) in &value.extra {
if matches!(key.as_str(), "type" | "usage") { return Err(Error); }
Raw::parse_exact(item)?; if !output.ends_with('{') { output.push(','); } json::quote(key, output); output.push(':'); output.push_str(item);
}
output.push('}'); Ok(())
}

fn read_create_speech_response_stream_event(value: Raw<'_>) -> Result<CreateSpeechResponseStreamEvent, Error> {
if let Ok(item) = read_speech_audio_delta_event(value) { return Ok(CreateSpeechResponseStreamEvent::Variant0(item)); }
if let Ok(item) = read_speech_audio_done_event(value) { return Ok(CreateSpeechResponseStreamEvent::Variant1(item)); }
Err(Error)
}
fn write_create_speech_response_stream_event(value: &CreateSpeechResponseStreamEvent, output: &mut String) -> Result<(), Error> {
match value { CreateSpeechResponseStreamEvent::Variant0(item) => write_speech_audio_delta_event(item, output),
CreateSpeechResponseStreamEvent::Variant1(item) => write_speech_audio_done_event(item, output), }
}

pub fn decode_speech_event(text: &str) -> Result<SpeechEvent, TransportError> {
Raw::parse_exact(text).and_then(read_create_speech_response_stream_event).map_err(|_| failure("Invalid OpenAI speech event"))
}
pub async fn create_speech(value: &SpeechRequest, api_key: &str, base_url: &str, transport: &dyn HttpTransport) -> Result<HttpResponse, TransportError> {
let mut body = String::new();
write_create_speech_request(value, &mut body).map_err(|_| failure("Invalid OpenAI speech wire request"))?;
let url = endpoint::append(base_url, "/audio/speech").ok_or_else(|| failure("Invalid OpenAI base_url"))?;
transport.send(HttpRequest { method: "POST".into(), url,
headers: vec![("Authorization".into(), format!("Bearer {api_key}")), ("Content-Type".into(), "application/json".into()), ("Accept".into(), "application/octet-stream, text/event-stream".into())], body: body.into_bytes() }).await
}
