import { describe, expect, expectTypeOf, test } from "bun:test";
import type { TtsRequest } from "../schemas/base.ts";
import { textChunks } from "./text.ts";

describe("normalized requests", () => {
  test("uses a plain request type", () => {
    expectTypeOf<TtsRequest>().toEqualTypeOf<{
      readonly text?: string | AsyncIterable<string | { readonly command: "clear" } | { readonly command: "flush" } | {
        readonly command: "update";
        readonly replacements?: readonly { readonly pattern: string; readonly replacement: string }[];
        readonly voiceGuidance?: number;
        readonly temperature?: number;
        readonly maxAudioTokens?: number;
        readonly language?: string;
        readonly textNormalization?: boolean;
        readonly speed?: number;
      }>;
      readonly voice?: string | number;
      readonly voiceBlend?: readonly { readonly voice: string; readonly weight: number }[];
      readonly voiceName?: string;
      readonly voiceStyle?: string;
      readonly voiceSource?: "catalog" | "custom";
      readonly voiceDescription?: string;
      readonly referenceAudio?: Uint8Array;
      readonly referenceSamples?: readonly { readonly audio: Uint8Array; readonly text: string }[];
      readonly speakers?: readonly { readonly alias?: string; readonly voice?: string; readonly voiceName?: string; readonly voiceSource?: "catalog" | "custom"; readonly referenceSamples?: readonly { readonly audio: Uint8Array; readonly text: string }[] }[];
      readonly turns?: readonly { readonly speaker: string; readonly text: string; readonly instructions?: string; readonly speed?: number; readonly trailingSilenceMs?: number }[] | AsyncIterable<{ readonly speaker: string; readonly text: string; readonly instructions?: string; readonly speed?: number; readonly trailingSilenceMs?: number } | { readonly command: "flush" }>;
      readonly instructions?: string;
      readonly safetySettings?: readonly { readonly category: "hate_speech" | "dangerous_content" | "harassment" | "sexually_explicit"; readonly threshold: "low" | "medium" | "high" | "none" | "off" }[];
      readonly deliveryReference?: string;
      readonly inputType?: "text" | "ssml" | "markup";
      readonly model?: string;
      readonly modelImprovementOptOut?: boolean;
      readonly tags?: readonly string[];
      readonly language?: string;
      readonly lexicon?: string | readonly string[];
      readonly output?: {
        readonly format: "mp3" | "ogg_vorbis" | "wav" | "pcm" | "ogg_opus" | "alaw" | "mulaw" | "flac" | "aac" | "opus" | "webm_opus" | "truesilk" | "amr_wb" | "g722";
        readonly sampleRateHz?: number;
        readonly bitRateBps?: number;
        readonly channelCount?: number;
        readonly constantBitRate?: boolean;
        readonly sampleEncoding?: "signed_integer_16" | "signed_integer_32" | "float_32" | "mulaw" | "alaw";
        readonly byteOrder?: "little_endian" | "big_endian";
      };
      readonly speed?: number;
      readonly trailingSilenceMs?: number;
      readonly splitTurns?: boolean;
      readonly pacingBias?: number;
      readonly voiceGuidance?: number;
      readonly targetDurationMs?: number;
      readonly deliveryVariance?: number;
      readonly temperature?: number;
      readonly deliveryMode?: "stable" | "balanced" | "creative";
      readonly topP?: number;
      readonly topK?: number;
      readonly volumeDb?: number;
      readonly pitchSemitones?: number;
      readonly pitchBias?: number;
      readonly formulaReading?: "latex";
      readonly voiceTransform?: {
        readonly brightness?: number;
        readonly softness?: number;
        readonly crispness?: number;
        readonly effect?: "spacious_echo" | "auditorium_echo" | "telephone" | "robotic";
      };
      readonly effectsProfiles?: readonly string[];
      readonly loudnessNormalization?: boolean;
      readonly maxAudioTokens?: number;
      readonly repetitionPenalty?: number;
      readonly textChunkLength?: number;
      readonly minTextChunkLength?: number;
      readonly conditionOnPreviousChunks?: boolean;
      readonly earlyStopThreshold?: number;
      readonly features?: readonly string[];
      readonly randomSeed?: number;
      readonly voiceBoost?: boolean;
      readonly voiceSimilarity?: number;
      readonly styleExaggeration?: number;
      readonly pronunciationDictionaries?: readonly { readonly id: string; readonly versionId?: string }[];
      readonly pronunciationDictionarySelection?: { readonly scope: string | number; readonly ids?: readonly (string | number)[] };
      readonly contextBefore?: { readonly text?: string; readonly texts?: readonly string[]; readonly requestIds?: readonly string[]; readonly turns?: readonly { readonly speaker: string; readonly text: string; readonly instructions?: string; readonly speed?: number; readonly trailingSilenceMs?: number }[] };
      readonly contextAfter?: { readonly text?: string; readonly requestIds?: readonly string[] };
      readonly languageTextNormalization?: boolean;
      readonly textBuffering?: boolean;
      readonly textBufferThresholds?: readonly number[];
      readonly textBufferThreshold?: number;
      readonly automaticTextFlushing?: boolean;
      readonly durationStretching?: boolean;
      readonly processingPriority?: "standard" | "realtime";
      readonly automaticGainControl?: boolean;
      readonly speakerGender?: "male" | "female";
      readonly accentBlend?: { readonly baseLocale: string; readonly targetLocale: string; readonly ratio: number };
      readonly timestampGranularity?: "character" | "word" | "phoneme" | "segment" | "sentence" | "viseme" | "ssml" | readonly ("word" | "phoneme" | "sentence" | "viseme" | "ssml")[];
      readonly timestampDelivery?: "chunk" | "trailing";
      readonly stability?: number;
      readonly volumeScale?: number;
      readonly emotion?: string;
      readonly accent?: string;
      readonly maxBufferDelayMs?: number;
      readonly timestampText?: "original" | "normalized";
      readonly audioEnhancement?: boolean;
      readonly namedEntityPronunciationEnhancement?: boolean;
      readonly referenceAudioEnhancement?: boolean;
      readonly accentPreservation?: boolean;
      readonly textFlushDelayMs?: number;
      readonly inferenceSteps?: number;
      readonly segmentation?: "sentence" | "immediate";
      readonly textNormalization?: boolean | "auto" | { readonly locale?: string; readonly rules?: readonly string[] };
      readonly replacements?: readonly {
        readonly pattern: string;
        readonly replacement: string;
        readonly alphabet?: "ipa" | "x_sampa" | "japanese_yomigana" | "pinyin";
      }[];
      readonly latencyOptimization?: "none" | "moderate" | "strong" | "aggressive" | "maximum";
    }>();
  });

  test("iterates static and streaming input consistently", async () => {
    const streamed = async function* () {
      yield "one";
      yield "two";
    };
    expect(await Array.fromAsync(textChunks("one"))).toEqual(["one"]);
    expect(await Array.fromAsync(textChunks(streamed()))).toEqual(["one", "two"]);
  });
});
