use super::{
    format::{Audio, IntoAudio},
    Input,
};
use crate::{
    generated::minimax::*,
    runtime::{JsonValue, StreamingInput, ValidationError},
};
use std::{any::Any, collections::BTreeMap};
pub(super) type Map = BTreeMap<String, JsonValue>;
pub(super) type Validator =
    Box<dyn Fn(&dyn Any, Option<&str>) -> Result<(), ValidationError> + Send>;
pub(super) struct Settings {
    pub wire: Map,
    pub text: Option<String>,
    pub input: Option<StreamingInput<Input>>,
    pub streaming: bool,
    pub timing: Option<&'static str>,
}
struct Parts {
    model: &'static str,
    voice: String,
    blend: Option<Vec<TtsRequestText77d171beVoiceBlendItem>>,
    text: Option<String>,
    input: Option<StreamingInput<Input>>,
    language: &'static str,
    emotion: Option<&'static str>,
    formula: bool,
    normalize: bool,
    split: bool,
    output: Audio,
    speed: f64,
    volume: f64,
    pitch: f64,
    replacements: Option<Vec<TtsRequestText77d171beReplacementsItem>>,
    transform: Option<TtsRequestText77d171beVoiceTransform>,
    timing: Option<&'static str>,
}
pub(super) fn settings(request: TtsRequest) -> Settings {
    // Consume concrete generated variants after schema validation, without rechecking their constraints.
    let p = match request {
        TtsRequest::Text77d171be(v) => Parts {
            model: v.model.value(),
            voice: String::new(),
            blend: Some(v.voice_blend),
            text: Some(v.text),
            input: None,
            language: v.language.map(|v| v.value()).unwrap_or("auto"),
            emotion: v.emotion.map(|v| v.value()),
            formula: false,
            normalize: v.text_normalization.is_some_and(|v| v.value()),
            split: true,
            output: v.output.map(|v| v.into_audio()).unwrap_or_default(),
            speed: v.speed.unwrap_or(1.0),
            volume: v.volume_scale.unwrap_or(1.0),
            pitch: v.pitch_bias.unwrap_or(0.0),
            replacements: v.replacements,
            transform: Some(v.voice_transform),
            timing: v.timestamp_granularity.map(|v| v.value()),
        },
        TtsRequest::Text8a99d813(v) => Parts {
            model: v.model.value(),
            voice: String::new(),
            blend: Some(v.voice_blend),
            text: Some(v.text),
            input: None,
            language: v.language.map(|v| v.value()).unwrap_or("zh"),
            emotion: v.emotion.map(|v| v.value()),
            formula: true,
            normalize: v.text_normalization.is_some_and(|v| v.value()),
            split: true,
            output: v.output.map(|v| v.into_audio()).unwrap_or_default(),
            speed: v.speed.unwrap_or(1.0),
            volume: v.volume_scale.unwrap_or(1.0),
            pitch: v.pitch_bias.unwrap_or(0.0),
            replacements: v.replacements,
            transform: Some(v.voice_transform),
            timing: v.timestamp_granularity.map(|v| v.value()),
        },
        TtsRequest::Textf2dcc77e(v) => Parts {
            model: v.model.value(),
            voice: String::new(),
            blend: Some(v.voice_blend),
            text: Some(v.text),
            input: None,
            language: v.language.map(|v| v.value()).unwrap_or("zh"),
            emotion: v.emotion.map(|v| v.value()),
            formula: true,
            normalize: v.text_normalization.is_some_and(|v| v.value()),
            split: true,
            output: v.output.map(|v| v.into_audio()).unwrap_or_default(),
            speed: v.speed.unwrap_or(1.0),
            volume: v.volume_scale.unwrap_or(1.0),
            pitch: v.pitch_bias.unwrap_or(0.0),
            replacements: v.replacements,
            transform: None,
            timing: v.timestamp_granularity.map(|v| v.value()),
        },
        TtsRequest::Textbc3e8901(v) => Parts {
            model: v.model.value(),
            voice: String::new(),
            blend: Some(v.voice_blend),
            text: Some(v.text),
            input: None,
            language: v.language.map(|v| v.value()).unwrap_or("auto"),
            emotion: v.emotion.map(|v| v.value()),
            formula: false,
            normalize: v.text_normalization.is_some_and(|v| v.value()),
            split: true,
            output: v.output.map(|v| v.into_audio()).unwrap_or_default(),
            speed: v.speed.unwrap_or(1.0),
            volume: v.volume_scale.unwrap_or(1.0),
            pitch: v.pitch_bias.unwrap_or(0.0),
            replacements: v.replacements,
            transform: None,
            timing: v.timestamp_granularity.map(|v| v.value()),
        },
        TtsRequest::TextVoice9d11e112(v) => Parts {
            model: v.model.value(),
            voice: v.voice,
            blend: None,
            text: Some(v.text),
            input: None,
            language: v.language.map(|v| v.value()).unwrap_or("auto"),
            emotion: v.emotion.map(|v| v.value()),
            formula: false,
            normalize: v.text_normalization.is_some_and(|v| v.value()),
            split: true,
            output: v.output.map(|v| v.into_audio()).unwrap_or_default(),
            speed: v.speed.unwrap_or(1.0),
            volume: v.volume_scale.unwrap_or(1.0),
            pitch: v.pitch_bias.unwrap_or(0.0),
            replacements: v.replacements,
            transform: Some(v.voice_transform),
            timing: v.timestamp_granularity.map(|v| v.value()),
        },
        TtsRequest::TextVoicec9541dfe(v) => Parts {
            model: v.model.value(),
            voice: v.voice,
            blend: None,
            text: Some(v.text),
            input: None,
            language: v.language.map(|v| v.value()).unwrap_or("zh"),
            emotion: v.emotion.map(|v| v.value()),
            formula: true,
            normalize: v.text_normalization.is_some_and(|v| v.value()),
            split: true,
            output: v.output.map(|v| v.into_audio()).unwrap_or_default(),
            speed: v.speed.unwrap_or(1.0),
            volume: v.volume_scale.unwrap_or(1.0),
            pitch: v.pitch_bias.unwrap_or(0.0),
            replacements: v.replacements,
            transform: Some(v.voice_transform),
            timing: v.timestamp_granularity.map(|v| v.value()),
        },
        TtsRequest::TextVoice579df7d3(v) => Parts {
            model: v.model.value(),
            voice: v.voice,
            blend: None,
            text: Some(v.text),
            input: None,
            language: v.language.map(|v| v.value()).unwrap_or("zh"),
            emotion: v.emotion.map(|v| v.value()),
            formula: true,
            normalize: v.text_normalization.is_some_and(|v| v.value()),
            split: true,
            output: v.output.map(|v| v.into_audio()).unwrap_or_default(),
            speed: v.speed.unwrap_or(1.0),
            volume: v.volume_scale.unwrap_or(1.0),
            pitch: v.pitch_bias.unwrap_or(0.0),
            replacements: v.replacements,
            transform: None,
            timing: v.timestamp_granularity.map(|v| v.value()),
        },
        TtsRequest::TextVoiceab653629(v) => Parts {
            model: v.model.value(),
            voice: v.voice,
            blend: None,
            text: Some(v.text),
            input: None,
            language: v.language.map(|v| v.value()).unwrap_or("auto"),
            emotion: v.emotion.map(|v| v.value()),
            formula: false,
            normalize: v.text_normalization.is_some_and(|v| v.value()),
            split: true,
            output: v.output.map(|v| v.into_audio()).unwrap_or_default(),
            speed: v.speed.unwrap_or(1.0),
            volume: v.volume_scale.unwrap_or(1.0),
            pitch: v.pitch_bias.unwrap_or(0.0),
            replacements: v.replacements,
            transform: None,
            timing: v.timestamp_granularity.map(|v| v.value()),
        },
        TtsRequest::StreamingText12421ea0(v) => Parts {
            model: v.model.value(),
            voice: String::new(),
            blend: Some(v.voice_blend),
            text: None,
            input: Some(v.text),
            language: v.language.map(|v| v.value()).unwrap_or("auto"),
            emotion: v.emotion.map(|v| v.value()),
            formula: false,
            normalize: v.language_text_normalization.is_some_and(|v| v.value()),
            split: true,
            output: v.output.map(|v| v.into_audio()).unwrap_or_default(),
            speed: v.speed.unwrap_or(1.0),
            volume: v.volume_scale.unwrap_or(1.0),
            pitch: v.pitch_bias.unwrap_or(0.0),
            replacements: v.replacements,
            transform: Some(v.voice_transform),
            timing: None,
        },
        TtsRequest::StreamingText3a58293c(v) => Parts {
            model: v.model.value(),
            voice: String::new(),
            blend: Some(v.voice_blend),
            text: None,
            input: Some(v.text),
            language: v.language.map(|v| v.value()).unwrap_or("zh"),
            emotion: v.emotion.map(|v| v.value()),
            formula: true,
            normalize: v.language_text_normalization.is_some_and(|v| v.value()),
            split: true,
            output: v.output.map(|v| v.into_audio()).unwrap_or_default(),
            speed: v.speed.unwrap_or(1.0),
            volume: v.volume_scale.unwrap_or(1.0),
            pitch: v.pitch_bias.unwrap_or(0.0),
            replacements: v.replacements,
            transform: Some(v.voice_transform),
            timing: None,
        },
        TtsRequest::StreamingTextaa771f19(v) => Parts {
            model: v.model.value(),
            voice: String::new(),
            blend: Some(v.voice_blend),
            text: None,
            input: Some(v.text),
            language: v.language.map(|v| v.value()).unwrap_or("zh"),
            emotion: v.emotion.map(|v| v.value()),
            formula: true,
            normalize: v.language_text_normalization.is_some_and(|v| v.value()),
            split: true,
            output: v.output.map(|v| v.into_audio()).unwrap_or_default(),
            speed: v.speed.unwrap_or(1.0),
            volume: v.volume_scale.unwrap_or(1.0),
            pitch: v.pitch_bias.unwrap_or(0.0),
            replacements: v.replacements,
            transform: None,
            timing: None,
        },
        TtsRequest::StreamingText62be105a(v) => Parts {
            model: v.model.value(),
            voice: String::new(),
            blend: Some(v.voice_blend),
            text: None,
            input: Some(v.text),
            language: v.language.map(|v| v.value()).unwrap_or("auto"),
            emotion: v.emotion.map(|v| v.value()),
            formula: false,
            normalize: v.language_text_normalization.is_some_and(|v| v.value()),
            split: true,
            output: v.output.map(|v| v.into_audio()).unwrap_or_default(),
            speed: v.speed.unwrap_or(1.0),
            volume: v.volume_scale.unwrap_or(1.0),
            pitch: v.pitch_bias.unwrap_or(0.0),
            replacements: v.replacements,
            transform: None,
            timing: None,
        },
        TtsRequest::StreamingTextVoice6d21fc54(v) => Parts {
            model: v.model.value(),
            voice: v.voice,
            blend: None,
            text: None,
            input: Some(v.text),
            language: v.language.map(|v| v.value()).unwrap_or("auto"),
            emotion: v.emotion.map(|v| v.value()),
            formula: false,
            normalize: v.language_text_normalization.is_some_and(|v| v.value()),
            split: true,
            output: v.output.map(|v| v.into_audio()).unwrap_or_default(),
            speed: v.speed.unwrap_or(1.0),
            volume: v.volume_scale.unwrap_or(1.0),
            pitch: v.pitch_bias.unwrap_or(0.0),
            replacements: v.replacements,
            transform: Some(v.voice_transform),
            timing: None,
        },
        TtsRequest::StreamingTextVoice80c0de17(v) => Parts {
            model: v.model.value(),
            voice: v.voice,
            blend: None,
            text: None,
            input: Some(v.text),
            language: v.language.map(|v| v.value()).unwrap_or("zh"),
            emotion: v.emotion.map(|v| v.value()),
            formula: true,
            normalize: v.language_text_normalization.is_some_and(|v| v.value()),
            split: true,
            output: v.output.map(|v| v.into_audio()).unwrap_or_default(),
            speed: v.speed.unwrap_or(1.0),
            volume: v.volume_scale.unwrap_or(1.0),
            pitch: v.pitch_bias.unwrap_or(0.0),
            replacements: v.replacements,
            transform: Some(v.voice_transform),
            timing: None,
        },
        TtsRequest::StreamingTextVoiceb9340145(v) => Parts {
            model: v.model.value(),
            voice: v.voice,
            blend: None,
            text: None,
            input: Some(v.text),
            language: v.language.map(|v| v.value()).unwrap_or("zh"),
            emotion: v.emotion.map(|v| v.value()),
            formula: true,
            normalize: v.language_text_normalization.is_some_and(|v| v.value()),
            split: true,
            output: v.output.map(|v| v.into_audio()).unwrap_or_default(),
            speed: v.speed.unwrap_or(1.0),
            volume: v.volume_scale.unwrap_or(1.0),
            pitch: v.pitch_bias.unwrap_or(0.0),
            replacements: v.replacements,
            transform: None,
            timing: None,
        },
        TtsRequest::StreamingTextVoice40504229(v) => Parts {
            model: v.model.value(),
            voice: v.voice,
            blend: None,
            text: None,
            input: Some(v.text),
            language: v.language.map(|v| v.value()).unwrap_or("auto"),
            emotion: v.emotion.map(|v| v.value()),
            formula: false,
            normalize: v.language_text_normalization.is_some_and(|v| v.value()),
            split: true,
            output: v.output.map(|v| v.into_audio()).unwrap_or_default(),
            speed: v.speed.unwrap_or(1.0),
            volume: v.volume_scale.unwrap_or(1.0),
            pitch: v.pitch_bias.unwrap_or(0.0),
            replacements: v.replacements,
            transform: None,
            timing: None,
        },
        TtsRequest::Texte253c939(v) => Parts {
            model: v.model.value(),
            voice: String::new(),
            blend: Some(v.voice_blend),
            text: Some(v.text),
            input: None,
            language: v.language.map(|v| v.value()).unwrap_or("auto"),
            emotion: v.emotion.map(|v| v.value()),
            formula: false,
            normalize: v.text_normalization.is_some_and(|v| v.value()),
            split: true,
            output: v.output.map(|v| v.into_audio()).unwrap_or_default(),
            speed: v.speed.unwrap_or(1.0),
            volume: v.volume_scale.unwrap_or(1.0),
            pitch: v.pitch_bias.unwrap_or(0.0),
            replacements: v.replacements,
            transform: Some(v.voice_transform),
            timing: v.timestamp_granularity.map(|v| v.value()),
        },
        TtsRequest::Text75fe6b00(v) => Parts {
            model: v.model.value(),
            voice: String::new(),
            blend: Some(v.voice_blend),
            text: Some(v.text),
            input: None,
            language: v.language.map(|v| v.value()).unwrap_or("zh"),
            emotion: v.emotion.map(|v| v.value()),
            formula: true,
            normalize: v.text_normalization.is_some_and(|v| v.value()),
            split: true,
            output: v.output.map(|v| v.into_audio()).unwrap_or_default(),
            speed: v.speed.unwrap_or(1.0),
            volume: v.volume_scale.unwrap_or(1.0),
            pitch: v.pitch_bias.unwrap_or(0.0),
            replacements: v.replacements,
            transform: Some(v.voice_transform),
            timing: v.timestamp_granularity.map(|v| v.value()),
        },
        TtsRequest::Text1ddad1c5(v) => Parts {
            model: v.model.value(),
            voice: String::new(),
            blend: Some(v.voice_blend),
            text: Some(v.text),
            input: None,
            language: v.language.map(|v| v.value()).unwrap_or("zh"),
            emotion: v.emotion.map(|v| v.value()),
            formula: true,
            normalize: v.text_normalization.is_some_and(|v| v.value()),
            split: true,
            output: v.output.map(|v| v.into_audio()).unwrap_or_default(),
            speed: v.speed.unwrap_or(1.0),
            volume: v.volume_scale.unwrap_or(1.0),
            pitch: v.pitch_bias.unwrap_or(0.0),
            replacements: v.replacements,
            transform: None,
            timing: v.timestamp_granularity.map(|v| v.value()),
        },
        TtsRequest::Text7c0eb1eb(v) => Parts {
            model: v.model.value(),
            voice: String::new(),
            blend: Some(v.voice_blend),
            text: Some(v.text),
            input: None,
            language: v.language.map(|v| v.value()).unwrap_or("auto"),
            emotion: v.emotion.map(|v| v.value()),
            formula: false,
            normalize: v.text_normalization.is_some_and(|v| v.value()),
            split: true,
            output: v.output.map(|v| v.into_audio()).unwrap_or_default(),
            speed: v.speed.unwrap_or(1.0),
            volume: v.volume_scale.unwrap_or(1.0),
            pitch: v.pitch_bias.unwrap_or(0.0),
            replacements: v.replacements,
            transform: None,
            timing: v.timestamp_granularity.map(|v| v.value()),
        },
        TtsRequest::TextVoicedd885701(v) => Parts {
            model: v.model.value(),
            voice: v.voice,
            blend: None,
            text: Some(v.text),
            input: None,
            language: v.language.map(|v| v.value()).unwrap_or("auto"),
            emotion: v.emotion.map(|v| v.value()),
            formula: false,
            normalize: v.text_normalization.is_some_and(|v| v.value()),
            split: true,
            output: v.output.map(|v| v.into_audio()).unwrap_or_default(),
            speed: v.speed.unwrap_or(1.0),
            volume: v.volume_scale.unwrap_or(1.0),
            pitch: v.pitch_bias.unwrap_or(0.0),
            replacements: v.replacements,
            transform: Some(v.voice_transform),
            timing: v.timestamp_granularity.map(|v| v.value()),
        },
        TtsRequest::TextVoice36766bcb(v) => Parts {
            model: v.model.value(),
            voice: v.voice,
            blend: None,
            text: Some(v.text),
            input: None,
            language: v.language.map(|v| v.value()).unwrap_or("zh"),
            emotion: v.emotion.map(|v| v.value()),
            formula: true,
            normalize: v.text_normalization.is_some_and(|v| v.value()),
            split: true,
            output: v.output.map(|v| v.into_audio()).unwrap_or_default(),
            speed: v.speed.unwrap_or(1.0),
            volume: v.volume_scale.unwrap_or(1.0),
            pitch: v.pitch_bias.unwrap_or(0.0),
            replacements: v.replacements,
            transform: Some(v.voice_transform),
            timing: v.timestamp_granularity.map(|v| v.value()),
        },
        TtsRequest::TextVoicea492ec5e(v) => Parts {
            model: v.model.value(),
            voice: v.voice,
            blend: None,
            text: Some(v.text),
            input: None,
            language: v.language.map(|v| v.value()).unwrap_or("zh"),
            emotion: v.emotion.map(|v| v.value()),
            formula: true,
            normalize: v.text_normalization.is_some_and(|v| v.value()),
            split: true,
            output: v.output.map(|v| v.into_audio()).unwrap_or_default(),
            speed: v.speed.unwrap_or(1.0),
            volume: v.volume_scale.unwrap_or(1.0),
            pitch: v.pitch_bias.unwrap_or(0.0),
            replacements: v.replacements,
            transform: None,
            timing: v.timestamp_granularity.map(|v| v.value()),
        },
        TtsRequest::TextVoicecbe3fac7(v) => Parts {
            model: v.model.value(),
            voice: v.voice,
            blend: None,
            text: Some(v.text),
            input: None,
            language: v.language.map(|v| v.value()).unwrap_or("auto"),
            emotion: v.emotion.map(|v| v.value()),
            formula: false,
            normalize: v.text_normalization.is_some_and(|v| v.value()),
            split: true,
            output: v.output.map(|v| v.into_audio()).unwrap_or_default(),
            speed: v.speed.unwrap_or(1.0),
            volume: v.volume_scale.unwrap_or(1.0),
            pitch: v.pitch_bias.unwrap_or(0.0),
            replacements: v.replacements,
            transform: None,
            timing: v.timestamp_granularity.map(|v| v.value()),
        },
        TtsRequest::StreamingText81902e1a(v) => Parts {
            model: v.model.value(),
            voice: String::new(),
            blend: Some(v.voice_blend),
            text: None,
            input: Some(v.text),
            language: v.language.map(|v| v.value()).unwrap_or("auto"),
            emotion: v.emotion.map(|v| v.value()),
            formula: false,
            normalize: v.language_text_normalization.is_some_and(|v| v.value()),
            split: true,
            output: v.output.map(|v| v.into_audio()).unwrap_or_default(),
            speed: v.speed.unwrap_or(1.0),
            volume: v.volume_scale.unwrap_or(1.0),
            pitch: v.pitch_bias.unwrap_or(0.0),
            replacements: v.replacements,
            transform: Some(v.voice_transform),
            timing: None,
        },
        TtsRequest::StreamingText909fab39(v) => Parts {
            model: v.model.value(),
            voice: String::new(),
            blend: Some(v.voice_blend),
            text: None,
            input: Some(v.text),
            language: v.language.map(|v| v.value()).unwrap_or("zh"),
            emotion: v.emotion.map(|v| v.value()),
            formula: true,
            normalize: v.language_text_normalization.is_some_and(|v| v.value()),
            split: true,
            output: v.output.map(|v| v.into_audio()).unwrap_or_default(),
            speed: v.speed.unwrap_or(1.0),
            volume: v.volume_scale.unwrap_or(1.0),
            pitch: v.pitch_bias.unwrap_or(0.0),
            replacements: v.replacements,
            transform: Some(v.voice_transform),
            timing: None,
        },
        TtsRequest::StreamingText67fca2f3(v) => Parts {
            model: v.model.value(),
            voice: String::new(),
            blend: Some(v.voice_blend),
            text: None,
            input: Some(v.text),
            language: v.language.map(|v| v.value()).unwrap_or("zh"),
            emotion: v.emotion.map(|v| v.value()),
            formula: true,
            normalize: v.language_text_normalization.is_some_and(|v| v.value()),
            split: true,
            output: v.output.map(|v| v.into_audio()).unwrap_or_default(),
            speed: v.speed.unwrap_or(1.0),
            volume: v.volume_scale.unwrap_or(1.0),
            pitch: v.pitch_bias.unwrap_or(0.0),
            replacements: v.replacements,
            transform: None,
            timing: None,
        },
        TtsRequest::StreamingText5ae80cbf(v) => Parts {
            model: v.model.value(),
            voice: String::new(),
            blend: Some(v.voice_blend),
            text: None,
            input: Some(v.text),
            language: v.language.map(|v| v.value()).unwrap_or("auto"),
            emotion: v.emotion.map(|v| v.value()),
            formula: false,
            normalize: v.language_text_normalization.is_some_and(|v| v.value()),
            split: true,
            output: v.output.map(|v| v.into_audio()).unwrap_or_default(),
            speed: v.speed.unwrap_or(1.0),
            volume: v.volume_scale.unwrap_or(1.0),
            pitch: v.pitch_bias.unwrap_or(0.0),
            replacements: v.replacements,
            transform: None,
            timing: None,
        },
        TtsRequest::StreamingTextVoicee206c70a(v) => Parts {
            model: v.model.value(),
            voice: v.voice,
            blend: None,
            text: None,
            input: Some(v.text),
            language: v.language.map(|v| v.value()).unwrap_or("auto"),
            emotion: v.emotion.map(|v| v.value()),
            formula: false,
            normalize: v.language_text_normalization.is_some_and(|v| v.value()),
            split: true,
            output: v.output.map(|v| v.into_audio()).unwrap_or_default(),
            speed: v.speed.unwrap_or(1.0),
            volume: v.volume_scale.unwrap_or(1.0),
            pitch: v.pitch_bias.unwrap_or(0.0),
            replacements: v.replacements,
            transform: Some(v.voice_transform),
            timing: None,
        },
        TtsRequest::StreamingTextVoiceeb83b1ec(v) => Parts {
            model: v.model.value(),
            voice: v.voice,
            blend: None,
            text: None,
            input: Some(v.text),
            language: v.language.map(|v| v.value()).unwrap_or("zh"),
            emotion: v.emotion.map(|v| v.value()),
            formula: true,
            normalize: v.language_text_normalization.is_some_and(|v| v.value()),
            split: true,
            output: v.output.map(|v| v.into_audio()).unwrap_or_default(),
            speed: v.speed.unwrap_or(1.0),
            volume: v.volume_scale.unwrap_or(1.0),
            pitch: v.pitch_bias.unwrap_or(0.0),
            replacements: v.replacements,
            transform: Some(v.voice_transform),
            timing: None,
        },
        TtsRequest::StreamingTextVoice96bca430(v) => Parts {
            model: v.model.value(),
            voice: v.voice,
            blend: None,
            text: None,
            input: Some(v.text),
            language: v.language.map(|v| v.value()).unwrap_or("zh"),
            emotion: v.emotion.map(|v| v.value()),
            formula: true,
            normalize: v.language_text_normalization.is_some_and(|v| v.value()),
            split: true,
            output: v.output.map(|v| v.into_audio()).unwrap_or_default(),
            speed: v.speed.unwrap_or(1.0),
            volume: v.volume_scale.unwrap_or(1.0),
            pitch: v.pitch_bias.unwrap_or(0.0),
            replacements: v.replacements,
            transform: None,
            timing: None,
        },
        TtsRequest::StreamingTextVoice21264c0c(v) => Parts {
            model: v.model.value(),
            voice: v.voice,
            blend: None,
            text: None,
            input: Some(v.text),
            language: v.language.map(|v| v.value()).unwrap_or("auto"),
            emotion: v.emotion.map(|v| v.value()),
            formula: false,
            normalize: v.language_text_normalization.is_some_and(|v| v.value()),
            split: true,
            output: v.output.map(|v| v.into_audio()).unwrap_or_default(),
            speed: v.speed.unwrap_or(1.0),
            volume: v.volume_scale.unwrap_or(1.0),
            pitch: v.pitch_bias.unwrap_or(0.0),
            replacements: v.replacements,
            transform: None,
            timing: None,
        },
        TtsRequest::Text21d6f721(v) => Parts {
            model: v.model.map(|v| v.value()).unwrap_or("speech-2.8-hd"),
            voice: String::new(),
            blend: Some(v.voice_blend),
            text: Some(v.text),
            input: None,
            language: v.language.map(|v| v.value()).unwrap_or("auto"),
            emotion: v.emotion.map(|v| v.value()),
            formula: false,
            normalize: v.text_normalization.is_some_and(|v| v.value()),
            split: true,
            output: v.output.map(|v| v.into_audio()).unwrap_or_default(),
            speed: v.speed.unwrap_or(1.0),
            volume: v.volume_scale.unwrap_or(1.0),
            pitch: v.pitch_bias.unwrap_or(0.0),
            replacements: v.replacements,
            transform: Some(v.voice_transform),
            timing: v.timestamp_granularity.map(|v| v.value()),
        },
        TtsRequest::Text5b5ff955(v) => Parts {
            model: v.model.map(|v| v.value()).unwrap_or("speech-2.8-hd"),
            voice: String::new(),
            blend: Some(v.voice_blend),
            text: Some(v.text),
            input: None,
            language: v.language.map(|v| v.value()).unwrap_or("zh"),
            emotion: v.emotion.map(|v| v.value()),
            formula: true,
            normalize: v.text_normalization.is_some_and(|v| v.value()),
            split: true,
            output: v.output.map(|v| v.into_audio()).unwrap_or_default(),
            speed: v.speed.unwrap_or(1.0),
            volume: v.volume_scale.unwrap_or(1.0),
            pitch: v.pitch_bias.unwrap_or(0.0),
            replacements: v.replacements,
            transform: Some(v.voice_transform),
            timing: v.timestamp_granularity.map(|v| v.value()),
        },
        TtsRequest::Text6f172e70(v) => Parts {
            model: v.model.map(|v| v.value()).unwrap_or("speech-2.8-hd"),
            voice: String::new(),
            blend: Some(v.voice_blend),
            text: Some(v.text),
            input: None,
            language: v.language.map(|v| v.value()).unwrap_or("zh"),
            emotion: v.emotion.map(|v| v.value()),
            formula: true,
            normalize: v.text_normalization.is_some_and(|v| v.value()),
            split: true,
            output: v.output.map(|v| v.into_audio()).unwrap_or_default(),
            speed: v.speed.unwrap_or(1.0),
            volume: v.volume_scale.unwrap_or(1.0),
            pitch: v.pitch_bias.unwrap_or(0.0),
            replacements: v.replacements,
            transform: None,
            timing: v.timestamp_granularity.map(|v| v.value()),
        },
        TtsRequest::Texta20d3295(v) => Parts {
            model: v.model.map(|v| v.value()).unwrap_or("speech-2.8-hd"),
            voice: String::new(),
            blend: Some(v.voice_blend),
            text: Some(v.text),
            input: None,
            language: v.language.map(|v| v.value()).unwrap_or("auto"),
            emotion: v.emotion.map(|v| v.value()),
            formula: false,
            normalize: v.text_normalization.is_some_and(|v| v.value()),
            split: true,
            output: v.output.map(|v| v.into_audio()).unwrap_or_default(),
            speed: v.speed.unwrap_or(1.0),
            volume: v.volume_scale.unwrap_or(1.0),
            pitch: v.pitch_bias.unwrap_or(0.0),
            replacements: v.replacements,
            transform: None,
            timing: v.timestamp_granularity.map(|v| v.value()),
        },
        TtsRequest::TextVoice472a8ec3(v) => Parts {
            model: v.model.map(|v| v.value()).unwrap_or("speech-2.8-hd"),
            voice: v.voice,
            blend: None,
            text: Some(v.text),
            input: None,
            language: v.language.map(|v| v.value()).unwrap_or("auto"),
            emotion: v.emotion.map(|v| v.value()),
            formula: false,
            normalize: v.text_normalization.is_some_and(|v| v.value()),
            split: true,
            output: v.output.map(|v| v.into_audio()).unwrap_or_default(),
            speed: v.speed.unwrap_or(1.0),
            volume: v.volume_scale.unwrap_or(1.0),
            pitch: v.pitch_bias.unwrap_or(0.0),
            replacements: v.replacements,
            transform: Some(v.voice_transform),
            timing: v.timestamp_granularity.map(|v| v.value()),
        },
        TtsRequest::TextVoice6862a939(v) => Parts {
            model: v.model.map(|v| v.value()).unwrap_or("speech-2.8-hd"),
            voice: v.voice,
            blend: None,
            text: Some(v.text),
            input: None,
            language: v.language.map(|v| v.value()).unwrap_or("zh"),
            emotion: v.emotion.map(|v| v.value()),
            formula: true,
            normalize: v.text_normalization.is_some_and(|v| v.value()),
            split: true,
            output: v.output.map(|v| v.into_audio()).unwrap_or_default(),
            speed: v.speed.unwrap_or(1.0),
            volume: v.volume_scale.unwrap_or(1.0),
            pitch: v.pitch_bias.unwrap_or(0.0),
            replacements: v.replacements,
            transform: Some(v.voice_transform),
            timing: v.timestamp_granularity.map(|v| v.value()),
        },
        TtsRequest::TextVoice7c08f303(v) => Parts {
            model: v.model.map(|v| v.value()).unwrap_or("speech-2.8-hd"),
            voice: v.voice,
            blend: None,
            text: Some(v.text),
            input: None,
            language: v.language.map(|v| v.value()).unwrap_or("zh"),
            emotion: v.emotion.map(|v| v.value()),
            formula: true,
            normalize: v.text_normalization.is_some_and(|v| v.value()),
            split: true,
            output: v.output.map(|v| v.into_audio()).unwrap_or_default(),
            speed: v.speed.unwrap_or(1.0),
            volume: v.volume_scale.unwrap_or(1.0),
            pitch: v.pitch_bias.unwrap_or(0.0),
            replacements: v.replacements,
            transform: None,
            timing: v.timestamp_granularity.map(|v| v.value()),
        },
        TtsRequest::TextVoice9b47fc40(v) => Parts {
            model: v.model.map(|v| v.value()).unwrap_or("speech-2.8-hd"),
            voice: v.voice,
            blend: None,
            text: Some(v.text),
            input: None,
            language: v.language.map(|v| v.value()).unwrap_or("auto"),
            emotion: v.emotion.map(|v| v.value()),
            formula: false,
            normalize: v.text_normalization.is_some_and(|v| v.value()),
            split: true,
            output: v.output.map(|v| v.into_audio()).unwrap_or_default(),
            speed: v.speed.unwrap_or(1.0),
            volume: v.volume_scale.unwrap_or(1.0),
            pitch: v.pitch_bias.unwrap_or(0.0),
            replacements: v.replacements,
            transform: None,
            timing: v.timestamp_granularity.map(|v| v.value()),
        },
        TtsRequest::StreamingText1aae4cf9(v) => Parts {
            model: v.model.map(|v| v.value()).unwrap_or("speech-2.8-hd"),
            voice: String::new(),
            blend: Some(v.voice_blend),
            text: None,
            input: Some(v.text),
            language: v.language.map(|v| v.value()).unwrap_or("auto"),
            emotion: v.emotion.map(|v| v.value()),
            formula: false,
            normalize: v.language_text_normalization.is_some_and(|v| v.value()),
            split: v.split_turns.map(|v| v.value()).unwrap_or(true),
            output: v.output.map(|v| v.into_audio()).unwrap_or_default(),
            speed: v.speed.unwrap_or(1.0),
            volume: v.volume_scale.unwrap_or(1.0),
            pitch: v.pitch_bias.unwrap_or(0.0),
            replacements: v.replacements,
            transform: Some(v.voice_transform),
            timing: None,
        },
        TtsRequest::StreamingText09035640(v) => Parts {
            model: v.model.map(|v| v.value()).unwrap_or("speech-2.8-hd"),
            voice: String::new(),
            blend: Some(v.voice_blend),
            text: None,
            input: Some(v.text),
            language: v.language.map(|v| v.value()).unwrap_or("zh"),
            emotion: v.emotion.map(|v| v.value()),
            formula: true,
            normalize: v.language_text_normalization.is_some_and(|v| v.value()),
            split: v.split_turns.map(|v| v.value()).unwrap_or(true),
            output: v.output.map(|v| v.into_audio()).unwrap_or_default(),
            speed: v.speed.unwrap_or(1.0),
            volume: v.volume_scale.unwrap_or(1.0),
            pitch: v.pitch_bias.unwrap_or(0.0),
            replacements: v.replacements,
            transform: Some(v.voice_transform),
            timing: None,
        },
        TtsRequest::StreamingTexte79a87b2(v) => Parts {
            model: v.model.map(|v| v.value()).unwrap_or("speech-2.8-hd"),
            voice: String::new(),
            blend: Some(v.voice_blend),
            text: None,
            input: Some(v.text),
            language: v.language.map(|v| v.value()).unwrap_or("zh"),
            emotion: v.emotion.map(|v| v.value()),
            formula: true,
            normalize: v.language_text_normalization.is_some_and(|v| v.value()),
            split: v.split_turns.map(|v| v.value()).unwrap_or(true),
            output: v.output.map(|v| v.into_audio()).unwrap_or_default(),
            speed: v.speed.unwrap_or(1.0),
            volume: v.volume_scale.unwrap_or(1.0),
            pitch: v.pitch_bias.unwrap_or(0.0),
            replacements: v.replacements,
            transform: None,
            timing: None,
        },
        TtsRequest::StreamingTextb71a212f(v) => Parts {
            model: v.model.map(|v| v.value()).unwrap_or("speech-2.8-hd"),
            voice: String::new(),
            blend: Some(v.voice_blend),
            text: None,
            input: Some(v.text),
            language: v.language.map(|v| v.value()).unwrap_or("auto"),
            emotion: v.emotion.map(|v| v.value()),
            formula: false,
            normalize: v.language_text_normalization.is_some_and(|v| v.value()),
            split: v.split_turns.map(|v| v.value()).unwrap_or(true),
            output: v.output.map(|v| v.into_audio()).unwrap_or_default(),
            speed: v.speed.unwrap_or(1.0),
            volume: v.volume_scale.unwrap_or(1.0),
            pitch: v.pitch_bias.unwrap_or(0.0),
            replacements: v.replacements,
            transform: None,
            timing: None,
        },
        TtsRequest::StreamingTextVoice84ca6717(v) => Parts {
            model: v.model.map(|v| v.value()).unwrap_or("speech-2.8-hd"),
            voice: v.voice,
            blend: None,
            text: None,
            input: Some(v.text),
            language: v.language.map(|v| v.value()).unwrap_or("auto"),
            emotion: v.emotion.map(|v| v.value()),
            formula: false,
            normalize: v.language_text_normalization.is_some_and(|v| v.value()),
            split: v.split_turns.map(|v| v.value()).unwrap_or(true),
            output: v.output.map(|v| v.into_audio()).unwrap_or_default(),
            speed: v.speed.unwrap_or(1.0),
            volume: v.volume_scale.unwrap_or(1.0),
            pitch: v.pitch_bias.unwrap_or(0.0),
            replacements: v.replacements,
            transform: Some(v.voice_transform),
            timing: None,
        },
        TtsRequest::StreamingTextVoicee1061835(v) => Parts {
            model: v.model.map(|v| v.value()).unwrap_or("speech-2.8-hd"),
            voice: v.voice,
            blend: None,
            text: None,
            input: Some(v.text),
            language: v.language.map(|v| v.value()).unwrap_or("zh"),
            emotion: v.emotion.map(|v| v.value()),
            formula: true,
            normalize: v.language_text_normalization.is_some_and(|v| v.value()),
            split: v.split_turns.map(|v| v.value()).unwrap_or(true),
            output: v.output.map(|v| v.into_audio()).unwrap_or_default(),
            speed: v.speed.unwrap_or(1.0),
            volume: v.volume_scale.unwrap_or(1.0),
            pitch: v.pitch_bias.unwrap_or(0.0),
            replacements: v.replacements,
            transform: Some(v.voice_transform),
            timing: None,
        },
        TtsRequest::StreamingTextVoice94f805c2(v) => Parts {
            model: v.model.map(|v| v.value()).unwrap_or("speech-2.8-hd"),
            voice: v.voice,
            blend: None,
            text: None,
            input: Some(v.text),
            language: v.language.map(|v| v.value()).unwrap_or("zh"),
            emotion: v.emotion.map(|v| v.value()),
            formula: true,
            normalize: v.language_text_normalization.is_some_and(|v| v.value()),
            split: v.split_turns.map(|v| v.value()).unwrap_or(true),
            output: v.output.map(|v| v.into_audio()).unwrap_or_default(),
            speed: v.speed.unwrap_or(1.0),
            volume: v.volume_scale.unwrap_or(1.0),
            pitch: v.pitch_bias.unwrap_or(0.0),
            replacements: v.replacements,
            transform: None,
            timing: None,
        },
        TtsRequest::StreamingTextVoice9e2e17ce(v) => Parts {
            model: v.model.map(|v| v.value()).unwrap_or("speech-2.8-hd"),
            voice: v.voice,
            blend: None,
            text: None,
            input: Some(v.text),
            language: v.language.map(|v| v.value()).unwrap_or("auto"),
            emotion: v.emotion.map(|v| v.value()),
            formula: false,
            normalize: v.language_text_normalization.is_some_and(|v| v.value()),
            split: v.split_turns.map(|v| v.value()).unwrap_or(true),
            output: v.output.map(|v| v.into_audio()).unwrap_or_default(),
            speed: v.speed.unwrap_or(1.0),
            volume: v.volume_scale.unwrap_or(1.0),
            pitch: v.pitch_bias.unwrap_or(0.0),
            replacements: v.replacements,
            transform: None,
            timing: None,
        },
    };
    let socket = p.input.is_some();
    let mut voice = Map::from([
        ("voice_id".into(), JsonValue::String(p.voice)),
        ("speed".into(), JsonValue::Number(p.speed)),
        ("vol".into(), JsonValue::Number(p.volume)),
        ("pitch".into(), JsonValue::Number(p.pitch)),
        ("latex_read".into(), JsonValue::Bool(p.formula)),
        (
            (if socket {
                "english_normalization"
            } else {
                "text_normalization"
            })
            .into(),
            JsonValue::Bool(p.normalize),
        ),
    ]);
    if let Some(emotion) = p.emotion {
        voice.insert("emotion".into(), JsonValue::String(emotion.into()));
    }
    let (audio, format) = p.output.wire(socket);
    let streaming = format != "wav" && !(p.transform.is_some() && format == "flac");
    let language = match p.language {
        "zh" => "Chinese",
        "yue" => "Chinese,Yue",
        "en" => "English",
        "ar" => "Arabic",
        "ru" => "Russian",
        "es" => "Spanish",
        "fr" => "French",
        "pt" => "Portuguese",
        "de" => "German",
        "tr" => "Turkish",
        "nl" => "Dutch",
        "uk" => "Ukrainian",
        "vi" => "Vietnamese",
        "id" => "Indonesian",
        "ja" => "Japanese",
        "it" => "Italian",
        "ko" => "Korean",
        "th" => "Thai",
        "pl" => "Polish",
        "ro" => "Romanian",
        "el" => "Greek",
        "cs" => "Czech",
        "fi" => "Finnish",
        "hi" => "Hindi",
        "bg" => "Bulgarian",
        "da" => "Danish",
        "he" => "Hebrew",
        "ms" => "Malay",
        "fa" => "Persian",
        "sk" => "Slovak",
        "sv" => "Swedish",
        "hr" => "Croatian",
        "fil" => "Filipino",
        "hu" => "Hungarian",
        "no" => "Norwegian",
        "sl" => "Slovenian",
        "ca" => "Catalan",
        "nn" => "Nynorsk",
        "ta" => "Tamil",
        "af" => "Afrikaans",
        _ => "auto",
    };
    let mut wire = Map::from([
        ("model".into(), JsonValue::String(p.model.into())),
        ("language_boost".into(), JsonValue::String(language.into())),
        ("voice_setting".into(), JsonValue::Object(voice)),
        ("audio_setting".into(), JsonValue::Object(audio)),
    ]);
    if let Some(blend) = p.blend {
        wire.insert(
            "timbre_weights".into(),
            JsonValue::Array(
                blend
                    .into_iter()
                    .map(|v| {
                        JsonValue::Object(Map::from([
                            ("voice_id".into(), JsonValue::String(v.voice)),
                            ("weight".into(), JsonValue::Number(v.weight)),
                        ]))
                    })
                    .collect(),
            ),
        );
    }
    if let Some(replacements) = p.replacements {
        wire.insert(
            "pronunciation_dict".into(),
            JsonValue::Object(Map::from([(
                "tone".into(),
                JsonValue::Array(
                    replacements
                        .into_iter()
                        .map(|v| JsonValue::String(format!("{}/{}", v.pattern, v.replacement)))
                        .collect(),
                ),
            )])),
        );
    }
    if let Some(v) = p.transform {
        let mut transform = Map::new();
        for (key, value) in [
            ("pitch", v.brightness),
            ("intensity", v.softness),
            ("timbre", v.crispness),
        ] {
            if let Some(value) = value {
                transform.insert(key.into(), JsonValue::Number(value));
            }
        }
        if let Some(effect) = v.effect {
            transform.insert(
                "sound_effects".into(),
                JsonValue::String(
                    match effect.value() {
                        "telephone" => "lofi_telephone",
                        v => v,
                    }
                    .into(),
                ),
            );
        }
        wire.insert("voice_modify".into(), JsonValue::Object(transform));
    }
    if socket && matches!(p.model, "speech-2.8-hd" | "speech-2.8-turbo") {
        wire.insert("continuous_sound".into(), JsonValue::Bool(!p.split));
    }
    Settings {
        wire,
        text: p.text,
        input: p.input,
        streaming,
        timing: p.timing,
    }
}
