// Generated by codegen/generate-clients.ts from https://raw.githubusercontent.com/openai/openai-node/main/api_reference/openapi.transformed.yml. Do not edit.
package openai

import (
"bytes"
"context"
"encoding/json"
"errors"
"math"
"net/http"
"net/url"
"strings"
"unicode/utf8"
"github.com/speechswitch/client/sdks/go/runtime"
)

const DefaultBaseURL = "https://api.openai.com/v1"
const SpeechStatus = 200
var errWireValue = errors.New("Invalid OpenAI wire value")

type CreateSpeechRequestInput = string

type CreateSpeechRequestInstructions = string

type CreateSpeechRequestModelVariant0 = string

type CreateSpeechRequestModelVariant1 = string

type CreateSpeechRequestModel interface { isCreateSpeechRequestModel() }
type CreateSpeechRequestModelAsVariant0 struct { Value CreateSpeechRequestModelVariant0 }
func (CreateSpeechRequestModelAsVariant0) isCreateSpeechRequestModel() {}
type CreateSpeechRequestModelAsVariant1 struct { Value CreateSpeechRequestModelVariant1 }
func (CreateSpeechRequestModelAsVariant1) isCreateSpeechRequestModel() {}

type CreateSpeechRequestResponseFormat = string

type CreateSpeechRequestSpeed = float64

type CreateSpeechRequestStreamFormat = string

type VoiceIdsSharedVariant0 = string

type VoiceIdsSharedVariant1 = string

type VoiceIdsShared interface { isVoiceIdsShared() }
type VoiceIdsSharedAsVariant0 struct { Value VoiceIdsSharedVariant0 }
func (VoiceIdsSharedAsVariant0) isVoiceIdsShared() {}
type VoiceIdsSharedAsVariant1 struct { Value VoiceIdsSharedVariant1 }
func (VoiceIdsSharedAsVariant1) isVoiceIdsShared() {}

type VoiceIdsOrCustomVoiceVariant1Id = string

type VoiceIdsOrCustomVoiceVariant1 struct {
Id VoiceIdsOrCustomVoiceVariant1Id

}

type VoiceIdsOrCustomVoice interface { isVoiceIdsOrCustomVoice() }
type VoiceIdsOrCustomVoiceAsVariant0 struct { Value VoiceIdsShared }
func (VoiceIdsOrCustomVoiceAsVariant0) isVoiceIdsOrCustomVoice() {}
type VoiceIdsOrCustomVoiceAsVariant1 struct { Value VoiceIdsOrCustomVoiceVariant1 }
func (VoiceIdsOrCustomVoiceAsVariant1) isVoiceIdsOrCustomVoice() {}

type CreateSpeechRequest struct {
Input CreateSpeechRequestInput
Instructions runtime.Optional[CreateSpeechRequestInstructions]
Model CreateSpeechRequestModel
ResponseFormat runtime.Optional[CreateSpeechRequestResponseFormat]
Speed runtime.Optional[CreateSpeechRequestSpeed]
StreamFormat runtime.Optional[CreateSpeechRequestStreamFormat]
Voice VoiceIdsOrCustomVoice

}

type SpeechAudioDeltaEventAudio = string

type SpeechAudioDeltaEventType = string

type SpeechAudioDeltaEvent struct {
Audio SpeechAudioDeltaEventAudio
Type SpeechAudioDeltaEventType
Extra map[string]any
}

type SpeechAudioDoneEventType = string

type SpeechAudioDoneEventUsageInputTokens = float64

type SpeechAudioDoneEventUsageOutputTokens = float64

type SpeechAudioDoneEventUsageTotalTokens = float64

type SpeechAudioDoneEventUsage struct {
InputTokens SpeechAudioDoneEventUsageInputTokens
OutputTokens SpeechAudioDoneEventUsageOutputTokens
TotalTokens SpeechAudioDoneEventUsageTotalTokens
Extra map[string]any
}

type SpeechAudioDoneEvent struct {
Type SpeechAudioDoneEventType
Usage SpeechAudioDoneEventUsage
Extra map[string]any
}

type CreateSpeechResponseStreamEvent interface { isCreateSpeechResponseStreamEvent() }
type CreateSpeechResponseStreamEventAsVariant0 struct { Value SpeechAudioDeltaEvent }
func (CreateSpeechResponseStreamEventAsVariant0) isCreateSpeechResponseStreamEvent() {}
type CreateSpeechResponseStreamEventAsVariant1 struct { Value SpeechAudioDoneEvent }
func (CreateSpeechResponseStreamEventAsVariant1) isCreateSpeechResponseStreamEvent() {}

type SpeechRequest = CreateSpeechRequest

type SpeechEvent = CreateSpeechResponseStreamEvent

func decodeCreateSpeechRequestInput(value any) (CreateSpeechRequestInput, error) {
decoded, ok := value.(string)
if !(ok && utf8.ValidString(decoded) && utf8.RuneCountInString(decoded) <= 4096) { var zero CreateSpeechRequestInput; return zero, errWireValue }; return decoded, nil
}
func encodeCreateSpeechRequestInput(value CreateSpeechRequestInput) (any, error) {
return decodeCreateSpeechRequestInput(value)
}

func decodeCreateSpeechRequestInstructions(value any) (CreateSpeechRequestInstructions, error) {
decoded, ok := value.(string)
if !(ok && utf8.ValidString(decoded) && utf8.RuneCountInString(decoded) <= 4096) { var zero CreateSpeechRequestInstructions; return zero, errWireValue }; return decoded, nil
}
func encodeCreateSpeechRequestInstructions(value CreateSpeechRequestInstructions) (any, error) {
return decodeCreateSpeechRequestInstructions(value)
}

func decodeCreateSpeechRequestModelVariant0(value any) (CreateSpeechRequestModelVariant0, error) {
decoded, ok := value.(string)
if !(ok && utf8.ValidString(decoded)) { var zero CreateSpeechRequestModelVariant0; return zero, errWireValue }; return decoded, nil
}
func encodeCreateSpeechRequestModelVariant0(value CreateSpeechRequestModelVariant0) (any, error) {
return decodeCreateSpeechRequestModelVariant0(value)
}

func decodeCreateSpeechRequestModelVariant1(value any) (CreateSpeechRequestModelVariant1, error) {
decoded, ok := value.(string)
if !(ok && utf8.ValidString(decoded) && (decoded == "tts-1" || decoded == "tts-1-hd" || decoded == "gpt-4o-mini-tts" || decoded == "gpt-4o-mini-tts-2025-12-15")) { var zero CreateSpeechRequestModelVariant1; return zero, errWireValue }; return decoded, nil
}
func encodeCreateSpeechRequestModelVariant1(value CreateSpeechRequestModelVariant1) (any, error) {
return decodeCreateSpeechRequestModelVariant1(value)
}

func decodeCreateSpeechRequestModel(value any) (CreateSpeechRequestModel, error) {
if item, err := decodeCreateSpeechRequestModelVariant0(value); err == nil { return CreateSpeechRequestModelAsVariant0{Value: item}, nil }
if item, err := decodeCreateSpeechRequestModelVariant1(value); err == nil { return CreateSpeechRequestModelAsVariant1{Value: item}, nil }
return nil, errWireValue
}
func encodeCreateSpeechRequestModel(value CreateSpeechRequestModel) (any, error) {
switch value := value.(type) {
case CreateSpeechRequestModelAsVariant0: return encodeCreateSpeechRequestModelVariant0(value.Value)
case *CreateSpeechRequestModelAsVariant0: if value != nil { return encodeCreateSpeechRequestModelVariant0(value.Value) }
case CreateSpeechRequestModelAsVariant1: return encodeCreateSpeechRequestModelVariant1(value.Value)
case *CreateSpeechRequestModelAsVariant1: if value != nil { return encodeCreateSpeechRequestModelVariant1(value.Value) }
}; return nil, errWireValue
}

func decodeCreateSpeechRequestResponseFormat(value any) (CreateSpeechRequestResponseFormat, error) {
decoded, ok := value.(string)
if !(ok && utf8.ValidString(decoded) && (decoded == "mp3" || decoded == "opus" || decoded == "aac" || decoded == "flac" || decoded == "wav" || decoded == "pcm")) { var zero CreateSpeechRequestResponseFormat; return zero, errWireValue }; return decoded, nil
}
func encodeCreateSpeechRequestResponseFormat(value CreateSpeechRequestResponseFormat) (any, error) {
return decodeCreateSpeechRequestResponseFormat(value)
}

func decodeCreateSpeechRequestSpeed(value any) (CreateSpeechRequestSpeed, error) {
decoded, ok := value.(float64)
if !(ok && !math.IsNaN(decoded) && !math.IsInf(decoded, 0) && decoded >= 0.25 && decoded <= 4) { var zero CreateSpeechRequestSpeed; return zero, errWireValue }; return decoded, nil
}
func encodeCreateSpeechRequestSpeed(value CreateSpeechRequestSpeed) (any, error) {
return decodeCreateSpeechRequestSpeed(value)
}

func decodeCreateSpeechRequestStreamFormat(value any) (CreateSpeechRequestStreamFormat, error) {
decoded, ok := value.(string)
if !(ok && utf8.ValidString(decoded) && (decoded == "sse" || decoded == "audio")) { var zero CreateSpeechRequestStreamFormat; return zero, errWireValue }; return decoded, nil
}
func encodeCreateSpeechRequestStreamFormat(value CreateSpeechRequestStreamFormat) (any, error) {
return decodeCreateSpeechRequestStreamFormat(value)
}

func decodeVoiceIdsSharedVariant0(value any) (VoiceIdsSharedVariant0, error) {
decoded, ok := value.(string)
if !(ok && utf8.ValidString(decoded)) { var zero VoiceIdsSharedVariant0; return zero, errWireValue }; return decoded, nil
}
func encodeVoiceIdsSharedVariant0(value VoiceIdsSharedVariant0) (any, error) {
return decodeVoiceIdsSharedVariant0(value)
}

func decodeVoiceIdsSharedVariant1(value any) (VoiceIdsSharedVariant1, error) {
decoded, ok := value.(string)
if !(ok && utf8.ValidString(decoded) && (decoded == "alloy" || decoded == "ash" || decoded == "ballad" || decoded == "coral" || decoded == "echo" || decoded == "sage" || decoded == "shimmer" || decoded == "verse" || decoded == "marin" || decoded == "cedar")) { var zero VoiceIdsSharedVariant1; return zero, errWireValue }; return decoded, nil
}
func encodeVoiceIdsSharedVariant1(value VoiceIdsSharedVariant1) (any, error) {
return decodeVoiceIdsSharedVariant1(value)
}

func decodeVoiceIdsShared(value any) (VoiceIdsShared, error) {
if item, err := decodeVoiceIdsSharedVariant0(value); err == nil { return VoiceIdsSharedAsVariant0{Value: item}, nil }
if item, err := decodeVoiceIdsSharedVariant1(value); err == nil { return VoiceIdsSharedAsVariant1{Value: item}, nil }
return nil, errWireValue
}
func encodeVoiceIdsShared(value VoiceIdsShared) (any, error) {
switch value := value.(type) {
case VoiceIdsSharedAsVariant0: return encodeVoiceIdsSharedVariant0(value.Value)
case *VoiceIdsSharedAsVariant0: if value != nil { return encodeVoiceIdsSharedVariant0(value.Value) }
case VoiceIdsSharedAsVariant1: return encodeVoiceIdsSharedVariant1(value.Value)
case *VoiceIdsSharedAsVariant1: if value != nil { return encodeVoiceIdsSharedVariant1(value.Value) }
}; return nil, errWireValue
}

func decodeVoiceIdsOrCustomVoiceVariant1Id(value any) (VoiceIdsOrCustomVoiceVariant1Id, error) {
decoded, ok := value.(string)
if !(ok && utf8.ValidString(decoded)) { var zero VoiceIdsOrCustomVoiceVariant1Id; return zero, errWireValue }; return decoded, nil
}
func encodeVoiceIdsOrCustomVoiceVariant1Id(value VoiceIdsOrCustomVoiceVariant1Id) (any, error) {
return decodeVoiceIdsOrCustomVoiceVariant1Id(value)
}

func decodeVoiceIdsOrCustomVoiceVariant1(value any) (VoiceIdsOrCustomVoiceVariant1, error) {
var result VoiceIdsOrCustomVoiceVariant1
object, ok := value.(map[string]any); if !ok || object == nil { return result, errWireValue }
if raw, present := object["id"]; present {
decoded, err := decodeVoiceIdsOrCustomVoiceVariant1Id(raw); if err != nil { return result, err }
result.Id = decoded
} else { return result, errWireValue }
for key, item := range object {
switch key { case "id": continue }
_ = item; return result, errWireValue
}
return result, nil
}
func encodeVoiceIdsOrCustomVoiceVariant1(value VoiceIdsOrCustomVoiceVariant1) (any, error) {
object := map[string]any{}

{
item, err := encodeVoiceIdsOrCustomVoiceVariant1Id(value.Id); if err != nil { return nil, err }
object["id"] = item
}
return object, nil
}

func decodeVoiceIdsOrCustomVoice(value any) (VoiceIdsOrCustomVoice, error) {
if item, err := decodeVoiceIdsShared(value); err == nil { return VoiceIdsOrCustomVoiceAsVariant0{Value: item}, nil }
if item, err := decodeVoiceIdsOrCustomVoiceVariant1(value); err == nil { return VoiceIdsOrCustomVoiceAsVariant1{Value: item}, nil }
return nil, errWireValue
}
func encodeVoiceIdsOrCustomVoice(value VoiceIdsOrCustomVoice) (any, error) {
switch value := value.(type) {
case VoiceIdsOrCustomVoiceAsVariant0: return encodeVoiceIdsShared(value.Value)
case *VoiceIdsOrCustomVoiceAsVariant0: if value != nil { return encodeVoiceIdsShared(value.Value) }
case VoiceIdsOrCustomVoiceAsVariant1: return encodeVoiceIdsOrCustomVoiceVariant1(value.Value)
case *VoiceIdsOrCustomVoiceAsVariant1: if value != nil { return encodeVoiceIdsOrCustomVoiceVariant1(value.Value) }
}; return nil, errWireValue
}

func decodeCreateSpeechRequest(value any) (CreateSpeechRequest, error) {
var result CreateSpeechRequest
object, ok := value.(map[string]any); if !ok || object == nil { return result, errWireValue }
if raw, present := object["input"]; present {
decoded, err := decodeCreateSpeechRequestInput(raw); if err != nil { return result, err }
result.Input = decoded
} else { return result, errWireValue }
if raw, present := object["instructions"]; present {
decoded, err := decodeCreateSpeechRequestInstructions(raw); if err != nil { return result, err }
result.Instructions = runtime.Some(decoded)
}
if raw, present := object["model"]; present {
decoded, err := decodeCreateSpeechRequestModel(raw); if err != nil { return result, err }
result.Model = decoded
} else { return result, errWireValue }
if raw, present := object["response_format"]; present {
decoded, err := decodeCreateSpeechRequestResponseFormat(raw); if err != nil { return result, err }
result.ResponseFormat = runtime.Some(decoded)
}
if raw, present := object["speed"]; present {
decoded, err := decodeCreateSpeechRequestSpeed(raw); if err != nil { return result, err }
result.Speed = runtime.Some(decoded)
}
if raw, present := object["stream_format"]; present {
decoded, err := decodeCreateSpeechRequestStreamFormat(raw); if err != nil { return result, err }
result.StreamFormat = runtime.Some(decoded)
}
if raw, present := object["voice"]; present {
decoded, err := decodeVoiceIdsOrCustomVoice(raw); if err != nil { return result, err }
result.Voice = decoded
} else { return result, errWireValue }
for key, item := range object {
switch key { case "input", "instructions", "model", "response_format", "speed", "stream_format", "voice": continue }
_ = item; return result, errWireValue
}
return result, nil
}
func encodeCreateSpeechRequest(value CreateSpeechRequest) (any, error) {
object := map[string]any{}

{
item, err := encodeCreateSpeechRequestInput(value.Input); if err != nil { return nil, err }
object["input"] = item
}
if value.Instructions.Present {
item, err := encodeCreateSpeechRequestInstructions(value.Instructions.Value); if err != nil { return nil, err }
object["instructions"] = item
}
{
item, err := encodeCreateSpeechRequestModel(value.Model); if err != nil { return nil, err }
object["model"] = item
}
if value.ResponseFormat.Present {
item, err := encodeCreateSpeechRequestResponseFormat(value.ResponseFormat.Value); if err != nil { return nil, err }
object["response_format"] = item
}
if value.Speed.Present {
item, err := encodeCreateSpeechRequestSpeed(value.Speed.Value); if err != nil { return nil, err }
object["speed"] = item
}
if value.StreamFormat.Present {
item, err := encodeCreateSpeechRequestStreamFormat(value.StreamFormat.Value); if err != nil { return nil, err }
object["stream_format"] = item
}
{
item, err := encodeVoiceIdsOrCustomVoice(value.Voice); if err != nil { return nil, err }
object["voice"] = item
}
return object, nil
}

func decodeSpeechAudioDeltaEventAudio(value any) (SpeechAudioDeltaEventAudio, error) {
decoded, ok := value.(string)
if !(ok && utf8.ValidString(decoded)) { var zero SpeechAudioDeltaEventAudio; return zero, errWireValue }; return decoded, nil
}
func encodeSpeechAudioDeltaEventAudio(value SpeechAudioDeltaEventAudio) (any, error) {
return decodeSpeechAudioDeltaEventAudio(value)
}

func decodeSpeechAudioDeltaEventType(value any) (SpeechAudioDeltaEventType, error) {
decoded, ok := value.(string)
if !(ok && utf8.ValidString(decoded) && (decoded == "speech.audio.delta")) { var zero SpeechAudioDeltaEventType; return zero, errWireValue }; return decoded, nil
}
func encodeSpeechAudioDeltaEventType(value SpeechAudioDeltaEventType) (any, error) {
return decodeSpeechAudioDeltaEventType(value)
}

func decodeSpeechAudioDeltaEvent(value any) (SpeechAudioDeltaEvent, error) {
var result SpeechAudioDeltaEvent
object, ok := value.(map[string]any); if !ok || object == nil { return result, errWireValue }
if raw, present := object["audio"]; present {
decoded, err := decodeSpeechAudioDeltaEventAudio(raw); if err != nil { return result, err }
result.Audio = decoded
} else { return result, errWireValue }
if raw, present := object["type"]; present {
decoded, err := decodeSpeechAudioDeltaEventType(raw); if err != nil { return result, err }
result.Type = decoded
} else { return result, errWireValue }
for key, item := range object {
switch key { case "audio", "type": continue }
if result.Extra == nil { result.Extra = map[string]any{} }; result.Extra[key] = item
}
return result, nil
}
func encodeSpeechAudioDeltaEvent(value SpeechAudioDeltaEvent) (any, error) {
object := map[string]any{}
for key, item := range value.Extra { switch key { case "audio", "type": return nil, errWireValue }; object[key] = item }
{
item, err := encodeSpeechAudioDeltaEventAudio(value.Audio); if err != nil { return nil, err }
object["audio"] = item
}
{
item, err := encodeSpeechAudioDeltaEventType(value.Type); if err != nil { return nil, err }
object["type"] = item
}
return object, nil
}

func decodeSpeechAudioDoneEventType(value any) (SpeechAudioDoneEventType, error) {
decoded, ok := value.(string)
if !(ok && utf8.ValidString(decoded) && (decoded == "speech.audio.done")) { var zero SpeechAudioDoneEventType; return zero, errWireValue }; return decoded, nil
}
func encodeSpeechAudioDoneEventType(value SpeechAudioDoneEventType) (any, error) {
return decodeSpeechAudioDoneEventType(value)
}

func decodeSpeechAudioDoneEventUsageInputTokens(value any) (SpeechAudioDoneEventUsageInputTokens, error) {
decoded, ok := value.(float64)
if !(ok && !math.IsNaN(decoded) && !math.IsInf(decoded, 0) && math.Trunc(decoded) == decoded && math.Abs(decoded) <= 9007199254740991) { var zero SpeechAudioDoneEventUsageInputTokens; return zero, errWireValue }; return decoded, nil
}
func encodeSpeechAudioDoneEventUsageInputTokens(value SpeechAudioDoneEventUsageInputTokens) (any, error) {
return decodeSpeechAudioDoneEventUsageInputTokens(value)
}

func decodeSpeechAudioDoneEventUsageOutputTokens(value any) (SpeechAudioDoneEventUsageOutputTokens, error) {
decoded, ok := value.(float64)
if !(ok && !math.IsNaN(decoded) && !math.IsInf(decoded, 0) && math.Trunc(decoded) == decoded && math.Abs(decoded) <= 9007199254740991) { var zero SpeechAudioDoneEventUsageOutputTokens; return zero, errWireValue }; return decoded, nil
}
func encodeSpeechAudioDoneEventUsageOutputTokens(value SpeechAudioDoneEventUsageOutputTokens) (any, error) {
return decodeSpeechAudioDoneEventUsageOutputTokens(value)
}

func decodeSpeechAudioDoneEventUsageTotalTokens(value any) (SpeechAudioDoneEventUsageTotalTokens, error) {
decoded, ok := value.(float64)
if !(ok && !math.IsNaN(decoded) && !math.IsInf(decoded, 0) && math.Trunc(decoded) == decoded && math.Abs(decoded) <= 9007199254740991) { var zero SpeechAudioDoneEventUsageTotalTokens; return zero, errWireValue }; return decoded, nil
}
func encodeSpeechAudioDoneEventUsageTotalTokens(value SpeechAudioDoneEventUsageTotalTokens) (any, error) {
return decodeSpeechAudioDoneEventUsageTotalTokens(value)
}

func decodeSpeechAudioDoneEventUsage(value any) (SpeechAudioDoneEventUsage, error) {
var result SpeechAudioDoneEventUsage
object, ok := value.(map[string]any); if !ok || object == nil { return result, errWireValue }
if raw, present := object["input_tokens"]; present {
decoded, err := decodeSpeechAudioDoneEventUsageInputTokens(raw); if err != nil { return result, err }
result.InputTokens = decoded
} else { return result, errWireValue }
if raw, present := object["output_tokens"]; present {
decoded, err := decodeSpeechAudioDoneEventUsageOutputTokens(raw); if err != nil { return result, err }
result.OutputTokens = decoded
} else { return result, errWireValue }
if raw, present := object["total_tokens"]; present {
decoded, err := decodeSpeechAudioDoneEventUsageTotalTokens(raw); if err != nil { return result, err }
result.TotalTokens = decoded
} else { return result, errWireValue }
for key, item := range object {
switch key { case "input_tokens", "output_tokens", "total_tokens": continue }
if result.Extra == nil { result.Extra = map[string]any{} }; result.Extra[key] = item
}
return result, nil
}
func encodeSpeechAudioDoneEventUsage(value SpeechAudioDoneEventUsage) (any, error) {
object := map[string]any{}
for key, item := range value.Extra { switch key { case "input_tokens", "output_tokens", "total_tokens": return nil, errWireValue }; object[key] = item }
{
item, err := encodeSpeechAudioDoneEventUsageInputTokens(value.InputTokens); if err != nil { return nil, err }
object["input_tokens"] = item
}
{
item, err := encodeSpeechAudioDoneEventUsageOutputTokens(value.OutputTokens); if err != nil { return nil, err }
object["output_tokens"] = item
}
{
item, err := encodeSpeechAudioDoneEventUsageTotalTokens(value.TotalTokens); if err != nil { return nil, err }
object["total_tokens"] = item
}
return object, nil
}

func decodeSpeechAudioDoneEvent(value any) (SpeechAudioDoneEvent, error) {
var result SpeechAudioDoneEvent
object, ok := value.(map[string]any); if !ok || object == nil { return result, errWireValue }
if raw, present := object["type"]; present {
decoded, err := decodeSpeechAudioDoneEventType(raw); if err != nil { return result, err }
result.Type = decoded
} else { return result, errWireValue }
if raw, present := object["usage"]; present {
decoded, err := decodeSpeechAudioDoneEventUsage(raw); if err != nil { return result, err }
result.Usage = decoded
} else { return result, errWireValue }
for key, item := range object {
switch key { case "type", "usage": continue }
if result.Extra == nil { result.Extra = map[string]any{} }; result.Extra[key] = item
}
return result, nil
}
func encodeSpeechAudioDoneEvent(value SpeechAudioDoneEvent) (any, error) {
object := map[string]any{}
for key, item := range value.Extra { switch key { case "type", "usage": return nil, errWireValue }; object[key] = item }
{
item, err := encodeSpeechAudioDoneEventType(value.Type); if err != nil { return nil, err }
object["type"] = item
}
{
item, err := encodeSpeechAudioDoneEventUsage(value.Usage); if err != nil { return nil, err }
object["usage"] = item
}
return object, nil
}

func decodeCreateSpeechResponseStreamEvent(value any) (CreateSpeechResponseStreamEvent, error) {
if item, err := decodeSpeechAudioDeltaEvent(value); err == nil { return CreateSpeechResponseStreamEventAsVariant0{Value: item}, nil }
if item, err := decodeSpeechAudioDoneEvent(value); err == nil { return CreateSpeechResponseStreamEventAsVariant1{Value: item}, nil }
return nil, errWireValue
}
func encodeCreateSpeechResponseStreamEvent(value CreateSpeechResponseStreamEvent) (any, error) {
switch value := value.(type) {
case CreateSpeechResponseStreamEventAsVariant0: return encodeSpeechAudioDeltaEvent(value.Value)
case *CreateSpeechResponseStreamEventAsVariant0: if value != nil { return encodeSpeechAudioDeltaEvent(value.Value) }
case CreateSpeechResponseStreamEventAsVariant1: return encodeSpeechAudioDoneEvent(value.Value)
case *CreateSpeechResponseStreamEventAsVariant1: if value != nil { return encodeSpeechAudioDoneEvent(value.Value) }
}; return nil, errWireValue
}

func DecodeSpeechEvent(data []byte) (SpeechEvent, error) {
var value any
if !runtime.ValidUTF8JSON(data) { return nil, errors.New("Invalid OpenAI speech event") }
if err := json.Unmarshal(data, &value); err != nil { return nil, errors.New("Invalid OpenAI speech event") }
result, err := decodeCreateSpeechResponseStreamEvent(value)
if err != nil { return nil, errors.New("Invalid OpenAI speech event") }; return result, nil
}

func CreateSpeech(ctx context.Context, value SpeechRequest, apiKey, baseURL string, transport runtime.HTTPTransport) (*runtime.HTTPResponse, error) {
raw, err := encodeCreateSpeechRequest(value)
if err != nil { return nil, errors.New("Invalid OpenAI speech wire request") }
data, err := json.Marshal(raw)
if err != nil { return nil, errors.New("Invalid OpenAI speech wire request") }
target, err := url.Parse(baseURL)
if err != nil || target.Hostname() == "" || target.User != nil || target.Fragment != "" || target.Opaque != "" || (target.Scheme != "http" && target.Scheme != "https") { return nil, errors.New("Invalid OpenAI BaseURL") }
escaped := strings.TrimRight(target.EscapedPath(), "/") + "/audio/speech"
target.Path, err = url.PathUnescape(escaped); if err != nil { return nil, errors.New("Invalid OpenAI request URL") }; target.RawPath = escaped
request, err := http.NewRequestWithContext(ctx, "POST", target.String(), bytes.NewReader(data))
if err != nil { return nil, errors.New("Invalid OpenAI request URL") }
request.Header.Set("Authorization", "Bearer " + apiKey)
request.Header.Set("Content-Type", "application/json")
request.Header.Set("Accept", "application/octet-stream, text/event-stream")
return runtime.OpenResponse(request, transport)
}
