use crate::{
    generated::elevenlabs::*,
    runtime::{JsonValue, StreamingInput},
};
use std::collections::BTreeMap;

pub(super) type Input = TtsRequestStreamingTextVoice194990a6TextItem;
pub(super) type DialogueInput = TtsRequestElevenV3StreamingTextVoicef18e078fTextItem;
pub(super) enum Text {
    Whole(String),
    Tts(StreamingInput<Input>),
    Dialogue(StreamingInput<DialogueInput>),
}
pub(super) struct Prepared {
    pub model: &'static str,
    pub voice: String,
    pub text: Text,
    pub output: TtsRequestTextVoice4a0120aeOutput,
    pub language: Option<String>,
    pub seed: Option<f64>,
    pub stability: Option<f64>,
    pub speed: Option<f64>,
    pub similarity: Option<f64>,
    pub style: Option<f64>,
    pub boost: Option<bool>,
    pub normalization: &'static str,
    pub latency: Option<&'static str>,
    pub language_normalization: bool,
    pub before: Option<TtsRequestTextVoice4a0120aeContextAfter>,
    pub after: Option<TtsRequestTextVoice4a0120aeContextAfter>,
    pub dictionaries: Option<JsonValue>,
    pub schedule: Option<Vec<f64>>,
    pub unbuffered: bool,
    pub ssml: bool,
    pub timed: bool,
    pub normalized: bool,
}
pub(super) fn prepare(request: TtsRequest) -> Prepared {
    match request {
        TtsRequest::TextVoice4a0120ae(r) => Prepared {
            model: r.model.value(),
            voice: r.voice,
            text: Text::Whole(r.text),
            output: r.output,
            language: r.language,
            seed: r.random_seed,
            stability: r.stability,
            speed: r.speed,
            similarity: r.voice_similarity,
            style: r.style_exaggeration,
            before: r.context_before,
            after: r.context_after,
            schedule: None,
            boost: r.voice_boost.map(|v| v.value()),
            normalization: normalization(r.text_normalization),
            latency: r.latency_optimization.map(|v| v.value()),
            language_normalization: r.language_text_normalization.is_some_and(|v| v.value()),
            dictionaries: http_dictionaries(r.pronunciation_dictionaries),
            unbuffered: false,
            ssml: false,
            timed: false,
            normalized: false,
        },
        TtsRequest::TextVoice68b36b42(r) => Prepared {
            model: r.model.value(),
            voice: r.voice,
            text: Text::Whole(r.text),
            output: r.output,
            language: r.language,
            seed: r.random_seed,
            stability: r.stability,
            speed: r.speed,
            similarity: r.voice_similarity,
            style: r.style_exaggeration,
            before: r.context_before,
            after: r.context_after,
            schedule: None,
            boost: r.voice_boost.map(|v| v.value()),
            normalization: "off",
            latency: Some(r.latency_optimization.value()),
            language_normalization: r.language_text_normalization.is_some_and(|v| v.value()),
            dictionaries: http_dictionaries(r.pronunciation_dictionaries),
            unbuffered: false,
            ssml: false,
            timed: false,
            normalized: false,
        },
        TtsRequest::TextVoice9cb211ad(r) => Prepared {
            model: r.model.value(),
            voice: r.voice,
            text: Text::Whole(r.text),
            output: r.output,
            language: r.language,
            seed: r.random_seed,
            stability: r.stability,
            speed: r.speed,
            similarity: r.voice_similarity,
            style: r.style_exaggeration,
            before: r.context_before,
            after: r.context_after,
            schedule: None,
            boost: r.voice_boost.map(|v| v.value()),
            normalization: "off",
            latency: Some(r.latency_optimization.value()),
            language_normalization: r.language_text_normalization.is_some_and(|v| v.value()),
            dictionaries: http_dictionaries(r.pronunciation_dictionaries),
            unbuffered: false,
            ssml: false,
            timed: true,
            normalized: r.timestamp_text.is_some_and(|v| v.value() == "normalized"),
        },
        TtsRequest::StreamingTextVoice194990a6(r) => Prepared {
            model: r.model.value(),
            voice: r.voice,
            text: Text::Tts(r.text),
            output: raw_output(r.output),
            language: r.language,
            seed: r.random_seed,
            stability: r.stability,
            speed: r.speed,
            similarity: r.voice_similarity,
            style: r.style_exaggeration,
            before: None,
            after: None,
            schedule: r.text_buffer_thresholds,
            boost: r.voice_boost.map(|v| v.value()),
            normalization: normalization(r.text_normalization),
            latency: None,
            language_normalization: false,
            dictionaries: live_dictionaries(r.pronunciation_dictionaries),
            unbuffered: false,
            ssml: r.input_type.is_some_and(|v| v.value() == "ssml"),
            timed: false,
            normalized: false,
        },
        TtsRequest::TextVoiceac5e804b(r) => Prepared {
            model: r.model.value(),
            voice: r.voice,
            text: Text::Whole(r.text),
            output: r.output,
            language: r.language,
            seed: r.random_seed,
            stability: r.stability,
            speed: r.speed,
            similarity: r.voice_similarity,
            style: r.style_exaggeration,
            before: r.context_before,
            after: r.context_after,
            schedule: None,
            boost: r.voice_boost.map(|v| v.value()),
            normalization: normalization(r.text_normalization),
            latency: r.latency_optimization.map(|v| v.value()),
            language_normalization: r.language_text_normalization.is_some_and(|v| v.value()),
            dictionaries: http_dictionaries(r.pronunciation_dictionaries),
            unbuffered: false,
            ssml: false,
            timed: true,
            normalized: r.timestamp_text.is_some_and(|v| v.value() == "normalized"),
        },
        TtsRequest::StreamingTextVoice04078405(r) => Prepared {
            model: r.model.value(),
            voice: r.voice,
            text: Text::Tts(r.text),
            output: raw_output(r.output),
            language: r.language,
            seed: r.random_seed,
            stability: r.stability,
            speed: r.speed,
            similarity: r.voice_similarity,
            style: r.style_exaggeration,
            before: None,
            after: None,
            schedule: r.text_buffer_thresholds,
            boost: r.voice_boost.map(|v| v.value()),
            normalization: normalization(r.text_normalization),
            latency: None,
            language_normalization: false,
            dictionaries: live_dictionaries(r.pronunciation_dictionaries),
            unbuffered: false,
            ssml: r.input_type.is_some_and(|v| v.value() == "ssml"),
            timed: true,
            normalized: r.timestamp_text.is_some_and(|v| v.value() == "normalized"),
        },
        TtsRequest::StreamingTextVoicef49cfea8(r) => Prepared {
            model: r.model.value(),
            voice: r.voice,
            text: Text::Tts(r.text),
            output: raw_output(r.output),
            language: r.language,
            seed: r.random_seed,
            stability: r.stability,
            speed: r.speed,
            similarity: r.voice_similarity,
            style: r.style_exaggeration,
            before: None,
            after: None,
            schedule: None,
            boost: r.voice_boost.map(|v| v.value()),
            normalization: normalization(r.text_normalization),
            latency: None,
            language_normalization: false,
            dictionaries: live_dictionaries(r.pronunciation_dictionaries),
            unbuffered: true,
            ssml: r.input_type.is_some_and(|v| v.value() == "ssml"),
            timed: false,
            normalized: false,
        },
        TtsRequest::StreamingTextVoice282de2db(r) => Prepared {
            model: r.model.value(),
            voice: r.voice,
            text: Text::Tts(r.text),
            output: raw_output(r.output),
            language: r.language,
            seed: r.random_seed,
            stability: r.stability,
            speed: r.speed,
            similarity: r.voice_similarity,
            style: r.style_exaggeration,
            before: None,
            after: None,
            schedule: None,
            boost: r.voice_boost.map(|v| v.value()),
            normalization: normalization(r.text_normalization),
            latency: None,
            language_normalization: false,
            dictionaries: live_dictionaries(r.pronunciation_dictionaries),
            unbuffered: true,
            ssml: r.input_type.is_some_and(|v| v.value() == "ssml"),
            timed: true,
            normalized: r.timestamp_text.is_some_and(|v| v.value() == "normalized"),
        },
        TtsRequest::MultilingualV2TextVoiceb7dcb211(r) => Prepared {
            model: r.model.value(),
            voice: r.voice,
            text: Text::Whole(r.text),
            output: r.output,
            language: None,
            seed: r.random_seed,
            stability: r.stability,
            speed: r.speed,
            similarity: r.voice_similarity,
            style: r.style_exaggeration,
            before: r.context_before,
            after: r.context_after,
            schedule: None,
            boost: r.voice_boost.map(|v| v.value()),
            normalization: normalization(r.text_normalization),
            latency: r.latency_optimization.map(|v| v.value()),
            language_normalization: r.language_text_normalization.is_some_and(|v| v.value()),
            dictionaries: http_dictionaries(r.pronunciation_dictionaries),
            unbuffered: false,
            ssml: false,
            timed: false,
            normalized: false,
        },
        TtsRequest::MultilingualV2TextVoice6b4236de(r) => Prepared {
            model: r.model.value(),
            voice: r.voice,
            text: Text::Whole(r.text),
            output: r.output,
            language: None,
            seed: r.random_seed,
            stability: r.stability,
            speed: r.speed,
            similarity: r.voice_similarity,
            style: r.style_exaggeration,
            before: r.context_before,
            after: r.context_after,
            schedule: None,
            boost: r.voice_boost.map(|v| v.value()),
            normalization: "off",
            latency: Some(r.latency_optimization.value()),
            language_normalization: r.language_text_normalization.is_some_and(|v| v.value()),
            dictionaries: http_dictionaries(r.pronunciation_dictionaries),
            unbuffered: false,
            ssml: false,
            timed: false,
            normalized: false,
        },
        TtsRequest::MultilingualV2TextVoiceca4ba9c1(r) => Prepared {
            model: r.model.value(),
            voice: r.voice,
            text: Text::Whole(r.text),
            output: r.output,
            language: None,
            seed: r.random_seed,
            stability: r.stability,
            speed: r.speed,
            similarity: r.voice_similarity,
            style: r.style_exaggeration,
            before: r.context_before,
            after: r.context_after,
            schedule: None,
            boost: r.voice_boost.map(|v| v.value()),
            normalization: "off",
            latency: Some(r.latency_optimization.value()),
            language_normalization: r.language_text_normalization.is_some_and(|v| v.value()),
            dictionaries: http_dictionaries(r.pronunciation_dictionaries),
            unbuffered: false,
            ssml: false,
            timed: true,
            normalized: r.timestamp_text.is_some_and(|v| v.value() == "normalized"),
        },
        TtsRequest::MultilingualV2StreamingTextVoice90f3837b(r) => Prepared {
            model: r.model.value(),
            voice: r.voice,
            text: Text::Tts(r.text),
            output: raw_output(r.output),
            language: None,
            seed: r.random_seed,
            stability: r.stability,
            speed: r.speed,
            similarity: r.voice_similarity,
            style: r.style_exaggeration,
            before: None,
            after: None,
            schedule: r.text_buffer_thresholds,
            boost: r.voice_boost.map(|v| v.value()),
            normalization: normalization(r.text_normalization),
            latency: None,
            language_normalization: false,
            dictionaries: live_dictionaries(r.pronunciation_dictionaries),
            unbuffered: false,
            ssml: r.input_type.is_some_and(|v| v.value() == "ssml"),
            timed: false,
            normalized: false,
        },
        TtsRequest::MultilingualV2TextVoice51150c25(r) => Prepared {
            model: r.model.value(),
            voice: r.voice,
            text: Text::Whole(r.text),
            output: r.output,
            language: None,
            seed: r.random_seed,
            stability: r.stability,
            speed: r.speed,
            similarity: r.voice_similarity,
            style: r.style_exaggeration,
            before: r.context_before,
            after: r.context_after,
            schedule: None,
            boost: r.voice_boost.map(|v| v.value()),
            normalization: normalization(r.text_normalization),
            latency: r.latency_optimization.map(|v| v.value()),
            language_normalization: r.language_text_normalization.is_some_and(|v| v.value()),
            dictionaries: http_dictionaries(r.pronunciation_dictionaries),
            unbuffered: false,
            ssml: false,
            timed: true,
            normalized: r.timestamp_text.is_some_and(|v| v.value() == "normalized"),
        },
        TtsRequest::MultilingualV2StreamingTextVoice7bc2227c(r) => Prepared {
            model: r.model.value(),
            voice: r.voice,
            text: Text::Tts(r.text),
            output: raw_output(r.output),
            language: None,
            seed: r.random_seed,
            stability: r.stability,
            speed: r.speed,
            similarity: r.voice_similarity,
            style: r.style_exaggeration,
            before: None,
            after: None,
            schedule: r.text_buffer_thresholds,
            boost: r.voice_boost.map(|v| v.value()),
            normalization: normalization(r.text_normalization),
            latency: None,
            language_normalization: false,
            dictionaries: live_dictionaries(r.pronunciation_dictionaries),
            unbuffered: false,
            ssml: r.input_type.is_some_and(|v| v.value() == "ssml"),
            timed: true,
            normalized: r.timestamp_text.is_some_and(|v| v.value() == "normalized"),
        },
        TtsRequest::MultilingualV2StreamingTextVoice388d65c0(r) => Prepared {
            model: r.model.value(),
            voice: r.voice,
            text: Text::Tts(r.text),
            output: raw_output(r.output),
            language: None,
            seed: r.random_seed,
            stability: r.stability,
            speed: r.speed,
            similarity: r.voice_similarity,
            style: r.style_exaggeration,
            before: None,
            after: None,
            schedule: None,
            boost: r.voice_boost.map(|v| v.value()),
            normalization: normalization(r.text_normalization),
            latency: None,
            language_normalization: false,
            dictionaries: live_dictionaries(r.pronunciation_dictionaries),
            unbuffered: true,
            ssml: r.input_type.is_some_and(|v| v.value() == "ssml"),
            timed: false,
            normalized: false,
        },
        TtsRequest::MultilingualV2StreamingTextVoice1e73ed4e(r) => Prepared {
            model: r.model.value(),
            voice: r.voice,
            text: Text::Tts(r.text),
            output: raw_output(r.output),
            language: None,
            seed: r.random_seed,
            stability: r.stability,
            speed: r.speed,
            similarity: r.voice_similarity,
            style: r.style_exaggeration,
            before: None,
            after: None,
            schedule: None,
            boost: r.voice_boost.map(|v| v.value()),
            normalization: normalization(r.text_normalization),
            latency: None,
            language_normalization: false,
            dictionaries: live_dictionaries(r.pronunciation_dictionaries),
            unbuffered: true,
            ssml: r.input_type.is_some_and(|v| v.value() == "ssml"),
            timed: true,
            normalized: r.timestamp_text.is_some_and(|v| v.value() == "normalized"),
        },
        TtsRequest::ElevenV3TextVoiceedc22df3(r) => Prepared {
            model: r.model.value(),
            voice: r.voice,
            text: Text::Whole(r.text),
            output: r.output,
            language: r.language,
            seed: r.random_seed,
            stability: r.stability,
            speed: None,
            similarity: None,
            style: None,
            before: r.context_before,
            after: r.context_after,
            schedule: None,
            boost: None,
            normalization: normalization(r.text_normalization),
            latency: r.latency_optimization.map(|v| v.value()),
            language_normalization: r.language_text_normalization.is_some_and(|v| v.value()),
            dictionaries: http_dictionaries(r.pronunciation_dictionaries),
            unbuffered: false,
            ssml: false,
            timed: false,
            normalized: false,
        },
        TtsRequest::ElevenV3TextVoicea067d696(r) => Prepared {
            model: r.model.value(),
            voice: r.voice,
            text: Text::Whole(r.text),
            output: r.output,
            language: r.language,
            seed: r.random_seed,
            stability: r.stability,
            speed: None,
            similarity: None,
            style: None,
            before: r.context_before,
            after: r.context_after,
            schedule: None,
            boost: None,
            normalization: "off",
            latency: Some(r.latency_optimization.value()),
            language_normalization: r.language_text_normalization.is_some_and(|v| v.value()),
            dictionaries: http_dictionaries(r.pronunciation_dictionaries),
            unbuffered: false,
            ssml: false,
            timed: false,
            normalized: false,
        },
        TtsRequest::ElevenV3TextVoiceb4b74c48(r) => Prepared {
            model: r.model.value(),
            voice: r.voice,
            text: Text::Whole(r.text),
            output: r.output,
            language: r.language,
            seed: r.random_seed,
            stability: r.stability,
            speed: None,
            similarity: None,
            style: None,
            before: r.context_before,
            after: r.context_after,
            schedule: None,
            boost: None,
            normalization: "off",
            latency: Some(r.latency_optimization.value()),
            language_normalization: r.language_text_normalization.is_some_and(|v| v.value()),
            dictionaries: http_dictionaries(r.pronunciation_dictionaries),
            unbuffered: false,
            ssml: false,
            timed: true,
            normalized: r.timestamp_text.is_some_and(|v| v.value() == "normalized"),
        },
        TtsRequest::ElevenV3StreamingTextVoicef18e078f(r) => Prepared {
            model: r.model.value(),
            voice: r.voice,
            text: Text::Dialogue(r.text),
            output: raw_output(r.output),
            language: r.language,
            seed: r.random_seed,
            stability: r.stability,
            speed: None,
            similarity: None,
            style: None,
            before: None,
            after: None,
            schedule: None,
            boost: None,
            normalization: normalization(r.text_normalization),
            latency: None,
            language_normalization: false,
            dictionaries: live_dictionaries(r.pronunciation_dictionaries),
            unbuffered: false,
            ssml: false,
            timed: false,
            normalized: false,
        },
        TtsRequest::ElevenV3TextVoicef41607cd(r) => Prepared {
            model: r.model.value(),
            voice: r.voice,
            text: Text::Whole(r.text),
            output: r.output,
            language: r.language,
            seed: r.random_seed,
            stability: r.stability,
            speed: None,
            similarity: None,
            style: None,
            before: r.context_before,
            after: r.context_after,
            schedule: None,
            boost: None,
            normalization: normalization(r.text_normalization),
            latency: r.latency_optimization.map(|v| v.value()),
            language_normalization: r.language_text_normalization.is_some_and(|v| v.value()),
            dictionaries: http_dictionaries(r.pronunciation_dictionaries),
            unbuffered: false,
            ssml: false,
            timed: true,
            normalized: r.timestamp_text.is_some_and(|v| v.value() == "normalized"),
        },
        TtsRequest::ElevenV3StreamingTextVoicec9aef256(r) => Prepared {
            model: r.model.value(),
            voice: r.voice,
            text: Text::Dialogue(r.text),
            output: raw_output(r.output),
            language: r.language,
            seed: r.random_seed,
            stability: r.stability,
            speed: None,
            similarity: None,
            style: None,
            before: None,
            after: None,
            schedule: None,
            boost: None,
            normalization: normalization(r.text_normalization),
            latency: None,
            language_normalization: false,
            dictionaries: live_dictionaries(r.pronunciation_dictionaries),
            unbuffered: false,
            ssml: false,
            timed: true,
            normalized: r.timestamp_text.is_some_and(|v| v.value() == "normalized"),
        },
    }
}
fn normalization(value: Option<TtsRequestTextVoice4a0120aeTextNormalization>) -> &'static str {
    match value {
        Some(TtsRequestTextVoice4a0120aeTextNormalization::True(_)) => "on",
        Some(TtsRequestTextVoice4a0120aeTextNormalization::False(_)) => "off",
        _ => "auto",
    }
}
fn http_dictionaries(
    value: Option<Vec<TtsRequestTextVoice4a0120aePronunciationDictionariesItem>>,
) -> Option<JsonValue> {
    value.map(|items| {
        JsonValue::Array(
            items
                .into_iter()
                .map(|v| {
                    let mut fields = BTreeMap::from([(
                        "pronunciation_dictionary_id".into(),
                        JsonValue::String(v.id),
                    )]);
                    if let Some(version) = v.version_id {
                        fields.insert("version_id".into(), JsonValue::String(version));
                    }
                    JsonValue::Object(fields)
                })
                .collect(),
        )
    })
}
fn live_dictionaries(
    value: Option<Vec<TtsRequestStreamingTextVoice194990a6PronunciationDictionariesItem>>,
) -> Option<JsonValue> {
    value.map(|items| {
        JsonValue::Array(
            items
                .into_iter()
                .map(|v| {
                    JsonValue::Object(BTreeMap::from([
                        (
                            "pronunciation_dictionary_id".into(),
                            JsonValue::String(v.id),
                        ),
                        ("version_id".into(), JsonValue::String(v.version_id)),
                    ]))
                })
                .collect(),
        )
    })
}
fn raw_output(
    value: TtsRequestStreamingTextVoice194990a6Output,
) -> TtsRequestTextVoice4a0120aeOutput {
    match value {
        TtsRequestStreamingTextVoice194990a6Output::Mp31de777c9(v) => {
            TtsRequestTextVoice4a0120aeOutput::Mp31de777c9(v)
        }
        TtsRequestStreamingTextVoice194990a6Output::Mp34def27fa(v) => {
            TtsRequestTextVoice4a0120aeOutput::Mp34def27fa(v)
        }
        TtsRequestStreamingTextVoice194990a6Output::Mp356cad1fb(v) => {
            TtsRequestTextVoice4a0120aeOutput::Mp356cad1fb(v)
        }
        TtsRequestStreamingTextVoice194990a6Output::OggOpus(v) => {
            TtsRequestTextVoice4a0120aeOutput::OggOpus(v)
        }
        TtsRequestStreamingTextVoice194990a6Output::Pcm(v) => {
            TtsRequestTextVoice4a0120aeOutput::Pcm(v)
        }
        TtsRequestStreamingTextVoice194990a6Output::Object(v) => {
            TtsRequestTextVoice4a0120aeOutput::Object(v)
        }
    }
}
pub(super) fn output_format(value: &TtsRequestTextVoice4a0120aeOutput) -> String {
    match value {
        TtsRequestTextVoice4a0120aeOutput::Mp31de777c9(_) => "mp3_22050_32".into(),
        TtsRequestTextVoice4a0120aeOutput::Mp34def27fa(_) => "mp3_24000_48".into(),
        TtsRequestTextVoice4a0120aeOutput::Mp356cad1fb(v) => format!(
            "mp3_44100_{}",
            v.bit_rate_bps.as_ref().map_or(128000.0, |v| v.value()) / 1000.0
        ),
        TtsRequestTextVoice4a0120aeOutput::OggOpus(v) => format!(
            "opus_48000_{}",
            v.bit_rate_bps.as_ref().map_or(128000.0, |v| v.value()) / 1000.0
        ),
        TtsRequestTextVoice4a0120aeOutput::Pcm(v) => format!("pcm_{}", v.sample_rate_hz.value()),
        TtsRequestTextVoice4a0120aeOutput::Wav(v) => format!("wav_{}", v.sample_rate_hz.value()),
        TtsRequestTextVoice4a0120aeOutput::Object(v) => format!(
            "{}_8000",
            if v.format.value() == "mulaw" {
                "ulaw"
            } else {
                "alaw"
            }
        ),
    }
}
pub(super) fn context_fields(
    value: TtsRequestTextVoice4a0120aeContextAfter,
    prefix: &str,
    body: &mut BTreeMap<String, JsonValue>,
) {
    match value {
        TtsRequestTextVoice4a0120aeContextAfter::Text(v) => {
            body.insert(format!("{prefix}_text"), JsonValue::String(v.text));
        }
        TtsRequestTextVoice4a0120aeContextAfter::Object(v) => {
            body.insert(
                format!("{prefix}_request_ids"),
                JsonValue::Array(v.request_ids.into_iter().map(JsonValue::String).collect()),
            );
        }
    }
}
