use crate::{
    generated::elevenlabs::*,
    runtime::{JsonValue, StreamingInput},
};
use std::collections::BTreeMap;

pub(super) type Input = TtsRequestStreamingTextVoice5024de38TextItem;
pub(super) type DialogueInput = TtsRequestElevenV3StreamingTextVoice145c0c5aTextItem;
pub(super) enum Text {
    Whole(String),
    Tts(StreamingInput<Input>),
    Dialogue(StreamingInput<DialogueInput>),
}
pub(super) struct Prepared {
    pub model: &'static str,
    pub voice: String,
    pub text: Text,
    pub output: TtsRequestTextVoice814840b5Output,
    pub language: Option<String>,
    pub seed: Option<f64>,
    pub stability: Option<f64>,
    pub speed: Option<f64>,
    pub similarity: Option<f64>,
    pub style: Option<f64>,
    pub boost: Option<bool>,
    pub normalization: &'static str,
    pub latency: Option<&'static str>,
    pub language_normalization: bool,
    pub before: Option<TtsRequestTextVoice814840b5ContextAfter>,
    pub after: Option<TtsRequestTextVoice814840b5ContextAfter>,
    pub dictionaries: Option<JsonValue>,
    pub schedule: Option<Vec<f64>>,
    pub unbuffered: bool,
    pub ssml: bool,
    pub timed: bool,
    pub normalized: bool,
}
pub(super) fn prepare(request: TtsRequest) -> Prepared {
    match request {
        TtsRequest::TextVoice814840b5(r) => Prepared {
            model: r.model.value(),
            voice: r.voice,
            text: Text::Whole(r.text),
            output: r.output,
            language: r.language,
            seed: r.random_seed,
            stability: r.stability,
            speed: r.speed,
            similarity: r.voice_similarity,
            style: r.style_exaggeration,
            before: r.context_before,
            after: r.context_after,
            schedule: None,
            boost: r.voice_boost.map(|v| v.value()),
            normalization: normalization(r.text_normalization),
            latency: r.latency_optimization.map(|v| v.value()),
            language_normalization: r.language_text_normalization.is_some_and(|v| v.value()),
            dictionaries: http_dictionaries(r.pronunciation_dictionaries),
            unbuffered: false,
            ssml: false,
            timed: false,
            normalized: false,
        },
        TtsRequest::TextVoiceeabc9ca0(r) => Prepared {
            model: r.model.value(),
            voice: r.voice,
            text: Text::Whole(r.text),
            output: r.output,
            language: r.language,
            seed: r.random_seed,
            stability: r.stability,
            speed: r.speed,
            similarity: r.voice_similarity,
            style: r.style_exaggeration,
            before: r.context_before,
            after: r.context_after,
            schedule: None,
            boost: r.voice_boost.map(|v| v.value()),
            normalization: "off",
            latency: Some(r.latency_optimization.value()),
            language_normalization: r.language_text_normalization.is_some_and(|v| v.value()),
            dictionaries: http_dictionaries(r.pronunciation_dictionaries),
            unbuffered: false,
            ssml: false,
            timed: false,
            normalized: false,
        },
        TtsRequest::TextVoice1aa1b026(r) => Prepared {
            model: r.model.value(),
            voice: r.voice,
            text: Text::Whole(r.text),
            output: r.output,
            language: r.language,
            seed: r.random_seed,
            stability: r.stability,
            speed: r.speed,
            similarity: r.voice_similarity,
            style: r.style_exaggeration,
            before: r.context_before,
            after: r.context_after,
            schedule: None,
            boost: r.voice_boost.map(|v| v.value()),
            normalization: "off",
            latency: Some(r.latency_optimization.value()),
            language_normalization: r.language_text_normalization.is_some_and(|v| v.value()),
            dictionaries: http_dictionaries(r.pronunciation_dictionaries),
            unbuffered: false,
            ssml: false,
            timed: true,
            normalized: r.timestamp_text.is_some_and(|v| v.value() == "normalized"),
        },
        TtsRequest::StreamingTextVoice5024de38(r) => Prepared {
            model: r.model.value(),
            voice: r.voice,
            text: Text::Tts(r.text),
            output: raw_output(r.output),
            language: r.language,
            seed: r.random_seed,
            stability: r.stability,
            speed: r.speed,
            similarity: r.voice_similarity,
            style: r.style_exaggeration,
            before: None,
            after: None,
            schedule: r.text_buffer_thresholds,
            boost: r.voice_boost.map(|v| v.value()),
            normalization: normalization(r.text_normalization),
            latency: None,
            language_normalization: false,
            dictionaries: live_dictionaries(r.pronunciation_dictionaries),
            unbuffered: false,
            ssml: r.input_type.is_some_and(|v| v.value() == "ssml"),
            timed: false,
            normalized: false,
        },
        TtsRequest::TextVoice6596490e(r) => Prepared {
            model: r.model.value(),
            voice: r.voice,
            text: Text::Whole(r.text),
            output: r.output,
            language: r.language,
            seed: r.random_seed,
            stability: r.stability,
            speed: r.speed,
            similarity: r.voice_similarity,
            style: r.style_exaggeration,
            before: r.context_before,
            after: r.context_after,
            schedule: None,
            boost: r.voice_boost.map(|v| v.value()),
            normalization: normalization(r.text_normalization),
            latency: r.latency_optimization.map(|v| v.value()),
            language_normalization: r.language_text_normalization.is_some_and(|v| v.value()),
            dictionaries: http_dictionaries(r.pronunciation_dictionaries),
            unbuffered: false,
            ssml: false,
            timed: true,
            normalized: r.timestamp_text.is_some_and(|v| v.value() == "normalized"),
        },
        TtsRequest::StreamingTextVoiceb9af60c3(r) => Prepared {
            model: r.model.value(),
            voice: r.voice,
            text: Text::Tts(r.text),
            output: raw_output(r.output),
            language: r.language,
            seed: r.random_seed,
            stability: r.stability,
            speed: r.speed,
            similarity: r.voice_similarity,
            style: r.style_exaggeration,
            before: None,
            after: None,
            schedule: r.text_buffer_thresholds,
            boost: r.voice_boost.map(|v| v.value()),
            normalization: normalization(r.text_normalization),
            latency: None,
            language_normalization: false,
            dictionaries: live_dictionaries(r.pronunciation_dictionaries),
            unbuffered: false,
            ssml: r.input_type.is_some_and(|v| v.value() == "ssml"),
            timed: true,
            normalized: r.timestamp_text.is_some_and(|v| v.value() == "normalized"),
        },
        TtsRequest::StreamingTextVoice732994d4(r) => Prepared {
            model: r.model.value(),
            voice: r.voice,
            text: Text::Tts(r.text),
            output: raw_output(r.output),
            language: r.language,
            seed: r.random_seed,
            stability: r.stability,
            speed: r.speed,
            similarity: r.voice_similarity,
            style: r.style_exaggeration,
            before: None,
            after: None,
            schedule: None,
            boost: r.voice_boost.map(|v| v.value()),
            normalization: normalization(r.text_normalization),
            latency: None,
            language_normalization: false,
            dictionaries: live_dictionaries(r.pronunciation_dictionaries),
            unbuffered: true,
            ssml: r.input_type.is_some_and(|v| v.value() == "ssml"),
            timed: false,
            normalized: false,
        },
        TtsRequest::StreamingTextVoicebc33fdb4(r) => Prepared {
            model: r.model.value(),
            voice: r.voice,
            text: Text::Tts(r.text),
            output: raw_output(r.output),
            language: r.language,
            seed: r.random_seed,
            stability: r.stability,
            speed: r.speed,
            similarity: r.voice_similarity,
            style: r.style_exaggeration,
            before: None,
            after: None,
            schedule: None,
            boost: r.voice_boost.map(|v| v.value()),
            normalization: normalization(r.text_normalization),
            latency: None,
            language_normalization: false,
            dictionaries: live_dictionaries(r.pronunciation_dictionaries),
            unbuffered: true,
            ssml: r.input_type.is_some_and(|v| v.value() == "ssml"),
            timed: true,
            normalized: r.timestamp_text.is_some_and(|v| v.value() == "normalized"),
        },
        TtsRequest::MultilingualV2TextVoiceae5db0bf(r) => Prepared {
            model: r.model.value(),
            voice: r.voice,
            text: Text::Whole(r.text),
            output: r.output,
            language: None,
            seed: r.random_seed,
            stability: r.stability,
            speed: r.speed,
            similarity: r.voice_similarity,
            style: r.style_exaggeration,
            before: r.context_before,
            after: r.context_after,
            schedule: None,
            boost: r.voice_boost.map(|v| v.value()),
            normalization: normalization(r.text_normalization),
            latency: r.latency_optimization.map(|v| v.value()),
            language_normalization: r.language_text_normalization.is_some_and(|v| v.value()),
            dictionaries: http_dictionaries(r.pronunciation_dictionaries),
            unbuffered: false,
            ssml: false,
            timed: false,
            normalized: false,
        },
        TtsRequest::MultilingualV2TextVoice2ee6cad1(r) => Prepared {
            model: r.model.value(),
            voice: r.voice,
            text: Text::Whole(r.text),
            output: r.output,
            language: None,
            seed: r.random_seed,
            stability: r.stability,
            speed: r.speed,
            similarity: r.voice_similarity,
            style: r.style_exaggeration,
            before: r.context_before,
            after: r.context_after,
            schedule: None,
            boost: r.voice_boost.map(|v| v.value()),
            normalization: "off",
            latency: Some(r.latency_optimization.value()),
            language_normalization: r.language_text_normalization.is_some_and(|v| v.value()),
            dictionaries: http_dictionaries(r.pronunciation_dictionaries),
            unbuffered: false,
            ssml: false,
            timed: false,
            normalized: false,
        },
        TtsRequest::MultilingualV2TextVoice4ed687d7(r) => Prepared {
            model: r.model.value(),
            voice: r.voice,
            text: Text::Whole(r.text),
            output: r.output,
            language: None,
            seed: r.random_seed,
            stability: r.stability,
            speed: r.speed,
            similarity: r.voice_similarity,
            style: r.style_exaggeration,
            before: r.context_before,
            after: r.context_after,
            schedule: None,
            boost: r.voice_boost.map(|v| v.value()),
            normalization: "off",
            latency: Some(r.latency_optimization.value()),
            language_normalization: r.language_text_normalization.is_some_and(|v| v.value()),
            dictionaries: http_dictionaries(r.pronunciation_dictionaries),
            unbuffered: false,
            ssml: false,
            timed: true,
            normalized: r.timestamp_text.is_some_and(|v| v.value() == "normalized"),
        },
        TtsRequest::MultilingualV2StreamingTextVoice729ee226(r) => Prepared {
            model: r.model.value(),
            voice: r.voice,
            text: Text::Tts(r.text),
            output: raw_output(r.output),
            language: None,
            seed: r.random_seed,
            stability: r.stability,
            speed: r.speed,
            similarity: r.voice_similarity,
            style: r.style_exaggeration,
            before: None,
            after: None,
            schedule: r.text_buffer_thresholds,
            boost: r.voice_boost.map(|v| v.value()),
            normalization: normalization(r.text_normalization),
            latency: None,
            language_normalization: false,
            dictionaries: live_dictionaries(r.pronunciation_dictionaries),
            unbuffered: false,
            ssml: r.input_type.is_some_and(|v| v.value() == "ssml"),
            timed: false,
            normalized: false,
        },
        TtsRequest::MultilingualV2TextVoice11f62a92(r) => Prepared {
            model: r.model.value(),
            voice: r.voice,
            text: Text::Whole(r.text),
            output: r.output,
            language: None,
            seed: r.random_seed,
            stability: r.stability,
            speed: r.speed,
            similarity: r.voice_similarity,
            style: r.style_exaggeration,
            before: r.context_before,
            after: r.context_after,
            schedule: None,
            boost: r.voice_boost.map(|v| v.value()),
            normalization: normalization(r.text_normalization),
            latency: r.latency_optimization.map(|v| v.value()),
            language_normalization: r.language_text_normalization.is_some_and(|v| v.value()),
            dictionaries: http_dictionaries(r.pronunciation_dictionaries),
            unbuffered: false,
            ssml: false,
            timed: true,
            normalized: r.timestamp_text.is_some_and(|v| v.value() == "normalized"),
        },
        TtsRequest::MultilingualV2StreamingTextVoice3f7db298(r) => Prepared {
            model: r.model.value(),
            voice: r.voice,
            text: Text::Tts(r.text),
            output: raw_output(r.output),
            language: None,
            seed: r.random_seed,
            stability: r.stability,
            speed: r.speed,
            similarity: r.voice_similarity,
            style: r.style_exaggeration,
            before: None,
            after: None,
            schedule: r.text_buffer_thresholds,
            boost: r.voice_boost.map(|v| v.value()),
            normalization: normalization(r.text_normalization),
            latency: None,
            language_normalization: false,
            dictionaries: live_dictionaries(r.pronunciation_dictionaries),
            unbuffered: false,
            ssml: r.input_type.is_some_and(|v| v.value() == "ssml"),
            timed: true,
            normalized: r.timestamp_text.is_some_and(|v| v.value() == "normalized"),
        },
        TtsRequest::MultilingualV2StreamingTextVoiceac3750e0(r) => Prepared {
            model: r.model.value(),
            voice: r.voice,
            text: Text::Tts(r.text),
            output: raw_output(r.output),
            language: None,
            seed: r.random_seed,
            stability: r.stability,
            speed: r.speed,
            similarity: r.voice_similarity,
            style: r.style_exaggeration,
            before: None,
            after: None,
            schedule: None,
            boost: r.voice_boost.map(|v| v.value()),
            normalization: normalization(r.text_normalization),
            latency: None,
            language_normalization: false,
            dictionaries: live_dictionaries(r.pronunciation_dictionaries),
            unbuffered: true,
            ssml: r.input_type.is_some_and(|v| v.value() == "ssml"),
            timed: false,
            normalized: false,
        },
        TtsRequest::MultilingualV2StreamingTextVoiceb51c2303(r) => Prepared {
            model: r.model.value(),
            voice: r.voice,
            text: Text::Tts(r.text),
            output: raw_output(r.output),
            language: None,
            seed: r.random_seed,
            stability: r.stability,
            speed: r.speed,
            similarity: r.voice_similarity,
            style: r.style_exaggeration,
            before: None,
            after: None,
            schedule: None,
            boost: r.voice_boost.map(|v| v.value()),
            normalization: normalization(r.text_normalization),
            latency: None,
            language_normalization: false,
            dictionaries: live_dictionaries(r.pronunciation_dictionaries),
            unbuffered: true,
            ssml: r.input_type.is_some_and(|v| v.value() == "ssml"),
            timed: true,
            normalized: r.timestamp_text.is_some_and(|v| v.value() == "normalized"),
        },
        TtsRequest::ElevenV3TextVoicec3eabebc(r) => Prepared {
            model: r.model.value(),
            voice: r.voice,
            text: Text::Whole(r.text),
            output: r.output,
            language: r.language,
            seed: r.random_seed,
            stability: r.stability,
            speed: None,
            similarity: None,
            style: None,
            before: r.context_before,
            after: r.context_after,
            schedule: None,
            boost: None,
            normalization: normalization(r.text_normalization),
            latency: r.latency_optimization.map(|v| v.value()),
            language_normalization: r.language_text_normalization.is_some_and(|v| v.value()),
            dictionaries: http_dictionaries(r.pronunciation_dictionaries),
            unbuffered: false,
            ssml: false,
            timed: false,
            normalized: false,
        },
        TtsRequest::ElevenV3TextVoicefade944d(r) => Prepared {
            model: r.model.value(),
            voice: r.voice,
            text: Text::Whole(r.text),
            output: r.output,
            language: r.language,
            seed: r.random_seed,
            stability: r.stability,
            speed: None,
            similarity: None,
            style: None,
            before: r.context_before,
            after: r.context_after,
            schedule: None,
            boost: None,
            normalization: "off",
            latency: Some(r.latency_optimization.value()),
            language_normalization: r.language_text_normalization.is_some_and(|v| v.value()),
            dictionaries: http_dictionaries(r.pronunciation_dictionaries),
            unbuffered: false,
            ssml: false,
            timed: false,
            normalized: false,
        },
        TtsRequest::ElevenV3TextVoicebb26fac2(r) => Prepared {
            model: r.model.value(),
            voice: r.voice,
            text: Text::Whole(r.text),
            output: r.output,
            language: r.language,
            seed: r.random_seed,
            stability: r.stability,
            speed: None,
            similarity: None,
            style: None,
            before: r.context_before,
            after: r.context_after,
            schedule: None,
            boost: None,
            normalization: "off",
            latency: Some(r.latency_optimization.value()),
            language_normalization: r.language_text_normalization.is_some_and(|v| v.value()),
            dictionaries: http_dictionaries(r.pronunciation_dictionaries),
            unbuffered: false,
            ssml: false,
            timed: true,
            normalized: r.timestamp_text.is_some_and(|v| v.value() == "normalized"),
        },
        TtsRequest::ElevenV3StreamingTextVoice145c0c5a(r) => Prepared {
            model: r.model.value(),
            voice: r.voice,
            text: Text::Dialogue(r.text),
            output: raw_output(r.output),
            language: r.language,
            seed: r.random_seed,
            stability: r.stability,
            speed: None,
            similarity: None,
            style: None,
            before: None,
            after: None,
            schedule: None,
            boost: None,
            normalization: normalization(r.text_normalization),
            latency: None,
            language_normalization: false,
            dictionaries: live_dictionaries(r.pronunciation_dictionaries),
            unbuffered: false,
            ssml: false,
            timed: false,
            normalized: false,
        },
        TtsRequest::ElevenV3TextVoicede803f4c(r) => Prepared {
            model: r.model.value(),
            voice: r.voice,
            text: Text::Whole(r.text),
            output: r.output,
            language: r.language,
            seed: r.random_seed,
            stability: r.stability,
            speed: None,
            similarity: None,
            style: None,
            before: r.context_before,
            after: r.context_after,
            schedule: None,
            boost: None,
            normalization: normalization(r.text_normalization),
            latency: r.latency_optimization.map(|v| v.value()),
            language_normalization: r.language_text_normalization.is_some_and(|v| v.value()),
            dictionaries: http_dictionaries(r.pronunciation_dictionaries),
            unbuffered: false,
            ssml: false,
            timed: true,
            normalized: r.timestamp_text.is_some_and(|v| v.value() == "normalized"),
        },
        TtsRequest::ElevenV3StreamingTextVoicec1dc022a(r) => Prepared {
            model: r.model.value(),
            voice: r.voice,
            text: Text::Dialogue(r.text),
            output: raw_output(r.output),
            language: r.language,
            seed: r.random_seed,
            stability: r.stability,
            speed: None,
            similarity: None,
            style: None,
            before: None,
            after: None,
            schedule: None,
            boost: None,
            normalization: normalization(r.text_normalization),
            latency: None,
            language_normalization: false,
            dictionaries: live_dictionaries(r.pronunciation_dictionaries),
            unbuffered: false,
            ssml: false,
            timed: true,
            normalized: r.timestamp_text.is_some_and(|v| v.value() == "normalized"),
        },
    }
}
fn normalization(value: Option<TtsRequestTextVoice814840b5TextNormalization>) -> &'static str {
    match value {
        Some(TtsRequestTextVoice814840b5TextNormalization::True(_)) => "on",
        Some(TtsRequestTextVoice814840b5TextNormalization::False(_)) => "off",
        _ => "auto",
    }
}
fn http_dictionaries(
    value: Option<Vec<TtsRequestTextVoice814840b5PronunciationDictionariesItem>>,
) -> Option<JsonValue> {
    value.map(|items| {
        JsonValue::Array(
            items
                .into_iter()
                .map(|v| {
                    let mut fields = BTreeMap::from([(
                        "pronunciation_dictionary_id".into(),
                        JsonValue::String(v.id),
                    )]);
                    if let Some(version) = v.version_id {
                        fields.insert("version_id".into(), JsonValue::String(version));
                    }
                    JsonValue::Object(fields)
                })
                .collect(),
        )
    })
}
fn live_dictionaries(
    value: Option<Vec<TtsRequestStreamingTextVoice5024de38PronunciationDictionariesItem>>,
) -> Option<JsonValue> {
    value.map(|items| {
        JsonValue::Array(
            items
                .into_iter()
                .map(|v| {
                    JsonValue::Object(BTreeMap::from([
                        (
                            "pronunciation_dictionary_id".into(),
                            JsonValue::String(v.id),
                        ),
                        ("version_id".into(), JsonValue::String(v.version_id)),
                    ]))
                })
                .collect(),
        )
    })
}
fn raw_output(
    value: TtsRequestStreamingTextVoice5024de38Output,
) -> TtsRequestTextVoice814840b5Output {
    match value {
        TtsRequestStreamingTextVoice5024de38Output::Mp31de777c9(v) => {
            TtsRequestTextVoice814840b5Output::Mp31de777c9(v)
        }
        TtsRequestStreamingTextVoice5024de38Output::Mp34def27fa(v) => {
            TtsRequestTextVoice814840b5Output::Mp34def27fa(v)
        }
        TtsRequestStreamingTextVoice5024de38Output::Mp356cad1fb(v) => {
            TtsRequestTextVoice814840b5Output::Mp356cad1fb(v)
        }
        TtsRequestStreamingTextVoice5024de38Output::OggOpus(v) => {
            TtsRequestTextVoice814840b5Output::OggOpus(v)
        }
        TtsRequestStreamingTextVoice5024de38Output::Pcm(v) => {
            TtsRequestTextVoice814840b5Output::Pcm(v)
        }
        TtsRequestStreamingTextVoice5024de38Output::Object(v) => {
            TtsRequestTextVoice814840b5Output::Object(v)
        }
    }
}
pub(super) fn output_format(value: &TtsRequestTextVoice814840b5Output) -> String {
    match value {
        TtsRequestTextVoice814840b5Output::Mp31de777c9(_) => "mp3_22050_32".into(),
        TtsRequestTextVoice814840b5Output::Mp34def27fa(_) => "mp3_24000_48".into(),
        TtsRequestTextVoice814840b5Output::Mp356cad1fb(v) => format!(
            "mp3_44100_{}",
            v.bit_rate_bps.as_ref().map_or(128000.0, |v| v.value()) / 1000.0
        ),
        TtsRequestTextVoice814840b5Output::OggOpus(v) => format!(
            "opus_48000_{}",
            v.bit_rate_bps.as_ref().map_or(128000.0, |v| v.value()) / 1000.0
        ),
        TtsRequestTextVoice814840b5Output::Pcm(v) => format!("pcm_{}", v.sample_rate_hz.value()),
        TtsRequestTextVoice814840b5Output::Wav(v) => format!("wav_{}", v.sample_rate_hz.value()),
        TtsRequestTextVoice814840b5Output::Object(v) => format!(
            "{}_8000",
            if v.format.value() == "mulaw" {
                "ulaw"
            } else {
                "alaw"
            }
        ),
    }
}
pub(super) fn context_fields(
    value: TtsRequestTextVoice814840b5ContextAfter,
    prefix: &str,
    body: &mut BTreeMap<String, JsonValue>,
) {
    match value {
        TtsRequestTextVoice814840b5ContextAfter::Text(v) => {
            body.insert(format!("{prefix}_text"), JsonValue::String(v.text));
        }
        TtsRequestTextVoice814840b5ContextAfter::Object(v) => {
            body.insert(
                format!("{prefix}_request_ids"),
                JsonValue::Array(v.request_ids.into_iter().map(JsonValue::String).collect()),
            );
        }
    }
}
